### ISSUE TITLE
Installation using `pip` results in broken `edgedb`

### ISSUE THREAD

**Issue by Chaz6** [edgedb/edgedb#1166]
Host: CentOS Linux release 7.7.1908 (Core)
Python version: 3.8.1

```
$ pip3 install -U --user git+https://github.com/edgedb/edgedb.git#egg=edgedb-server
Collecting edgedb-server
  Cloning https://github.com/edgedb/edgedb.git to /home/chaz/.local/tmp/tmux/pip-install-czp99713/edgedb-server
  Running command git clone -q https://github.com/edgedb/edgedb.git /home/chaz/.local/tmp/tmux/pip-install-czp99713/edgedb-server
  Running command git submodule update --init --recursive -q
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Requirement already satisfied, skipping upgrade: uvloop~=0.14.0 in /home/chaz/.local/lib/python3.8/site-packages (from edgedb-server) (0.14.0)
Requirement already satisfied, skipping upgrade: setproctitle~=1.1.10 in /home/chaz/.local/lib/python3.8/site-packages (from edgedb-server) (1.1.10)
Requirement already satisfied, skipping upgrade: Pygments~=2.3.0 in /home/chaz/.local/lib/python3.8/site-packages (from edgedb-server) (2.3.1)
Requirement already satisfied, skipping upgrade: asyncpg~=0.20.0 in /home/chaz/.local/lib/python3.8/site-packages (from edgedb-server) (0.20.1)
Collecting edgedb>=0.7.0a9
  Using cached edgedb-0.7.0-cp38-cp38-manylinux1_x86_64.whl (2.8 MB)
Requirement already satisfied, skipping upgrade: parsing~=1.6.1 in /home/chaz/.local/lib/python3.8/site-packages (from edgedb-server) (1.6.1)
Requirement already satisfied, skipping upgrade: immutables>=0.9 in /home/chaz/.local/lib/python3.8/site-packages (from edgedb-server) (0.11)
Requirement already satisfied, skipping upgrade: httptools>=0.0.13 in /home/chaz/.local/lib/python3.8/site-packages (from edgedb-server) (0.0.13)
Requirement already satisfied, skipping upgrade: psutil~=5.6.1 in /home/chaz/.local/lib/python3.8/site-packages (from edgedb-server) (5.6.3)
Requirement already satisfied, skipping upgrade: setuptools-scm~=3.2.0 in /home/chaz/.local/lib/python3.8/site-packages (from edgedb-server) (3.2.0)
Requirement already satisfied, skipping upgrade: setuptools-rust==0.10.3 in /home/chaz/.local/lib/python3.8/site-packages (from edgedb-server) (0.10.3)
Requirement already satisfied, skipping upgrade: prompt-toolkit>=2.0.0 in /home/chaz/.local/lib/python3.8/site-packages (from edgedb-server) (3.0.3)
Requirement already satisfied, skipping upgrade: typing-inspect~=0.5.0 in /home/chaz/.local/lib/python3.8/site-packages (from edgedb-server) (0.5.0)
Requirement already satisfied, skipping upgrade: graphql-core~=2.2.1 in /home/chaz/.local/lib/python3.8/site-packages (from edgedb-server) (2.2.1)
Requirement already satisfied, skipping upgrade: click~=6.7 in /home/chaz/.local/lib/python3.8/site-packages (from edgedb-server) (6.7)
Requirement already satisfied, skipping upgrade: promise~=2.2.0 in /home/chaz/.local/lib/python3.8/site-packages (from edgedb-server) (2.2.1)
Requirement already satisfied, skipping upgrade: six>=1.8.0 in /home/chaz/.local/lib/python3.8/site-packages (from parsing~=1.6.1->edgedb-server) (1.12.0)
Requirement already satisfied, skipping upgrade: semantic-version>=2.6.0 in /home/chaz/.local/lib/python3.8/site-packages (from setuptools-rust==0.10.3->edgedb-server) (2.8.4)
Requirement already satisfied, skipping upgrade: toml>=0.9.0 in /home/chaz/.local/lib/python3.8/site-packages (from setuptools-rust==0.10.3->edgedb-server) (0.10.0)
Requirement already satisfied, skipping upgrade: wcwidth in /home/chaz/.local/lib/python3.8/site-packages (from prompt-toolkit>=2.0.0->edgedb-server) (0.1.8)
Requirement already satisfied, skipping upgrade: mypy-extensions>=0.3.0 in /home/chaz/.local/lib/python3.8/site-packages (from typing-inspect~=0.5.0->edgedb-server) (0.4.3)
Requirement already satisfied, skipping upgrade: typing-extensions>=3.7.4 in /home/chaz/.local/lib/python3.8/site-packages (from typing-inspect~=0.5.0->edgedb-server) (3.7.4.1)
Requirement already satisfied, skipping upgrade: rx<3,>=1.6 in /home/chaz/.local/lib/python3.8/site-packages (from graphql-core~=2.2.1->edgedb-server) (1.6.1)
Building wheels for collected packages: edgedb-server
Building wheels for collected packages: edgedb-server
  Building wheel for edgedb-server (PEP 517) ... done
  Created wheel for edgedb-server: filename=edgedb_server-1.0a3.dev5+gfde3cf7-cp38-cp38-linux_x86_64.whl size=4734606 sha256=28e7e3e04322c6bbbee3d99cd8f692f5e0a55dfc784106bddda8219abeda9943
  Stored in directory: /home/chaz/.local/tmp/tmux/pip-ephem-wheel-cache-_jq712tx/wheels/f7/b5/a7/f4d1bc3bfbd401f1e780773fc8a20bfbf3ba77f5cc98ff7211
Successfully built edgedb-server
Installing collected packages: edgedb, edgedb-server
  Attempting uninstall: edgedb-server
    Found existing installation: edgedb-server 1.0a3.dev5+gfde3cf7
    Uninstalling edgedb-server-1.0a3.dev5+gfde3cf7:
      Successfully uninstalled edgedb-server-1.0a3.dev5+gfde3cf7
Successfully installed edgedb-0.7.0 edgedb-server-1.0a3.dev5+gfde3cf7

$ edgedb --help
Traceback (most recent call last):
  File "/home/chaz/.local/bin/edgedb", line 5, in <module>
    from edb.cli import cli
  File "/home/chaz/.local/lib/python3.8/site-packages/edb/cli/__init__.py", line 28, in <module>
    from edb import repl
  File "/home/chaz/.local/lib/python3.8/site-packages/edb/repl/__init__.py", line 47, in <module>
    from edb.edgeql import pygments as eql_pygments
  File "/home/chaz/.local/lib/python3.8/site-packages/edb/edgeql/__init__.py", line 22, in <module>
    from . import ast  # NOQA
  File "/home/chaz/.local/lib/python3.8/site-packages/edb/edgeql/ast.py", line 30, in <module>
    from . import quote
  File "/home/chaz/.local/lib/python3.8/site-packages/edb/edgeql/quote.py", line 24, in <module>
    from .parser.grammar import keywords
  File "/home/chaz/.local/lib/python3.8/site-packages/edb/edgeql/parser/__init__.py", line 22, in <module>
    from . import parser as ql_parser
  File "/home/chaz/.local/lib/python3.8/site-packages/edb/edgeql/parser/parser.py", line 24, in <module>
    from .grammar import lexer
  File "/home/chaz/.local/lib/python3.8/site-packages/edb/edgeql/parser/grammar/lexer.py", line 25, in <module>
    from edb.edgeql import _edgeql_rust  # noqa
ImportError: cannot import name '_edgeql_rust' from partially initialized module 'edb.edgeql' (most likely due to a circular import) (/home/chaz/.local/lib/python3.8/site-packages/edb/edgeql/__init__.py)
```

**Comment by elprans** [comment]
The installation of edgedb-server this way is not supported.  If you want to build locally from master please follow https://edgedb.com/docs/internals/dev

**Comment by Chaz6** [comment]
Thanks for the patch, I will try it out this evening.

**Comment by elprans** [comment]
@Chaz6, the patch does not enable EdgeDB to be pip-installable, it just fixes the particular error.  We only support EdgeDB development mode installs of EdgeDB via `pip install -e`.  For regular use, please use one of the prebuilt packages from https://edgedb.com/download/ or Docker.
