### ISSUE TITLE
ISE when not submitting enough query arguments

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb#1339]
```
>>> c.fetchone('select <int64>$0 + 1')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/yury/dev/venvs/edgedb/lib/python3.8/site-packages/edgedb/blocking_con.py", line 107, in fetchone
    return self._protocol.sync_execute_anonymous(
  File "edgedb/protocol/blocking_proto.pyx", line 91, in edgedb.protocol.blocking_proto.BlockingIOProtocol.sync_execute_anonymous
  File "edgedb/protocol/blocking_proto.pyx", line 77, in edgedb.protocol.blocking_proto.BlockingIOProtocol._iter_coroutine
  File "edgedb/protocol/protocol.pyx", line 542, in execute_anonymous
  File "edgedb/protocol/protocol.pyx", line 339, in _execute
edgedb.errors.InternalServerError: bind message supplies 0 parameters, but prepared statement "" requires 1
```

**Comment by RobertoPrevato** [comment]
I cannot reproduce this issue anymore. Now a user friendly exception is thrown: `edgedb.errors.QueryError: invalid argument count, expected: 1, got: 0`.

```
/edgedb-python/edgedb/blocking_con.py", line 107, in fetchone
    return self._protocol.sync_execute_anonymous(
  File "edgedb/protocol/blocking_proto.pyx", line 91, in edgedb.protocol.blocking_proto.BlockingIOProtocol.sync_execute_anonymous
  File "edgedb/protocol/blocking_proto.pyx", line 77, in edgedb.protocol.blocking_proto.BlockingIOProtocol._iter_coroutine
  File "edgedb/protocol/protocol.pyx", line 541, in execute_anonymous
  File "edgedb/protocol/protocol.pyx", line 338, in _execute
edgedb.errors.QueryError: invalid argument count, expected: 1, got: 0
```
