### ISSUE TITLE
query normalizer does not work with some decimals (bigints?) literals

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb#1364]
```
yury> select 1e20n;
ERROR: InternalServerError: decimal cannot be encoded: value is out of range
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "edb/server/mng_port/edgecon.pyx", line 1319, in edb.server.mng_port.edgecon.EdgeConnection.main
          await self.parse()
        File "edb/server/mng_port/edgecon.pyx", line 938, in parse
          compiled_query = await self._parse(
        File "edb/server/mng_port/edgecon.pyx", line 761, in _parse
          normalized = normalize(eql)
        File "edb/server/tokenizer.pyx", line 58, in edb.server.tokenizer.normalize
          return _normalize(eql_str)
      AssertionError: decimal cannot be encoded: value is out of range
```

**Comment by tailhook** [comment]
Fixed by #1372
