### ISSUE TITLE
Error creating a function

### ISSUE THREAD

**Issue by haikyuu** [edgedb/edgedb#1386]
- EdgeDB Version: nightly EdgeDB 1.0-alpha.3+dev.175.ge0b2da65
- OS Version: ubuntu 18.04

Steps to Reproduce:

Query 
```
CREATE FUNCTION getAvailability(class: Class) ->  SET OF TimeSpot
USING EdgeQL $$
with availability:= (SELECT class.school.potentiallyAvailableAt)
select availability
$$;
```

Error:
```
ERROR: InternalServerError: there is no range var for (__derived__::expr~1) source in <pg.SelectStmt at 0x7f36ab8d7a90>
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/pgsql/compiler/__init__.py", line 83, in compile_ir_to_sql_tree
          qtree = dispatch.compile(ir_expr, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/functools.py", line 874, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/pgsql/compiler/expr.py", line 59, in compile_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/pgsql/compiler/expr.py", line 111, in _compile_set_impl
          _compile_set(ir_set, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/pgsql/compiler/expr.py", line 565, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/pgsql/compiler/relgen.py", line 125, in get_set_rvar
          return _process_toplevel_query(ir_set, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/pgsql/compiler/relgen.py", line 208, in _process_toplevel_query
          rvars = _get_set_rvar(ir_set, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/pgsql/compiler/relgen.py", line 221, in _get_set_rvar
          rvars = process_set_as_subquery(ir_set, stmt, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/pgsql/compiler/relgen.py", line 1057, in process_set_as_subquery
          dispatch.visit(ir_set.expr, ctx=newctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/functools.py", line 874, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/pgsql/compiler/dispatch.py", line 44, in visit
          compile(ir, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/functools.py", line 874, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/pgsql/compiler/stmt.py", line 60, in compile_SelectStmt
          outvar = clauses.compile_output(stmt.result, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/pgsql/compiler/clauses.py", line 112, in compile_output
          dispatch.visit(ir_set, ctx=newctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/functools.py", line 874, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/pgsql/compiler/expr.py", line 82, in visit_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/pgsql/compiler/expr.py", line 107, in _compile_set_impl
          _compile_set(ir_set, ctx=scopectx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/pgsql/compiler/expr.py", line 565, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/pgsql/compiler/relgen.py", line 170, in get_set_rvar
          rvars = _get_set_rvar(ir_set, ctx=subctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/pgsql/compiler/relgen.py", line 221, in _get_set_rvar
          rvars = process_set_as_subquery(ir_set, stmt, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/pgsql/compiler/relgen.py", line 1057, in process_set_as_subquery
          dispatch.visit(ir_set.expr, ctx=newctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/functools.py", line 874, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/pgsql/compiler/dispatch.py", line 44, in visit
          compile(ir, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/functools.py", line 874, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/pgsql/compiler/stmt.py", line 60, in compile_SelectStmt
          outvar = clauses.compile_output(stmt.result, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/pgsql/compiler/clauses.py", line 112, in compile_output
          dispatch.visit(ir_set, ctx=newctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/functools.py", line 874, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/pgsql/compiler/expr.py", line 82, in visit_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/pgsql/compiler/expr.py", line 111, in _compile_set_impl
          _compile_set(ir_set, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/pgsql/compiler/expr.py", line 565, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/pgsql/compiler/relgen.py", line 170, in get_set_rvar
          rvars = _get_set_rvar(ir_set, ctx=subctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/pgsql/compiler/relgen.py", line 297, in _get_set_rvar
          rvars = process_set_as_path(ir_set, stmt, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/pgsql/compiler/relgen.py", line 872, in process_set_as_path
          src_rvar = get_set_rvar(ir_source, ctx=srcctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/pgsql/compiler/relgen.py", line 170, in get_set_rvar
          rvars = _get_set_rvar(ir_set, ctx=subctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/pgsql/compiler/relgen.py", line 297, in _get_set_rvar
          rvars = process_set_as_path(ir_set, stmt, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/pgsql/compiler/relgen.py", line 873, in process_set_as_path
          set_rvar = relctx.semi_join(stmt, ir_set, src_rvar, ctx=srcctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/pgsql/compiler/relctx.py", line 539, in semi_join
          pathctx.get_path_identity_output(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/pgsql/compiler/pathctx.py", line 933, in get_path_identity_output
          return get_path_output(rel, path_id, aspect='identity', env=env)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/pgsql/compiler/pathctx.py", line 796, in get_path_output
          return _get_path_output(rel, path_id=path_id, aspect=aspect,
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/pgsql/compiler/pathctx.py", line 835, in _get_path_output
          ref = get_path_var(rel, path_id, aspect=aspect, env=env)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/pgsql/compiler/pathctx.py", line 294, in get_path_var
          outvar = get_path_output(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/pgsql/compiler/pathctx.py", line 796, in get_path_output
          return _get_path_output(rel, path_id=path_id, aspect=aspect,
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/pgsql/compiler/pathctx.py", line 835, in _get_path_output
          ref = get_path_var(rel, path_id, aspect=aspect, env=env)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/pgsql/compiler/pathctx.py", line 277, in get_path_var
          raise LookupError(
      LookupError: there is no range var for (__derived__::expr~1) source in <pg.SelectStmt at 0x7f36ab8d7a90>

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/server/procpool/worker.py", line 75, in worker
          res = await meth(*args)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 1283, in compile_eql_tokens
          return self._compile(ctx=ctx, tokens=eql_tokens)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 945, in _compile
          comp: dbstate.BaseQuery = self._compile_dispatch_ql(ctx, stmt)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 880, in _compile_dispatch_ql
          return self._compile_ql_ddl(ctx, ql)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 575, in _compile_ql_ddl
          return self._compile_command(ctx, cmd)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 557, in _compile_command
          return self._compile_and_apply_ddl_command(ctx, cmd)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 520, in _compile_and_apply_ddl_command
          schema, plan = self._process_delta(ctx, cmd, schema)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 313, in _process_delta
          schema = delta.apply(schema, context)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/pgsql/delta.py", line 4017, in apply
          schema = sd.DeltaRoot.apply(self, schema, context)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/schema/delta.py", line 851, in apply
          schema = objop.apply(schema, context)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/pgsql/delta.py", line 658, in apply
          dbf = self.compile_edgeql_function(func, schema, context)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/pgsql/delta.py", line 629, in compile_edgeql_function
          sql_text, _ = compiler.compile_ir_to_sql(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/pgsql/compiler/__init__.py", line 105, in compile_ir_to_sql
          qtree = compile_ir_to_sql_tree(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/pgsql/compiler/__init__.py", line 90, in compile_ir_to_sql_tree
          raise errors.InternalServerError(*args) from e
      edb.errors.InternalServerError: there is no range var for (__derived__::expr~1) source in <pg.SelectStmt at 0x7f36ab8d7a90>
```

Schema:
```
type TimeSpot{
  property name -> str;
};
abstract type HasPotentialAvailability {
     multi link potentiallyAvailableAt -> TimeSpot;
    };
type School extending HasPotentialAvailability{
      required property timezone -> str;
    };
type Class extending HasPotentialAvailability {
      required link school -> School;
    };
```

**Comment by elprans** [comment]
Thanks for the report! Looks like a dupe of #1335

**Comment by haikyuu** [comment]
Right
