### ISSUE TITLE
Error connecting to remote postgres database

### ISSUE THREAD

**Issue by haikyuu** [edgedb/edgedb#1388]
I have a server containing edgedb and another one containing postgres 12.

I try to run the edgedb server using `sudo edgedb-server --postgres-dsn "postgres://postgres:pwd@172.16.1.233:5432/lms"` where lms is a postgres db i created.

It runs ok:
```
NFO 12310 2020-05-10 03:12:14,642 edb.server: EdgeDB server (1.0-alpha.3+dev.178.gf5b4ba7b) starting.
INFO 12310 2020-05-10 03:12:48,663 edb.server: Serving on 127.0.0.1:5656
INFO 12310 2020-05-10 03:12:48,663 edb.server: Serving on /run/edgedb/.s.EDGEDB.5656
INFO 12310 2020-05-10 03:12:48,663 edb.server: Serving admin on /run/edgedb/.s.EDGEDB.admin.5656
```

And i can connect to edgedb using `edgedb -d edgedb -u edgedb`.

When i create a database  in edgedb or connect to it using `\c lms` or even `edgedb -d lms -u edgedb`, i get the following error

```
Error: Error authenticating: ERROR: InternalServerError: schema "edgedb" does not exist
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/server/procpool/worker.py", line 75, in worker
          res = await meth(*args)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 276, in connect
          await self._get_database(dbver)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 253, in _get_database
          self._std_schema = await load_std_schema(con)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 191, in load_std_schema
          data = await backend_conn.fetchval('SELECT edgedb.__syscache_stdschema();')
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/asyncpg/connection.py", line 438, in fetchval
          data = await self._execute(query, args, 1, timeout)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/asyncpg/connection.py", line 1402, in _execute
          result, _ = await self.__execute(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/asyncpg/connection.py", line 1411, in __execute
          return await self._do_execute(query, executor, timeout)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/asyncpg/connection.py", line 1423, in _do_execute
          stmt = await self._get_statement(query, None)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/asyncpg/connection.py", line 328, in _get_statement
          statement = await self._protocol.prepare(stmt_name, query, timeout)
        File "asyncpg/protocol/protocol.pyx", line 163, in prepare
      asyncpg.exceptions.InvalidSchemaNameError: schema "edgedb" does not exist
```

And the server logs 
```
====================== Exception occurred: schema "edgedb" does not exist ======================

2. edb.common.taskgroup.TaskGroupError: unhandled errors in a TaskGroup; 1 sub errors: (InvalidSchemaNameError)
 + InvalidSchemaNameError: schema "edgedb" does not exist
 |   File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/server/baseport.py", line 66, in new_compiler
 |     await compiler_worker.call('connect', dbname, dbver)
 |   File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/server/procpool/pool.py", line 120, in call
 |     raise exc



------------------------------------------ Traceback -------------------------------------------

    /usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/server/mng_port/port.py, line 94, in new_backend
        > compiler_task = g.create_task(self.new_compiler(dbname, dbver))
    /usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/common/taskgroup.py, line 169, in aexit
        > raise me from None

edb.common.taskgroup.TaskGroupError: unhandled errors in a TaskGroup; 1 sub errors: (InvalidSchemaNameError)
 + InvalidSchemaNameError: schema "edgedb" does not exist
 |   File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/server/baseport.py", line 66, in new_compiler
 |     await compiler_worker.call('connect', dbname, dbver)
 |   File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/server/procpool/pool.py", line 120, in call
 |     raise exc



============== During handling of the above exception, another exception occurred ==============

1. asyncpg.exceptions.InvalidSchemaNameError: schema "edgedb" does not exist

------------------------------------------ Traceback -------------------------------------------

    edb/server/mng_port/edgecon.pyx, line 1280, in edb.server.mng_port.edgecon.EdgeConnection.main

    edb/server/mng_port/edgecon.pyx, line 266, in auth

    /usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/server/mng_port/port.py, line 98, in new_backend
        > raise ex.errors[0]
    /usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/server/baseport.py, line 66, in new_compiler
        > await compiler_worker.call('connect', dbname, dbver)
    /usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/server/procpool/pool.py, line 120, in call
        > raise exc

asyncpg.exceptions.InvalidSchemaNameError: schema "edgedb" does not exist
ERROR 12310 2020-05-10 03:13:03,369 asyncio: unhandled error in edgedb protocol while accepting new connection
protocol: <edb.server.mng_port.edgecon.EdgeConnection object at 0x7f44bc65d4a0>
task: <Task pending name='Task-18' coro=<EdgeConnection.main() running>>
transport: None
```

**Comment by haikyuu** [comment]
I have dropped the lms database in postgresql and created it again successfully. It works fine now
