### ISSUE TITLE
Backward links and inheritence. Bug?

### ISSUE THREAD

**Issue by haikyuu** [edgedb/edgedb#1403]
I'm trying to access a property of a parent type through type intersection. Note that `Course` inherits from `HasSchedule` and this Select clause is in the context of a computed property. But
  - For `SELECT .<class[IS Course].scheduledAt` where scheduled at is a property from `HasSchedule` , I get the following error: `Error: ERROR: InvalidReferenceError: object type 'default::Course' has no link or property 'scheduledAt'`
  - For `SELECT (.<class[IS Course][IS HasSchedule]).scheduledAt`, i get the following error
```
Error: ERROR: InternalServerError: 'TypeIntersection' object has no attribute 'direction'
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/server/procpool/worker.py", line 75, in worker
          res = await meth(*args)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 1304, in compile_eql_tokens_in_tx
          return self._compile(ctx=ctx, tokens=eql_tokens)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 945, in _compile
          comp: dbstate.BaseQuery = self._compile_dispatch_ql(ctx, stmt)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 874, in _compile_dispatch_ql
          return self._compile_ql_migration(ctx, ql)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 608, in _compile_ql_migration
          cmd = s_ddl.compile_migration(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/schema/ddl.py", line 340, in compile_migration
          target_schema = apply_sdl(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/schema/ddl.py", line 364, in apply_sdl
          ddl_stmts = s_decl.sdl_to_ddl(current_schema, documents)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/edgeql/declarative.py", line 229, in sdl_to_ddl
          trace_dependencies(decl_ast, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/functools.py", line 874, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/edgeql/declarative.py", line 493, in trace_default
          _register_item(node, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/edgeql/declarative.py", line 603, in _register_item
          trace_dependencies(cmd, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/functools.py", line 874, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/edgeql/declarative.py", line 442, in trace_ConcretePointer
          _register_item(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/edgeql/declarative.py", line 618, in _register_item
          tdeps = qltracer.trace_refs(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/edgeql/tracer.py", line 126, in trace_refs
          trace(qltree, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/functools.py", line 874, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/edgeql/tracer.py", line 561, in trace_Select
          tip = trace(node.result, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/functools.py", line 874, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/edgeql/tracer.py", line 418, in trace_Path
          if prev_step.direction == '<':
      AttributeError: 'TypeIntersection' object has no attribute 'direction'
```

**Comment by elprans** [comment]
Yep, this is a bug with chained type intersections.

**Comment by msullivan** [comment]
I tried to replicate the bug from your description, and wasn't able to. Since there's been a fair amount of change since the report, I think this may have been fixed. If it hasn't been, could you let us know and share a full schema where the issue can be reproduced?

Thanks!
