### ISSUE TITLE
BUG in latest nightly: 'edb.server.pgcon.pgcon.PGProto' object has no attribute 'send_flush'

### ISSUE THREAD

**Issue by haikyuu** [edgedb/edgedb#1434]
- EdgeDB Version:1.0-alpha.3+dev.204.g4d5cacba
- OS Version: Debian 10

Steps to Reproduce:

2. edgedb -u edgedb -d edgedb
```
Error: request error: ERROR: InternalServerError: 'edb.server.pgcon.pgcon.PGProto' object has no attribute 'send_flush'
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "edb/server/mng_port/edgecon.pyx", line 1349, in edb.server.mng_port.edgecon.EdgeConnection.main
        File "edb/server/mng_port/edgecon.pyx", line 1567, in edb.server.mng_port.edgecon.EdgeConnection.fallthrough
      AttributeError: 'edb.server.pgcon.pgcon.PGProto' object has no attribute 'send_flush'
```

**Comment by haikyuu** [comment]
Restarting the `edgedb-server` causes the following error:
```
-- The job identifier is 4326.
May 28 16:37:39 ip-172-16-1-100 edgedb-server[17703]: INFO 17703 2020-05-28 16:37:39,451 edb.server: EdgeDB server (1.0-alpha.3+dev.204.g4d5cacba) starting.
May 28 16:37:40 ip-172-16-1-100 edgedb-server[17703]: WARNING 17703 2020-05-28 16:37:40,520 py.warnings: /usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/server/pgcluster.p
May 28 16:37:40 ip-172-16-1-100 edgedb-server[17703]:   is_rds = loop.run_until_complete(_is_rds())
May 28 16:37:40 ip-172-16-1-100 edgedb-server[17703]: ---- Exception occurred: [Errno 111] Connection refused ----
May 28 16:37:40 ip-172-16-1-100 edgedb-server[17703]: 1. ConnectionRefusedError: [Errno 111] Connection refused
May 28 16:37:40 ip-172-16-1-100 edgedb-server[17703]: ---- Traceback ----
May 28 16:37:40 ip-172-16-1-100 edgedb-server[17703]:     /usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/bin/edgedb-server, line 10, in <module>
May 28 16:37:40 ip-172-16-1-100 edgedb-server[17703]:         > sys.exit(main())
May 28 16:37:40 ip-172-16-1-100 edgedb-server[17703]:     /usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/click/core.py, line 722, in __call__
May 28 16:37:40 ip-172-16-1-100 edgedb-server[17703]:         > return self.main(*args, **kwargs)
May 28 16:37:40 ip-172-16-1-100 edgedb-server[17703]:     /usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/click/core.py, line 697, in main
May 28 16:37:40 ip-172-16-1-100 edgedb-server[17703]:         > rv = self.invoke(ctx)
May 28 16:37:40 ip-172-16-1-100 edgedb-server[17703]:     /usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/click/core.py, line 895, in invoke
May 28 16:37:40 ip-172-16-1-100 edgedb-server[17703]:         > return ctx.invoke(self.callback, **ctx.params)
May 28 16:37:40 ip-172-16-1-100 edgedb-server[17703]:     /usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/click/core.py, line 535, in invoke
May 28 16:37:40 ip-172-16-1-100 edgedb-server[17703]:         > return callback(*args, **kwargs)
May 28 16:37:40 ip-172-16-1-100 edgedb-server[17703]:     /usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/server/main.py, line 597, in main
May 28 16:37:40 ip-172-16-1-100 edgedb-server[17703]:         > server_main(**kwargs)
May 28 16:37:40 ip-172-16-1-100 edgedb-server[17703]:     /usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/server/main.py, line 586, in server_main
May 28 16:37:40 ip-172-16-1-100 edgedb-server[17703]:         > run_server(ServerConfig(**kwargs))
May 28 16:37:40 ip-172-16-1-100 edgedb-server[17703]:     /usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/server/main.py, line 247, in run_server
May 28 16:37:40 ip-172-16-1-100 edgedb-server[17703]:         > cluster = pgcluster.get_remote_pg_cluster(args.postgres_dsn)
May 28 16:37:40 ip-172-16-1-100 edgedb-server[17703]:     /usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/server/pgcluster.py, line 740, in get_remote_pg_cluster
May 28 16:37:40 ip-172-16-1-100 edgedb-server[17703]:         > is_rds = loop.run_until_complete(_is_rds())
May 28 16:37:40 ip-172-16-1-100 edgedb-server[17703]:     uvloop/loop.pyx, line 1456, in uvloop.loop.Loop.run_until_complete
May 28 16:37:40 ip-172-16-1-100 edgedb-server[17703]:
May 28 16:37:40 ip-172-16-1-100 edgedb-server[17703]:     /usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/server/pgcluster.py, line 728, in _is_rds
May 28 16:37:40 ip-172-16-1-100 edgedb-server[17703]:         > conn = await rcluster.connect()
May 28 16:37:40 ip-172-16-1-100 edgedb-server[17703]:     /usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/edb/server/pgcluster.py, line 84, in connect
May 28 16:37:40 ip-172-16-1-100 edgedb-server[17703]:         > conn = await asyncpg.connect(loop=loop, **conn_info)
May 28 16:37:40 ip-172-16-1-100 edgedb-server[17703]:     /usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/asyncpg/connection.py, line 1668, in connect
May 28 16:37:40 ip-172-16-1-100 edgedb-server[17703]:         > return await connect_utils._connect(
May 28 16:37:40 ip-172-16-1-100 edgedb-server[17703]:     /usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/asyncpg/connect_utils.py, line 663, in _connect
May 28 16:37:40 ip-172-16-1-100 edgedb-server[17703]:         > raise last_error
May 28 16:37:40 ip-172-16-1-100 edgedb-server[17703]:     /usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/asyncpg/connect_utils.py, line 652, in _connect
May 28 16:37:40 ip-172-16-1-100 edgedb-server[17703]:         > con = await _connect_addr(
May 28 16:37:40 ip-172-16-1-100 edgedb-server[17703]:     /usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/site-packages/asyncpg/connect_utils.py, line 621, in _connect_addr
May 28 16:37:40 ip-172-16-1-100 edgedb-server[17703]:         > tr, pr = await asyncio.wait_for(
May 28 16:37:40 ip-172-16-1-100 edgedb-server[17703]:     /usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha3/lib/python3.8/asyncio/tasks.py, line 483, in wait_for
May 28 16:37:40 ip-172-16-1-100 edgedb-server[17703]:         > return fut.result()
May 28 16:37:40 ip-172-16-1-100 edgedb-server[17703]:     uvloop/loop.pyx, line 1974, in create_connection
May 28 16:37:40 ip-172-16-1-100 edgedb-server[17703]:
May 28 16:37:40 ip-172-16-1-100 edgedb-server[17703]:     uvloop/loop.pyx, line 1951, in uvloop.loop.Loop.create_connection
May 28 16:37:40 ip-172-16-1-100 edgedb-server[17703]:
May 28 16:37:40 ip-172-16-1-100 edgedb-server[17703]: ConnectionRefusedError: [Errno 111] Connection refused
May 28 16:37:41 ip-172-16-1-100 systemd[1]: edgedb-server-1-alpha3.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by haikyuu** [comment]
And running admin commands `sudo edgedb --admin -H localhost configure insert Auth --method=Trust --priority 1`
```
Error: Can't connect to unix socket "/var/run/edgedb/.s.EDGEDB.admin.5656"

Caused by:
    No such file or directory (os error 2)
```

**Comment by 1st1** [comment]
This was an intermittent breakage of the master branch that accidentally was picked up by the nightly build process. It has been already fixed. Still, huge thanks for bringing this up -- this was the kind of error that we could have not detected in time.

**Comment by 1st1** [comment]
Would really appreciate if you could try tonight's nightly and see if it works as expected for you.

**Comment by haikyuu** [comment]
You're welcome @1st1, I will. 

In the meantime, how can i install the nightly build of yesterday?

**Comment by elprans** [comment]
The yesteday's nightly [failed to build](https://github.com/edgedb/edgedb/actions/runs/117397886), unfortunately, so look for tonights build.
