### ISSUE TITLE
Changing the text of an annotation via SDL returns InternalServerError: 'NoneType' object has no attribute 'get_name'

### ISSUE THREAD

**Issue by CodesInChaos** [edgedb/edgedb#1618]
- EdgeDB Version: Alpha 4
- OS Version: Ubuntu 20

Create the following schema via SDL:

```
START MIGRATION TO {
	module default {
		abstract annotation description;
		
		abstract link Ordered {
			annotation description := "1";
		}
	}
};
populate migration;
commit migration;
```

then execute the same migration again, with a different value for the description (e.g. `"2"`).

It fails with the following error:

```
ERROR: InternalServerError: 'NoneType' object has no attribute 'get_name'
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/server/procpool/worker.py", line 75, in worker
          res = await meth(*args)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 1704, in compile_eql_tokens_in_tx
          return self._compile(ctx=ctx, tokens=eql_tokens)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 1319, in _compile
          comp: dbstate.BaseQuery = self._compile_dispatch_ql(ctx, stmt)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 1242, in _compile_dispatch_ql
          return self._compile_ql_migration(ctx, ql)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 937, in _compile_ql_migration
          ddl_query = self._compile_and_apply_ddl_stmt(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 748, in _compile_and_apply_ddl_stmt
          block, new_types = self._process_delta(ctx, delta)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 433, in _process_delta
          self._compile_schema_storage_in_delta(ctx, delta, subblock)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 452, in _compile_schema_storage_in_delta
          s_refl.write_meta(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/functools.py", line 875, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/schema/reflection/writer.py", line 147, in write_meta_delta_root
          _descend(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/schema/reflection/writer.py", line 112, in _descend
          write_meta(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/functools.py", line 875, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/schema/reflection/writer.py", line 649, in write_meta_create_object
          _descend(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/schema/reflection/writer.py", line 112, in _descend
          write_meta(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/functools.py", line 875, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/schema/reflection/writer.py", line 717, in write_meta_alter_object
          _descend(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/schema/reflection/writer.py", line 112, in _descend
          write_meta(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/functools.py", line 875, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/schema/reflection/writer.py", line 707, in write_meta_alter_object
          _update_lprops(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/schema/reflection/writer.py", line 754, in _update_lprops
          target_ref = target_obj.get_name(schema)
      AttributeError: 'NoneType' object has no attribute 'get_name'
```

**Comment by CodesInChaos** [comment]
That was quick :+1:
