### ISSUE TITLE
ERROR:           assert isinstance(other, ObjectType)

### ISSUE THREAD

**Issue by isidentical** [edgedb/edgedb#1767]
I guess this is not a legit use case, which is OK (just trying to find my way around the queries), reporting since raw assertions might be replaced.
```
asttests> SELECT <model> FILTER .left = ();
ERROR: InternalServerError: 
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha5/lib/python3.8/site-packages/edb/server/procpool/worker.py", line 75, in worker
          res = await meth(*args)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha5/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 1795, in compile_eql_tokens
          return self._compile(ctx=ctx, tokens=eql_tokens)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha5/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 1429, in _compile
          comp: dbstate.BaseQuery = self._compile_dispatch_ql(ctx, stmt)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha5/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 1392, in _compile_dispatch_ql
          return self._compile_ql_query(ctx, ql)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha5/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 592, in _compile_ql_query
          ir = qlcompiler.compile_ast_to_ir(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha5/lib/python3.8/site-packages/edb/edgeql/compiler/__init__.py", line 175, in wrapper
          return func(*args, **kwargs)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha5/lib/python3.8/site-packages/edb/edgeql/compiler/__init__.py", line 223, in compile_ast_to_ir
          ir_set = dispatch_mod.compile(tree, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha5/lib/python3.8/functools.py", line 875, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha5/lib/python3.8/site-packages/edb/edgeql/compiler/stmt.py", line 92, in compile_SelectQuery
          clauses.compile_where_clause(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha5/lib/python3.8/site-packages/edb/edgeql/compiler/clauses.py", line 51, in compile_where_clause
          ir_expr = dispatch.compile(where, ctx=subctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha5/lib/python3.8/functools.py", line 875, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha5/lib/python3.8/site-packages/edb/edgeql/compiler/expr.py", line 78, in compile_BinOp
          op_node = func.compile_operator(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha5/lib/python3.8/site-packages/edb/edgeql/compiler/func.py", line 368, in compile_operator
          matched = polyres.find_callable(opers, args=args, kwargs={}, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha5/lib/python3.8/site-packages/edb/edgeql/compiler/polyres.py", line 86, in find_callable
          call = try_bind_call_args(args, kwargs, candidate, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha5/lib/python3.8/site-packages/edb/edgeql/compiler/polyres.py", line 330, in try_bind_call_args
          cd = _get_cast_distance(arg_val, arg_type, param_type)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha5/lib/python3.8/site-packages/edb/edgeql/compiler/polyres.py", line 183, in _get_cast_distance
          resolved_poly_base_type.find_common_implicitly_castable_type(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha5/lib/python3.8/site-packages/edb/schema/objtypes.py", line 170, in find_common_implicitly_castable_type
          assert isinstance(other, ObjectType)
      AssertionError
```

**Comment by 1st1** [comment]
This has been fixed, closing.
