### ISSUE TITLE
edgedb.errors.InternalServerError: could not serialize result in worker subprocess

### ISSUE THREAD

**Issue by isidentical** [edgedb/edgedb#1770]
This happens ~oftenly while I'm inserting tons of nodes. I don't know whether it is relevant or not, but I have a multiprocessing setup (ProcessPoolExecutor) which I insert using 1 transaction per process, and the transactions include the creation up to 10k nodes. (setup is the same with my other issues)

```
Traceback (most recent call last):
  File "/home/isidentical/reiz.io/reiz/db/insert.py", line 121, in insert
    if conversion := convert(child, connection):
  File "/home/isidentical/reiz.io/reiz/db/insert.py", line 105, in convert
    ", ".join(convert(value, connection) for value in child), "{}"
  File "/home/isidentical/reiz.io/reiz/db/insert.py", line 105, in <genexpr>
    ", ".join(convert(value, connection) for value in child), "{}"
  File "/home/isidentical/reiz.io/reiz/db/insert.py", line 99, in convert
    {"id": "<uuid>" + repr(str(insert(child, connection).id))},
  File "/home/isidentical/reiz.io/reiz/db/insert.py", line 124, in insert
    return connection.query_one(query)
  File "/home/isidentical/.venv38/lib/python3.8/site-packages/edgedb/blocking_con.py", line 108, in query_one
    return self._protocol.sync_execute_anonymous(
  File "edgedb/protocol/blocking_proto.pyx", line 91, in edgedb.protocol.blocking_proto.BlockingIOProtocol.sync_execute_anonymous
  File "edgedb/protocol/blocking_proto.pyx", line 77, in edgedb.protocol.blocking_proto.BlockingIOProtocol._iter_coroutine
  File "edgedb/protocol/protocol.pyx", line 526, in execute_anonymous
  File "edgedb/protocol/protocol.pyx", line 220, in _parse
edgedb.errors.InternalServerError: could not serialize result in worker subprocess
```

**Comment by isidentical** [comment]
From the same context (if needed can share some queries, but would be tricky to run them since they are all auto-generated, long, and multi-step things). Just sharing if it would make sense since I am unable to create a short reproducer, can close the issue if it doesn't make any sense.
```
Traceback (most recent call last):
  File "/home/isidentical/reiz.io/reiz/db/insert.py", line 158, in inject_project
    with connection.transaction():
  File "/home/isidentical/.venv38/lib/python3.8/site-packages/edgedb/blocking_con.py", line 108, in query_one
    return self._protocol.sync_execute_anonymous(
  File "edgedb/protocol/blocking_proto.pyx", line 91, in edgedb.protocol.blocking_proto.BlockingIOProtocol.sync_execute_anonymous
  File "edgedb/protocol/blocking_proto.pyx", line 77, in edgedb.protocol.blocking_proto.BlockingIOProtocol._iter_coroutine
  File "edgedb/protocol/protocol.pyx", line 542, in execute_anonymous
  File "edgedb/protocol/protocol.pyx", line 339, in _execute
edgedb.errors.InternalServerError: duplicate key value violates unique constraint "d190f438-f5f2-11ea-bd51-978163450_source_ptr_item_id_target_key"
```

**Comment by elprans** [comment]
Please provide a query and schema, if possible.

**Comment by isidentical** [comment]
> Please provide a query and schema, if possible.

Okay, so the first one, it is related with the length of query I guess. This is the schema and a log file contains all queries executed step by step: https://gist.github.com/isidentical/1e44b5ded525291cf7e88d1435f8e2f6

**Comment by isidentical** [comment]
Don't know if it would helpful but this is the query-set that leads to the `RecursionError` https://gist.github.com/isidentical/dbd6f9a84c6d44167f6fd5f9bb66b542

**Comment by isidentical** [comment]
Since it is from the same schema, here is another different InternalServerError that I've encountered (caused from a different reason than just very long queries), @elprans any idea?
```
asttests> SELECT ast::Dict FILTER count(.keys) = 1 AND array_agg(.keys) = [(SELECT ast::Expr)];
ERROR: InternalServerError: cannot determine type of empty array
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      edb.errors.InternalServerError: cannot determine type of empty array
```

**Comment by elprans** [comment]
> `[(SELECT ast::Expr)]`

The above doesn't do what you think it does, you want `array_agg(ast::Expr)` instead.

(`[<set>]` evaluates to a set of single-element arrays for every element of `<set>`)

That said, the bug is still there, as `[<set>]` is a valid expression.

**Comment by elprans** [comment]
> RecursionError

This should have been fixed to an extent in #1785.

**Comment by isidentical** [comment]
> The above doesn't do what you think it does, you want array_agg(ast::Expr) instead.
What I want to do is that matching whether `.keys` (`multi link ast::expr`) is a single-item set where the only item is the type of `ast::Something`. I don't think `array_agg(ast::Something)` would cover this? (btw it still gives the error)
```
asttests> SELECT ast::Dict FILTER array_agg(.keys) != array_agg(ast::Constant);
ERROR: InternalServerError: cannot determine type of empty array
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      edb.errors.InternalServerError: cannot determine type of empty array
```

> This should have been fixed to an extent in #1785.
Awesome!

**Comment by elprans** [comment]
> is a single-item set where the only item is the type of `ast::Something`

Oh.  Then the correct query would be this:

`SELECT ast::Dict FILTER count(.keys) = 1 AND all(.keys IS ast::Constant);`

`=` compares values, not types.

**Comment by isidentical** [comment]
Thanks for the help!
