### ISSUE TITLE
@target and @source are pretty broken

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb#1786]
query:

```
SELECT schema::ObjectType {
  name,
  is_abstract,
  bases: {
    name,
  } ORDER BY @index ASC,
  pointers: {
    cardinality,
    required,
    name,
    target: {
      name,
    },
    kind := 'link' IF @target IS schema::Link ELSE 'property'
  },
} FILTER NOT .is_compound_type;
```

**Comment by msullivan** [comment]
What is the correct behavior here? Rejecting the query because `target` is not a link attribute?

**Comment by elprans** [comment]
`@target` is a property present on all links.  `Foo.link@target` is equivalent to `Foo.link` in an expression, and it's probably easiest to make it equivalent in `compile_path` to avoid having to deal with a link property path that is not a scalar.

There are a couple of places where `@target` is useful: 1) in the example above as an abbreviated path to "self" in a shape; 2) in constraints on links, e.g `constraint exclusive on ((@property, @target))`.

**Comment by msullivan** [comment]
Ah, ok. And `SELECT Foo.link@target` ought to deduplicate, just like `SELECT Foo.link` does, I assume?
(I ask because my first attempt on this was to directly patch the crashing code to do an isinstance, and then we excitingly wind up with non-deduplicated results)

**Comment by msullivan** [comment]
Hm, though actually maybe not deduplicating makes more sense, since it is operating on the *link*...

**Comment by elprans** [comment]
> Hm, though actually maybe not deduplicating makes more sense, since it is operating on the _link_...

Exactly. See comment in `attach_path` in `scopetree.py`

**Comment by msullivan** [comment]
Elvis and I discussed this offline and the feeling is that `Foo.link@target` *should* be deduplicated--that all paths to objects should.

Making @target get deduplicated properly was a simple matter of handling it in `compile_path`. Working on @source now.

**Comment by 1st1** [comment]
> Elvis and I discussed this offline and the feeling is that Foo.link@target should be deduplicated--that all paths to objects should.

+1.

**Comment by vpetrovykh** [comment]
Currently just using `@target` in a path causes problems:
```
expraliases> select User.awards@target;
ERROR: InternalServerError: 'PointerRef' object has no attribute 'is_scalar'
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "/home/victor/dev/magicstack/edgedb/edb/pgsql/compiler/__init__.py", line 100, in compile_ir_to_sql_tree
          qtree = dispatch.compile(ir_expr, ctx=ctx)
        File "/usr/lib/python3.9/functools.py", line 877, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/home/victor/dev/magicstack/edgedb/edb/pgsql/compiler/expr.py", line 60, in compile_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/home/victor/dev/magicstack/edgedb/edb/pgsql/compiler/expr.py", line 114, in _compile_set_impl
          _compile_set(ir_set, ctx=ctx)
        File "/home/victor/dev/magicstack/edgedb/edb/pgsql/compiler/expr.py", line 589, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/home/victor/dev/magicstack/edgedb/edb/pgsql/compiler/relgen.py", line 160, in get_set_rvar
          return _process_toplevel_query(ir_set, ctx=ctx)
        File "/home/victor/dev/magicstack/edgedb/edb/pgsql/compiler/relgen.py", line 268, in _process_toplevel_query
          rvars = _get_set_rvar(ir_set, ctx=ctx)
        File "/home/victor/dev/magicstack/edgedb/edb/pgsql/compiler/relgen.py", line 302, in _get_set_rvar
          rvars = process_set_as_subquery(ir_set, stmt, ctx=ctx)
        File "/home/victor/dev/magicstack/edgedb/edb/pgsql/compiler/relgen.py", line 1253, in process_set_as_subquery
          dispatch.visit(ir_set.expr, ctx=newctx)
        File "/usr/lib/python3.9/functools.py", line 877, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/home/victor/dev/magicstack/edgedb/edb/pgsql/compiler/dispatch.py", line 44, in visit
          compile(ir, ctx=ctx)
        File "/usr/lib/python3.9/functools.py", line 877, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/home/victor/dev/magicstack/edgedb/edb/pgsql/compiler/stmt.py", line 98, in compile_SelectStmt
          outvar = clauses.compile_output(stmt.result, ctx=ictx)
        File "/home/victor/dev/magicstack/edgedb/edb/pgsql/compiler/clauses.py", line 230, in compile_output
          dispatch.visit(ir_set, ctx=newctx)
        File "/usr/lib/python3.9/functools.py", line 877, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/home/victor/dev/magicstack/edgedb/edb/pgsql/compiler/expr.py", line 85, in visit_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/home/victor/dev/magicstack/edgedb/edb/pgsql/compiler/expr.py", line 114, in _compile_set_impl
          _compile_set(ir_set, ctx=ctx)
        File "/home/victor/dev/magicstack/edgedb/edb/pgsql/compiler/expr.py", line 589, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/home/victor/dev/magicstack/edgedb/edb/pgsql/compiler/relgen.py", line 214, in get_set_rvar
          rvars = _get_set_rvar(ir_set, ctx=subctx)
        File "/home/victor/dev/magicstack/edgedb/edb/pgsql/compiler/relgen.py", line 396, in _get_set_rvar
          rvars = process_set_as_path(ir_set, stmt, ctx=ctx)
        File "/home/victor/dev/magicstack/edgedb/edb/pgsql/compiler/relgen.py", line 950, in process_set_as_path
          ptr_info = pg_types.get_ptrref_storage_info(
        File "/home/victor/dev/magicstack/edgedb/edb/pgsql/types.py", line 432, in get_ptrref_storage_info
          return _get_ptrref_storage_info(
        File "/home/victor/dev/magicstack/edgedb/edb/pgsql/types.py", line 484, in _get_ptrref_storage_info
          if irtyputils.is_scalar(source):
        File "/home/victor/dev/magicstack/edgedb/edb/ir/typeutils.py", line 55, in is_scalar
          return typeref.is_scalar
      AttributeError: 'PointerRef' object has no attribute 'is_scalar'
      The above exception was the direct cause of the following exception:
      Traceback (most recent call last):
        File "/home/victor/dev/magicstack/edgedb/edb/server/compiler_pool/worker.py", line 311, in worker
          res = meth(*args)
        File "/home/victor/dev/magicstack/edgedb/edb/server/compiler_pool/worker.py", line 180, in compile
          units, cstate = COMPILER.compile(
        File "/home/victor/dev/magicstack/edgedb/edb/server/compiler/compiler.py", line 2011, in compile
          units = self._compile(ctx=ctx, source=source)
        File "/home/victor/dev/magicstack/edgedb/edb/server/compiler/compiler.py", line 1588, in _compile
          return self._try_compile(ctx=ctx, source=source)
        File "/home/victor/dev/magicstack/edgedb/edb/server/compiler/compiler.py", line 1641, in _try_compile
          comp, capabilities = self._compile_dispatch_ql(ctx, stmt)
        File "/home/victor/dev/magicstack/edgedb/edb/server/compiler/compiler.py", line 1562, in _compile_dispatch_ql
          query = self._compile_ql_query(ctx, ql)
        File "/home/victor/dev/magicstack/edgedb/edb/server/compiler/compiler.py", line 599, in _compile_ql_query
          sql_text, argmap = pg_compiler.compile_ir_to_sql(
        File "/home/victor/dev/magicstack/edgedb/edb/pgsql/compiler/__init__.py", line 122, in compile_ir_to_sql
          qtree = compile_ir_to_sql_tree(
        File "/home/victor/dev/magicstack/edgedb/edb/pgsql/compiler/__init__.py", line 107, in compile_ir_to_sql_tree
          raise errors.InternalServerError(*args) from e
      edb.errors.InternalServerError: 'PointerRef' object has no attribute 'is_scalar'
```
