### ISSUE TITLE
Possible protocol error triggered by tests

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb#1792]
This happens in the https://github.com/edgedb/edgedb/tree/migtests branch.

Steps to Reproduce:

`EDGEDB_DEBUG_SERVER=1 edb test -k test_edgeql_migration_eq_`

After running about 50 tests or so the test suite crashes with:
```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/victor/dev/magicstack/edgedb/edb/tools/test/runner.py", line 144, in _run_test
    suite.run(test, result)
  File "/home/victor/dev/magicstack/edgedb/edb/tools/test/runner.py", line 109, in run
    self._run(test, result)
  File "/home/victor/dev/magicstack/edgedb/edb/tools/test/runner.py", line 129, in _run
    test.run(result)
  File "/usr/lib/python3.8/unittest/case.py", line 684, in run
    self._feedErrorsToResult(result, outcome.errors)
  File "/usr/lib/python3.8/unittest/case.py", line 602, in _feedErrorsToResult
    result.addError(test, exc_info)
  File "/home/victor/dev/magicstack/edgedb/edb/tools/test/runner.py", line 168, in _wrapper
    self._queue.put((meth, args, kwargs))
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 362, in put
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "stringsource", line 2, in edgedb.pgproto.pgproto.ReadBuffer.__reduce_cython__
TypeError: no default __reduce__ due to non-trivial __cinit__
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/victor/dev/venvs/edgedb/bin/edb", line 33, in <module>
    sys.exit(load_entry_point('edgedb-server', 'console_scripts', 'edb')())
  File "/home/victor/dev/venvs/edgedb/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/victor/dev/venvs/edgedb/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/victor/dev/venvs/edgedb/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/victor/dev/venvs/edgedb/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/victor/dev/venvs/edgedb/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/victor/dev/magicstack/edgedb/edb/tools/test/__init__.py", line 153, in test
    result = run()
  File "/home/victor/dev/magicstack/edgedb/edb/tools/test/__init__.py", line 265, in _run
    result = test_runner.run(suite)
  File "/home/victor/dev/magicstack/edgedb/edb/tools/test/runner.py", line 798, in run
    suite.run(result)
  File "/home/victor/dev/magicstack/edgedb/edb/tools/test/runner.py", line 262, in run
    ar.get(timeout=0.1)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
TypeError: no default __reduce__ due to non-trivial __cinit__
```

Printing out the `error_text` gets some additional insight as to what actually went wrong: https://github.com/edgedb/edgedb/blob/fa1b42a938141839316366d396e20c9d7c9123f0/edb/tools/test/runner.py#L163-L166 
```
Traceback (most recent call last):
  File "/home/victor/dev/magicstack/edgedb/tests/test_edgeql_data_migration.py", line 103, in migrate
    await self.con.execute(f"""
  File "/home/victor/dev/magicstack/edgedb-python/edgedb/asyncio_con.py", line 166, in execute
    await self._protocol.simple_query(query)
  File "edgedb/protocol/protocol.pyx", line 498, in simple_query
edgedb.errors.InternalServerError: unexpected message type '3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/victor/dev/magicstack/edgedb/edb/testbase/server.py", line 110, in wrapper
    self.loop.run_until_complete(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/victor/dev/magicstack/edgedb/tests/test_edgeql_data_migration.py", line 6027, in test_edgeql_migration_eq_collections_18
    await self.migrate(r"""
  File "/home/victor/dev/magicstack/edgedb/tests/test_edgeql_data_migration.py", line 103, in migrate
    await self.con.execute(f"""
  File "/home/victor/dev/magicstack/edgedb-python/edgedb/transaction.py", line 211, in __aexit__
    await self.__rollback()
  File "/home/victor/dev/magicstack/edgedb-python/edgedb/transaction.py", line 242, in __rollback
    await self._connection.execute(query)
  File "/home/victor/dev/magicstack/edgedb-python/edgedb/asyncio_con.py", line 166, in execute
    await self._protocol.simple_query(query)
  File "edgedb/protocol/protocol.pyx", line 498, in simple_query
edgedb.errors.TransactionError: savepoints can only be used in transaction blocks
```

Note, `EDGEDB_DEBUG_SERVER=1 edb test -j1 -k test_edgeql_migration_eq_` ultimately results in an error around the same point in tests as well. The error still seems to be triggered by `edgedb.errors.InternalServerError: unexpected message type '3'`, but it manifests a bit differently after that.

**Comment by elprans** [comment]
Fixed.
