### ISSUE TITLE
InternalServerError: <class 'edb.schema.annos.AnnotationValue'> has no edgeql class string assigned

### ISSUE THREAD

**Issue by nsidnev** [edgedb/edgedb#1797]
- EdgeDB Version: EdgeDB server (1.0-alpha.6+dev.5078.gd187a933)
- EdgeDB CLI Version:  https://github.com/edgedb/edgedb-cli/commit/690582f187f70a1006c9cdcf5d1d8eeef1a3544d
- OS Version: Arch Linux x86_64 5.8.1-arch1-1

**NOTE**: not sure if something needs to be changed in the CLI also, since applying migration like in cheatsheet works as expected.

Steps to Reproduce:
1. Init new EdgeDB cluster with `edb server --temp-dir`.
2. Create `default.esdl` file in `~/projects/app/db` directory.
3. Fill it in with content from [cheatsheet](https://edgedb.com/docs/cheatsheet/migrations).
4. Try to create migration with `cargo run -- --user edgedb create-migration --schema-dir ~/projects/app/db`.
5. Get internal server error:
```
Error: ERROR: InternalServerError: <class 'edb.schema.annos.AnnotationValue'> has no edgeql class string assigned
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
          File "/home/nik/projects/edgedb/edgedb/edb/server/procpool/worker.py", line 75, in worker
          res = await meth(*args)
          File "/home/nik/projects/edgedb/edgedb/edb/server/compiler/compiler.py", line 1824, in compile_eql_tokens_in_tx
          return self._compile(ctx=ctx, tokens=eql_tokens)
          File "/home/nik/projects/edgedb/edgedb/edb/server/compiler/compiler.py", line 1437, in _compile
          comp: dbstate.BaseQuery = self._compile_dispatch_ql(ctx, stmt)
          File "/home/nik/projects/edgedb/edgedb/edb/server/compiler/compiler.py", line 1360, in _compile_dispatch_ql
          return self._compile_ql_migration(ctx, ql)
          File "/home/nik/projects/edgedb/edgedb/edb/server/compiler/compiler.py", line 888, in _compile_ql_migration
          guided_diff = s_ddl.delta_schemas(
          File "/home/nik/projects/edgedb/edgedb/edb/schema/ddl.py", line 281, in delta_schemas
          sd.delta_objects(
          File "/home/nik/projects/edgedb/edgedb/edb/schema/delta.py", line 165, in delta_objects
          x.as_create_delta(
          File "/home/nik/projects/edgedb/edgedb/edb/schema/objects.py", line 1366, in as_create_delta
          delta.add(ref.as_create_delta(schema, context))
          File "/home/nik/projects/edgedb/edgedb/edb/schema/objects.py", line 1366, in as_create_delta
          delta.add(ref.as_create_delta(schema, context))
          File "/home/nik/projects/edgedb/edgedb/edb/schema/objects.py", line 1335, in as_create_delta
          delta.set_annotation('op_id', sd.get_object_command_id(delta))
          File "/home/nik/projects/edgedb/edgedb/edb/schema/delta.py", line 2990, in get_object_command_id
          qlcls = delta.get_schema_metaclass().get_ql_class_or_die()
          File "/home/nik/projects/edgedb/edgedb/edb/schema/objects.py", line 725, in get_ql_class_or_die
          raise LookupError(f'{cls} has no edgeql class string assigned')
          LookupError: <class 'edb.schema.annos.AnnotationValue'> has no edgeql class string assigned
```

**Comment by 1st1** [comment]
@vpetrovykh please take a look

**Comment by elprans** [comment]
This is fixed.
