### ISSUE TITLE
InternalServerError: While creating a new enum Scalar type

### ISSUE THREAD

**Issue by clmno** [edgedb/edgedb#1902]
- EdgeDB Version: 1.0-alpha.5+g83a2a4fac.d20200826 (repl 1.0.0-alpha.6)
- OS Version: Ubuntu 20.04.1 LTS

Steps to Reproduce:

1. Create a new database
```
create database tutorial;
```
2. Create a new `enum` scalar type
```
CREATE SCALAR TYPE ConsumptionType EXTENDING enum<veg, nonveg, none>;
```

**Server Traceback**
```
Traceback (most recent call last):
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha5/lib/python3.8/site-packages/edb/server/procpool/worker.py", line 75, in worker
          res = await meth(*args)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha5/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 1795, in compile_eql_tokens
          return self._compile(ctx=ctx, tokens=eql_tokens)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha5/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 1429, in _compile
          comp: dbstate.BaseQuery = self._compile_dispatch_ql(ctx, stmt)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha5/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 1364, in _compile_dispatch_ql
          return self._compile_and_apply_ddl_stmt(ctx, ql)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha5/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 714, in _compile_and_apply_ddl_stmt
          delta = s_ddl.delta_from_ddl(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha5/lib/python3.8/site-packages/edb/schema/ddl.py", line 443, in delta_from_ddl
          _, cmd = _delta_from_ddl(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha5/lib/python3.8/site-packages/edb/schema/ddl.py", line 478, in _delta_from_ddl
          cmd = cmd_from_ddl(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha5/lib/python3.8/site-packages/edb/schema/ddl.py", line 324, in cmd_from_ddl
          return sd.compile_ddl(schema, ddl, context=context)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha5/lib/python3.8/site-packages/edb/schema/delta.py", line 2913, in compile_ddl
          cmd = cmdcls._cmd_tree_from_ast(schema, astnode, context)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha5/lib/python3.8/site-packages/edb/schema/scalars.py", line 241, in _cmd_tree_from_ast
          cmd = super()._cmd_tree_from_ast(schema, astnode, context)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha5/lib/python3.8/site-packages/edb/schema/inheriting.py", line 649, in _cmd_tree_from_ast
          bases = cls._classbases_from_ast(schema, astnode, context)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha5/lib/python3.8/site-packages/edb/schema/inheriting.py", line 448, in _classbases_from_ast
          obj = utils.ast_to_object_shell(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha5/lib/python3.8/site-packages/edb/schema/utils.py", line 247, in ast_to_object_shell
          return ast_to_type_shell(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha5/lib/python3.8/site-packages/edb/schema/utils.py", line 128, in ast_to_type_shell
          elements=[
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha5/lib/python3.8/site-packages/edb/schema/utils.py", line 129, in <listcomp>
          st.val.value
      AttributeError: 'TypeName' object has no attribute 'val'
```

**Comment by clmno** [comment]
Thank you @elprans it works in the newer version.
