### ISSUE TITLE
Crash when trying to select inserted link props

### ISSUE THREAD

**Issue by msullivan** [edgedb/edgedb#1921]
```
insert> \c insert
insert> SELECT (INSERT test::InsertTest { l2 := 10, subordinates := (SELECT test::Subordinate { @comment := "uh" }) }) { subordinates: {name, @comment} };
```
produces
```
ERROR: InternalServerError: cannot find refs for path (__derived__::expr~21).>subordinates[IS test::Subordinate]@comment[IS std::str] value in <pg.SelectStmt at 0x7fa636151c40>
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "/home/sully/src/e/edgedb/edb/pgsql/compiler/__init__.py", line 86, in compile_ir_to_sql_tree
          qtree = dispatch.compile(ir_expr, ctx=ctx)
        File "/usr/lib/python3.8/functools.py", line 875, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/home/sully/src/e/edgedb/edb/pgsql/compiler/expr.py", line 60, in compile_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/home/sully/src/e/edgedb/edb/pgsql/compiler/expr.py", line 118, in _compile_set_impl
          _compile_set(ir_set, ctx=ctx)
        File "/home/sully/src/e/edgedb/edb/pgsql/compiler/expr.py", line 599, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/home/sully/src/e/edgedb/edb/pgsql/compiler/relgen.py", line 136, in get_set_rvar
          return _process_toplevel_query(ir_set, ctx=ctx)
        File "/home/sully/src/e/edgedb/edb/pgsql/compiler/relgen.py", line 220, in _process_toplevel_query
          rvars = _get_set_rvar(ir_set, ctx=ctx)
        File "/home/sully/src/e/edgedb/edb/pgsql/compiler/relgen.py", line 233, in _get_set_rvar
          rvars = process_set_as_subquery(ir_set, stmt, ctx=ctx)
        File "/home/sully/src/e/edgedb/edb/pgsql/compiler/relgen.py", line 1101, in process_set_as_subquery
          dispatch.visit(ir_set.expr, ctx=newctx)
        File "/usr/lib/python3.8/functools.py", line 875, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/home/sully/src/e/edgedb/edb/pgsql/compiler/dispatch.py", line 44, in visit
          compile(ir, ctx=ctx)
        File "/usr/lib/python3.8/functools.py", line 875, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/home/sully/src/e/edgedb/edb/pgsql/compiler/stmt.py", line 85, in compile_SelectStmt
          outvar = clauses.compile_output(stmt.result, ctx=ictx)
        File "/home/sully/src/e/edgedb/edb/pgsql/compiler/clauses.py", line 176, in compile_output
          dispatch.visit(ir_set, ctx=newctx)
        File "/usr/lib/python3.8/functools.py", line 875, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/home/sully/src/e/edgedb/edb/pgsql/compiler/expr.py", line 85, in visit_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/home/sully/src/e/edgedb/edb/pgsql/compiler/expr.py", line 114, in _compile_set_impl
          _compile_set(ir_set, ctx=scopectx)
        File "/home/sully/src/e/edgedb/edb/pgsql/compiler/expr.py", line 603, in _compile_set
          _compile_shape(
        File "/home/sully/src/e/edgedb/edb/pgsql/compiler/expr.py", line 614, in _compile_shape
          result = shapecomp.compile_shape(ir_set, shape, ctx=ctx)
        File "/home/sully/src/e/edgedb/edb/pgsql/compiler/shapecomp.py", line 75, in compile_shape
          wrapper = relgen.set_as_subquery(
        File "/home/sully/src/e/edgedb/edb/pgsql/compiler/relgen.py", line 330, in set_as_subquery
          dispatch.visit(ir_set, ctx=subctx)
        File "/usr/lib/python3.8/functools.py", line 875, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/home/sully/src/e/edgedb/edb/pgsql/compiler/expr.py", line 85, in visit_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/home/sully/src/e/edgedb/edb/pgsql/compiler/expr.py", line 114, in _compile_set_impl
          _compile_set(ir_set, ctx=scopectx)
        File "/home/sully/src/e/edgedb/edb/pgsql/compiler/expr.py", line 603, in _compile_set
          _compile_shape(
        File "/home/sully/src/e/edgedb/edb/pgsql/compiler/expr.py", line 614, in _compile_shape
          result = shapecomp.compile_shape(ir_set, shape, ctx=ctx)
        File "/home/sully/src/e/edgedb/edb/pgsql/compiler/shapecomp.py", line 75, in compile_shape
          wrapper = relgen.set_as_subquery(
        File "/home/sully/src/e/edgedb/edb/pgsql/compiler/relgen.py", line 335, in set_as_subquery
          pathctx.get_path_serialized_output(
        File "/home/sully/src/e/edgedb/edb/pgsql/compiler/pathctx.py", line 1034, in get_path_serialized_output
          ref = get_path_serialized_or_value_var(rel, path_id, env=env)
        File "/home/sully/src/e/edgedb/edb/pgsql/compiler/pathctx.py", line 1017, in get_path_serialized_or_value_var
          ref = get_path_value_var(rel, path_id, env=env)
        File "/home/sully/src/e/edgedb/edb/pgsql/compiler/pathctx.py", line 382, in get_path_value_var
          return get_path_var(rel, path_id, aspect='value', env=env)
        File "/home/sully/src/e/edgedb/edb/pgsql/compiler/pathctx.py", line 328, in get_path_var
          outvar = get_path_output(
        File "/home/sully/src/e/edgedb/edb/pgsql/compiler/pathctx.py", line 852, in get_path_output
          return _get_path_output(rel, path_id=path_id, aspect=aspect,
        File "/home/sully/src/e/edgedb/edb/pgsql/compiler/pathctx.py", line 896, in _get_path_output
          ref = get_path_var(rel, path_id, aspect=aspect, env=env)
        File "/home/sully/src/e/edgedb/edb/pgsql/compiler/pathctx.py", line 215, in get_path_var
          raise LookupError(
      LookupError: cannot find refs for path (__derived__::expr~21).>subordinates[IS test::Subordinate]@comment[IS std::str] value in <pg.SelectStmt at 0x7fa636151c40>
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "/home/sully/src/e/edgedb/edb/server/procpool/worker.py", line 75, in worker
          res = await meth(*args)
        File "/home/sully/src/e/edgedb/edb/server/compiler/compiler.py", line 1800, in compile_eql_tokens
          return self._compile(ctx=ctx, tokens=eql_tokens)
        File "/home/sully/src/e/edgedb/edb/server/compiler/compiler.py", line 1428, in _compile
          comp: dbstate.BaseQuery = self._compile_dispatch_ql(ctx, stmt)
        File "/home/sully/src/e/edgedb/edb/server/compiler/compiler.py", line 1391, in _compile_dispatch_ql
          return self._compile_ql_query(ctx, ql)
        File "/home/sully/src/e/edgedb/edb/server/compiler/compiler.py", line 624, in _compile_ql_query
          sql_text, argmap = pg_compiler.compile_ir_to_sql(
        File "/home/sully/src/e/edgedb/edb/pgsql/compiler/__init__.py", line 108, in compile_ir_to_sql
          qtree = compile_ir_to_sql_tree(
        File "/home/sully/src/e/edgedb/edb/pgsql/compiler/__init__.py", line 93, in compile_ir_to_sql_tree
          raise errors.InternalServerError(*args) from e
      edb.errors.InternalServerError: cannot find refs for path (__derived__::expr~21).>subordinates[IS test::Subordinate]@comment[IS std::str] value in <pg.SelectStmt at 0x7fa636151c40>
```

**Comment by 1st1** [comment]
Looks like this is now working, closing the issue.
