### ISSUE TITLE
InternalServerError occurs when try to SELECT link property after UPDATE

### ISSUE THREAD

**Issue by NatureGeorge** [edgedb/edgedb#2094]
- EdgeDB Version:  1.0a7-2020122418~buster
- OS Version: Debian GNU/Linux 10 (buster) [WSL2, win10]

Steps to Reproduce:

### 1. schema -> ✅good

```py
type Place {
    required property name -> str;
    multi link neighbors -> Place {
        property distance -> float64;
    }
};
```

### 2. insert data -> ✅good

```py
FOR x IN {
     (name := 'A'),
     (name := 'B'),
     (name := 'C'),
     (name := 'D'),
     (name := 'E')
 }
UNION ( INSERT Place {name := x.name} );

WITH
    MODULE default,
    Pa := Place
FOR x IN {
    (
        name := 'A',
        neighbors := [('B', 6.6)]),
    (
        name := 'C',
        neighbors := [('A', 15.4), ('D', 3.3)]),
    (
        name := 'B',
        neighbors := [('E', 2.1)])
}
UNION (
    UPDATE Place
    FILTER .name = x.name
    SET {
        neighbors := (
            FOR f in {array_unpack(x.neighbors)}
            UNION (SELECT Pa {@distance := f.1} FILTER Pa.name = f.0)
        )
    }
);
```

### 3. SELECT (UPDATE ...) {...}; -> 💫something wrong here

```py
SELECT (
  UPDATE Place
  FILTER .name = 'B'
  SET {
    neighbors += (SELECT DETACHED Place{@distance:= 10.2} FILTER .name = 'C')})
{
   name,
   neighbors: {name, @distance}
};
```

<details>
<summary>⚠traceback info</summary>

```py
ERROR: InternalServerError: cannot find refs for path (__derived__::expr~19).>neighbors[IS default::Place]@distance[IS std::float64] value in <pg.SelectStmt at 0x7f57bd507760>
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md        
  Server traceback:
      Traceback (most recent call last):
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/site-packages/edb/pgsql/compiler/__init__.py", line 86, in compile_ir_to_sql_tree    
          qtree = dispatch.compile(ir_expr, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/functools.py", line 875, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/site-packages/edb/pgsql/compiler/expr.py", line 60, in compile_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/site-packages/edb/pgsql/compiler/expr.py", line 118, in _compile_set_impl
          _compile_set(ir_set, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/site-packages/edb/pgsql/compiler/expr.py", line 594, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/site-packages/edb/pgsql/compiler/relgen.py", line 136, in get_set_rvar
          return _process_toplevel_query(ir_set, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/site-packages/edb/pgsql/compiler/relgen.py", line 220, in _process_toplevel_query    
          rvars = _get_set_rvar(ir_set, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/site-packages/edb/pgsql/compiler/relgen.py", line 233, in _get_set_rvar
          rvars = process_set_as_subquery(ir_set, stmt, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/site-packages/edb/pgsql/compiler/relgen.py", line 1101, in process_set_as_subquery   
          dispatch.visit(ir_set.expr, ctx=newctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/functools.py", line 875, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/site-packages/edb/pgsql/compiler/dispatch.py", line 44, in visit
          compile(ir, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/functools.py", line 875, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/site-packages/edb/pgsql/compiler/stmt.py", line 85, in compile_SelectStmt
          outvar = clauses.compile_output(stmt.result, ctx=ictx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/site-packages/edb/pgsql/compiler/clauses.py", line 176, in compile_output
          dispatch.visit(ir_set, ctx=newctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/functools.py", line 875, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/site-packages/edb/pgsql/compiler/expr.py", line 85, in visit_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/site-packages/edb/pgsql/compiler/expr.py", line 114, in _compile_set_impl
          _compile_set(ir_set, ctx=scopectx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/site-packages/edb/pgsql/compiler/expr.py", line 598, in _compile_set
          _compile_shape(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/site-packages/edb/pgsql/compiler/expr.py", line 609, in _compile_shape
          result = shapecomp.compile_shape(ir_set, shape, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/site-packages/edb/pgsql/compiler/shapecomp.py", line 75, in compile_shape
          wrapper = relgen.set_as_subquery(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/site-packages/edb/pgsql/compiler/relgen.py", line 330, in set_as_subquery
          dispatch.visit(ir_set, ctx=subctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/functools.py", line 875, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/site-packages/edb/pgsql/compiler/expr.py", line 85, in visit_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/site-packages/edb/pgsql/compiler/expr.py", line 114, in _compile_set_impl
          _compile_set(ir_set, ctx=scopectx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/site-packages/edb/pgsql/compiler/expr.py", line 598, in _compile_set
          _compile_shape(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/site-packages/edb/pgsql/compiler/expr.py", line 609, in _compile_shape
          result = shapecomp.compile_shape(ir_set, shape, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/site-packages/edb/pgsql/compiler/shapecomp.py", line 75, in compile_shape
          wrapper = relgen.set_as_subquery(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/site-packages/edb/pgsql/compiler/relgen.py", line 335, in set_as_subquery
          pathctx.get_path_serialized_output(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/site-packages/edb/pgsql/compiler/pathctx.py", line 1031, in get_path_serialized_output
          ref = get_path_serialized_or_value_var(rel, path_id, env=env)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/site-packages/edb/pgsql/compiler/pathctx.py", line 1014, in get_path_serialized_or_value_var
          ref = get_path_value_var(rel, path_id, env=env)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/site-packages/edb/pgsql/compiler/pathctx.py", line 382, in get_path_value_var        
          return get_path_var(rel, path_id, aspect='value', env=env)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/site-packages/edb/pgsql/compiler/pathctx.py", line 328, in get_path_var
          outvar = get_path_output(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/site-packages/edb/pgsql/compiler/pathctx.py", line 849, in get_path_output
          return _get_path_output(rel, path_id=path_id, aspect=aspect,
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/site-packages/edb/pgsql/compiler/pathctx.py", line 893, in _get_path_output
          ref = get_path_var(rel, path_id, aspect=aspect, env=env)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/site-packages/edb/pgsql/compiler/pathctx.py", line 215, in get_path_var
          raise LookupError(
      LookupError: cannot find refs for path (__derived__::expr~19).>neighbors[IS default::Place]@distance[IS std::float64] value in <pg.SelectStmt at 0x7f57bd507760>

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/site-packages/edb/server/procpool/worker.py", line 75, in worker
          res = await meth(*args)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 1870, in compile
          return self._compile(ctx=ctx, source=source)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 1428, in _compile
          return self._try_compile(ctx=ctx, source=source)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 1482, in _try_compile
          comp, capabilities = self._compile_dispatch_ql(ctx, stmt)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 1415, in _compile_dispatch_ql   
          query = self._compile_ql_query(ctx, ql)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 634, in _compile_ql_query       
          sql_text, argmap = pg_compiler.compile_ir_to_sql(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/site-packages/edb/pgsql/compiler/__init__.py", line 108, in compile_ir_to_sql        
          qtree = compile_ir_to_sql_tree(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/site-packages/edb/pgsql/compiler/__init__.py", line 93, in compile_ir_to_sql_tree    
          raise errors.InternalServerError(*args) from e
      edb.errors.InternalServerError: cannot find refs for path (__derived__::expr~19).>neighbors[IS default::Place]@distance[IS std::float64] value in <pg.SelectStmt at 0x7f57bd507760>
```

</details>

### 4. SELECT after UPDATE -> ✅good

```py
UPDATE Place FILTER .name = 'B'
SET {neighbors += (SELECT DETACHED Place{@distance:= 10.2} FILTER .name = 'C')};

SELECT Place {
  name,
  neighbors: {name, @distance}
} FILTER .name = 'B';
```

```py
{default::Place {name: 'B', neighbors: {default::Place {name: 'C', @distance: 10.2}, default::Place {name: 'E', @distance: 2.1}}}}
```

**Comment by vpetrovykh** [comment]
Aside from needing `assert_distinct` for assigning value to `neighbours` (because `array_unpack` can have repetitions) there are no issues with these queries anymore.
