### ISSUE TITLE
Better syntax errors for substitution tokens

### ISSUE THREAD

**Issue by tailhook** [edgedb/edgedb#2135]
Currently as of 1.0-alpha.8+dev.5341.g66ec73494 it fails with InternalServerError:
```
edgedb> SELECT \(x);
ERROR: InternalServerError: (<class 'edb.edgeql.parser.grammar.tokens.TokenMeta'>, 'SUBSTITUTION')
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "/work/edb/server/procpool/worker.py", line 75, in worker
          res = await meth(*args)
        File "/work/edb/server/compiler/compiler.py", line 1935, in compile
          return self._compile(ctx=ctx, source=source)
        File "/work/edb/server/compiler/compiler.py", line 1487, in _compile
          return self._try_compile(ctx=ctx, source=source)
        File "/work/edb/server/compiler/compiler.py", line 1519, in _try_compile
          statements = edgeql.parse_block(source)
        File "/work/edb/edgeql/parser/__init__.py", line 69, in parse_block
          return parser.parse(source)
        File "/work/edb/common/parsing.py", line 401, in parse
          token = self.process_lex_token(mod, tok)
        File "/work/edb/common/parsing.py", line 390, in process_lex_token
          return mod.TokenMeta.for_lex_token(tok.kind())(
        File "/work/edb/common/parsing.py", line 100, in for_lex_token
          return mcls.token_map[mcls, token]
      KeyError: (<class 'edb.edgeql.parser.grammar.tokens.TokenMeta'>, 'SUBSTITUTION')
```
This bug appeared after #2131

**Comment by elprans** [comment]
Yeah, you need to add a matching declaration to edgeql/parser/grammar/tokens.py
