### ISSUE TITLE
Better ISE on postgres crash

### ISSUE THREAD

**Issue by tailhook** [edgedb/edgedb#2269]
Here is how EdgeDB 1-beta1 fails when postgres crashes because of out of memory condition:
```
edgedb error: failed to dump "test1" -> ./edgedb.upgrade.test1.dump: Error authenticating: ERROR: InternalServerError: connection was closed in the middle of operation
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/site-packages/edb/server/procpool/worker.py", line 75, in worker
          res = await meth(*args)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 369, in connect
          await self._get_database(dbver)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 329, in _get_database
          schema = await self.introspect(con)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 292, in introspect
          data = await connection.fetch(self._intro_query)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/site-packages/asyncpg/connection.py", line 420, in fetch
          return await self._execute(query, args, 0, timeout)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/site-packages/asyncpg/connection.py", line 1402, in _execute
          result, _ = await self.__execute(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/site-packages/asyncpg/connection.py", line 1411, in __execute
          return await self._do_execute(query, executor, timeout)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha7/lib/python3.8/site-packages/asyncpg/connection.py", line 1433, in _do_execute
          result = await executor(stmt, None)
        File "asyncpg/protocol/protocol.pyx", line 196, in bind_execute
      asyncpg.exceptions.ConnectionDoesNotExistError: connection was closed in the middle of operation
```
While "Internal Server Error" is technically a good error here, it's still not EdgeDB bug. This kind of queries or postgres misconfigurations will happen on our users configs, and we have to describe better by providing better error message and/or by having a subclass of InternalServerError.

**Comment by 1st1** [comment]
> and we have to describe better by providing better error message 

Yeah, this is literally the reason for that "Hint: ..." message. Feel free to open a PR to remap this error to something more appropriate. The logic for remapping is in `errormech.py`.

**Comment by clmno** [comment]
> This kind of queries or postgres misconfigurations will happen on our users configs, and we have to describe better by providing better error message and/or by having a subclass of InternalServerError.

Good point. 
As a user, knowing it is a postgres config issue and not an EdgeDB issue enables us to find a solution faster and not wait for the community / github issues / github discussion to respond.

**Comment by tailhook** [comment]
Another example of such error:
```
edgedb error: Error creating database: ERROR: InternalServerError: could not write to file "base/23213/2691": No space left on device
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      edb.errors.InternalServerError: could not write to file "base/23213/2691": No space left on device
```
