### ISSUE TITLE
Failing tests on RDS

### ISSUE THREAD

**Issue by fantix** [edgedb/edgedb#2291]
- EdgeDB Version: 157e58b78315339ff620e04d7afcecb05f0505df
- OS Version: macOS 11.2.1 Darwin Kernel Version 20.3.0 xnu-7195.81.3~1/RELEASE_X86_64
- AWS RDS Version: 12.4

This is an issue to track all the failing tests when running on AWS RDS.

- [x] `ALTER ROLE ... SET password := ...` fails. Fixed in #2282 
- [x] test_edgeql_ddl_role_02 (test_edgeql_ddl.TestEdgeQLDDL)

   ```
   Traceback (most recent call last):
     File "edb/testbase/server.py", line 127, in wrapper
       self.loop.run_until_complete(
     File "asyncio/base_events.py", line 642, in run_until_complete
       return future.result()
     File "tests/test_edgeql_ddl.py", line 6284, in test_edgeql_ddl_role_02
       await self.assert_query_result(
     File "edb/testbase/server.py", line 534, in assert_query_result
       self._assert_data_shape(res, exp_result_json, message=msg)
     File "edb/testbase/server.py", line 742, in _assert_data_shape
       return _assert_generic_shape((), data, shape)
     File "edb/testbase/server.py", line 710, in _assert_generic_shape
       return _assert_list_shape(path, data, shape)
     File "edb/testbase/server.py", line 660, in _assert_list_shape
       _assert_generic_shape(
     File "edb/testbase/server.py", line 714, in _assert_generic_shape
       return _assert_dict_shape(path, data, shape)
     File "edb/testbase/server.py", line 619, in _assert_dict_shape
       _assert_generic_shape(path + (f'["{sk}"]',), data[sk], sv)
     File "edb/testbase/server.py", line 730, in _assert_generic_shape
       self.fail(
   AssertionError: data shape differs: False != True PATH: [0]["superuser"]
   ```

- [x] test_server_proto_ddlprop_01 (test_server_proto.TestServerProtoDdlPropagation)

   ```
   Traceback (most recent call last):
     File "edb/testbase/server.py", line 127, in wrapper
       self.loop.run_until_complete(
     File "asyncio/base_events.py", line 642, in run_until_complete
       return future.result()
     File "tests/test_server_proto.py", line 1895, in test_server_proto_ddlprop_01
       async with tb.start_edgedb_server(adjacent_to=self.con) as sd:
     File "edb/testbase/server.py", line 1495, in __aenter__
       data = await asyncio.wait_for(
     File "asyncio/tasks.py", line 481, in wait_for
       return fut.result()
     File "edb/testbase/server.py", line 1431, in _read_runtime_info
       raise RuntimeError("EdgeDB server terminated")
   RuntimeError: EdgeDB server terminated
   ```

- [x] test_edgeql_select_polymorphic_10 (test_edgeql_select.TestEdgeQLSelect) (passes when ran separately)

   ```
   Traceback (most recent call last):
     File "edb/testbase/server.py", line 127, in wrapper
       self.loop.run_until_complete(
     File "asyncio/base_events.py", line 642, in run_until_complete
       return future.result()
     File "tests/test_edgeql_select.py", line 1538, in test_edgeql_select_polymorphic_10
       await self.assert_query_result(
     File "edb/testbase/server.py", line 547, in assert_query_result
       res = await self.con._fetchall(
     File "edgedb/asyncio_con.py", line 201, in _fetchall
       result, _ = await self._impl._protocol.execute_anonymous(
     File "edgedb/protocol/protocol.pyx", line 633, in execute_anonymous
     File "edgedb/protocol/protocol.pyx", line 405, in _execute
   edgedb.errors.InternalServerError: remaining connection slots are reserved for non-replication superuser connections
   ```

- [x] Tests hangs in GitHub Action (fixed by adding TCP keepalive)
- [x] test_server_auth_01 (test_server_auth.TestServerAuth)

  ```
  Traceback (most recent call last):
    File "/home/runner/work/edgedb/edgedb/edb/testbase/server.py", line 127, in wrapper
      self.loop.run_until_complete(
    File "/opt/hostedtoolcache/Python/3.9.2/x64/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
      return future.result()
    File "/home/runner/work/edgedb/edgedb/tests/test_server_auth.py", line 40, in test_server_auth_01
      await self.connect(
    File "/opt/hostedtoolcache/Python/3.9.2/x64/lib/python3.9/contextlib.py", line 124, in __exit__
      next(self.gen)
    File "/home/runner/work/edgedb/edgedb/edb/testbase/server.py", line 215, in assertRaisesRegex
      raise
  AssertionError: AuthenticationError not raised
  ```

- [x] test_server_proto_concurrent_global_ddl (test_server_proto.TestServerProtoConcurrentGlobalDDL)

  ```
  Traceback (most recent call last):
    File "/home/runner/work/edgedb/edgedb/tests/test_server_proto.py", line 2852, in test_server_proto_concurrent_global_ddl
      g.create_task(con.execute(f'''
    File "/home/runner/work/edgedb/edgedb/edb/common/taskgroup.py", line 170, in __aexit__
      raise me from None
  edb.common.taskgroup.TaskGroupError: unhandled errors in a TaskGroup; 1 sub errors: (SchemaError)
   + SchemaError: role 'concurrent_1' is already present in the schema
   |   File "/home/runner/.virtualenvs/.venv/lib/python3.9/site-packages/edgedb/asyncio_con.py", line 359, in execute
   |     await self._impl._protocol.simple_query(
   |   File "edgedb/protocol/protocol.pyx", line 578, in simple_query
  
  
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/home/runner/work/edgedb/edgedb/edb/testbase/server.py", line 127, in wrapper
      self.loop.run_until_complete(
    File "/opt/hostedtoolcache/Python/3.9.2/x64/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
      return future.result()
    File "/home/runner/work/edgedb/edgedb/tests/test_server_proto.py", line 2856, in test_server_proto_concurrent_global_ddl
      self.assertIn(
  AssertionError: <class 'edgedb.errors.TransactionSerializationError'> not found in {<class 'edgedb.errors.SchemaError'>}
  ```

- [x] test_server_proto_configure_describe_database_config (test_server_config.TestServerConfig)

  ```
  Traceback (most recent call last):
    File "/home/runner/work/edgedb/edgedb/edb/testbase/server.py", line 127, in wrapper
      self.loop.run_until_complete(
    File "/opt/hostedtoolcache/Python/3.9.2/x64/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
      return future.result()
    File "/home/runner/work/edgedb/edgedb/tests/test_server_config.py", line 953, in test_server_proto_configure_describe_database_config
      self.assertIn(conf1, res)
  AssertionError: "CONFIGURE CURRENT DATABASE SET singleprop := '1337';" not found in ''
  ```

- [x] test_server_proto_configure_describe_system_config (test_server_config.TestServerConfig)

  ```
  Traceback (most recent call last):
    File "/home/runner/work/edgedb/edgedb/edb/testbase/server.py", line 127, in wrapper
      self.loop.run_until_complete(
    File "/opt/hostedtoolcache/Python/3.9.2/x64/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
      return future.result()
    File "/home/runner/work/edgedb/edgedb/tests/test_server_config.py", line 928, in test_server_proto_configure_describe_system_config
      self.assertIn(conf1, res)
  AssertionError: "CONFIGURE SYSTEM SET singleprop := '1337';" not found in "CONFIGURE SYSTEM INSERT cfg::Auth {\n    priority := 0,\n    user := {'*'},\n    method := (\n        (INSERT cfg::Trust)\n    ),\n};\n"
  ```

**Comment by elprans** [comment]
The latter two are probably related to the RDS connection limit.  We need to query and surface that setting via `BackendRuntimeParams` and size our backend connection pool accordingly.  Bundled postgres clusters run with `max_connections`: 500 currently

**Comment by fantix** [comment]
Thanks for the clue! Will try again with bumped limit.
