### ISSUE TITLE
Problem with generating migration

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb#2322]
- EdgeDB Version: 1.0.0-beta.1
- OS Version: Linux

Steps to Reproduce:

1. Use the following schema:
```
module default {
    # Base types, exercises are organized into sheets
    abstract type Exercise {
        property description -> str;
    }

    abstract type Sheet {
        multi link exercises -> Exercise {
            constraint exclusive;
        }
        property description -> str;
        property completed_on -> cal::local_date;
    }

    type MathEx extending Exercise {
        link sheet := .<exercises[IS MathSheet];

        required property num0 -> int64;
        required property num1 -> int64;
        required property op -> str;

        property answer -> int64;
        property correct_answer :=
            (.num0 + .num1) IF .op = '+' ELSE (.num0 - .num1);

        property is_completed := EXISTS .answer;
        property is_correct := .answer ?= .correct_answer;
    }

    type MathSheet extending Sheet {
        overloaded multi link exercises -> MathEx;

        property is_completed :=
            EXISTS .completed_on AND all(.exercises.is_completed);
        property num_correct := count((
            SELECT .exercises FILTER .is_correct));
    }
};
```
2. run `create-migration` (which should be OK)
3. run `migrate`, which causes the following error:

```
edgedb error: ERROR: InternalServerError: 'NoneType' object has no attribute 'irast'
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "/home/victor/dev/magicstack/edgedb/edb/server/compiler_pool/worker.py", line 312, in worker
          res = meth(*args)
        File "/home/victor/dev/magicstack/edgedb/edb/server/compiler_pool/worker.py", line 198, in compile_in_tx
          units, cstate = COMPILER.compile_in_tx(cstate, *args, **kwargs)
        File "/home/victor/dev/magicstack/edgedb/edb/server/compiler/compiler.py", line 2004, in compile_in_tx
          return self._compile(ctx=ctx, source=source), ctx.state
        File "/home/victor/dev/magicstack/edgedb/edb/server/compiler/compiler.py", line 1548, in _compile
          return self._try_compile(ctx=ctx, source=source)
        File "/home/victor/dev/magicstack/edgedb/edb/server/compiler/compiler.py", line 1602, in _try_compile
          comp, capabilities = self._compile_dispatch_ql(ctx, stmt)
        File "/home/victor/dev/magicstack/edgedb/edb/server/compiler/compiler.py", line 1484, in _compile_dispatch_ql
          query = self._compile_ql_migration(ctx, ql)
        File "/home/victor/dev/magicstack/edgedb/edb/server/compiler/compiler.py", line 880, in _compile_ql_migration
          query = self._compile_and_apply_ddl_stmt(ctx, ql)
        File "/home/victor/dev/magicstack/edgedb/edb/server/compiler/compiler.py", line 800, in _compile_and_apply_ddl_stmt
          block, new_types = self._process_delta(ctx, delta)
        File "/home/victor/dev/magicstack/edgedb/edb/server/compiler/compiler.py", line 336, in _process_delta
          schema = pgdelta.apply(schema, context)
        File "/home/victor/dev/magicstack/edgedb/edb/pgsql/delta.py", line 5129, in apply
          schema = sd.DeltaRoot.apply(self, schema, context)
        File "/home/victor/dev/magicstack/edgedb/edb/schema/delta.py", line 1372, in apply
          schema = objop.apply(schema, context)
        File "/home/victor/dev/magicstack/edgedb/edb/pgsql/delta.py", line 205, in apply
          schema = self.__class__.get_adaptee().apply(self, schema, context)
        File "/home/victor/dev/magicstack/edgedb/edb/schema/delta.py", line 2872, in apply
          schema = self._create_innards(schema, context)
        File "/home/victor/dev/magicstack/edgedb/edb/schema/delta.py", line 2841, in _create_innards
          schema = op.apply(schema, context=context)
        File "/home/victor/dev/magicstack/edgedb/edb/pgsql/delta.py", line 2131, in apply
          schema = s_objtypes.CreateObjectType.apply(self, schema, context)
        File "/home/victor/dev/magicstack/edgedb/edb/schema/delta.py", line 2872, in apply
          schema = self._create_innards(schema, context)
        File "/home/victor/dev/magicstack/edgedb/edb/schema/inheriting.py", line 735, in _create_innards
          return super()._create_innards(schema, context)
        File "/home/victor/dev/magicstack/edgedb/edb/schema/delta.py", line 2841, in _create_innards
          schema = op.apply(schema, context=context)
        File "/home/victor/dev/magicstack/edgedb/edb/pgsql/delta.py", line 3552, in apply
          schema = s_links.AlterLink.apply(self, schema, context)
        File "/home/victor/dev/magicstack/edgedb/edb/schema/delta.py", line 3321, in apply
          schema = self._alter_innards(schema, context)
        File "/home/victor/dev/magicstack/edgedb/edb/schema/delta.py", line 2978, in _alter_innards
          schema = op.apply(schema, context=context)
        File "/home/victor/dev/magicstack/edgedb/edb/pgsql/delta.py", line 3478, in apply
          self._alter_pointer_type(self.scls, schema, orig_schema, context)
        File "/home/victor/dev/magicstack/edgedb/edb/pgsql/delta.py", line 2872, in _alter_pointer_type
          self._compile_conversion_expr(
        File "/home/victor/dev/magicstack/edgedb/edb/pgsql/delta.py", line 3078, in _compile_conversion_expr
          if conv_expr.irast is not None:
      AttributeError: 'NoneType' object has no attribute 'irast'
```

Here's the generated DDL:
```
CREATE MIGRATION m1i6vw5no7747rw642ju5zjxkwklseny6k6wfbenvlfghkjnuvccoa
    ONTO initial
{
  CREATE ABSTRACT TYPE default::Exercise {
      CREATE PROPERTY description -> std::str;
  };
  CREATE ABSTRACT TYPE default::Sheet {
      CREATE MULTI LINK exercises -> default::Exercise {
          CREATE CONSTRAINT std::exclusive;
      };
      CREATE PROPERTY completed_on -> cal::local_date;
      CREATE PROPERTY description -> std::str;
  };
  CREATE TYPE default::MathEx EXTENDING default::Exercise {
      CREATE PROPERTY answer -> std::int64;
      CREATE REQUIRED PROPERTY num0 -> std::int64;
      CREATE REQUIRED PROPERTY num1 -> std::int64;
      CREATE REQUIRED PROPERTY op -> std::str;
      CREATE PROPERTY correct_answer := (((.num0 + .num1) IF (.op = '+') ELSE (.num0 - .num1)));
      CREATE PROPERTY is_completed := (EXISTS (.answer));
      CREATE PROPERTY is_correct := ((.answer ?= .correct_answer));
  };
  CREATE TYPE default::MathSheet EXTENDING default::Sheet {
      ALTER LINK exercises {
          SET MULTI;
          SET OWNED;
          SET TYPE default::MathEx;
      };
      CREATE PROPERTY is_completed := ((EXISTS (.completed_on) AND std::all(.exercises.is_completed)));
      CREATE PROPERTY num_correct := (std::count((SELECT
          .exercises
      FILTER
          .is_correct
      )));
  };
  ALTER TYPE default::MathEx {
      CREATE LINK sheet := (.<exercises[IS default::MathSheet]);
  };
};
```

**Comment by msullivan** [comment]
This seems fixed.
