### ISSUE TITLE
InternalServerError: cannot cast type record[] to edgedbpub."d9d212dc-a213-2fe7-a592-5a2c94a4a8ff_t"[]

### ISSUE THREAD

**Issue by Fogapod** [edgedb/edgedb#2342]
- EdgeDB Version: `1-beta1`

This exception happens every time I run this query with any valid data (correct types). ID `d9d212dc-a213-2fe7-a592-5a2c94a4a8ff_t` is always the same

Traceback
```python
Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/eugene/.local/lib/python3.9/site-packages/edgedb/asyncio_pool.py", line 441, in query
    return await con.query(query, *args, **kwargs)
  File "/home/eugene/.local/lib/python3.9/site-packages/edgedb/asyncio_con.py", line 270, in query
    result, _ = await self._impl._protocol.execute_anonymous(
  File "edgedb/protocol/protocol.pyx", line 633, in execute_anonymous
    ret, attrs = await self._execute(in_dc, out_dc, args, kwargs)
  File "edgedb/protocol/protocol.pyx", line 405, in _execute
    raise exc
edgedb.errors.InternalServerError: cannot cast type record[] to edgedbpub."d9d212dc-a213-2fe7-a592-5a2c94a4a8ff_t"[]
```

Schema:
```esdl
module default {
    type UserGuildSettings {
        required property user_id -> snowflake;
        required property guild_id -> snowflake;
        property accents -> array<tuple<name: str, severity: int16>> {
            default := <array<tuple<name: str, severity: int16>>>[]
        };

        # https://github.com/edgedb/edgedb/issues/1939#issuecomment-789197413
        # constraint exclusive on ((.user_id, .guild_id));
        property exclusive_hack {
            using ((.user_id, .guild_id));
            constraint exclusive;
        };
    }

    scalar type snowflake extending int64;
};
```

Query:
```edgeql
            INSERT UserGuildSettings {
                guild_id := <snowflake>$guild_id,
                user_id  := <snowflake>$user_id,
                accents  := <array<tuple<str, int16>>><json>$accents,
            } UNLESS CONFLICT ON .exclusive_hack
            ELSE (
                UPDATE UserGuildSettings
                SET {
                    accents := <array<tuple<str, int16>>><json>$accents,
                }
            )
```
Query arguments:
```python
{
accents: '[["E", 1]]', 
guild_id: 391987311468085248, 
user_id: 253384991940149249
}
```

There are no conflicting records in DB, so problem is probably in INSERT.
EDIT: I removed UNLESS CONFLICT part and error looks slightly different now:
```python
Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/eugene/.local/lib/python3.9/site-packages/edgedb/asyncio_pool.py", line 441, in query
    return await con.query(query, *args, **kwargs)
  File "/home/eugene/.local/lib/python3.9/site-packages/edgedb/asyncio_con.py", line 270, in query
    result, _ = await self._impl._protocol.execute_anonymous(
  File "edgedb/protocol/protocol.pyx", line 633, in execute_anonymous
    ret, attrs = await self._execute(in_dc, out_dc, args, kwargs)
  File "edgedb/protocol/protocol.pyx", line 405, in _execute
    raise exc
edgedb.errors.InternalServerError: column "a711fdba-803a-11eb-8dba-5103861e7680" is of type edgedbpub."d9d212dc-a213-2fe7-a592-5a2c94a4a8ff_t"[] but expression is of type record[]
```

Query:
```edgeql
            INSERT UserGuildSettings {
                guild_id := <snowflake>$guild_id,
                user_id  := <snowflake>$user_id,
                accents  := <array<tuple<str, int16>>><json>$accents,
            }
```

Server logs are empty for some reason.

**Comment by Fogapod** [comment]
Can confirm that this doesn't happen on nightly
