### ISSUE TITLE
AssertionError: Normalized and non-normalized query errors differ

### ISSUE THREAD

**Issue by Fogapod** [edgedb/edgedb#2343]
- EdgeDB Version: `1-beta1`

Steps to Reproduce:

1. `select <tuple<"">>1;`
<details>
  <summary>Traceback</summary>

  ```python
  ERROR: InternalServerError: Normalized and non-normalized query errors differ
    Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
    Server traceback:
        Traceback (most recent call last):
          File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/common/parsing.py", line 403, in parse
            self.parser.token(token)
          File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/parsing/__init__.py", line 209, in token
            self._act(token, tokenSpec)
          File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/parsing/__init__.py", line 233, in _act
            raise UnexpectedToken("Unexpected token: %r" % sym)
        parsing.errors.UnexpectedToken: Unexpected token: <Token LANGBRACKET "<">
  
        The above exception was the direct cause of the following exception:
  
        Traceback (most recent call last):
          File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/server/compiler/compiler.py", line 1548, in _compile
            return self._try_compile(ctx=ctx, source=source)
          File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/server/compiler/compiler.py", line 1580, in _try_compile
            statements = edgeql.parse_block(source)
          File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/edgeql/parser/__init__.py", line 69, in parse_block
            return parser.parse(source)
          File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/common/parsing.py", line 416, in parse
            raise self.get_exception(
        edb.errors.EdgeQLSyntaxError: Unexpected '<'
  
        During handling of the above exception, another exception occurred:
  
        Traceback (most recent call last):
          File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/server/compiler/compiler.py", line 1555, in _compile
            self._try_compile(ctx=ctx, source=original)
          File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/server/compiler/compiler.py", line 1602, in _try_compile
            comp, capabilities = self._compile_dispatch_ql(ctx, stmt)
          File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/server/compiler/compiler.py", line 1522, in _compile_dispatch_ql
            query = self._compile_ql_query(ctx, ql)
          File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/server/compiler/compiler.py", line 561, in _compile_ql_query
            ir = qlcompiler.compile_ast_to_ir(
          File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/edgeql/compiler/__init__.py", line 177, in wrapper
            return func(*args, **kwargs)
          File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/edgeql/compiler/__init__.py", line 225, in compile_ast_to_ir
            ir_set = dispatch_mod.compile(tree, ctx=ctx)
          File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/functools.py", line 877, in wrapper
            return dispatch(args[0].__class__)(*args, **kw)
          File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/edgeql/compiler/stmt.py", line 85, in compile_SelectQuery
            stmt.result = compile_result_clause(
          File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/edgeql/compiler/stmt.py", line 1231, in compile_result_clause
            dispatch.compile(result_expr, ctx=sctx), ctx=sctx)
          File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/functools.py", line 877, in wrapper
            return dispatch(args[0].__class__)(*args, **kw)
          File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/edgeql/compiler/expr.py", line 408, in compile_TypeCast
            target_stype = typegen.ql_typeexpr_to_type(expr.type, ctx=ctx)
          File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/edgeql/compiler/typegen.py", line 73, in ql_typeexpr_to_type
            types = _ql_typeexpr_to_type(ql_t, ctx=ctx)
          File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/edgeql/compiler/typegen.py", line 102, in _ql_typeexpr_to_type
            return [_ql_typename_to_type(ql_t, ctx=ctx)]
          File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/edgeql/compiler/typegen.py", line 126, in _ql_typename_to_type
            t_subtypes[type_name] = ql_typeexpr_to_type(st, ctx=ctx)
          File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/edgeql/compiler/typegen.py", line 73, in ql_typeexpr_to_type
            types = _ql_typeexpr_to_type(ql_t, ctx=ctx)
          File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/edgeql/compiler/typegen.py", line 105, in _ql_typeexpr_to_type
            raise errors.InternalServerError(f'unexpected TypeExpr: {ql_t!r}')
        edb.errors.InternalServerError: unexpected TypeExpr: <edb.edgeql.ast.TypeExprLiteral object at 0x7f47f5a39310>
  
        During handling of the above exception, another exception occurred:
  
        Traceback (most recent call last):
          File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/server/compiler_pool/worker.py", line 312, in worker
            res = meth(*args)
          File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/server/compiler_pool/worker.py", line 173, in compile
            units, cstate = COMPILER.compile(
          File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/server/compiler/compiler.py", line 1967, in compile
            units = self._compile(ctx=ctx, source=source)
          File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/server/compiler/compiler.py", line 1559, in _compile
            raise AssertionError(
        AssertionError: Normalized and non-normalized query errors differ
  ```

</details>

**Comment by tailhook** [comment]
> > It seems to extract properly:
> 
> No. Type expressions are not value expressions, there must be no extraction there. EdgeQL does not support arguments there, because it alters the meaning of the query.

We don't have grammar in extraction code. So there is no way to distinguish:
```
 a < b < "some constant"
```
From:
```
<tuple<"">>$var;
```

**Comment by elprans** [comment]
OK, fair enough.  Let's turn the original into a proper `SyntaxError` and drop the error consistency assertion, since we can't expect errors to match always.
