### ISSUE TITLE
Backward-links fail when multiple types with the same link name exist

### ISSUE THREAD

**Issue by clmno** [edgedb/edgedb#2360]
- EdgeDB Version: 1.0-beta.1+g2eee1afe4.d20210301
- OS Version: Ubuntu 20.04.2 LTS
- CLI Version: repl 1.0.0-beta.1

Steps to Reproduce:

1. Create a new schema and populate the DB. I used the cli
```sql
START MIGRATION TO {
    module default {
        type Company {
            required property name -> str {
                constraint exclusive;
            }
        }
        type Product {
            required property name -> str;
            multi link category -> Category;
            link company -> Company;
        }
        type Category {
            required property name -> str {
                constraint exclusive;
            }
            link company -> Company;
        }
        type User {
            required property name -> str;
            required multi link company -> Company;
        }
    }
};
POPULATE MIGRATION;
COMMIT MIGRATION;

INSERT Company {name := "ABC Company"};
INSERT User {name := "Alice", company := (SELECT Company FILTER .name = <str>"ABC Company")};
INSERT Category {name := "Category 1", company := (SELECT Company FILTER .name = <str>"ABC Company")};
INSERT Product {name := "Product 1", company := (SELECT Company FILTER .name = <str>"ABC Company"), category := (SELECT Category FILTER .name = <str>"Category 1")};
INSERT Product {name := "Product 2", company := (SELECT Company FILTER .name = <str>"ABC Company"), category := (SELECT Category FILTER .name = <str>"Category 1")};
```
2. Execute a backward link query
```sql
Select Company {id, name, users := Company.<company[IS User].name};
```

## Observation

1. The query is looking for `company` in the type `User`. But there are other types with the same name linking to `Company`.
2. The error says
    ```
    ERROR: InternalServerError: cannot determine backend storage parameters for the __derived__::__|company@__derived__|(opaque: default:Category || default:Product || default:User) pointer: unexpected characteristics
    ```

<details><summary>view error log</summary>
<p>

```
ERROR: InternalServerError: cannot determine backend storage parameters for the __derived__::__|company@__derived__|(opaque: default:Category || default:Product || default:User) pointer: unexpected characteristics
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/pgsql/compiler/__init__.py", line 93, in compile_ir_to_sql_tree
          qtree = dispatch.compile(ir_expr, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/functools.py", line 877, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/pgsql/compiler/expr.py", line 60, in compile_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/pgsql/compiler/expr.py", line 118, in _compile_set_impl
          _compile_set(ir_set, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/pgsql/compiler/expr.py", line 593, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/pgsql/compiler/relgen.py", line 136, in get_set_rvar
          return _process_toplevel_query(ir_set, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/pgsql/compiler/relgen.py", line 236, in _process_toplevel_query
          rvars = _get_set_rvar(ir_set, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/pgsql/compiler/relgen.py", line 270, in _get_set_rvar
          rvars = process_set_as_subquery(ir_set, stmt, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/pgsql/compiler/relgen.py", line 1195, in process_set_as_subquery
          dispatch.visit(ir_set.expr, ctx=newctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/functools.py", line 877, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/pgsql/compiler/dispatch.py", line 44, in visit
          compile(ir, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/functools.py", line 877, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/pgsql/compiler/stmt.py", line 95, in compile_SelectStmt
          outvar = clauses.compile_output(stmt.result, ctx=ictx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/pgsql/compiler/clauses.py", line 176, in compile_output
          dispatch.visit(ir_set, ctx=newctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/functools.py", line 877, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/pgsql/compiler/expr.py", line 85, in visit_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/pgsql/compiler/expr.py", line 118, in _compile_set_impl
          _compile_set(ir_set, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/pgsql/compiler/expr.py", line 597, in _compile_set
          _compile_shape(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/pgsql/compiler/expr.py", line 608, in _compile_shape
          result = shapecomp.compile_shape(ir_set, shape, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/pgsql/compiler/shapecomp.py", line 76, in compile_shape
          wrapper = relgen.set_as_subquery(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/pgsql/compiler/relgen.py", line 406, in set_as_subquery
          dispatch.visit(ir_set, ctx=subctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/functools.py", line 877, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/pgsql/compiler/expr.py", line 85, in visit_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/pgsql/compiler/expr.py", line 114, in _compile_set_impl
          _compile_set(ir_set, ctx=scopectx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/pgsql/compiler/expr.py", line 593, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/pgsql/compiler/relgen.py", line 182, in get_set_rvar
          rvars = _get_set_rvar(ir_set, ctx=subctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/pgsql/compiler/relgen.py", line 270, in _get_set_rvar
          rvars = process_set_as_subquery(ir_set, stmt, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/pgsql/compiler/relgen.py", line 1195, in process_set_as_subquery
          dispatch.visit(ir_set.expr, ctx=newctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/functools.py", line 877, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/pgsql/compiler/dispatch.py", line 44, in visit
          compile(ir, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/functools.py", line 877, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/pgsql/compiler/stmt.py", line 95, in compile_SelectStmt
          outvar = clauses.compile_output(stmt.result, ctx=ictx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/pgsql/compiler/clauses.py", line 176, in compile_output
          dispatch.visit(ir_set, ctx=newctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/functools.py", line 877, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/pgsql/compiler/expr.py", line 85, in visit_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/pgsql/compiler/expr.py", line 118, in _compile_set_impl
          _compile_set(ir_set, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/pgsql/compiler/expr.py", line 593, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/pgsql/compiler/relgen.py", line 182, in get_set_rvar
          rvars = _get_set_rvar(ir_set, ctx=subctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/pgsql/compiler/relgen.py", line 355, in _get_set_rvar
          rvars = process_set_as_path(ir_set, stmt, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/pgsql/compiler/relgen.py", line 1008, in process_set_as_path
          get_set_rvar(ir_source, ctx=srcctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/pgsql/compiler/relgen.py", line 182, in get_set_rvar
          rvars = _get_set_rvar(ir_set, ctx=subctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/pgsql/compiler/relgen.py", line 355, in _get_set_rvar
          rvars = process_set_as_path(ir_set, stmt, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/pgsql/compiler/relgen.py", line 929, in process_set_as_path
          return process_set_as_path_type_intersection(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/pgsql/compiler/relgen.py", line 838, in process_set_as_path_type_intersection
          source_rvar = get_set_rvar(ir_source, ctx=subctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/pgsql/compiler/relgen.py", line 182, in get_set_rvar
          rvars = _get_set_rvar(ir_set, ctx=subctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/pgsql/compiler/relgen.py", line 355, in _get_set_rvar
          rvars = process_set_as_path(ir_set, stmt, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/pgsql/compiler/relgen.py", line 933, in process_set_as_path
          ptr_info = pg_types.get_ptrref_storage_info(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/pgsql/types.py", line 459, in get_ptrref_storage_info
          raise RuntimeError(
      RuntimeError: cannot determine backend storage parameters for the __derived__::__|company@__derived__|(opaque: default:Category || default:Product || default:User) pointer: unexpected characteristics
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/server/compiler_pool/worker.py", line 312, in worker
          res = meth(*args)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/server/compiler_pool/worker.py", line 173, in compile
          units, cstate = COMPILER.compile(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/server/compiler/compiler.py", line 1967, in compile
          units = self._compile(ctx=ctx, source=source)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/server/compiler/compiler.py", line 1548, in _compile
          return self._try_compile(ctx=ctx, source=source)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/server/compiler/compiler.py", line 1602, in _try_compile
          comp, capabilities = self._compile_dispatch_ql(ctx, stmt)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/server/compiler/compiler.py", line 1522, in _compile_dispatch_ql
          query = self._compile_ql_query(ctx, ql)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/server/compiler/compiler.py", line 593, in _compile_ql_query
          sql_text, argmap = pg_compiler.compile_ir_to_sql(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/pgsql/compiler/__init__.py", line 115, in compile_ir_to_sql
          qtree = compile_ir_to_sql_tree(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/pgsql/compiler/__init__.py", line 100, in compile_ir_to_sql_tree
          raise errors.InternalServerError(*args) from e
      edb.errors.InternalServerError: cannot determine backend storage parameters for the __derived__::__|company@__derived__|(opaque: default:Category || default:Product || default:User) pointer: unexpected characteristics
```
</p>
</details>

**Comment by msullivan** [comment]
I think the bug stems from one of the links being `multi` and one being `single`.

**Comment by msullivan** [comment]
@clmno I have a workaround for you: if you add a link property to the single company links (like `property _dummy -> bool;`, it should work.

(This is because we store link properties in separate link tables. The issue here is that we don't properly handle unioned links that are a mix of inline storage and storage in separate link tables. Shouldn't be too hard to fix.)
