### ISSUE TITLE
RebaseObjectType does not implement `get_verb()`

### ISSUE THREAD

**Issue by ambv** [edgedb/edgedb#2381]
- EdgeDB Version: 1.0b1
- OS Version: macOS 10.15.7

Schema before:
```esdl
module commonplace {
    type User;

    abstract type Named {
        required property name -> util::Slug {
            constraint exclusive;
        };
        index on (__subject__.name);
    }
}
```

Schema after:
```esdl
module commonplace {
    type User extending
        Named;

    abstract type Named {
        required property name -> util::Slug {
            constraint exclusive;
        };
        index on (__subject__.name);
    }
}
```

During `create-migration`:
```
  Server traceback:
      Traceback (most recent call last):
        File "/Library/Frameworks/EdgeDB.framework/Versions/1-beta1/lib/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/server/compiler_pool/worker.py", line 312, in worker
          res = meth(*args)
        File "/Library/Frameworks/EdgeDB.framework/Versions/1-beta1/lib/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/server/compiler_pool/worker.py", line 198, in compile_in_tx
          units, cstate = COMPILER.compile_in_tx(cstate, *args, **kwargs)
        File "/Library/Frameworks/EdgeDB.framework/Versions/1-beta1/lib/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/server/compiler/compiler.py", line 2004, in compile_in_tx
          return self._compile(ctx=ctx, source=source), ctx.state
        File "/Library/Frameworks/EdgeDB.framework/Versions/1-beta1/lib/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/server/compiler/compiler.py", line 1545, in _compile
          return self._try_compile(ctx=ctx, source=original)
        File "/Library/Frameworks/EdgeDB.framework/Versions/1-beta1/lib/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/server/compiler/compiler.py", line 1602, in _try_compile
          comp, capabilities = self._compile_dispatch_ql(ctx, stmt)
        File "/Library/Frameworks/EdgeDB.framework/Versions/1-beta1/lib/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/server/compiler/compiler.py", line 1484, in _compile_dispatch_ql
          query = self._compile_ql_migration(ctx, ql)
        File "/Library/Frameworks/EdgeDB.framework/Versions/1-beta1/lib/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/server/compiler/compiler.py", line 1018, in _compile_ql_migration
          prompt_id, prompt_text = top_op.get_user_prompt()
        File "/Library/Frameworks/EdgeDB.framework/Versions/1-beta1/lib/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/schema/delta.py", line 1641, in get_user_prompt
          return subcommand.get_user_prompt(parent_op=parent_op)
        File "/Library/Frameworks/EdgeDB.framework/Versions/1-beta1/lib/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/schema/delta.py", line 1645, in get_user_prompt
          desc = self.get_friendly_description(parent_op=parent_op)
        File "/Library/Frameworks/EdgeDB.framework/Versions/1-beta1/lib/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/schema/delta.py", line 1608, in get_friendly_description
          return f'{self.get_verb()} {object_desc}'
        File "/Library/Frameworks/EdgeDB.framework/Versions/1-beta1/lib/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/schema/delta.py", line 405, in get_verb
          raise NotImplementedError
      NotImplementedError
```

`self` in the traceback is of type `<class 'edb.schema.objtypes.RebaseObjectType'>`.

**Comment by elprans** [comment]
Fixed in #2303.
