### ISSUE TITLE
Inheriting from enum throws UnresolvedReferenceError stack

### ISSUE THREAD

**Issue by limx0** [edgedb/edgedb#2556]
I accidentally inherited from an enum type instead of my abstract type, which threw the following stacktrace.

```
❯ edgedb create-migration
ERROR: InternalServerError: reference to an undefined item default::AnEnum in default::SubType
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "/Library/Frameworks/EdgeDB.framework/Versions/1-beta2/lib/edgedb-server-1-beta2/lib/python3.9/site-packages/edb/server/compiler_pool/worker.py", line 312, in worker
          res = meth(*args)
        File "/Library/Frameworks/EdgeDB.framework/Versions/1-beta2/lib/edgedb-server-1-beta2/lib/python3.9/site-packages/edb/server/compiler_pool/worker.py", line 173, in compile
          units, cstate = COMPILER.compile(
        File "/Library/Frameworks/EdgeDB.framework/Versions/1-beta2/lib/edgedb-server-1-beta2/lib/python3.9/site-packages/edb/server/compiler/compiler.py", line 1986, in compile
          units = self._compile(ctx=ctx, source=source)
        File "/Library/Frameworks/EdgeDB.framework/Versions/1-beta2/lib/edgedb-server-1-beta2/lib/python3.9/site-packages/edb/server/compiler/compiler.py", line 1565, in _compile
          return self._try_compile(ctx=ctx, source=source)
        File "/Library/Frameworks/EdgeDB.framework/Versions/1-beta2/lib/edgedb-server-1-beta2/lib/python3.9/site-packages/edb/server/compiler/compiler.py", line 1618, in _try_compile
          comp, capabilities = self._compile_dispatch_ql(ctx, stmt)
        File "/Library/Frameworks/EdgeDB.framework/Versions/1-beta2/lib/edgedb-server-1-beta2/lib/python3.9/site-packages/edb/server/compiler/compiler.py", line 1501, in _compile_dispatch_ql
          query = self._compile_ql_migration(ctx, ql)
        File "/Library/Frameworks/EdgeDB.framework/Versions/1-beta2/lib/edgedb-server-1-beta2/lib/python3.9/site-packages/edb/server/compiler/compiler.py", line 915, in _compile_ql_migration
          target_schema = s_ddl.apply_sdl(
        File "/Library/Frameworks/EdgeDB.framework/Versions/1-beta2/lib/edgedb-server-1-beta2/lib/python3.9/site-packages/edb/schema/ddl.py", line 479, in apply_sdl
          ddl_stmts = s_decl.sdl_to_ddl(current_schema, documents)
        File "/Library/Frameworks/EdgeDB.framework/Versions/1-beta2/lib/edgedb-server-1-beta2/lib/python3.9/site-packages/edb/edgeql/declarative.py", line 337, in sdl_to_ddl
          topological.normalize(
        File "/Library/Frameworks/EdgeDB.framework/Versions/1-beta2/lib/edgedb-server-1-beta2/lib/python3.9/site-packages/edb/common/topological.py", line 210, in normalize
          for name, item in sort_ex(graph):
        File "/Library/Frameworks/EdgeDB.framework/Versions/1-beta2/lib/edgedb-server-1-beta2/lib/python3.9/site-packages/edb/common/topological.py", line 106, in sort_ex
          raise UnresolvedReferenceError(
      edb.common.topological.UnresolvedReferenceError: reference to an undefined item default::AnEnum in default::SubType
edgedb error: cannot proceed until .esdl files are fixed
``` 

- EdgeDB Version: 1.0b2+ga7130d5c7.cv202104290000
- OS Version: macOS Big Sur (11.3.1)

Steps to Reproduce:
1. Add schema
2. create-migration

Schema:
```
scalar type AnEnum extending enum<TEST>;
type SubType extending AnEnum {}
```

**Comment by elprans** [comment]
There's also a similar issue in DDL: #1425.

**Comment by limx0** [comment]
Thanks @elprans - in almost all cases the error messages are very helpful! Documenting here any I find in the hopes it helps someone else. 

Another one - accidentally using `id` as a link.

Schema:
```
module default {

    abstract type Identifer {
        required property value -> str;
        constraint exclusive on ( .value );
    }

    type AccountId extending Identifer {}

    type Account {
        required link id -> AccountId;
    }
}
```

Running migrate gives:
```
ERROR: InvalidReferenceError: schema object UUID('436c6a9c-bcf9-11eb-87d6-59a58b286906') exists, but is not link
```

^ This may be hard to find in a larger migration
