### ISSUE TITLE
dump/restore is broken in beta2: RuntimeError: pgcon: cannot issue new command; waiting for sync

### ISSUE THREAD

**Issue by Fogapod** [edgedb/edgedb#2606]
- EdgeDB Version: `1-beta2-22542f0`

Looks like empty array of named tuples is causing restore to fail.

Steps to Reproduce:

1. `edgedb server init test`
2. `edgedb migrate`
3. `edgedb -I test`
4. `INSERT AccentSettings { guild_id := 0, user_id := 0 };`
5. `edgedb -I test dump d`
6. `edgedb server destroy test`
7. `edgedb server init test`
8. `edgedb -I test restore d`

```python
edgedb error: ERROR: InternalServerError: pgcon: cannot issue new command; waiting for sync
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "edb/server/protocol/binary.pyx", line 2498, in edb.server.protocol.binary.EdgeConnection.restore
        File "edb/server/pgcon/pgcon.pyx", line 1470, in restore
        File "edb/server/pgcon/pgcon.pyx", line 1226, in _restore
        File "edb/server/pgcon/pgcon.pyx", line 1353, in edb.server.pgcon.pgcon.PGConnection._rewrite_copy_data
        File "edb/server/pgcon/pgcon.pyx", line 1419, in edb.server.pgcon.pgcon.PGConnection._mend_copy_datum
        File "edb/server/pgproto/./frb.pxd", line 28, in edb.server.pgproto.pgproto.frb_read
        File "edb/server/pgproto/./frb.pyx", line 10, in edb.server.pgproto.pgproto.frb_check
      AssertionError: insufficient data in buffer: requested 4 remaining 0

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "edb/server/protocol/binary.pyx", line 1710, in edb.server.protocol.binary.EdgeConnection.main
        File "edb/server/protocol/binary.pyx", line 2513, in restore
        File "edb/server/pgcon/pgcon.pyx", line 1046, in simple_query
        File "edb/server/pgcon/pgcon.pyx", line 1586, in edb.server.pgcon.pgcon.PGConnection.before_command
      RuntimeError: pgcon: cannot issue new command; waiting for sync
```

Only empty array causes this error.
I tried using array with 1 item, multiple items, add records with different amount of array items, only empty array causes this.

Schema:
https://github.com/Fogapod/pink/tree/main/dbschema
This line: https://github.com/Fogapod/pink/blob/122b4b700b52ee9d4cc82e0ed45c624a98704915/dbschema/default.esdl#L13

**Comment by 1st1** [comment]
Good catch, thanks!
