### ISSUE TITLE
ISE: `unimplemented auth method: NoneType` when inserting new user on clean instance

### ISSUE THREAD

**Issue by nsidnev** [edgedb/edgedb#2848]
- EdgeDB Version: 1-beta3-451baf4
- OS Version: ubuntu 18.04

Steps to Reproduce:

1. initialize new project with new `EdgeDB` instance in docker with `edgedb project init`
2. login into EdgeDB shell using `edgedb` command and create new user with password:
```
CREATE SUPERUSER ROLE edgedb_scram {
    SET password := 'edgedb_scram_password'
};

CONFIGURE INSTANCE INSERT Auth {
    user := 'edgedb_scram',
    method := (INSERT SCRAM),
    priority := 2
};
```
3. exit current shell session and try running `edgedb` command again to login into shell
```
$ edgedb
edgedb error: Error authenticating: ERROR: InternalServerError: unimplemented auth method: NoneType
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "edb/server/protocol/binary.pyx", line 1689, in edb.server.protocol.binary.EdgeConnection.main
        File "edb/server/protocol/binary.pyx", line 445, in auth
      edb.errors.InternalServerError: unimplemented auth method: NoneType
```

As I understand it, this is because the default user (`edgedb`) created by the EdgeDB bootstrap process is not being added to `cfg::Auth`. This can be verified by selecting the existing `cfg::Auth` objects before inserting a new one:
```
SELECT cfg::Auth {
    user,
    method,
    priority
};
```
The output will be an empty set (`{}`).

But in any case, user should not receive such error from the EdgeDB server in case of authentication failure. I would rather expect something like `AuthenticationError: no authentication method configured for the "edgedb" role` or something similar.

It's possible I missed something about roles configuration, but that part of EdgeDB is poorly documented right now, IMO.

**Comment by 1st1** [comment]
Yeah, this is a bug, huge thanks for reporting it

**Comment by nsidnev** [comment]
Well, the second part of this issue was quite easy to fix, so I created [PR](https://github.com/edgedb/edgedb/pull/2849) for it. I hope I hope it's correct and no one has started working on this yet :)

The first part with bootstrap should be fixed somewhere here if I understood correctly: https://github.com/edgedb/edgedb-docker/blob/7f9047dd510a622a1e942de6db18ed7aed7c3990/docker-entrypoint-funcs.sh#L404-L415

**Comment by 1st1** [comment]
> As I understand it, this is because the default user (edgedb) created by the EdgeDB bootstrap process is not being added to cfg::Auth. This can be verified by selecting the existing cfg::Auth objects before inserting a new one:

@elprans should we fix this?

**Comment by elprans** [comment]
Our current global default is SCRAM, so the correct behavior is to use it if there is no explicit user record.

**Comment by nsidnev** [comment]
Ok, got it, thanks. Can this behavior be documented? Maybe somewhere under [this](https://www.edgedb.com/docs/admin/setup#setting-up-passwordless-connections) section as a separate one?
