### ISSUE TITLE
Fly.io: server instance fails to start

### ISSUE THREAD

**Issue by asfaltboy** [edgedb/edgedb#3638]
EdgeDB Version: 1.2+85bef76
OS Version: fly.io with image edgedb/edgedb

Steps to Reproduce:

1. Sign up for fly.io
2. Follow steps in https://www.edgedb.com/docs/guides/deployment/fly_io
3. Upon completing the step **[Start EdgeDB](https://www.edgedb.com/docs/guides/deployment/fly_io)** obeserve the failure

<details>
  <summary>Click to see log</summary>

```log
2022-03-19T17:53:24Z runner[5cd4687a] lhr [info]Starting instance
2022-03-19T17:53:24Z runner[5cd4687a] lhr [info]Configuring virtual machine
2022-03-19T17:53:24Z runner[5cd4687a] lhr [info]Pulling container image
2022-03-19T17:53:26Z runner[5cd4687a] lhr [info]Unpacking image
2022-03-19T17:53:31Z runner[5cd4687a] lhr [info]Preparing kernel init
2022-03-19T17:53:32Z runner[5cd4687a] lhr [info]Configuring firecracker
2022-03-19T17:53:32Z runner[5cd4687a] lhr [info]Starting virtual machine
2022-03-19T17:53:32Z app[5cd4687a] lhr [info]Starting init (commit: 0c50bff)...
2022-03-19T17:53:32Z app[5cd4687a] lhr [info]Preparing to run: `docker-entrypoint.sh edgedb-server` as root
2022-03-19T17:53:32Z app[5cd4687a] lhr [info]2022/03/19 17:53:32 listening on [fdaa:0:54d5:a7b:a98:5cd4:687a:2]:22 (DNS: [fdaa::3]:53)
2022-03-19T17:53:36Z app[5cd4687a] lhr [info]INFO 516 2022-03-19T17:53:36.520 edb.server: starting EdgeDB server 1.2+85bef76, built on 2022-03-17T18:49Z from revision c0d870b92 (2022-03-16T02:01Z) for x86_64-unknown-linux-gnu
2022-03-19T17:53:38Z app[5cd4687a] lhr [info]INFO 516 2022-03-19T17:53:38.057 edb.server: Detected 297 backend connections available.
2022-03-19T17:53:39Z app[5cd4687a] lhr [info]INFO 516 2022-03-19T17:53:39.160 edb.server: Connection established to backend database: edgedb
2022-03-19T17:53:40Z app[5cd4687a] lhr [info]WARNING 516 2022-03-19T17:53:40.308 edb.server: Released an unhealthy pgcon; discard now.
2022-03-19T17:53:40Z app[5cd4687a] lhr [info]INFO 516 2022-03-19T17:53:40.308 edb.server: Connection discarded to backend database: edgedb
2022-03-19T17:53:40Z app[5cd4687a] lhr [info]---- Exception occurred: unhandled errors in a TaskGroup; 1 sub errors: (ConnectionAbortedError)
2022-03-19T17:53:40Z app[5cd4687a] lhr [info] + ConnectionAbortedError:
2022-03-19T17:53:40Z app[5cd4687a] lhr [info] |   File "/usr/lib/x86_64-linux-gnu/edgedb-server-1/lib/python3.10/site-packages/edb/server/server.py", line 679, in introspect_db
2022-03-19T17:53:40Z app[5cd4687a] lhr [info] |     user_schema = await self.introspect_user_schema(conn)
2022-03-19T17:53:40Z app[5cd4687a] lhr [info] |   File "/usr/lib/x86_64-linux-gnu/edgedb-server-1/lib/python3.10/site-packages/edb/server/server.py", line 629, in introspect_user_schema
2022-03-19T17:53:40Z app[5cd4687a] lhr [info] |     json_data = await conn.parse_execute_json(
2022-03-19T17:53:40Z app[5cd4687a] lhr [info] |   File "edb/server/pgcon/pgcon.pyx", line 794, in parse_execute_json
2022-03-19T17:53:40Z app[5cd4687a] lhr [info] |   File "edb/server/pgcon/pgcon.pyx", line 744, in _parse_execute_json
2022-03-19T17:53:40Z app[5cd4687a] lhr [info] |   File "edb/server/pgcon/pgcon.pyx", line 688, in _parse_execute_to_buf
2022-03-19T17:53:40Z app[5cd4687a] lhr [info] |   File "edb/server/pgcon/pgcon.pyx", line 2143, in wait_for_message
2022-03-19T17:53:40Z app[5cd4687a] lhr [info] ----
2022-03-19T17:53:40Z app[5cd4687a] lhr [info]1. edb.common.taskgroup.TaskGroupError: unhandled errors in a TaskGroup; 1 sub errors: (ConnectionAbortedError)
2022-03-19T17:53:40Z app[5cd4687a] lhr [info] + ConnectionAbortedError:
2022-03-19T17:53:40Z app[5cd4687a] lhr [info] |   File "/usr/lib/x86_64-linux-gnu/edgedb-server-1/lib/python3.10/site-packages/edb/server/server.py", line 679, in introspect_db
2022-03-19T17:53:40Z app[5cd4687a] lhr [info] |     user_schema = await self.introspect_user_schema(conn)
2022-03-19T17:53:40Z app[5cd4687a] lhr [info] |   File "/usr/lib/x86_64-linux-gnu/edgedb-server-1/lib/python3.10/site-packages/edb/server/server.py", line 629, in introspect_user_schema
2022-03-19T17:53:40Z app[5cd4687a] lhr [info] |     json_data = await conn.parse_execute_json(
2022-03-19T17:53:40Z app[5cd4687a] lhr [info] |   File "edb/server/pgcon/pgcon.pyx", line 794, in parse_execute_json
2022-03-19T17:53:40Z app[5cd4687a] lhr [info] |   File "edb/server/pgcon/pgcon.pyx", line 744, in _parse_execute_json
2022-03-19T17:53:40Z app[5cd4687a] lhr [info] |   File "edb/server/pgcon/pgcon.pyx", line 688, in _parse_execute_to_buf
2022-03-19T17:53:40Z app[5cd4687a] lhr [info] |   File "edb/server/pgcon/pgcon.pyx", line 2143, in wait_for_message
2022-03-19T17:53:40Z app[5cd4687a] lhr [info]---- Traceback ----
2022-03-19T17:53:40Z app[5cd4687a] lhr [info]    /usr/lib/x86_64-linux-gnu/edgedb-server-1/bin/edgedb-server.py, line 7, in <module>
2022-03-19T17:53:40Z app[5cd4687a] lhr [info]        > sys.exit(main())
2022-03-19T17:53:40Z app[5cd4687a] lhr [info]    /usr/lib/x86_64-linux-gnu/edgedb-server-1/lib/python3.10/site-packages/click/core.py, line 829, in __call__
2022-03-19T17:53:40Z app[5cd4687a] lhr [info]        > return self.main(*args, **kwargs)
2022-03-19T17:53:40Z app[5cd4687a] lhr [info]    /usr/lib/x86_64-linux-gnu/edgedb-server-1/lib/python3.10/site-packages/click/core.py, line 782, in main
2022-03-19T17:53:40Z app[5cd4687a] lhr [info]        > rv = self.invoke(ctx)
2022-03-19T17:53:40Z app[5cd4687a] lhr [info]    /usr/lib/x86_64-linux-gnu/edgedb-server-1/lib/python3.10/site-packages/click/core.py, line 1066, in invoke
2022-03-19T17:53:40Z app[5cd4687a] lhr [info]        > return ctx.invoke(self.callback, **ctx.params)
2022-03-19T17:53:40Z app[5cd4687a] lhr [info]    /usr/lib/x86_64-linux-gnu/edgedb-server-1/lib/python3.10/site-packages/click/core.py, line 610, in invoke
2022-03-19T17:53:40Z app[5cd4687a] lhr [info]        > return callback(*args, **kwargs)
2022-03-19T17:53:40Z app[5cd4687a] lhr [info]    /usr/lib/x86_64-linux-gnu/edgedb-server-1/lib/python3.10/site-packages/edb/server/main.py, line 624, in main
2022-03-19T17:53:40Z app[5cd4687a] lhr [info]        > server_main(**kwargs)
2022-03-19T17:53:40Z app[5cd4687a] lhr [info]    /usr/lib/x86_64-linux-gnu/edgedb-server-1/lib/python3.10/site-packages/edb/server/main.py, line 609, in server_main
2022-03-19T17:53:40Z app[5cd4687a] lhr [info]        > asyncio.run(run_server(server_args))
2022-03-19T17:53:40Z app[5cd4687a] lhr [info]    /usr/lib/x86_64-linux-gnu/edgedb-server-1/lib/python3.10/asyncio/runners.py, line 44, in run
2022-03-19T17:53:40Z app[5cd4687a] lhr [info]        > return loop.run_until_complete(main)
2022-03-19T17:53:40Z app[5cd4687a] lhr [info]    uvloop/loop.pyx, line 1501, in uvloop.loop.Loop.run_until_complete
2022-03-19T17:53:40Z app[5cd4687a] lhr [info]    /usr/lib/x86_64-linux-gnu/edgedb-server-1/lib/python3.10/site-packages/edb/server/main.py, line 532, in run_server
2022-03-19T17:53:40Z app[5cd4687a] lhr [info]        > await _run_server(
2022-03-19T17:53:40Z app[5cd4687a] lhr [info]    /usr/lib/x86_64-linux-gnu/edgedb-server-1/lib/python3.10/site-packages/edb/server/main.py, line 209, in _run_server
2022-03-19T17:53:40Z app[5cd4687a] lhr [info]        > await sc.wait_for(ss.init())
2022-03-19T17:53:40Z app[5cd4687a] lhr [info]    /usr/lib/x86_64-linux-gnu/edgedb-server-1/lib/python3.10/site-packages/edb/common/signalctl.py, line 160, in wait_for
2022-03-19T17:53:40Z app[5cd4687a] lhr [info]        > return fut.result()
2022-03-19T17:53:40Z app[5cd4687a] lhr [info]    /usr/lib/x86_64-linux-gnu/edgedb-server-1/lib/python3.10/site-packages/edb/server/server.py, line 383, in init
2022-03-19T17:53:40Z app[5cd4687a] lhr [info]        > await self._introspect_dbs()
2022-03-19T17:53:40Z app[5cd4687a] lhr [info]    /usr/lib/x86_64-linux-gnu/edgedb-server-1/lib/python3.10/site-packages/edb/server/server.py, line 760, in _introspect_dbs
2022-03-19T17:53:40Z app[5cd4687a] lhr [info]        > async with taskgroup.TaskGroup(name='introspect DBs') as g:
2022-03-19T17:53:40Z app[5cd4687a] lhr [info]    /usr/lib/x86_64-linux-gnu/edgedb-server-1/lib/python3.10/site-packages/edb/common/taskgroup.py, line 170, in __aexit__
2022-03-19T17:53:40Z app[5cd4687a] lhr [info]        > raise me from None
2022-03-19T17:53:40Z app[5cd4687a] lhr [info]edb.common.taskgroup.TaskGroupError: unhandled errors in a TaskGroup; 1 sub errors: (ConnectionAbortedError)
2022-03-19T17:53:40Z app[5cd4687a] lhr [info] + ConnectionAbortedError:
2022-03-19T17:53:40Z app[5cd4687a] lhr [info] |   File "/usr/lib/x86_64-linux-gnu/edgedb-server-1/lib/python3.10/site-packages/edb/server/server.py", line 679, in introspect_db
2022-03-19T17:53:40Z app[5cd4687a] lhr [info] |     user_schema = await self.introspect_user_schema(conn)
2022-03-19T17:53:40Z app[5cd4687a] lhr [info] |   File "/usr/lib/x86_64-linux-gnu/edgedb-server-1/lib/python3.10/site-packages/edb/server/server.py", line 629, in introspect_user_schema
2022-03-19T17:53:40Z app[5cd4687a] lhr [info] |     json_data = await conn.parse_execute_json(
2022-03-19T17:53:40Z app[5cd4687a] lhr [info] |   File "edb/server/pgcon/pgcon.pyx", line 794, in parse_execute_json
2022-03-19T17:53:40Z app[5cd4687a] lhr [info] |   File "edb/server/pgcon/pgcon.pyx", line 744, in _parse_execute_json
2022-03-19T17:53:40Z app[5cd4687a] lhr [info] |   File "edb/server/pgcon/pgcon.pyx", line 688, in _parse_execute_to_buf
2022-03-19T17:53:40Z app[5cd4687a] lhr [info] |   File "edb/server/pgcon/pgcon.pyx", line 2143, in wait_for_message
2022-03-19T17:53:41Z app[5cd4687a] lhr [info]Main child exited normally with code: 1
2022-03-19T17:53:41Z app[5cd4687a] lhr [info]Starting clean up.
```
</details>

**Comment by riolly** [comment]
I also have issue deploying to fly.io

`edgedb --dsn edgedb://edgedb:mysecretpassword@myedgedb.internal:8080 --tls-security insecure
`

```
edgedb error: InternalServerError:
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "edb/server/pgcon/pgcon.pyx", line 2149, in wait_for_message
      ConnectionAbortedError

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "edb/server/protocol/binary.pyx", line 1311, in edb.server.protocol.binary.EdgeConnection.main
        File "edb/server/protocol/binary.pyx", line 476, in auth
        File "edb/server/protocol/binary.pyx", line 588, in _start_connection
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-2/lib/python3.10/site-packages/edb/server/server.py", line 537, in new_dbview
          await db.introspection()
        File "edb/server/dbview/dbview.pyx", line 258, in introspection
        File "edb/server/dbview/dbview.pyx", line 260, in edb.server.dbview.dbview.Database.introspection
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-2/lib/python3.10/site-packages/edb/server/server.py", line 710, in introspect_db
          user_schema = await self.introspect_user_schema(conn)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-2/lib/python3.10/site-packages/edb/server/server.py", line 656, in introspect_user_schema
          json_data = await conn.sql_fetch_val(self._local_intro_query)
        File "edb/server/pgcon/pgcon.pyx", line 1152, in sql_fetch_val
        File "edb/server/pgcon/pgcon.pyx", line 1137, in sql_fetch
        File "edb/server/pgcon/pgcon.pyx", line 1076, in parse_execute
        File "edb/server/pgcon/pgcon.pyx", line 1059, in _parse_execute
        File "edb/server/pgcon/pgcon.pyx", line 586, in wait_for_sync
        File "edb/server/pgcon/pgcon.pyx", line 2147, in wait_for_message
      ConnectionAbortedError
```

**Comment by elprans** [comment]
Just in case, EdgeDB cannot run on the smallest Fly.io Postgres.

**Comment by fmoor** [comment]
I can't reproduce the OP's error following the current fly deployment guide. At the time of writing the `edgedb/edgedb:latest` points to `2.0`. Perhaps something was fixed since version `1.2`?

**Comment by fmoor** [comment]
@riolly what do your server logs look like? Can you give us the output from `flyctl logs --app $EDB_APP`

**Comment by fmoor** [comment]
Closing due to inactivity.
