### ISSUE TITLE
`insert foo { id }` produces invalid SQL (should just be rejected)

### ISSUE THREAD

**Issue by internalfx** [edgedb/edgedb#3647]
Stack Trace
```
InternalServerError: invalid reference to FROM-clause entry for table "Person~1"
    at RawConnection._parseErrorMessage (/home/bmorris/internalfx/projects/internalfx-icx/node_modules/edgedb/dist/rawConn.js:371:21)
    at RawConnection._executeFlow (/home/bmorris/internalfx/projects/internalfx-icx/node_modules/edgedb/dist/rawConn.js:861:34)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RawConnection.fetch (/home/bmorris/internalfx/projects/internalfx-icx/node_modules/edgedb/dist/rawConn.js:981:13)
    at async ClientConnectionHolder.retryingFetch (/home/bmorris/internalfx/projects/internalfx-icx/node_modules/edgedb/dist/client.js:178:26)
    at async Client.querySingle (/home/bmorris/internalfx/projects/internalfx-icx/node_modules/edgedb/dist/client.js:486:20)
    at async Object.create [as peopleController.create] (/home/bmorris/internalfx/projects/internalfx-icx/api/controllers/peopleController.js:79:20)
    at async /home/bmorris/internalfx/projects/internalfx-icx/system/middleware/router.js:40:7
    at async /home/bmorris/internalfx/projects/internalfx-icx/system/middleware/nuxtRender.js:32:5
    at async /home/bmorris/internalfx/projects/internalfx-icx/system/middleware/httpError.js:5:7
    at async /home/bmorris/internalfx/projects/internalfx-icx/system/middleware/performance.js:5:5
    at async cors (/home/bmorris/internalfx/projects/internalfx-icx/node_modules/@koa/cors/index.js:106:16)
    at async ratelimit (/home/bmorris/internalfx/projects/internalfx-icx/node_modules/koa-ratelimit/index.js:100:33) {
  source: undefined
}
```

- EdgeDB Version: EdgeDB 1.2+5aecabc
- OS Version: POP_os 21.10

Steps to Reproduce:

1. `const query = e.insert(e.Person, () => ({
      firstName: 'john',
      lastName: 'smith',
    }))`
3. `const person = await query.run(client)`

Schema:
```
module default {
  type Person {
    property firstName -> str;
    property middleName -> str;
    property lastName -> str;

    property fullName := .firstName ++ ' ' ++ .lastName;
  }
}
```

**Comment by internalfx** [comment]
User error.

**Comment by jaclarke** [comment]
Re-opening since the InternalServerError is a bug.

Querybuilder generates the (incorrect) edgeql:
```edgeql
INSERT default::Person {
  id
}
```

**Comment by internalfx** [comment]
Hi @jaclarke,

I closed this because I found out I had erroneously used a function when it should have been an object literal.

**Comment by jaclarke** [comment]
Yes, the querybuilder insert usage is incorrect, but the ISE is a bug in EdgeDB, and we should also still throw a useful error in the querybuilder. (I've opened an issue for this in edgeql-js)

**Comment by internalfx** [comment]
> we should also still throw a useful error in the querybuilder.

Awesome, agreed.
