### ISSUE TITLE
`Can't compile ref to visible binding` for nested FOR

### ISSUE THREAD

**Issue by colinhacks** [edgedb/edgedb#3678]
- EdgeDB Version: `2.0-dev.6463+c6f9815` (nightly)
- OS Version: macOS 12.0.1

Steps to reproduce:

Schema:

```
abstract type Person {
  required property name -> str {
    constraint exclusive;
  };
}

type Villain extending Person {
  link nemesis -> Hero;
}

type Hero extending Person {
  property secret_identity -> str;
  property number_of_movies -> int64;
  multi link villains := .<nemesis[IS Villain];
}
```

This query: 

```
WITH
  v := DETACHED default::Villain
SELECT v {
  id,
  name,
  nemesis := (
    WITH
      nemesis := v.nemesis,
      nemesis_mod := (FOR nem IN {nemesis} UNION (
        WITH
          name_len := std::len(nem.name)
        SELECT nem {
          name_len := name_len
        }
      ))
    SELECT nemesis_mod {
      name,
      single nameLen := nemesis_mod.name_len,
      single nameLen2 := nemesis_mod.name_len
    }
  )
}
```

Causes ISE:

```
edgedb error: InternalServerError: Can't compile ref to visible binding ns~5@@(__derived__::nem@w~4)
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/__init__.py", line 114, in compile_ir_to_sql_tree
          qtree = dispatch.compile(ir_expr, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 60, in compile_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 114, in _compile_set_impl
          _compile_set(ir_set, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 643, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 160, in get_set_rvar
          return _process_toplevel_query(ir_set, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 263, in _process_toplevel_query
          rvars = _get_set_rvar(ir_set, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 302, in _get_set_rvar
          rvars = process_set_as_subquery(ir_set, stmt, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 1301, in process_set_as_subquery
          dispatch.visit(expr, ctx=newctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/dispatch.py", line 44, in visit
          compile(ir, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/stmt.py", line 96, in compile_SelectStmt
          outvar = clauses.compile_output(stmt.result, ctx=ictx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/clauses.py", line 203, in compile_output
          dispatch.visit(ir_set, ctx=newctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 85, in visit_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 110, in _compile_set_impl
          _compile_set(ir_set, ctx=scopectx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 647, in _compile_set
          _compile_shape(ir_set, ir_set.shape, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 666, in _compile_shape
          result = shapecomp.compile_shape(ir_set, shape, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/shapecomp.py", line 100, in compile_shape
          wrapper = relgen.set_as_subquery(
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 481, in set_as_subquery
          dispatch.visit(ir_set, ctx=subctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 85, in visit_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 110, in _compile_set_impl
          _compile_set(ir_set, ctx=scopectx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 643, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 207, in get_set_rvar
          rvars = _get_set_rvar(ir_set, ctx=subctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 302, in _get_set_rvar
          rvars = process_set_as_subquery(ir_set, stmt, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 1301, in process_set_as_subquery
          dispatch.visit(expr, ctx=newctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/dispatch.py", line 44, in visit
          compile(ir, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/stmt.py", line 96, in compile_SelectStmt
          outvar = clauses.compile_output(stmt.result, ctx=ictx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/clauses.py", line 203, in compile_output
          dispatch.visit(ir_set, ctx=newctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 85, in visit_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 110, in _compile_set_impl
          _compile_set(ir_set, ctx=scopectx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 643, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 207, in get_set_rvar
          rvars = _get_set_rvar(ir_set, ctx=subctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 302, in _get_set_rvar
          rvars = process_set_as_subquery(ir_set, stmt, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 1301, in process_set_as_subquery
          dispatch.visit(expr, ctx=newctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/dispatch.py", line 44, in visit
          compile(ir, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/stmt.py", line 96, in compile_SelectStmt
          outvar = clauses.compile_output(stmt.result, ctx=ictx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/clauses.py", line 203, in compile_output
          dispatch.visit(ir_set, ctx=newctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 85, in visit_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 110, in _compile_set_impl
          _compile_set(ir_set, ctx=scopectx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 647, in _compile_set
          _compile_shape(ir_set, ir_set.shape, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 666, in _compile_shape
          result = shapecomp.compile_shape(ir_set, shape, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/shapecomp.py", line 100, in compile_shape
          wrapper = relgen.set_as_subquery(
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 481, in set_as_subquery
          dispatch.visit(ir_set, ctx=subctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 85, in visit_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 110, in _compile_set_impl
          _compile_set(ir_set, ctx=scopectx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 643, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 207, in get_set_rvar
          rvars = _get_set_rvar(ir_set, ctx=subctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 302, in _get_set_rvar
          rvars = process_set_as_subquery(ir_set, stmt, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 1301, in process_set_as_subquery
          dispatch.visit(expr, ctx=newctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/dispatch.py", line 44, in visit
          compile(ir, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/stmt.py", line 96, in compile_SelectStmt
          outvar = clauses.compile_output(stmt.result, ctx=ictx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/clauses.py", line 203, in compile_output
          dispatch.visit(ir_set, ctx=newctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 85, in visit_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 110, in _compile_set_impl
          _compile_set(ir_set, ctx=scopectx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 643, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 207, in get_set_rvar
          rvars = _get_set_rvar(ir_set, ctx=subctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 302, in _get_set_rvar
          rvars = process_set_as_subquery(ir_set, stmt, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 1301, in process_set_as_subquery
          dispatch.visit(expr, ctx=newctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/dispatch.py", line 44, in visit
          compile(ir, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/stmt.py", line 96, in compile_SelectStmt
          outvar = clauses.compile_output(stmt.result, ctx=ictx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/clauses.py", line 203, in compile_output
          dispatch.visit(ir_set, ctx=newctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 85, in visit_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 110, in _compile_set_impl
          _compile_set(ir_set, ctx=scopectx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 643, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 207, in get_set_rvar
          rvars = _get_set_rvar(ir_set, ctx=subctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 302, in _get_set_rvar
          rvars = process_set_as_subquery(ir_set, stmt, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 1301, in process_set_as_subquery
          dispatch.visit(expr, ctx=newctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/dispatch.py", line 44, in visit
          compile(ir, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/stmt.py", line 96, in compile_SelectStmt
          outvar = clauses.compile_output(stmt.result, ctx=ictx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/clauses.py", line 203, in compile_output
          dispatch.visit(ir_set, ctx=newctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 85, in visit_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 110, in _compile_set_impl
          _compile_set(ir_set, ctx=scopectx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 643, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 207, in get_set_rvar
          rvars = _get_set_rvar(ir_set, ctx=subctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 302, in _get_set_rvar
          rvars = process_set_as_subquery(ir_set, stmt, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 1301, in process_set_as_subquery
          dispatch.visit(expr, ctx=newctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/dispatch.py", line 44, in visit
          compile(ir, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/stmt.py", line 96, in compile_SelectStmt
          outvar = clauses.compile_output(stmt.result, ctx=ictx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/clauses.py", line 203, in compile_output
          dispatch.visit(ir_set, ctx=newctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 85, in visit_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 114, in _compile_set_impl
          _compile_set(ir_set, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 643, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 207, in get_set_rvar
          rvars = _get_set_rvar(ir_set, ctx=subctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 383, in _get_set_rvar
          rvars = process_set_as_func_expr(ir_set, stmt, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 2889, in process_set_as_func_expr
          args = _compile_call_args(ir_set, ctx=newctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 2800, in _compile_call_args
          arg_ref = dispatch.compile(ir_arg.expr, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 60, in compile_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 114, in _compile_set_impl
          _compile_set(ir_set, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 643, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 207, in get_set_rvar
          rvars = _get_set_rvar(ir_set, ctx=subctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 418, in _get_set_rvar
          rvars = process_set_as_path(ir_set, stmt, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 1073, in process_set_as_path
          ensure_source_rvar(ir_source, stmt, ctx=ctx),
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 441, in ensure_source_rvar
          get_set_rvar(ir_set, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 207, in get_set_rvar
          rvars = _get_set_rvar(ir_set, ctx=subctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 426, in _get_set_rvar
          rvars = process_set_as_root(ir_set, stmt, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 710, in process_set_as_root
          assert not ir_set.is_visible_binding_ref, (
      AssertionError: Can't compile ref to visible binding ns~5@@(__derived__::nem@w~4)
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/server/compiler_pool/worker.py", line 309, in worker
          res = meth(*args)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/server/compiler_pool/worker.py", line 177, in compile
          units, cstate = COMPILER.compile(
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 2109, in compile
          units = self._compile(ctx=ctx, source=source)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 1671, in _compile
          return self._try_compile(ctx=ctx, source=source)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 1724, in _try_compile
          comp, capabilities = self._compile_dispatch_ql(
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 1645, in _compile_dispatch_ql
          query = self._compile_ql_query(ctx, ql)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 605, in _compile_ql_query
          sql_text, argmap = pg_compiler.compile_ir_to_sql(
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/__init__.py", line 146, in compile_ir_to_sql
          qtree = compile_ir_to_sql_tree(
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6463/lib/python3.10/site-packages/edb/pgsql/compiler/__init__.py", line 129, in compile_ir_to_sql_tree
          raise errors.InternalServerError(*args) from e
      edb.errors.InternalServerError: Can't compile ref to visible binding ns~5@@(__derived__::nem@w~4)

```

**Comment by msullivan** [comment]
```
SELECT User {
  name,
  avatar := (
    WITH
      nemesis := User.avatar,
      nemesis_mod := (FOR nem IN {nemesis} UNION (
        WITH
          name_len := std::len(nem.name)
        SELECT nem {
          name_len := name_len
        }
      ))
    SELECT nemesis_mod {
      name,
      single nameLen := nemesis_mod.name_len,
      single nameLen2 := nemesis_mod.name_len
    }
  )
};
```
is a version that fails on the `scope` database
