### ISSUE TITLE
ISE on `elements` subquery in `group`

### ISSUE THREAD

**Issue by colinhacks** [edgedb/edgedb#3951]
A simple `group` statement implemented with the query builder may look like this:

```ts
const group = e.group(e.Movie, movie => ({
  ry: movie.release_year,
}));
```

To customize the shape of `elements`, users must wrap this in an outer select:

```ts
const query = e.select(group, () => ({
    key: true,
    grouping: true,
    elements: {
      title: true,
      release_year: true,
    }
  }));
```

This produces the following query, which throws an `ISE: None`:

```
WITH
  __scope_0_GroupResult := (
    WITH
      __scope_2_Movie := DETACHED default::Movie
    GROUP __scope_2_Movie
    USING
      ry := __scope_2_Movie.release_year
    BY ry
  )
SELECT __scope_0_GroupResult {
  key,
  grouping,
  multi elements := (
    WITH
      __scope_1_Movie := __scope_0_GroupResult.elements
    SELECT __scope_1_Movie {
      title,
      release_year
    }
  )
};
```

A similar approach (where nested shapes are compiled to subqueries) works elsewhere. Full traceback:

```
edgedb error: InternalServerError: None
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/__init__.py", line 118, in compile_ir_to_sql_tree
          qtree = dispatch.compile(ir_expr, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 60, in compile_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 114, in _compile_set_impl
          _compile_set(ir_set, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 633, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 160, in get_set_rvar
          return _process_toplevel_query(ir_set, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 263, in _process_toplevel_query
          rvars = _get_set_rvar(ir_set, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 302, in _get_set_rvar
          rvars = process_set_as_subquery(ir_set, stmt, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 1334, in process_set_as_subquery
          dispatch.visit(expr, ctx=newctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/dispatch.py", line 44, in visit
          compile(ir, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/stmt.py", line 97, in compile_SelectStmt
          outvar = clauses.compile_output(stmt.result, ctx=ictx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/clauses.py", line 204, in compile_output
          dispatch.visit(ir_set, ctx=newctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 85, in visit_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 110, in _compile_set_impl
          _compile_set(ir_set, ctx=scopectx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 637, in _compile_set
          _compile_shape(ir_set, ir_set.shape, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 656, in _compile_shape
          result = shapecomp.compile_shape(ir_set, shape, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/shapecomp.py", line 100, in compile_shape
          wrapper = relgen.set_as_subquery(
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 482, in set_as_subquery
          dispatch.visit(ir_set, ctx=subctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 85, in visit_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 110, in _compile_set_impl
          _compile_set(ir_set, ctx=scopectx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 633, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 207, in get_set_rvar
          rvars = _get_set_rvar(ir_set, ctx=subctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 302, in _get_set_rvar
          rvars = process_set_as_subquery(ir_set, stmt, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 1334, in process_set_as_subquery
          dispatch.visit(expr, ctx=newctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/dispatch.py", line 44, in visit
          compile(ir, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/stmt.py", line 97, in compile_SelectStmt
          outvar = clauses.compile_output(stmt.result, ctx=ictx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/clauses.py", line 204, in compile_output
          dispatch.visit(ir_set, ctx=newctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 85, in visit_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 110, in _compile_set_impl
          _compile_set(ir_set, ctx=scopectx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 633, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 207, in get_set_rvar
          rvars = _get_set_rvar(ir_set, ctx=subctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 302, in _get_set_rvar
          rvars = process_set_as_subquery(ir_set, stmt, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 1334, in process_set_as_subquery
          dispatch.visit(expr, ctx=newctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/dispatch.py", line 44, in visit
          compile(ir, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/stmt.py", line 97, in compile_SelectStmt
          outvar = clauses.compile_output(stmt.result, ctx=ictx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/clauses.py", line 204, in compile_output
          dispatch.visit(ir_set, ctx=newctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 85, in visit_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 110, in _compile_set_impl
          _compile_set(ir_set, ctx=scopectx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 633, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 207, in get_set_rvar
          rvars = _get_set_rvar(ir_set, ctx=subctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 302, in _get_set_rvar
          rvars = process_set_as_subquery(ir_set, stmt, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 1334, in process_set_as_subquery
          dispatch.visit(expr, ctx=newctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/dispatch.py", line 44, in visit
          compile(ir, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/stmt.py", line 97, in compile_SelectStmt
          outvar = clauses.compile_output(stmt.result, ctx=ictx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/clauses.py", line 204, in compile_output
          dispatch.visit(ir_set, ctx=newctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 85, in visit_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 110, in _compile_set_impl
          _compile_set(ir_set, ctx=scopectx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 633, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 207, in get_set_rvar
          rvars = _get_set_rvar(ir_set, ctx=subctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 296, in _get_set_rvar
          rvars = process_set_as_subquery(ir_set, stmt, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 1301, in process_set_as_subquery
          or _lookup_set_rvar_in_source(ir_set, source_set_rvar, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 1205, in _lookup_set_rvar_in_source
          if packed_ref := pathctx.maybe_get_rvar_path_var(
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/pathctx.py", line 752, in maybe_get_rvar_path_var
          return get_rvar_path_var(
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/pathctx.py", line 735, in get_rvar_path_var
          outvar = get_path_output(
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/pathctx.py", line 1068, in get_path_output
          return _get_path_output(rel, path_id=path_id, aspect=aspect,
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/pathctx.py", line 1128, in _get_path_output
          ref = get_path_var(rel, path_id, aspect=aspect, flavor=flavor, env=env)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/pathctx.py", line 232, in get_path_var
          src_aspect, rel_rvar, found_path_var = _find_rel_rvar(
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/pathctx.py", line 352, in _find_rel_rvar
          assert flavor == 'normal'
      AssertionError
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/server/compiler_pool/worker_proc.py", line 55, in worker
          res = meth(*args)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/server/compiler_pool/worker.py", line 158, in compile
          units, cstate = COMPILER.compile(
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 2142, in compile
          units = self._compile(ctx=ctx, source=source)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 1694, in _compile
          return self._try_compile(ctx=ctx, source=source)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 1747, in _try_compile
          comp, capabilities = self._compile_dispatch_ql(
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 1668, in _compile_dispatch_ql
          query = self._compile_ql_query(ctx, ql)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 614, in _compile_ql_query
          sql_text, argmap = pg_compiler.compile_ir_to_sql(
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/__init__.py", line 150, in compile_ir_to_sql
          qtree = compile_ir_to_sql_tree(
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6625/lib/python3.10/site-packages/edb/pgsql/compiler/__init__.py", line 133, in compile_ir_to_sql_tree
          raise errors.InternalServerError(*args) from e
      edb.errors.InternalServerError: None
```

**Comment by msullivan** [comment]
Could you check if  #3927 fixed it?

**Comment by colinhacks** [comment]
Problem still happens using the most recent nightly (`2.0-dev.6638+4b0caac`).

**Comment by msullivan** [comment]
Moves it to a different assert failure, but still broken, yeah
