### ISSUE TITLE
"ISE: Cannot determine backend storage parameters" on GROUP with `with` and shape

### ISSUE THREAD

**Issue by colinhacks** [edgedb/edgedb#3967]
The query builder does automatic `with` extraction that produces queries like this:

```
WITH
  __scope_0_Movie_expr := DETACHED default::Movie,
  __scope_0_Movie := (FOR __scope_0_Movie_inner IN {__scope_0_Movie_expr} UNI
ON (
    WITH
      __withVar_1 := std::len(__scope_0_Movie_inner.title)
    SELECT __scope_0_Movie_inner {
      __withVar_1 := __withVar_1
    }
  ))
GROUP __scope_0_Movie {
  id,
  title
}
USING
  title := std::len(__scope_0_Movie.title),
  title1 := __scope_0_Movie.__withVar_1,
  title2 := __scope_0_Movie.__withVar_1,
  title3 := __scope_0_Movie.__withVar_1
BY title1, title2, title3;
```

This query fails with `edgedb error: InternalServerError: cannot determine backend storage parameters for the <QualName __derived__::__|__withVar_1@__derived__|__scope_0_Movie&w~2> pointer: the cardinality is not known`.

The query works if the shape is removed:

```
WITH
  __scope_0_Movie_expr := DETACHED default::Movie,
  __scope_0_Movie := (FOR __scope_0_Movie_inner IN {__scope_0_Movie_expr} UNI
ON (
    WITH
      __withVar_1 := std::len(__scope_0_Movie_inner.title)
    SELECT __scope_0_Movie_inner {
      __withVar_1 := __withVar_1
    }
  ))
GROUP __scope_0_Movie
USING
  title := std::len(__scope_0_Movie.title),
  title1 := __scope_0_Movie.__withVar_1,
  title2 := __scope_0_Movie.__withVar_1,
  title3 := __scope_0_Movie.__withVar_1
BY title1, title2, title3;
```
Full traceback:

```
edgedb> WITH
.......   __scope_0_Movie_expr := DETACHED default::Movie,
.......   __scope_0_Movie := (FOR __scope_0_Movie_inner IN {__scope_0_Movie_expr} UNI
ON (
.......     WITH
.......       __withVar_1 := std::len(__scope_0_Movie_inner.title)
.......     SELECT __scope_0_Movie_inner {
.......       __withVar_1 := __withVar_1
.......     }
.......   ))
....... GROUP __scope_0_Movie {
.......   id,
.......   title
....... }
....... USING
.......   title := std::len(__scope_0_Movie.title),
.......   title1 := __scope_0_Movie.__withVar_1,
.......   title2 := __scope_0_Movie.__withVar_1,
.......   title3 := __scope_0_Movie.__withVar_1
....... BY title1, title2, title3;
edgedb error: InternalServerError: cannot determine backend storage parameters for the <QualName __derived__::__|__withVar_1@__derived__|__scope_0_Movie&w~2> pointer: the cardinality is not known
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6638/lib/python3.10/site-packages/edb/pgsql/compiler/__init__.py", line 118, in compile_ir_to_sql_tree
          qtree = dispatch.compile(ir_expr, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6638/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6638/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 60, in compile_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6638/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 114, in _compile_set_impl
          _compile_set(ir_set, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6638/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 633, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6638/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 160, in get_set_rvar
          return _process_toplevel_query(ir_set, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6638/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 263, in _process_toplevel_query
          rvars = _get_set_rvar(ir_set, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6638/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 302, in _get_set_rvar
          rvars = process_set_as_subquery(ir_set, stmt, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6638/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 1334, in process_set_as_subquery
          dispatch.visit(expr, ctx=newctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6638/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6638/lib/python3.10/site-packages/edb/pgsql/compiler/dispatch.py", line 44, in visit
          compile(ir, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6638/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6638/lib/python3.10/site-packages/edb/pgsql/compiler/stmt.py", line 146, in compile_GroupStmt
          return group.compile_group(stmt, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6638/lib/python3.10/site-packages/edb/pgsql/compiler/group.py", line 386, in compile_group
          return _compile_group(stmt, ctx=sctx, parent_ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6638/lib/python3.10/site-packages/edb/pgsql/compiler/group.py", line 221, in _compile_group
          dispatch.visit(value, ctx=groupctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6638/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6638/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 85, in visit_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6638/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 110, in _compile_set_impl
          _compile_set(ir_set, ctx=scopectx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6638/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 633, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6638/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 207, in get_set_rvar
          rvars = _get_set_rvar(ir_set, ctx=subctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6638/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 302, in _get_set_rvar
          rvars = process_set_as_subquery(ir_set, stmt, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6638/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 1334, in process_set_as_subquery
          dispatch.visit(expr, ctx=newctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6638/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6638/lib/python3.10/site-packages/edb/pgsql/compiler/dispatch.py", line 44, in visit
          compile(ir, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6638/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6638/lib/python3.10/site-packages/edb/pgsql/compiler/stmt.py", line 97, in compile_SelectStmt
          outvar = clauses.compile_output(stmt.result, ctx=ictx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6638/lib/python3.10/site-packages/edb/pgsql/compiler/clauses.py", line 204, in compile_output
          dispatch.visit(ir_set, ctx=newctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6638/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6638/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 85, in visit_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6638/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 110, in _compile_set_impl
          _compile_set(ir_set, ctx=scopectx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6638/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 633, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6638/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 155, in get_set_rvar
          if rvar := _lookup_set_rvar(ir_set, scope_stmt=scope_stmt, ctx=ctx):
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6638/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 136, in _lookup_set_rvar
          rvar = relctx.unpack_rvar(
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6638/lib/python3.10/site-packages/edb/pgsql/compiler/relctx.py", line 915, in unpack_rvar
          ref = pathctx.get_rvar_path_var(
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6638/lib/python3.10/site-packages/edb/pgsql/compiler/pathctx.py", line 734, in get_rvar_path_var
          outvar = get_path_output(
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6638/lib/python3.10/site-packages/edb/pgsql/compiler/pathctx.py", line 1067, in get_path_output
          return _get_path_output(rel, path_id=path_id, aspect=aspect,
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6638/lib/python3.10/site-packages/edb/pgsql/compiler/pathctx.py", line 1127, in _get_path_output
          ref = get_path_var(rel, path_id, aspect=aspect, flavor=flavor, env=env)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6638/lib/python3.10/site-packages/edb/pgsql/compiler/pathctx.py", line 162, in get_path_var
          ptr_info = pg_types.get_ptrref_storage_info(
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6638/lib/python3.10/site-packages/edb/pgsql/types.py", line 437, in get_ptrref_storage_info
          return _get_ptrref_storage_info(
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6638/lib/python3.10/site-packages/edb/pgsql/types.py", line 457, in _get_ptrref_storage_info
          raise RuntimeError(
      RuntimeError: cannot determine backend storage parameters for the <QualName __derived__::__|__withVar_1@__derived__|__scope_0_Movie&w~2> pointer: the cardinality is not known
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6638/lib/python3.10/site-packages/edb/server/compiler_pool/worker_proc.py", line 55, in worker
          res = meth(*args)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6638/lib/python3.10/site-packages/edb/server/compiler_pool/worker.py", line 158, in compile
          units, cstate = COMPILER.compile(
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6638/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 2142, in compile
          units = self._compile(ctx=ctx, source=source)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6638/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 1694, in _compile
          return self._try_compile(ctx=ctx, source=source)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6638/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 1747, in _try_compile
          comp, capabilities = self._compile_dispatch_ql(
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6638/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 1668, in _compile_dispatch_ql
          query = self._compile_ql_query(ctx, ql)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6638/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 614, in _compile_ql_query
          sql_text, argmap = pg_compiler.compile_ir_to_sql(
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6638/lib/python3.10/site-packages/edb/pgsql/compiler/__init__.py", line 150, in compile_ir_to_sql
          qtree = compile_ir_to_sql_tree(
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0-dev.6638/lib/python3.10/site-packages/edb/pgsql/compiler/__init__.py", line 133, in compile_ir_to_sql_tree
          raise errors.InternalServerError(*args) from e
      edb.errors.InternalServerError: cannot determine backend storage parameters for the <QualName __derived__::__|__withVar_1@__derived__|__scope_0_Movie&w~2> pointer: the cardinality is not known
```

**Comment by msullivan** [comment]
Obviously it's a bug either way, but what's the deal with using for like that?

**Comment by colinhacks** [comment]
Basically the query builder makes it easy to declare intermediate variables that depend on each other:

```
e.group(e.Movie, movie => ({
  const titleLen = e.len(movie.title);
  const titleLenPlusOne = e.op(titleLen, '+', 1);
  const titleLenPlusTwo = e.op(titleLenPlusOne, '+', 1);

  return {
    title: true,
    titleLenPlusTwo, 
    by: { titleLenPlusTwo }
  }
}));
```

Because we automatically extract all expressions that occur more than once, we need some sort of `with` construct s.t. we can declare a series of computed expressions, some of which may reference previously defined expressions. So we do this weird `for` construct to do that.

```
WITH
  __scope_0_Movie_expr := DETACHED default::Movie,
  __scope_0_Movie := (FOR __scope_0_Movie_inner IN {__scope_0_Movie_expr} UNION (
    WITH
      __withVar_1 := std::len(__scope_0_Movie_inner.title),
      __withVar_2 := (__withVar_1 + 1)
    SELECT __scope_0_Movie_inner {
      __withVar_1 := __withVar_1,
      __withVar_2 := __withVar_2
    }
  ))
SELECT __scope_0_Movie {
  title,
  single titleLen := __scope_0_Movie.__withVar_1,
  single titleLenPlusOne := __scope_0_Movie.__withVar_2,
  single titleLenPlusTwo := (__scope_0_Movie.__withVar_2 + 1)
}
```

Another possibly nicer alternative (which I alluded to on the call) would be to use a series of anonymous aliases. But as you add more of these in a row, the query gets slower and slower. For me, compilation hangs if you add ~12-15 of these in a row.

```
WITH
  __scope_0_Movie_0 := DETACHED default::Movie,
  __scope_0_Movie_1 := (__scope_0_Movie_0 {
    __withVar_1 := std::len(__scope_0_Movie_inner.title)
  }),
  scope_0_Movie_final := (__scope_0_Movie_1 {
    __withVar_2 := (__scope_0_Movie_1.__withVar_1 + 1)
  })
SELECT scope_0_Movie_final {
  title,
  single titleLen := __scope_0_Movie.__withVar_1,
  single titleLenPlusOne := scope_0_Movie_final.__withVar_2,
  single titleLenPlusTwo := (scope_0_Movie_final.__withVar_2 + 1)
}
```
