### ISSUE TITLE
InternalServerError changing listen_addresses on bare metal install

### ISSUE THREAD

**Issue by fmoor** [edgedb/edgedb#3971]
I followed the instructions in the [bare metal deployment guide](https://www.edgedb.com/docs/guides/deployment/bare_metal) and discovered that I could not change the `listen_addresses` without restarting the server.

- EdgeDB Version: EdgeDB 1.4+9d299d7 (repl 1.1.2+f832277)
- OS Version: ubuntu 22.04

Steps to Reproduce:
```bash
$ sudo edgedb --tls-security=insecure --admin -P 5656
EdgeDB 1.4+9d299d7 (repl 1.1.2+f832277)
Type \help for help, \quit to quit.
edgedb> alter role edgedb set password := 'super1secret';
OK: ALTER ROLE

edgedb> configure instance set listen_addresses := {'0.0.0.0'};
Error: InternalServerError: could not create any listen sockets
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md

edgedb> \q
$ sudo systemctl restart edgedb-server-1.service
$ sudo edgedb --tls-security=insecure -P 5656 --password
Password for 'edgedb':
EdgeDB 1.4+9d299d7 (repl 1.1.2+f832277)
Type \help for help, \quit to quit.
edgedb> configure instance set listen_addresses := {'0.0.0.0'};
OK: CONFIGURE INSTANCE
edgedb> \q
```

**Comment by elprans** [comment]
This isn't specific to "bare metal", easily reproducible on a dev build too.

**Comment by coleerickson** [comment]
Still here in `EdgeDB 1.4+0a5653c (repl 1.2.2+e81d259)`

```
root@edgedb-test-1:~# sudo edgedb --port 5656 --tls-security insecure --password query  "CONFIGURE INSTANCE SET listen_addresses := {'0.0.0.0'};"
Password for 'edgedb':
edgedb error: InternalServerError: could not create any listen sockets
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "edb/server/protocol/binary.pyx", line 1845, in edb.server.protocol.binary.EdgeConnection.main
        File "edb/server/protocol/binary.pyx", line 1712, in execute
        File "edb/server/protocol/binary.pyx", line 1662, in _execute
        File "edb/server/protocol/binary.pyx", line 1619, in edb.server.protocol.binary.EdgeConnection._execute
        File "edb/server/protocol/binary.pyx", line 1560, in _execute_system_config
        File "edb/server/dbview/dbview.pyx", line 550, in apply_config_ops
        File "edb/server/dbview/dbview.pyx", line 693, in apply_system_config_op
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1/lib/python3.10/site-packages/edb/server/server.py", line 978, in _on_system_config_set
          await self._restart_servers_new_addr(value, self._listen_port)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1/lib/python3.10/site-packages/edb/server/server.py", line 884, in _restart_servers_new_addr
          new_servers, *_ = await self._start_servers(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1/lib/python3.10/site-packages/edb/server/server.py", line 1412, in _start_servers
          raise StartupError("could not create any listen sockets")
      edb.server.server.StartupError: could not create any listen sockets
```
