### ISSUE TITLE
Can't install on WSL

### ISSUE THREAD

**Issue by aradalvand** [edgedb/edgedb#4082]
Hi there.
I'm on Windows 11 (build 22622, if that matters) and I've been trying to install EdgeDB on WSL Ubuntu 20.04.

As per the [instructions in the documentation](https://www.edgedb.com/docs/guides/quickstart#installation), first I ran the following command:
```bash
curl https://sh.edgedb.com --proto '=https' -sSf1 | sh
```
And then:
```bash
edgedb project init
```
Leading to the following error:
![image](https://user-images.githubusercontent.com/26527405/179272244-96e77421-4c9d-4084-a1c8-a8717a14c2f3.png)
Clearly, this has something to do with the fact that there's no `systemd` and by extension `systemctl` in WSL.

But how are you supposed to get EdgeDB work on WSL exactly? I searched through the issues in this repo and also [edgedb/edgedb-cli](https://github.com/edgedb/edgedb-cli) but the explanations and the suggested workarounds were either confusing or outdated/didn't work.

Thanks.

**Comment by aradalvand** [comment]
> Are you planning to run your app in WSL also? If not, then you can consider using the Windows-native CLI build which does not rely on systemd at all (although it still uses WSL under the hood to run the server in a separate distro).

Well, I use WSL as my development workspace, so I have everything dev-related installed there (Node, etc.), it would be awkward to have to make an exception for EdgeDB.
But even ignoring this, would I then be able to run the `edgedb` command in my Ubuntu WSL if I install the Windows-native CLI?

Isn't there a way I can manually start the relevant service? Note that in WSL you CAN start services like `sudo service [service-name] start`, just not with `systemctl`. This is for example how I start Postgres (`sudo service postgresql start`).

**Comment by elprans** [comment]
> WSL is getting more and more popular, so I think it's important to make sure the experience is as seamless and hassle-free as possible there

Absolutely, we're working on it.  (Ideally, of course, Microsoft should just make systemd work in WSL distros (there are even third-party hacks to make it work)

**Comment by riolly** [comment]
I still get the same error when initializing a project even though my `systemctl` has run.
I using this [workaround](https://github.com/nullpo-head/wsl-distrod) to enable `systemd` in WSL.

WSL2 - ubuntu 20.04
edgedb 1.4 & edged 2,0-rc2

```
● riolly-windows
    State: running
     Jobs: 0 queued
   Failed: 0 units
    Since: Mon 2022-07-18 22:14:12 WIB; 5min ago
   CGroup: /
           ├─init.scope
           │ └─1 /sbin/init systemd.setenv=WSLENV= systemd.setenv=WSL_INTEROP=/run/WSL/8_interop systemd.setenv=WSL_DIS>
           ├─system.slice
           │ ├─snap-lxd-19188.mount
           │ │ └─86 snapfuse /var/lib/snapd/snaps/lxd_19188.snap /snap/lxd/19188 -o ro,nodev,allow_other,suid
           │ ├─systemd-networkd.service
           │ │ └─118 /lib/systemd/systemd-networkd
           │ ├─systemd-udevd.service
           │ │ └─65 /lib/systemd/systemd-udevd
           │ ├─cron.service
           │ │ └─309 /usr/sbin/cron -f
```

**Comment by riolly** [comment]
> And it fails to detect the _toml_ file even though it have been initialized.
> 
> Using next.js server API and following this [guide](https://www.edgedb.com/docs/guides/tutorials/nextjs).
> 
> ```
> error - ClientConnectionError: Found 'edgedb.toml' but the project is not initialized. Run `edgedb project init`.
>     at parseConnectDsnAndArgs (/home/alberto/sandbox/edgedb-nextjs/node_modules/edgedb/dist/conUtils.js:458:19)
>     at async parseConnectArguments (/home/alberto/sandbox/edgedb-nextjs/node_modules/edgedb/dist/conUtils.js:54:13)
>     at async ClientPool.getNewConnection (/home/alberto/sandbox/edgedb-nextjs/node_modules/edgedb/dist/client.js:338:24)
>     at async ClientConnectionHolder._getConnection (/home/alberto/sandbox/edgedb-nextjs/node_modules/edgedb/dist/client.js:89:32)
>     at async ClientConnectionHolder.retryingFetch (/home/alberto/sandbox/edgedb-nextjs/node_modules/edgedb/dist/client.js:176:26)
>     at async Client.query (/home/alberto/sandbox/edgedb-nextjs/node_modules/edgedb/dist/client.js:468:20)
>     at async handler (webpack-internal:///(api)/./pages/api/post.ts:11:19)
>     at async Object.apiResolver (/home/alberto/sandbox/edgedb-nextjs/node_modules/next/dist/server/api-utils/node.js:179:9)
>     at async DevServer.runApi (/home/alberto/sandbox/edgedb-nextjs/node_modules/next/dist/server/next-server.js:381:9)
>     at async Object.fn (/home/alberto/sandbox/edgedb-nextjs/node_modules/next/dist/server/base-server.js:497:37) {
>   source: undefined,
>   page: '/api/post'
> }
> ```

We just need to run the `edgedb project init` again and use the instance that has been created on the first. 
Oh my goodness 😞

**Comment by tailhook** [comment]
@aradalvand, @riolly, can you please try the latest nightly?
```
curl https://sh.edgedb.com --proto '=https' -sSf1 | sh -s -- --nightly
```
It seems to work for me both within default ubuntu and distrod. If it doesn't please show the output of the `env` command.

**Comment by riolly** [comment]
I'm done with WSL. 
Recently I install dual boot Linux instead. 
I really want to use edgedb.

Because there is also a problem when I run `npx edgedb-js` when generating the edgejs.

**Comment by cerenodeng** [comment]
The same issue is happened for EdgeDB 3.5 on WSL too.

```
Successfully installed 3.5+719acc6
Initializing EdgeDB instance...
[systemctl] Failed to connect to bus: No such file or directory
[2023-10-31T13:36:50Z WARN  edgedb::portable::linux] failed to reload systemd daemon: systemctl failed: exit status: 1 (command-line: Command { std: LANG="C.UTF-8" LC_ALL="C.UTF-8" "systemctl" "--user" "daemon-reload", kill_on_drop: false })
[systemctl] Created symlink /home/me/.config/systemd/user/default.target.wants/edgedb-server@my_project.socket → /home/me/.config/systemd/user/edgedb-server@my_project.socket.
[systemctl] Failed to connect to bus: No such file or directory
[2023-10-31T13:36:50Z WARN  edgedb::portable::project] Error running EdgeDB as a service: service start failed: exit status: 1 (command-line: Command { std: LANG="C.UTF-8" LC_ALL="C.UTF-8" "systemctl" "--user" "start" "edgedb-server@my_project.socket", kill_on_drop: false })
EdgeDB will not start on next login. Trying to start database in the background...
```
