### ISSUE TITLE
Migration fails with sub-nested hierarchies

### ISSUE THREAD

**Issue by fantix** [edgedb/edgedb#4105]
- EdgeDB Version: 2.0-rc.3+f035802, 3.0-dev.6761+local

Maybe related: #3289.

Steps to Reproduce:

```
edgedb> start migration to {}; populate migration; commit migration;
OK: START MIGRATION
OK: POPULATE MIGRATION
Error: InternalServerError: column old.bcab4e74-0793-11ed-81d4-a5e4b75261ac does not exist
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
```

Schema:
```
abstract type R {
    required property name -> str {
        delegated constraint exclusive;
    }
}

type S extending R {
    required property s -> str;
}


type T extending R {
    required property t -> str;
}


type V extending S, T;
```

**Comment by msullivan** [comment]
There is a follow-on issue here, which is that after I get the ISE, when I try to rollback, I get
```
edgedb error: InternalServerError: failed to lookup transaction or savepoint with id=6606099709193
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "/home/sully/src/e/edgedb/edb/server/compiler_pool/worker_proc.py", line 55, in worker
          res = meth(*args)
        File "/home/sully/src/e/edgedb/edb/server/compiler_pool/worker.py", line 185, in compile_in_tx
          units, cstate = COMPILER.compile_in_tx(cstate, *args, **kwargs)
        File "/home/sully/src/e/edgedb/edb/server/compiler/compiler.py", line 2198, in compile_in_tx
          state.sync_tx(txid)
        File "/home/sully/src/e/edgedb/edb/server/compiler/dbstate.py", line 762, in sync_tx
          raise errors.InternalServerError(
      edb.errors.InternalServerError: failed to lookup transaction or savepoint with id=6606099709193
```

**Comment by msullivan** [comment]
Oh, to make things better, the constraints don't work right either:
```
edgedb> insert S { name := "!", s := "1" };
{default::S {id: 9ed97756-093f-11ed-afc6-33b5f34ff832}}
edgedb> insert V { name := "!", s := "2", t := "2" };
{default::V {id: a490c280-093f-11ed-afc6-e762a7374254}}
```
All of the other permutations work right, though: inserting V and then S properly errors, as do both directions of `T` and `V`.

**Comment by fantix** [comment]
> There is a follow-on issue here, which is that after I get the ISE, when I try to rollback, I get
> 
> ```
> edgedb error: InternalServerError: failed to lookup transaction or savepoint with id=6606099709193
>   Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
>   Server traceback:
>       Traceback (most recent call last):
>         File "/home/sully/src/e/edgedb/edb/server/compiler_pool/worker_proc.py", line 55, in worker
>           res = meth(*args)
>         File "/home/sully/src/e/edgedb/edb/server/compiler_pool/worker.py", line 185, in compile_in_tx
>           units, cstate = COMPILER.compile_in_tx(cstate, *args, **kwargs)
>         File "/home/sully/src/e/edgedb/edb/server/compiler/compiler.py", line 2198, in compile_in_tx
>           state.sync_tx(txid)
>         File "/home/sully/src/e/edgedb/edb/server/compiler/dbstate.py", line 762, in sync_tx
>           raise errors.InternalServerError(
>       edb.errors.InternalServerError: failed to lookup transaction or savepoint with id=6606099709193
> ```

This was introduced in #4065 where we use regular `compile()` to compile expected `rollback`, also caused a regression like this:

```
edgedb> start transaction;
OK: START TRANSACTION
edgedb[tx]> select 1/0;
edgedb error: DivisionByZeroError: division by zero
edgedb[tx:failed]> commit;
edgedb error: TransactionError: current transaction is aborted, commands ignored until end of transaction block
edgedb[tx:failed]> rollback;
edgedb error: InternalServerError: failed to lookup transaction or savepoint with id=76599601371706
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "edb/server/compiler_pool/worker_proc.py", line 55, in worker
          res = meth(*args)
        File "edb/server/compiler_pool/worker.py", line 185, in compile_in_tx
          units, cstate = COMPILER.compile_in_tx(cstate, *args, **kwargs)
        File "edb/server/compiler/compiler.py", line 2198, in compile_in_tx
          state.sync_tx(txid)
        File "edb/server/compiler/dbstate.py", line 762, in sync_tx
          raise errors.InternalServerError(
      edb.errors.InternalServerError: failed to lookup transaction or savepoint with id=76599601371706
```

I'm working on a fix.
