### ISSUE TITLE
ISE on `unless conflict` when setting custom `id`

### ISSUE THREAD

**Issue by colinhacks** [edgedb/edgedb#4184]
On 2.0, the following causes an ISE. I've enabled `allow_user_specified_id`.

```
INSERT default::Hero {
   name := "asdf",
   id := <uuid>"00000000-0000-0000-0000-000000000000"
} 
UNLESS CONFLICT;
```

This works with `unless conflict on (.id)` or when not setting a custom `id`.

-------

Full traceback:

```
edgedb> INSERT default::Hero {
.......    name := "asdf",
.......    id := <uuid>"00000000-0000-0000-0000-000000000000"
....... } 
....... UNLESS CONFLICT;
edgedb error: InternalServerError: 
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0/lib/python3.10/site-packages/edb/server/compiler_pool/worker_proc.py", line 55, in worker
          res = meth(*args)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0/lib/python3.10/site-packages/edb/server/compiler_pool/worker.py", line 160, in compile
          units, cstate = COMPILER.compile(
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 2207, in compile
          unit_group = self._compile(ctx=ctx, source=source)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 1738, in _compile
          return self._try_compile(ctx=ctx, source=source)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 1802, in _try_compile
          comp, capabilities = self._compile_dispatch_ql(
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 1712, in _compile_dispatch_ql
          query = self._compile_ql_query(ctx, ql, script_info=script_info)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 621, in _compile_ql_query
          ir = qlcompiler.compile_ast_to_ir(
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0/lib/python3.10/site-packages/edb/edgeql/compiler/__init__.py", line 179, in wrapper
          return func(*args, **kwargs)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0/lib/python3.10/site-packages/edb/edgeql/compiler/__init__.py", line 237, in compile_ast_to_ir
          ir_set = dispatch_mod.compile(tree, ctx=ctx)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0/lib/python3.10/site-packages/edb/edgeql/compiler/stmt.py", line 507, in compile_InsertQuery
          stmt.on_conflict = conflicts.compile_insert_unless_conflict(
        File "/Users/colinmcd94/Library/Application Support/edgedb/portable/2.0/lib/python3.10/site-packages/edb/edgeql/compiler/conflicts.py", line 430, in compile_insert_unless_conflict
          assert not _has_explicit_id_write(stmt)
      AssertionError
```

**Comment by msullivan** [comment]
Sort of baffled why I had an assert in there instead of just supporting it in the first place?
