### ISSUE TITLE
ISE creating role with empty password

### ISSUE THREAD

**Issue by fantix** [edgedb/edgedb#4209]
```
EdgeDB 2.0-rc.3+f035802 (repl 2.1.0)
Type \help for help, \quit to quit.
edgedb> create superuser role xxx {
.......     set password := ()
....... };
edgedb error: InternalServerError: string index out of range
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "edb/server/compiler_pool/worker_proc.py", line 55, in worker
          res = meth(*args)
        File "edb/server/compiler_pool/worker.py", line 160, in compile
          units, cstate = COMPILER.compile(
        File "edb/server/compiler/compiler.py", line 2171, in compile
          unit_group = self._compile(ctx=ctx, source=source)
        File "edb/server/compiler/compiler.py", line 1717, in _compile
          return self._try_compile(ctx=ctx, source=source)
        File "edb/server/compiler/compiler.py", line 1774, in _try_compile
          comp, capabilities = self._compile_dispatch_ql(
        File "edb/server/compiler/compiler.py", line 1662, in _compile_dispatch_ql
          self._compile_and_apply_ddl_stmt(ctx, ql, source=source),
        File "edb/server/compiler/compiler.py", line 849, in _compile_and_apply_ddl_stmt
          delta = s_ddl.delta_from_ddl(
        File "edb/schema/ddl.py", line 588, in delta_from_ddl
          _, cmd = _delta_from_ddl(
        File "edb/schema/ddl.py", line 628, in _delta_from_ddl
          cmd = cmd_from_ddl(
        File "edb/schema/ddl.py", line 456, in cmd_from_ddl
          res = sd.compile_ddl(schema, ddl, context=context)
        File "edb/schema/delta.py", line 4237, in compile_ddl
          cmd = cmdcls._cmd_tree_from_ast(schema, astnode, context)
        File "edb/schema/roles.py", line 162, in _cmd_tree_from_ast
          cls._process_role_body(cmd, schema, astnode, context)
        File "edb/schema/roles.py", line 96, in _process_role_body
          salted_password = scram.build_verifier(password)
        File "edgedb/scram/__init__.py", line 55, in build_verifier
          password = saslprep(password).encode('utf-8')
        File "edgedb/scram/saslprep.py", line 61, in saslprep
          if in_table_d1(data[0]):
      IndexError: string index out of range
```

**Comment by fantix** [comment]
Hmm I should use `{}` instead of `()`, but still the error is weird.
