### ISSUE TITLE
InternalServerError while reading the Easy EdgeDB book

### ISSUE THREAD

**Issue by BeanieBarrow** [edgedb/edgedb#4303]
- EdgeDB Version: 2.1
- OS Version: Pop!_OS 22.04 LTS

Steps to Reproduce: 

1. Follow the Easy EdgeDB book and reach Chapter 10
2. Do the things it says until [Working with tuples and arrays](https://www.edgedb.com/easy-edgedb/chapter10#working-with-tuples-and-arrays)
3. Before reading further, try the command `edgedb migration create`

Schema:
```
edgedb error: InternalServerError:
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "/home/user/.local/share/edgedb/portable/2.1/lib/python3.10/site-packages/edb/server/compiler_pool/worker_proc.py", line 55, in worker
          res = meth(*args)
        File "/home/user/.local/share/edgedb/portable/2.1/lib/python3.10/site-packages/edb/server/compiler_pool/worker.py", line 160, in compile
          units, cstate = COMPILER.compile(
        File "/home/user/.local/share/edgedb/portable/2.1/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 2207, in compile
          unit_group = self._compile(ctx=ctx, source=source)
        File "/home/user/.local/share/edgedb/portable/2.1/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 1738, in _compile
          return self._try_compile(ctx=ctx, source=source)
        File "/home/user/.local/share/edgedb/portable/2.1/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 1802, in _try_compile
          comp, capabilities = self._compile_dispatch_ql(
        File "/home/user/.local/share/edgedb/portable/2.1/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 1668, in _compile_dispatch_ql
          query = self._compile_ql_migration(
        File "/home/user/.local/share/edgedb/portable/2.1/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 1049, in _compile_ql_migration
          target_schema = s_ddl.apply_sdl(
        File "/home/user/.local/share/edgedb/portable/2.1/lib/python3.10/site-packages/edb/schema/ddl.py", line 499, in apply_sdl
          cmd = cmd_from_ddl(
        File "/home/user/.local/share/edgedb/portable/2.1/lib/python3.10/site-packages/edb/schema/ddl.py", line 456, in cmd_from_ddl
          res = sd.compile_ddl(schema, ddl, context=context)
        File "/home/user/.local/share/edgedb/portable/2.1/lib/python3.10/site-packages/edb/schema/delta.py", line 4237, in compile_ddl
          cmd = cmdcls._cmd_tree_from_ast(schema, astnode, context)
        File "/home/user/.local/share/edgedb/portable/2.1/lib/python3.10/site-packages/edb/schema/inheriting.py", line 960, in _cmd_tree_from_ast
          cmd = super()._cmd_tree_from_ast(schema, astnode, context)
        File "/home/user/.local/share/edgedb/portable/2.1/lib/python3.10/site-packages/edb/schema/delta.py", line 3405, in _cmd_tree_from_ast
          cmd = super()._cmd_tree_from_ast(schema, astnode, context)
        File "/home/user/.local/share/edgedb/portable/2.1/lib/python3.10/site-packages/edb/schema/delta.py", line 1057, in _cmd_tree_from_ast
          subcmd = compile_ddl(schema, subastnode, context=context)
        File "/home/user/.local/share/edgedb/portable/2.1/lib/python3.10/site-packages/edb/schema/delta.py", line 4237, in compile_ddl
          cmd = cmdcls._cmd_tree_from_ast(schema, astnode, context)
        File "/home/user/.local/share/edgedb/portable/2.1/lib/python3.10/site-packages/edb/schema/properties.py", line 294, in _cmd_tree_from_ast
          cmd._process_create_or_alter_ast(schema, astnode, context)
        File "/home/user/.local/share/edgedb/portable/2.1/lib/python3.10/site-packages/edb/schema/pointers.py", line 1770, in _process_create_or_alter_ast
          assert astnode.target is not None
      AssertionError
```

**Comment by Dhghomon** [comment]
So looks like the book at this point after the big expansion, no longer generates the error which is nice, but the error in the schema above is still happening. Taking it apart bit by bit it turns out to be a pretty simple culprit: declaring `overloaded` for a property that doesn't exist. Doesn't even need to be extending another type to make it happen either, this schema will do it:

```
module default {
  type NPC {
    overloaded property age;
  }
}
```

The error generated should be something nicer like "no property `age` found to overload".
