### ISSUE TITLE
Query Builder generation fails if `edgedb` database doesn't exist

### ISSUE THREAD

**Issue by NetOpWibby** [edgedb/edgedb#4402]
- EdgeDB Version: EdgeDB CLI 2.0.5+53f9c9b
- OS Version: macOS Ventura (13.0 Beta (22A5342f))

```sh
# documentation should mention that these flags are required
deno run --allow-env --allow-net --allow-read --unstable https://deno.land/x/edgedb/generate.ts

# or just use
deno run -A --unstable https://deno.land/x/edgedb/generate.ts
```

```
# CLI output
Generating query builder...
Detected deno.json, generating TypeScript files with Deno-style imports.
   To override this, use the --target flag.
   Run `npx edgeql-js --help` for full options.
Introspecting database schema...
Unexpected connection error: UnknownDatabaseError: database 'edgedb' does not exist
    at RawConnection._parseErrorMessage (https://deno.land/x/edgedb@v0.22.7/_src/baseConn.ts:281:17)
    at RawConnection.connect (https://deno.land/x/edgedb@v0.22.7/_src/rawConn.ts:389:22)
    at async Function.connectWithTimeout (https://deno.land/x/edgedb@v0.22.7/_src/rawConn.ts:238:7)
    at async retryingConnect (https://deno.land/x/edgedb@v0.22.7/_src/retry.ts:38:14)
    at async ClientPool.getNewConnection (https://deno.land/x/edgedb@v0.22.7/_src/client.ts:375:24)
    at async ClientConnectionHolder._getConnection (https://deno.land/x/edgedb@v0.22.7/_src/client.ts:62:26)
    at async ClientConnectionHolder.retryingFetch (https://deno.land/x/edgedb@v0.22.7/_src/client.ts:175:20)
    at async Client.queryRequiredSingle (https://deno.land/x/edgedb@v0.22.7/_src/client.ts:628:14)
    at async generateQB (https://deno.land/x/edgedb@v0.22.7/_src/reflection/generate.ts:77:21)
    at async run (https://deno.land/x/edgedb@v0.22.7/_src/reflection/cli.ts:332:3)
error: Uncaught (in promise) UnknownDatabaseError: database 'edgedb' does not exist
    const err = new errorType(message);
                ^
    at RawConnection._parseErrorMessage (https://deno.land/x/edgedb@v0.22.7/_src/baseConn.ts:281:17)
    at RawConnection.connect (https://deno.land/x/edgedb@v0.22.7/_src/rawConn.ts:389:22)
    at async Function.connectWithTimeout (https://deno.land/x/edgedb@v0.22.7/_src/rawConn.ts:238:7)
    at async retryingConnect (https://deno.land/x/edgedb@v0.22.7/_src/retry.ts:38:14)
    at async ClientPool.getNewConnection (https://deno.land/x/edgedb@v0.22.7/_src/client.ts:375:24)
    at async ClientConnectionHolder._getConnection (https://deno.land/x/edgedb@v0.22.7/_src/client.ts:62:26)
    at async ClientConnectionHolder.retryingFetch (https://deno.land/x/edgedb@v0.22.7/_src/client.ts:175:20)
    at async Client.queryRequiredSingle (https://deno.land/x/edgedb@v0.22.7/_src/client.ts:628:14)
    at async generateQB (https://deno.land/x/edgedb@v0.22.7/_src/reflection/generate.ts:77:21)
    at async run (https://deno.land/x/edgedb@v0.22.7/_src/reflection/cli.ts:332:3)
```

I have an `.env` file with `EDGEDB_DATABASE`, `EDGEDB_INSTANCE`, and `EDGEDB_PORT` populated but it doesn't seem like this script checks the existence of them.

**Comment by NetOpWibby** [comment]
Ah, I had to pass specific EdgeDB options like I would the CLI. This worked:

```sh
deno run -A --unstable https://deno.land/x/edgedb/generate.ts --instance <instance-name> --database <database-name>
```

Yah, this should be in the docs too.
