### ISSUE TITLE
Cannot link the edgedb instance to fly.io

### ISSUE THREAD

**Issue by ricogallo** [edgedb/edgedb#4409]
- EdgeDB Version: 2.2
- OS Version: macOS 12.6 (21G115)

Steps to Reproduce:

1. I ran
```bash
edgedb instance link \
  --trust-tls-cert \
  --dsn $DSN \
  --non-interactive \
  fly
```
and got

```bash
Authenticating to edgedb://edgedb@<my_app_name>.internal:8080/edgedb
Trusting unknown server certificate: SHA1:599f02bab402dcc74606c0d83e0f557382ae9951
edgedb error: InternalServerError:
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "edb/server/pgcon/pgcon.pyx", line 2149, in wait_for_message
      ConnectionAbortedError

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "edb/server/protocol/binary.pyx", line 1306, in edb.server.protocol.binary.EdgeConnection.main
        File "edb/server/protocol/binary.pyx", line 476, in auth
        File "edb/server/protocol/binary.pyx", line 588, in _start_connection
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-2/lib/python3.10/site-packages/edb/server/server.py", line 536, in new_dbview
          await db.introspection()
        File "edb/server/dbview/dbview.pyx", line 258, in introspection
        File "edb/server/dbview/dbview.pyx", line 260, in edb.server.dbview.dbview.Database.introspection
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-2/lib/python3.10/site-packages/edb/server/server.py", line 709, in introspect_db
          user_schema = await self.introspect_user_schema(conn)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-2/lib/python3.10/site-packages/edb/server/server.py", line 655, in introspect_user_schema
          json_data = await conn.sql_fetch_val(self._local_intro_query)
        File "edb/server/pgcon/pgcon.pyx", line 1152, in sql_fetch_val
        File "edb/server/pgcon/pgcon.pyx", line 1137, in sql_fetch
        File "edb/server/pgcon/pgcon.pyx", line 1076, in parse_execute
        File "edb/server/pgcon/pgcon.pyx", line 1059, in _parse_execute
        File "edb/server/pgcon/pgcon.pyx", line 586, in wait_for_sync
        File "edb/server/pgcon/pgcon.pyx", line 2147, in wait_for_message
      ConnectionAbortedError
```

Please note that while the $DNS variable is correctly set up, it doesn't show that here `Authenticating to edgedb://edgedb@<my_app_name>.internal:8080/edgedb`, but I guess it's intentional.

Schema:

**Comment by elprans** [comment]
Make sure your instances are appropriately sized as per the deploy guide (at least `shared-cpu-1x`)

**Comment by ricogallo** [comment]
You are right! 🤗 Closing this issue
