### ISSUE TITLE
InternalServerError: Can't compile ref to visible binding ns~2@ns~6@@(__derived__::g~1)

### ISSUE THREAD

**Issue by halindraprakoso** [edgedb/edgedb#4481]
**Code**
The code causing the error. Specifically on the second sum when doing select

```typescript
const grouped = e.group(e.Bill, (b) => ({
    by: {
      category: b.PaymentType.PaymentCategory.name,
    },
  }));

  const select = await e
    .select(grouped, (g) => ({
      sum: e.op(
        e.sum(g.elements.amount),
        "-",
        e.sum(
          e.select(g.elements["<Bill[is AssignedPayment]"], (ap) => ({
            filter: e.op("exists", ap.Checker),
          })).amount
        )
      ),
    })).run(client)
```

**Schema**

Your application schema. 

```
module default {

   type Bill {
        required property updated_at -> datetime {default := std::datetime_current()}
        required property amount -> int64;
        required link PaymentType -> PaymentType;
    }

 type AssignedPayment {
        required property created_at -> datetime {default := std::datetime_current()}
        required property amount -> int64;
        required link Bill -> Bill;
        link Checker -> User;
    }

}
```

**Generated EdgeQL**

```js
WITH
  __scope_0_stdFreeObject := (
    WITH
      __scope_2_defaultBill := DETACHED default::Bill,
      __scope_2_defaultBill_groups := (
        GROUP __scope_2_defaultBill
        USING
          category := __scope_2_defaultBill.PaymentType.PaymentCategory.name
        BY category
    )
    SELECT __scope_2_defaultBill_groups {
      key: {category},
      grouping,
      elements: {
        id
      }
    }
  )
SELECT __scope_0_stdFreeObject {
  single sum := (
    std::sum(__scope_0_stdFreeObject.elements.amount) - std::sum((WITH
      __scope_1_defaultAssignedPayment := __scope_0_stdFreeObject.elements.<Bill[is AssignedPayment]
    SELECT __scope_1_defaultAssignedPayment {
      id
    }
    FILTER (exists __scope_1_defaultAssignedPayment.Checker)).amount)
  )
}
```

**Error or desired behavior**

```
InternalServerError: Can't compile ref to visible binding ns~1@ns~5@@(__derived__::g~1)
    at RawConnection._parseErrorMessage (/Users/halindra/Documents/Projects/myProject/node_modules/.pnpm/edgedb@0.22.8/node_modules/edgedb/dist/baseConn.js:317:21)
    at RawConnection._executeFlow (/Users/halindra/Documents/Projects/myProject/node_modules/.pnpm/edgedb@0.22.8/node_modules/edgedb/dist/baseConn.js:925:34)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at RawConnection.fetch (/Users/halindra/Documents/Projects/myProject/node_modules/.pnpm/edgedb@0.22.8/node_modules/edgedb/dist/baseConn.js:976:17)
    at ClientConnectionHolder.retryingFetch (/Users/halindra/Documents/Projects/myProject/node_modules/.pnpm/edgedb@0.22.8/node_modules/edgedb/dist/client.js:183:26)
    at Client.query (/Users/halindra/Documents/Projects/myProject/node_modules/.pnpm/edgedb@0.22.8/node_modules/edgedb/dist/client.js:485:20)
    at loader11 (/Users/halindra/Documents/Projects/myProject/app/services/academicYearId.server.ts:22:11)
    at Object.callRouteLoader (/Users/halindra/Documents/Projects/myProject/node_modules/.pnpm/@remix-run+server-runtime@1.7.2_biqbaboplfbrettd7655fr4n2y/node_modules/@remix-run/server-runtime/dist/data.js:77:14)
    at handleResourceRequest (/Users/halindra/Documents/Projects/myProject/node_modules/.pnpm/@remix-run+server-runtime@1.7.2_biqbaboplfbrettd7655fr4n2y/node_modules/@remix-run/server-runtime/dist/server.js:448:14)
    at requestHandler (/Users/halindra/Documents/Projects/myProject/node_modules/.pnpm/@remix-run+server-runtime@1.7.2_biqbaboplfbrettd7655fr4n2y/node_modules/@remix-run/server-runtime/dist/server.js:42:18) {
  source: undefined
}
```

**Versions (please complete the following information):**
 - OS: macOS Monterey
 - EdgeDB version: 2.1
 - `edgedb-js` version: `0.22.8`

**Comment by msullivan** [comment]
I was able to reproduce this using this finished schema:
```
type PaymentCategory {                                                                                                                                                                                                                                                                                                        
  required property name -> str;                                                                                                                                                                                                                                                                                              
}                                                                                                                                                                                                                                                                                                                             
type PaymentType {                                                                                                                                                                                                                                                                                                            
  required link PaymentCategory -> PaymentCategory;                                                                                                                                                                                                                                                                           
}                                                                                                                                                                                                                                                                                                                             
type User;                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                              
   type Bill {                                                                                                                                                                                                                                                                                                                
        required property updated_at -> datetime {default := std::datetime_current()}                                                                                                                                                                                                                                         
        required property amount -> int64;                                                                                                                                                                                                                                                                                    
        required link PaymentType -> PaymentType;                                                                                                                                                                                                                                                                             
    }                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                              
 type AssignedPayment {                                                                                                                                                                                                                                                                                                       
        required property created_at -> datetime {default := std::datetime_current()}                                                                                                                                                                                                                                         
        required property amount -> int64;                                                                                                                                                                                                                                                                                    
        required link Bill -> Bill;                                                                                                                                                                                                                                                                                           
        link Checker -> User;                                                                                                                                                                                                                                                                                                 
    }                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                              
}
```
