### ISSUE TITLE
Error traversing Access Policy'd link

### ISSUE THREAD

**Issue by jackfischer** [edgedb/edgedb#4560]
- EdgeDB Version: `2.4+9f3da78` (also affects nightly `3.0-dev.6990+794090f`)
- OS Version: macOS 12.6

Steps to Reproduce:

1. Create two linked object types, link destination object with Access Policies in terms of itself and link source object with Access Policies in terms of destination object
2. Query from source object to destination object

```
$ edgedb
EdgeDB 2.4+9f3da78 (repl 2.0.5+53f9c9b)
Type \help for help, \quit to quit.
edgedb> select DocumentVersion {};
{}
edgedb> select DocumentVersion {id, parentDocument};
edgedb error: InternalServerError: None
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "/Users/jack/Library/Application Support/edgedb/portable/2.4/lib/python3.10/site-packages/edb/pgsql/compiler/__init__.py", line 120, in compile_ir_to_sql_tree
          qtree = dispatch.compile(ir_expr, ctx=ctx)
        File "/Users/jack/Library/Application Support/edgedb/portable/2.4/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/jack/Library/Application Support/edgedb/portable/2.4/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 60, in compile_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/Users/jack/Library/Application Support/edgedb/portable/2.4/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 114, in _compile_set_impl
          _compile_set(ir_set, ctx=ctx)
  ...
```

Schema:

```
module default {
    global current_user -> uuid;

    type Document {
        required link author -> User;
        access policy author_has_full_access
            allow all
            using (global current_user ?= .author.id);
    }

    type User {}

    type DocumentVersion {
        required link parentDocument -> Document;
        access policy author_has_full_access
            allow all
            using (global current_user ?= .parentDocument.author.id);
    }

}
```

**Comment by msullivan** [comment]
Fixed yesterday in #4555, it seems!
