### ISSUE TITLE
edgedb error: InternalServerError: None

### ISSUE THREAD

**Issue by quinchs** [edgedb/edgedb#4577]
Instance version: 2.4+23aa420
CLI version: EdgeDB CLI 2.0.5+da7c868

Running the following query:

```
with EEFDMNGEOJHQ := (
  insert Person { name := <str>$JUOINWQCNSEY, email := <str>$IIRMTAUFXGSH,} 
  unless conflict on .email else (
    select Person
  )
) 
insert Person { name := <str>$YBOAISGNETAX, email := <str>$VKGJTAQCSKAT, best_friend := EEFDMNGEOJHQ} 
unless conflict on .email else (
  update Person set { name := <str>$TCIBXBHFSPMC, email := <str>$DKZXRGAVAAVV, best_friend := EEFDMNGEOJHQ }
);
```

With the following schema:

```
  type Person {
    required property name -> str;
    required property email -> str {
      constraint exclusive;
    }
    link best_friend -> Person;
    multi link friends -> Person;
  }
```

Traceback:
```
edgedb error: InternalServerError: None
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "/home/edgedb/.local/share/edgedb/portable/2.4/lib/python3.10/site-packages/edb/pgsql/compiler/__init__.py", line 120, in compile_ir_to_sql_tree
          qtree = dispatch.compile(ir_expr, ctx=ctx)
        File "/home/edgedb/.local/share/edgedb/portable/2.4/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/home/edgedb/.local/share/edgedb/portable/2.4/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 60, in compile_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/home/edgedb/.local/share/edgedb/portable/2.4/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 114, in _compile_set_impl
          _compile_set(ir_set, ctx=ctx)
        File "/home/edgedb/.local/share/edgedb/portable/2.4/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 677, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/home/edgedb/.local/share/edgedb/portable/2.4/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 160, in get_set_rvar
          return _process_toplevel_query(ir_set, ctx=ctx)
        File "/home/edgedb/.local/share/edgedb/portable/2.4/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 263, in _process_toplevel_query
          rvars = _get_set_rvar(ir_set, ctx=ctx)
        File "/home/edgedb/.local/share/edgedb/portable/2.4/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 302, in _get_set_rvar
          rvars = process_set_as_subquery(ir_set, stmt, ctx=ctx)
        File "/home/edgedb/.local/share/edgedb/portable/2.4/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 1384, in process_set_as_subquery
          dispatch.visit(expr, ctx=newctx)
        File "/home/edgedb/.local/share/edgedb/portable/2.4/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/home/edgedb/.local/share/edgedb/portable/2.4/lib/python3.10/site-packages/edb/pgsql/compiler/dispatch.py", line 44, in visit
          compile(ir, ctx=ctx)
        File "/home/edgedb/.local/share/edgedb/portable/2.4/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/home/edgedb/.local/share/edgedb/portable/2.4/lib/python3.10/site-packages/edb/pgsql/compiler/stmt.py", line 165, in compile_InsertStmt
          dml.process_insert_body(
        File "/home/edgedb/.local/share/edgedb/portable/2.4/lib/python3.10/site-packages/edb/pgsql/compiler/dml.py", line 674, in process_insert_body
          rel = compile_insert_shape_element(
        File "/home/edgedb/.local/share/edgedb/portable/2.4/lib/python3.10/site-packages/edb/pgsql/compiler/dml.py", line 1207, in compile_insert_shape_element
          dispatch.visit(shape_el, ctx=insvalctx)
        File "/home/edgedb/.local/share/edgedb/portable/2.4/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/home/edgedb/.local/share/edgedb/portable/2.4/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 85, in visit_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/home/edgedb/.local/share/edgedb/portable/2.4/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 110, in _compile_set_impl
          _compile_set(ir_set, ctx=scopectx)
        File "/home/edgedb/.local/share/edgedb/portable/2.4/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 677, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/home/edgedb/.local/share/edgedb/portable/2.4/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 207, in get_set_rvar
          rvars = _get_set_rvar(ir_set, ctx=subctx)
        File "/home/edgedb/.local/share/edgedb/portable/2.4/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 302, in _get_set_rvar
        File "/home/edgedb/.local/share/edgedb/portable/2.4/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 1384, in process_set_as_subquery
          dispatch.visit(expr, ctx=newctx)
        File "/home/edgedb/.local/share/edgedb/portable/2.4/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/home/edgedb/.local/share/edgedb/portable/2.4/lib/python3.10/site-packages/edb/pgsql/compiler/dispatch.py", line 44, in visit
          compile(ir, ctx=ctx)
        File "/home/edgedb/.local/share/edgedb/portable/2.4/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/home/edgedb/.local/share/edgedb/portable/2.4/lib/python3.10/site-packages/edb/pgsql/compiler/stmt.py", line 97, in compile_SelectStmt
          outvar = clauses.compile_output(stmt.result, ctx=ictx)
        File "/home/edgedb/.local/share/edgedb/portable/2.4/lib/python3.10/site-packages/edb/pgsql/compiler/clauses.py", line 212, in compile_output
          dispatch.visit(ir_set, ctx=newctx)
        File "/home/edgedb/.local/share/edgedb/portable/2.4/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/home/edgedb/.local/share/edgedb/portable/2.4/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 85, in visit_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/home/edgedb/.local/share/edgedb/portable/2.4/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 110, in _compile_set_impl
          _compile_set(ir_set, ctx=scopectx)
        File "/home/edgedb/.local/share/edgedb/portable/2.4/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 677, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/home/edgedb/.local/share/edgedb/portable/2.4/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 207, in get_set_rvar
          rvars = _get_set_rvar(ir_set, ctx=subctx)
        File "/home/edgedb/.local/share/edgedb/portable/2.4/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 302, in _get_set_rvar
          rvars = process_set_as_subquery(ir_set, stmt, ctx=ctx)
        File "/home/edgedb/.local/share/edgedb/portable/2.4/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 1382, in process_set_as_subquery
          dml.wrap_dml_cte(expr, dml_cte, ctx=subrelctx)
        File "/home/edgedb/.local/share/edgedb/portable/2.4/lib/python3.10/site-packages/edb/pgsql/compiler/dml.py", line 331, in wrap_dml_cte
          relctx.include_rvar(wrapper, dml_rvar, ir_stmt.subject.path_id, ctx=ctx)
        File "/home/edgedb/.local/share/edgedb/portable/2.4/lib/python3.10/site-packages/edb/pgsql/compiler/relctx.py", line 221, in include_rvar
          return include_specific_rvar(
        File "/home/edgedb/.local/share/edgedb/portable/2.4/lib/python3.10/site-packages/edb/pgsql/compiler/relctx.py", line 267, in include_specific_rvar
          rel_join(stmt, rvar, ctx=ctx)
        File "/home/edgedb/.local/share/edgedb/portable/2.4/lib/python3.10/site-packages/edb/pgsql/compiler/relctx.py", line 1252, in rel_join
          _plain_join(query, right_rvar, ctx=ctx)
        File "/home/edgedb/.local/share/edgedb/portable/2.4/lib/python3.10/site-packages/edb/pgsql/compiler/relctx.py", line 1264, in _plain_join
          lref = maybe_get_path_var(query, path_id, aspect='identity', ctx=ctx)
        File "/home/edgedb/.local/share/edgedb/portable/2.4/lib/python3.10/site-packages/edb/pgsql/compiler/relctx.py", line 397, in maybe_get_path_var
          return pathctx.get_rvar_path_var(
        File "/home/edgedb/.local/share/edgedb/portable/2.4/lib/python3.10/site-packages/edb/pgsql/compiler/pathctx.py", line 716, in get_rvar_path_var
          if (path_id, aspect) in (outs := rvar.query.get_path_outputs(flavor)):
        File "/home/edgedb/.local/share/edgedb/portable/2.4/lib/python3.10/site-packages/edb/pgsql/ast.py", line 245, in query
          raise NotImplementedError
      NotImplementedError

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "/home/edgedb/.local/share/edgedb/portable/2.4/lib/python3.10/site-packages/edb/server/compiler_pool/worker_proc.py", line 55, in worker
          res = meth(*args)
        File "/home/edgedb/.local/share/edgedb/portable/2.4/lib/python3.10/site-packages/edb/server/compiler_pool/worker.py", line 160, in compile
          units, cstate = COMPILER.compile(
        File "/home/edgedb/.local/share/edgedb/portable/2.4/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 2249, in compile
          unit_group = self._compile(ctx=ctx, source=source)
        File "/home/edgedb/.local/share/edgedb/portable/2.4/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 1770, in _compile
          return self._try_compile(ctx=ctx, source=source)
        File "/home/edgedb/.local/share/edgedb/portable/2.4/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 1834, in _try_compile
          comp, capabilities = self._compile_dispatch_ql(
        File "/home/edgedb/.local/share/edgedb/portable/2.4/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 1744, in _compile_dispatch_ql
          query = self._compile_ql_query(ctx, ql, script_info=script_info)
        File "/home/edgedb/.local/share/edgedb/portable/2.4/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 643, in _compile_ql_query
          sql_text, argmap = pg_compiler.compile_ir_to_sql(
        File "/home/edgedb/.local/share/edgedb/portable/2.4/lib/python3.10/site-packages/edb/pgsql/compiler/__init__.py", line 152, in compile_ir_to_sql
          qtree = compile_ir_to_sql_tree(
        File "/home/edgedb/.local/share/edgedb/portable/2.4/lib/python3.10/site-packages/edb/pgsql/compiler/__init__.py", line 135, in compile_ir_to_sql_tree
          raise errors.InternalServerError(*args) from e
      edb.errors.InternalServerError: None
```

**Comment by quinchs** [comment]
cc @msullivan
