### ISSUE TITLE
"InternalServerError: None" on inserting nested ACL'd objects

### ISSUE THREAD

**Issue by jackfischer** [edgedb/edgedb#4710]
- EdgeDB Version: 2.7+a86e274
- EdgeDB CLI Version: 2.2.6+7eabbf9
- OS Version: macOS 13.0.1

Steps to Reproduce:

```
EdgeDB 2.7+a86e274 (repl 2.2.6+7eabbf9)
Type \help for help, \quit to quit.
edgedb> insert User {};
{default::User {id: d3e9cc88-6b79-11ed-b883-0f574b4a0f74}}
edgedb> insert Document { author := ( select User filter .id = <uuid>"d3e9cc88-6b79-11ed-b883-0f574b4a0f74" ) };
{default::Document {id: 05b9b5ac-6b7a-11ed-b883-c3d78efc2603}}
edgedb> insert DocumentVersion { parentDocument := (select Document filter .id = <uuid>"05b9b5ac-6b7a-11ed-b883-c3d78efc2603" ) };
edgedb error: InternalServerError: None
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "/Users/jack/Library/Application Support/edgedb/portable/2.7/lib/python3.10/site-packages/edb/pgsql/compiler/__init__.py", line 120, in compile_ir_to_sql_tree
          qtree = dispatch.compile(ir_expr, ctx=ctx)
        File "/Users/jack/Library/Application Support/edgedb/portable/2.7/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/jack/Library/Application Support/edgedb/portable/2.7/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 60, in compile_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/Users/jack/Library/Application Support/edgedb/portable/2.7/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 114, in _compile_set_impl
...
```

Schema:

```
using future nonrecursive_access_policies;
module default {
    global current_user -> uuid;

    type Document {
        required link author -> User;
        multi link viewers -> User;
        multi link editors -> User;
        multi link owners -> User;
        multi link relevantUsers := distinct (
            .owners union .editors union .viewers union .author
        );

        access policy full_access
            allow all
            using (((global current_user) in { .author.id, .owners.id, .editors.id }) ?? false);

        access policy viewer_select
            allow select
            using ((global current_user in .viewers.id) ?? false);

        access policy allow_insert
            allow insert
            using (true);
    }

    type DocumentVersion {
        required link parentDocument -> Document;

        access policy full_access
            allow all
            using (((global current_user) in .parentDocument {
                 editable := {.author.id, .owners.id, .editors.id }
            }.editable) ?? false);

        access policy allow_select_for_viewer
            allow select
            using ((global current_user in .parentDocument.viewers.id) ?? false);

        access policy allow_insert
            allow insert
            using (true);
    }

    type User {
    }
}
```

**Comment by Sikarii** [comment]
Could you try this with the [nonrecursive access policies] future(https://www.edgedb.com/docs/datamodel/access_policies#ref-datamodel-access-policies-nonrecursive)?

**Comment by msullivan** [comment]
To add to the fun, this works on nightly but is broken in 2.7. 

My guess is that something about #4529 fixed this by accident. I'll need to dig a little.

**Comment by msullivan** [comment]
Oh, no, it's sillier than that: #4589 fixes this exact bug but it didn't make it into the 2.x branch. (Probably because it doesn't apply cleanly and needs to be half rewritten to backport.)

**Comment by jackfischer** [comment]
Fantastic news. Thank you
