### ISSUE TITLE
Error when trying to set a global variable using a query parameter

### ISSUE THREAD

**Issue by Marnixvdb** [edgedb/edgedb#4934]
- EdgeDB Version: 2.9+4fbadd2
- EdgeDB CLI Version: EdgeDB CLI 2.2.6+7eabbf9
- OS Version: MacOS Monterey 12.5.1

The docs are ambiguous about it, but if this is not a bug, you may read it as a feature request: it should be possible to set a global variable using a query parameter. Right now it isn't, as it causes EdgeDB to throw an error. 

Steps to Reproduce:

1. With a global variable defined in the schema, try to set it in the shell using a query parameter. Assuming dynamic 

```
create global my_var -> str;
set global my_var := <str>$my_param;
```
results in:

```shell
edgedb> create global my_var -> str;
....... set global my_var := <str>$my_param;
OK: CREATE GLOBAL
edgedb error: InternalServerError: my_param
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "/Users/********/Library/Application Support/edgedb/portable/2.9/lib/python3.10/site-packages/edb/pgsql/compiler/__init__.py", line 120, in compile_ir_to_sql_tree
          qtree = dispatch.compile(ir_expr, ctx=ctx)
        File "/Users/********/Library/Application Support/edgedb/portable/2.9/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/********/Library/Application Support/edgedb/portable/2.9/lib/python3.10/site-packages/edb/pgsql/compiler/config.py", line 47, in compile_ConfigSet
          val = _compile_config_value(op, ctx=ctx)
        File "/Users/********/Library/Application Support/edgedb/portable/2.9/lib/python3.10/site-packages/edb/pgsql/compiler/config.py", line 505, in _compile_config_value
          val = dispatch.compile(expr, ctx=subctx)
        File "/Users/********/Library/Application Support/edgedb/portable/2.9/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/********/Library/Application Support/edgedb/portable/2.9/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 60, in compile_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/Users/********/Library/Application Support/edgedb/portable/2.9/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 114, in _compile_set_impl
          _compile_set(ir_set, ctx=ctx)
        File "/Users/********/Library/Application Support/edgedb/portable/2.9/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 677, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/Users/********/Library/Application Support/edgedb/portable/2.9/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 162, in get_set_rvar
          return _process_toplevel_query(ir_set, ctx=ctx)
        File "/Users/********/Library/Application Support/edgedb/portable/2.9/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 265, in _process_toplevel_query
          rvars = _get_set_rvar(ir_set, ctx=ctx)
        File "/Users/********/Library/Application Support/edgedb/portable/2.9/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 418, in _get_set_rvar
          rvars = process_set_as_expr(ir_set, stmt, ctx=ctx)
        File "/Users/********/Library/Application Support/edgedb/portable/2.9/lib/python3.10/site-packages/edb/pgsql/compiler/relgen.py", line 2175, in process_set_as_expr
          set_expr = dispatch.compile(ir_set.expr, ctx=newctx)
        File "/Users/********/Library/Application Support/edgedb/portable/2.9/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/Users/********/Library/Application Support/edgedb/portable/2.9/lib/python3.10/site-packages/edb/pgsql/compiler/expr.py", line 131, in compile_Parameter
          index = ctx.argmap[expr.name].index
      KeyError: 'my_param'
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "/Users/********/Library/Application Support/edgedb/portable/2.9/lib/python3.10/site-packages/edb/server/compiler_pool/worker_proc.py", line 55, in worker
          res = meth(*args)
        File "/Users/********/Library/Application Support/edgedb/portable/2.9/lib/python3.10/site-packages/edb/server/compiler_pool/worker.py", line 160, in compile
          units, cstate = COMPILER.compile(
        File "/Users/********/Library/Application Support/edgedb/portable/2.9/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 2277, in compile
          unit_group = self._compile(ctx=ctx, source=source)
        File "/Users/********/Library/Application Support/edgedb/portable/2.9/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 1807, in _compile
          return self._try_compile(ctx=ctx, source=source)
        File "/Users/********/Library/Application Support/edgedb/portable/2.9/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 1871, in _try_compile
          comp, capabilities = self._compile_dispatch_ql(
        File "/Users/********/Library/Application Support/edgedb/portable/2.9/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 1776, in _compile_dispatch_ql
          self._compile_ql_config_op(ctx, ql),
        File "/Users/********/Library/Application Support/edgedb/portable/2.9/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 1668, in _compile_ql_config_op
          sql_text, _ = pg_compiler.compile_ir_to_sql(
        File "/Users/********/Library/Application Support/edgedb/portable/2.9/lib/python3.10/site-packages/edb/pgsql/compiler/__init__.py", line 152, in compile_ir_to_sql
          qtree = compile_ir_to_sql_tree(
        File "/Users/********/Library/Application Support/edgedb/portable/2.9/lib/python3.10/site-packages/edb/pgsql/compiler/__init__.py", line 135, in compile_ir_to_sql_tree
          raise errors.InternalServerError(*args) from e
      edb.errors.InternalServerError: my_param
edgedb> 

  ```

**Comment by msullivan** [comment]
I don't *really* think it's a bug (it was intentionally not implemented), but it should definitely produce a real error message and not an InternalServerError. (And I feel like I do remember writing an error message for this, but if I did I guess I didn't write a test!)

What is your use-case for wanting to use a parameter for `SET GLOBAL`? It doesn't seem like it is any easier at the CLI to enter it as an argument, and in language bindings you would use an API instead of running `SET GLOBAL` explicitly.

(I left it unsupported because it was work that didn't seem like it would ever be useful to anybody, but if there's something compelling that I'm missing, it is doable.)

**Comment by Marnixvdb** [comment]
Not sure it's compelling, but the reason is that I'm writing parameterised seed files to insert the first user and access roles in our database, that need to be populated with user-provided secrets at runtime. After the first user is created, a global variable that includes some of the output of first inserts, must to be set for the user to be allowed subsequent actions. Otherwise our access policies will deny all subsequent actions. This means it's unavoidable to populate the global variable with query output that includes global variables. 

Eventually we'll set this initialisation up from the client app, but since the application developers can't really do anything with their local access-restricted EdgeDB installation until they insert their first user, I want to provide them with seed scripts that do not contain any secrets, but instead uses parameters.
