### ISSUE TITLE
`InternalServerError` when creating migration with module name containing backtick

### ISSUE THREAD

**Issue by jaclarke** [edgedb/edgedb#5004]
- EdgeDB Version: EdgeDB 3.0-dev.7232+local
- EdgeDB CLI Version: 2.3.0

Steps to Reproduce:

1. Add a module with a name containing a backtick to schema file, eg:
```
  module default {
    module nested {
      type Test {}
    }
  
+   module `back``ticked` {
+     type Test {}
+   }
  }
```
2. Run `edgedb migration create`:
```
$ edgedb migration create
edgedb error: InternalServerError: 
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "/home/james/dev/edgedb/edb/server/compiler_pool/worker_proc.py", line 55, in worker
          res = meth(*args)
        File "/home/james/dev/edgedb/edb/server/compiler_pool/worker.py", line 186, in compile_in_tx
          units, cstate = COMPILER.compile_in_tx(cstate, *args, **kwargs)
        File "/home/james/dev/edgedb/edb/server/compiler/compiler.py", line 782, in compile_in_tx
          return compile(ctx=ctx, source=source), ctx.state
        File "/home/james/dev/edgedb/edb/server/compiler/compiler.py", line 1742, in compile
          return _try_compile(ctx=ctx, source=original)
        File "/home/james/dev/edgedb/edb/server/compiler/compiler.py", line 1813, in _try_compile
          comp, capabilities = _compile_dispatch_ql(
        File "/home/james/dev/edgedb/edb/server/compiler/compiler.py", line 1667, in _compile_dispatch_ql
          query = ddl.compile_dispatch_ql_migration(
        File "/home/james/dev/edgedb/edb/server/compiler/ddl.py", line 386, in compile_dispatch_ql_migration
          return _describe_current_migration(ctx, ql)
        File "/home/james/dev/edgedb/edb/server/compiler/ddl.py", line 605, in _describe_current_migration
          guided_diff = s_ddl.delta_schemas(
        File "/home/james/dev/edgedb/edb/schema/ddl.py", line 369, in delta_schemas
          assert mod is not None
      AssertionError
```

**Comment by jaclarke** [comment]
This looks like it's probably related:
```
nested> describe schema as sdl;
edgedb error: InternalServerError:
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "/home/james/dev/edgedb/edb/server/compiler_pool/worker_proc.py", line 55, in worker
          res = meth(*args)
        File "/home/james/dev/edgedb/edb/server/compiler_pool/worker.py", line 161, in compile
          units, cstate = COMPILER.compile(
        File "/home/james/dev/edgedb/edb/server/compiler/compiler.py", line 725, in compile
          unit_group = compile(ctx=ctx, source=source)
        File "/home/james/dev/edgedb/edb/server/compiler/compiler.py", line 1745, in compile
          return _try_compile(ctx=ctx, source=source)
        File "/home/james/dev/edgedb/edb/server/compiler/compiler.py", line 1813, in _try_compile
          comp, capabilities = _compile_dispatch_ql(
        File "/home/james/dev/edgedb/edb/server/compiler/compiler.py", line 1719, in _compile_dispatch_ql
          query = _compile_ql_query(ctx, ql, script_info=script_info)
        File "/home/james/dev/edgedb/edb/server/compiler/compiler.py", line 1310, in _compile_ql_query
          ir = qlcompiler.compile_ast_to_ir(
        File "/home/james/dev/edgedb/edb/edgeql/compiler/__init__.py", line 179, in wrapper
          return func(*args, **kwargs)
        File "/home/james/dev/edgedb/edb/edgeql/compiler/__init__.py", line 237, in compile_ast_to_ir
          ir_set = dispatch_mod.compile(tree, ctx=ctx)
        File "/usr/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/home/james/dev/edgedb/edb/edgeql/compiler/stmt.py", line 781, in compile_DescribeStmt
          text = s_ddl.sdl_text_from_schema(
        File "/home/james/dev/edgedb/edb/schema/ddl.py", line 880, in sdl_text_from_schema
          diff = delta_schemas(
        File "/home/james/dev/edgedb/edb/schema/ddl.py", line 238, in delta_schemas
          assert mod is not None
      AssertionError
```
