### ISSUE TITLE
edgedb migration create breaks for function in schema returning optional union of abstract types

### ISSUE THREAD

**Issue by Arrow7000** [edgedb/edgedb#5391]
- EdgeDB Version: 2.13+c171f92
- EdgeDB CLI Version: 2.3.1+ef99779
- OS Version: Ubuntu 20.04.6 LTS (GNU/Linux 5.4.0-147-generic x86_64)

My schema contains some abstract types and some concrete types that are derived from them. I've only copied the abstract types here as that's enough to reproduce the error

```
abstract type MessageFromUser {
    required property timestamp -> datetime;
    link replyTo -> MessageFromApi | MessageFromUser;
}

abstract type MessageFromApi {
    required property createdTimestamp -> datetime;
    required property apiPhoneId -> api_phone_id;
}
```

And I've just defined this fairly simple function in my schema
```
function getApiMsgRepliedTo(userMsg: MessageFromUser) -> optional (MessageFromApi | MessageFromUser)
    using (userMsg.replyTo);
```

But when I run `edgedb migration create` I get the below error

```
edgedb error: InternalServerError: 
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "/home/edgedb/.local/share/edgedb/portable/2.14/lib/python3.10/site-packages/edb/server/compiler_pool/worker_proc.py", line 55, in worker
          res = meth(*args)
        File "/home/edgedb/.local/share/edgedb/portable/2.14/lib/python3.10/site-packages/edb/server/compiler_pool/worker.py", line 160, in compile
          units, cstate = COMPILER.compile(
        File "/home/edgedb/.local/share/edgedb/portable/2.14/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 2524, in compile
          unit_group = self._compile(ctx=ctx, source=source)
        File "/home/edgedb/.local/share/edgedb/portable/2.14/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 2049, in _compile
          return self._try_compile(ctx=ctx, source=source)
        File "/home/edgedb/.local/share/edgedb/portable/2.14/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 2113, in _try_compile
          comp, capabilities = self._compile_dispatch_ql(
        File "/home/edgedb/.local/share/edgedb/portable/2.14/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 1971, in _compile_dispatch_ql
          query = self._compile_ql_migration(
        File "/home/edgedb/.local/share/edgedb/portable/2.14/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 1160, in _compile_ql_migration
          target_schema = s_ddl.apply_sdl(
        File "/home/edgedb/.local/share/edgedb/portable/2.14/lib/python3.10/site-packages/edb/schema/ddl.py", line 442, in apply_sdl
          cmd = cmd_from_ddl(
        File "/home/edgedb/.local/share/edgedb/portable/2.14/lib/python3.10/site-packages/edb/schema/ddl.py", line 394, in cmd_from_ddl
          res = sd.compile_ddl(schema, ddl, context=context)
        File "/home/edgedb/.local/share/edgedb/portable/2.14/lib/python3.10/site-packages/edb/schema/delta.py", line 4255, in compile_ddl
          cmd = cmdcls._cmd_tree_from_ast(schema, astnode, context)
        File "/home/edgedb/.local/share/edgedb/portable/2.14/lib/python3.10/site-packages/edb/schema/functions.py", line 1903, in _cmd_tree_from_ast
          cmd = super()._cmd_tree_from_ast(schema, astnode, context)
        File "/home/edgedb/.local/share/edgedb/portable/2.14/lib/python3.10/site-packages/edb/schema/functions.py", line 1085, in _cmd_tree_from_ast
          assert isinstance(astnode.returning, qlast.TypeName)
      AssertionError
```

**Comment by msullivan** [comment]
1. It producing an ISE is definitely a bug. If we aren't going to support something, we ought to produce a proper error message
2. I feel like properly supporting this shouldn't be /that/ hard either? I'd start by removing the assert and seeing where it goes.
