### ISSUE TITLE
CrewmanInBulgaria alias from Easy EdgeDB errs while other aliases do not

### ISSUE THREAD

**Issue by Dhghomon** [edgedb/edgedb#5396]
- EdgeDB Version: 2.14+7aec755 and 3.0-alpha.3+b5168d2'
- EdgeDB CLI Version: 2.3.1+ef99779
- OS Version: Windows 11

Steps to Reproduce:

1. edgedb project init, copy in schema from Chapter 17 https://github.com/edgedb/easy-edgedb/blob/master/chapter17/code.md
2. Add an extra alias below CrewmanInBulgaria:

    alias VampireAlias := Vampire {
      name := .name ++ " the alias"
    };

4. Migrate, then copy and paste the inserts from the same page in Chapter 17 to populate the database.
5. `select VampireAlias` will work fine, but `select CrewmanInBulgaria` will generate an error (output below).
6. `select VampireAlias filter .name = "Count Dracula the alias"` will work fine, but `select CrewmanInBulgaria filter .name = "Gospodin Crewman 1"` will not
7. Interestingly, `select VampireAlias {name};` works and `select CrewmanInBulgaria {name}` also works.

Originally thought this might be a 2.14 to 3.0 upgrade issue, but I see the same error when using version 2.14.

```
edgedb> select CrewmanInBulgaria filter .name = "Gospodin Crewman 1";
edgedb error: InternalServerError:
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "/home/edgedb/.local/share/edgedb/portable/3.0-alpha.3/lib/python3.10/site-packages/edb/server/compiler_pool/worker_proc.py", line 55, in worker
          res = meth(*args)
        File "/home/edgedb/.local/share/edgedb/portable/3.0-alpha.3/lib/python3.10/site-packages/edb/server/compiler_pool/worker.py", line 161, in compile
          units, cstate = COMPILER.compile(
        File "/home/edgedb/.local/share/edgedb/portable/3.0-alpha.3/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 742, in compile
          unit_group = compile(ctx=ctx, source=source)
        File "/home/edgedb/.local/share/edgedb/portable/3.0-alpha.3/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 1925, in compile
          return _try_compile(ctx=ctx, source=source)
        File "/home/edgedb/.local/share/edgedb/portable/3.0-alpha.3/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 1993, in _try_compile
          comp, capabilities = _compile_dispatch_ql(
        File "/home/edgedb/.local/share/edgedb/portable/3.0-alpha.3/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 1899, in _compile_dispatch_ql
          query = _compile_ql_query(ctx, ql, script_info=script_info)
        File "/home/edgedb/.local/share/edgedb/portable/3.0-alpha.3/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 1463, in _compile_ql_query
          ir = qlcompiler.compile_ast_to_ir(
        File "/home/edgedb/.local/share/edgedb/portable/3.0-alpha.3/lib/python3.10/site-packages/edb/edgeql/compiler/__init__.py", line 179, in wrapper
          return func(*args, **kwargs)
        File "/home/edgedb/.local/share/edgedb/portable/3.0-alpha.3/lib/python3.10/site-packages/edb/edgeql/compiler/__init__.py", line 237, in compile_ast_to_ir
          ir_set = dispatch_mod.compile(tree, ctx=ctx)
        File "/home/edgedb/.local/share/edgedb/portable/3.0-alpha.3/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/home/edgedb/.local/share/edgedb/portable/3.0-alpha.3/lib/python3.10/site-packages/edb/edgeql/compiler/stmt.py", line 127, in compile_SelectQuery
          stmt.result = compile_result_clause(
        File "/home/edgedb/.local/share/edgedb/portable/3.0-alpha.3/lib/python3.10/site-packages/edb/edgeql/compiler/stmt.py", line 1332, in compile_result_clause
          ir_result = compile_query_subject(
        File "/home/edgedb/.local/share/edgedb/portable/3.0-alpha.3/lib/python3.10/site-packages/edb/edgeql/compiler/stmt.py", line 1484, in compile_query_subject
          viewgen.late_compile_view_shapes(expr, ctx=ctx)
        File "/home/edgedb/.local/share/edgedb/portable/3.0-alpha.3/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/home/edgedb/.local/share/edgedb/portable/3.0-alpha.3/lib/python3.10/site-packages/edb/edgeql/compiler/viewgen.py", line 2289, in _late_compile_view_shapes_in_set
          late_compile_view_shapes(
        File "/home/edgedb/.local/share/edgedb/portable/3.0-alpha.3/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/home/edgedb/.local/share/edgedb/portable/3.0-alpha.3/lib/python3.10/site-packages/edb/edgeql/compiler/viewgen.py", line 2313, in _late_compile_view_shapes_in_set
          late_compile_view_shapes(
        File "/home/edgedb/.local/share/edgedb/portable/3.0-alpha.3/lib/python3.10/functools.py", line 889, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/home/edgedb/.local/share/edgedb/portable/3.0-alpha.3/lib/python3.10/site-packages/edb/edgeql/compiler/viewgen.py", line 2265, in _late_compile_view_shapes_in_set
          shape_ptrs = _get_late_shape_configuration(
        File "/home/edgedb/.local/share/edgedb/portable/3.0-alpha.3/lib/python3.10/site-packages/edb/edgeql/compiler/viewgen.py", line 2236, in _get_late_shape_configuration
          _get_shape_configuration_inner(
        File "/home/edgedb/.local/share/edgedb/portable/3.0-alpha.3/lib/python3.10/site-packages/edb/edgeql/compiler/viewgen.py", line 2153, in _get_shape_configuration_inner
          _inline_type_computable(
        File "/home/edgedb/.local/share/edgedb/portable/3.0-alpha.3/lib/python3.10/site-packages/edb/edgeql/compiler/viewgen.py", line 2009, in _inline_type_computable
          assert stype.is_view(ctx.env.schema)
      AssertionError
```

**Comment by Dhghomon** [comment]
After some more experimenting it's definitely related to the `current_location := (select Place filter .name = 'Bulgaria')` part of the alias.
