### ISSUE TITLE
Error inserting json in trigger

### ISSUE THREAD

**Issue by CSFlorin** [edgedb/edgedb#5494]
- EdgeDB Version: 3.0-beta.1+4cdeba3
- EdgeDB CLI Version: 3.0.0-beta.1+3df4cf7
- OS Version: Mac 12.4

Steps to Reproduce:

1. Create a trigger that inserts an entry with a json column like

```
trigger logInsert after insert for each do (
  insert Log {
    username := __new__.user.username,
    target := <json>(select { 
      direction := __new__.direction
    })
  }
);
```

2. Try to create a migration and get

```
InternalServerError: dependency cycle between ('create', 'default::__|target@default|Log') and ('delete', 'default::__|target@default|Log')
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "/Users/f/Library/Application Support/edgedb/portable/3.0-beta.1/lib/python3.10/site-packages/edb/server/compiler_pool/worker_proc.py", line 55, in worker
          res = meth(*args)
        File "/Users/f/Library/Application Support/edgedb/portable/3.0-beta.1/lib/python3.10/site-packages/edb/server/compiler_pool/worker.py", line 186, in compile_in_tx
          units, cstate = COMPILER.compile_in_tx(cstate, *args, **kwargs)
        File "/Users/f/Library/Application Support/edgedb/portable/3.0-beta.1/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 802, in compile_in_tx
          return compile(ctx=ctx, source=source), ctx.state
        File "/Users/f/Library/Application Support/edgedb/portable/3.0-beta.1/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 1924, in compile
          return _try_compile(ctx=ctx, source=original)
        File "/Users/f/Library/Application Support/edgedb/portable/3.0-beta.1/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 1995, in _try_compile
          comp, capabilities = _compile_dispatch_ql(
        File "/Users/f/Library/Application Support/edgedb/portable/3.0-beta.1/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 1834, in _compile_dispatch_ql
          query = ddl.compile_dispatch_ql_migration(
        File "/Users/f/Library/Application Support/edgedb/portable/3.0-beta.1/lib/python3.10/site-packages/edb/server/compiler/ddl.py", line 387, in compile_dispatch_ql_migration
          return _describe_current_migration(ctx, ql)
        File "/Users/f/Library/Application Support/edgedb/portable/3.0-beta.1/lib/python3.10/site-packages/edb/server/compiler/ddl.py", line 612, in _describe_current_migration
          guided_diff = s_ddl.delta_schemas(
        File "/Users/f/Library/Application Support/edgedb/portable/3.0-beta.1/lib/python3.10/site-packages/edb/schema/ddl.py", line 337, in delta_schemas
          objects = s_ordering.linearize_delta(
        File "/Users/f/Library/Application Support/edgedb/portable/3.0-beta.1/lib/python3.10/site-packages/edb/schema/ordering.py", line 113, in linearize_delta
          sortedlist = [i[1] for i in topological.sort_ex(depgraph)]
        File "/Users/f/Library/Application Support/edgedb/portable/3.0-beta.1/lib/python3.10/site-packages/edb/common/topological.py", line 187, in sort_ex
          visit(key)
        File "/Users/f/Library/Application Support/edgedb/portable/3.0-beta.1/lib/python3.10/site-packages/edb/common/topological.py", line 170, in visit
          visit(n, weak_link=weak_link)
        File "/Users/f/Library/Application Support/edgedb/portable/3.0-beta.1/lib/python3.10/site-packages/edb/common/topological.py", line 170, in visit
          visit(n, weak_link=weak_link)
        File "/Users/f/Library/Application Support/edgedb/portable/3.0-beta.1/lib/python3.10/site-packages/edb/common/topological.py", line 170, in visit
          visit(n, weak_link=weak_link)
        File "/Users/f/Library/Application Support/edgedb/portable/3.0-beta.1/lib/python3.10/site-packages/edb/common/topological.py", line 149, in visit
          raise CycleError(
      edb.common.topological.CycleError: dependency cycle between ('create', 'default::__|target@default|Log') and ('delete', 'default::__|target@default|Log')
```

**Comment by CSFlorin** [comment]
It was fixed in 3.0 beta rc1!
