### ISSUE TITLE
Dump fails with `error receiving dump header: unexpected constant type: <class 'edb.ir.statypes.Duration'>`

### ISSUE THREAD

**Issue by jackfischer** [edgedb/edgedb#5520]
- EdgeDB Version: `2.14` and `2.15`
- EdgeDB CLI Version: `2.3.1+5d93f42` and `3.0.0+80bc8b4`
- OS Version: macos 13

Steps to Reproduce:

Unsure as to the exact circumstances that led to this so apologies in advance for lack of detail. This does work as expected on an instance with identical version/schema, so this may be data dependent.

1. Run `edgedb dump -I instancename instance.dump`

```
edgedb error: InternalServerError: error receiving dump header: unexpected constant type: <class 'edb.ir.statypes.Duration'>
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-2/lib/python3.10/site-packages/edb/server/compiler_pool/worker_proc.py", line 55, in worker
          res = meth(*args)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-2/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 2595, in describe_database_dump
          config_ddl = config.to_edgeql(config.get_settings(), database_config)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-2/lib/python3.10/site-packages/edb/server/config/ops.py", line 394, in to_edgeql
          val = value_to_edgeql_const(setting, value.value)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-2/lib/python3.10/site-packages/edb/server/config/ops.py", line 333, in value_to_edgeql_const
          ql = s_utils.const_ast_from_python(value)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-2/lib/python3.10/site-packages/edb/schema/utils.py", line 1128, in const_ast_from_python
          raise ValueError(f'unexpected constant type: {type(val)!r}')
      ValueError: unexpected constant type: <class 'edb.ir.statypes.Duration'>
```

Schema:

Can send schema by discord DM Jack Fischer#5469. Happy to pull any other info that would be helpful. No `duration`s in schema.

**Comment by msullivan** [comment]
It looks like the bug is that we can't properly handle dumping databases that have had any *configuration values* of type `duration` set.

As a workaround, try unsetting the three configuration values with `duration` type on the database: `session_idle_timeout`, `session_idle_transaction_timeout`, `query_execution_timeout`.
