### ISSUE TITLE
Migration is suggesting dropping a rewrite when it should be not be doing so

### ISSUE THREAD

**Issue by aljazerzen** [edgedb/edgedb#5550]
```
(venv) ➜  demo-2 edb cli migration create
did you drop rewrite 'Insert' of link 'default_project'? [y,n,l,c,b,s,q,?]
> l
The following DDL statements will be applied:
    ALTER TYPE default::User {
        ALTER LINK default_project {
            DROP REWRITE
                INSERT ;
            };
        };
did you drop rewrite 'Insert' of link 'default_project'? [y,n,l,c,b,s,q,?]
> n
edgedb error: InternalServerError: argument of type 'NoneType' is not iterable
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "/home/aljaz/EdgeDB/edgedb/edb/server/compiler_pool/worker.py", line 186, in compile_in_tx
          units, cstate = COMPILER.compile_in_tx(cstate, *args, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/aljaz/EdgeDB/edgedb/edb/server/compiler/compiler.py", line 808, in compile_in_tx
          return compile(ctx=ctx, source=source), ctx.state
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/aljaz/EdgeDB/edgedb/edb/server/compiler/compiler.py", line 1932, in compile
          return _try_compile(ctx=ctx, source=original)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/aljaz/EdgeDB/edgedb/edb/server/compiler/compiler.py", line 2003, in _try_compile
          comp, capabilities = _compile_dispatch_ql(
                               ^^^^^^^^^^^^^^^^^^^^^
        File "/home/aljaz/EdgeDB/edgedb/edb/server/compiler/compiler.py", line 1842, in _compile_dispatch_ql
          query = ddl.compile_dispatch_ql_migration(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/aljaz/EdgeDB/edgedb/edb/server/compiler/ddl.py", line 387, in compile_dispatch_ql_migration
          return _describe_current_migration(ctx, ql)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/aljaz/EdgeDB/edgedb/edb/server/compiler/ddl.py", line 622, in _describe_current_migration
          proposed_ddl = s_ddl.statements_from_delta(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/aljaz/EdgeDB/edgedb/edb/schema/ddl.py", line 729, in statements_from_delta
          stmt_text = edgeql.generate_source(
                      ^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/aljaz/EdgeDB/edgedb/edb/edgeql/codegen.py", line 2488, in to_source
          return super().to_source(
                 ^^^^^^^^^^^^^^^^^^
        File "/home/aljaz/EdgeDB/edgedb/edb/common/ast/codegen.py", line 140, in to_source
          generator.visit(node)
        File "/home/aljaz/EdgeDB/edgedb/edb/edgeql/codegen.py", line 109, in visit
          visitor(node, **kwargs)
        File "/home/aljaz/EdgeDB/edgedb/edb/edgeql/codegen.py", line 1894, in visit_AlterObjectType
          self._visit_AlterObject(node, 'TYPE')
        File "/home/aljaz/EdgeDB/edgedb/edb/edgeql/codegen.py", line 1005, in _visit_AlterObject
          self._ddl_visit_body(
        File "/home/aljaz/EdgeDB/edgedb/edb/edgeql/codegen.py", line 934, in _ddl_visit_body
          self.visit_list(list(commands), terminator=';')
        File "/home/aljaz/EdgeDB/edgedb/edb/common/ast/codegen.py", line 115, in visit_list
          self.visit(item, **kwargs)  # type: ignore
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/aljaz/EdgeDB/edgedb/edb/edgeql/codegen.py", line 109, in visit
          visitor(node, **kwargs)
        File "/home/aljaz/EdgeDB/edgedb/edb/edgeql/codegen.py", line 1821, in visit_AlterConcreteLink
          self._visit_AlterObject(
        File "/home/aljaz/EdgeDB/edgedb/edb/edgeql/codegen.py", line 1005, in _visit_AlterObject
          self._ddl_visit_body(
        File "/home/aljaz/EdgeDB/edgedb/edb/edgeql/codegen.py", line 934, in _ddl_visit_body
          self.visit_list(list(commands), terminator=';')
        File "/home/aljaz/EdgeDB/edgedb/edb/common/ast/codegen.py", line 115, in visit_list
          self.visit(item, **kwargs)  # type: ignore
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/aljaz/EdgeDB/edgedb/edb/edgeql/codegen.py", line 109, in visit
          visitor(node, **kwargs)
        File "/home/aljaz/EdgeDB/edgedb/edb/edgeql/codegen.py", line 1602, in visit_AlterRewrite
          self._visit_AlterObject(
        File "/home/aljaz/EdgeDB/edgedb/edb/edgeql/codegen.py", line 997, in _visit_AlterObject
          after_name()
        File "/home/aljaz/EdgeDB/edgedb/edb/edgeql/codegen.py", line 1600, in an
          self._write_keywords(self._format_rewrite_kinds(node.kinds) + ' ')
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/aljaz/EdgeDB/edgedb/edb/edgeql/codegen.py", line 1569, in _format_rewrite_kinds
          kinds = [k for k in list(qltypes.RewriteKind) if k in kinds]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/aljaz/EdgeDB/edgedb/edb/edgeql/codegen.py", line 1569, in <listcomp>
          kinds = [k for k in list(qltypes.RewriteKind) if k in kinds]
                                                           ^^^^^^^^^^
      TypeError: a
```

- EdgeDB Version: current master
- EdgeDB CLI Version: dev
- OS Version: Linux

Steps to Reproduce:

1. Migrate to the schema
2. Run `edb cli migration create`, without changing anything.

Schema:

```
module default {

    
    type User {
        
        required password: str;
        
        multi link projects := .<owner[is Project];

        link default_project: Project {
            rewrite insert using (
                insert Project {
                    name := 'default',
                    owner := __subject__,
                }
            )
        };
    }

    type Project {
        required name: str;
        required owner: User;

        constraint exclusive on ( (.name, .owner) );
    }
}



```

**Comment by aljazerzen** [comment]
I'm not able to reproduce this again.
