### ISSUE TITLE
InternalServerError trying to select an alias

### ISSUE THREAD

**Issue by raddevon** [edgedb/edgedb#5679]
When I try to select an alias, I get InternalServerError:

```
edgedb error: InternalServerError:
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "/Users/raddevon/Library/Application Support/edgedb/portable/3.0-rc.5/lib/python3.11/site-packages/edb/server/compiler_pool/worker.py", line 161, in compile
          units, cstate = COMPILER.compile(
                          ^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/3.0-rc.5/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 755, in compile
          unit_group = compile(ctx=ctx, source=source)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/3.0-rc.5/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 1944, in compile
          return _try_compile(ctx=ctx, source=source)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/3.0-rc.5/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 2012, in _try_compile
          comp, capabilities = _compile_dispatch_ql(
                               ^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/3.0-rc.5/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 1918, in _compile_dispatch_ql
          query = _compile_ql_query(ctx, ql, script_info=script_info)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/3.0-rc.5/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 1478, in _compile_ql_query
          ir = qlcompiler.compile_ast_to_ir(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/3.0-rc.5/lib/python3.11/site-packages/edb/edgeql/compiler/__init__.py", line 179, in wrapper
          return func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/3.0-rc.5/lib/python3.11/site-packages/edb/edgeql/compiler/__init__.py", line 237, in compile_ast_to_ir
          ir_set = dispatch_mod.compile(tree, ctx=ctx)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/3.0-rc.5/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/3.0-rc.5/lib/python3.11/site-packages/edb/edgeql/compiler/stmt.py", line 128, in compile_SelectQuery
          stmt.result = compile_result_clause(
                        ^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/3.0-rc.5/lib/python3.11/site-packages/edb/edgeql/compiler/stmt.py", line 1364, in compile_result_clause
          ir_result = compile_query_subject(
                      ^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/3.0-rc.5/lib/python3.11/site-packages/edb/edgeql/compiler/stmt.py", line 1517, in compile_query_subject
          viewgen.late_compile_view_shapes(expr, ctx=ctx)
        File "/Users/raddevon/Library/Application Support/edgedb/portable/3.0-rc.5/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/3.0-rc.5/lib/python3.11/site-packages/edb/edgeql/compiler/viewgen.py", line 2336, in _late_compile_view_shapes_in_set
          late_compile_view_shapes(
        File "/Users/raddevon/Library/Application Support/edgedb/portable/3.0-rc.5/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/3.0-rc.5/lib/python3.11/site-packages/edb/edgeql/compiler/viewgen.py", line 2360, in _late_compile_view_shapes_in_set
          late_compile_view_shapes(
        File "/Users/raddevon/Library/Application Support/edgedb/portable/3.0-rc.5/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/3.0-rc.5/lib/python3.11/site-packages/edb/edgeql/compiler/viewgen.py", line 2312, in _late_compile_view_shapes_in_set
          shape_ptrs = _get_late_shape_configuration(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/3.0-rc.5/lib/python3.11/site-packages/edb/edgeql/compiler/viewgen.py", line 2283, in _get_late_shape_configuration
          _get_shape_configuration_inner(
        File "/Users/raddevon/Library/Application Support/edgedb/portable/3.0-rc.5/lib/python3.11/site-packages/edb/edgeql/compiler/viewgen.py", line 2200, in _get_shape_configuration_inner
          _inline_type_computable(
        File "/Users/raddevon/Library/Application Support/edgedb/portable/3.0-rc.5/lib/python3.11/site-packages/edb/edgeql/compiler/viewgen.py", line 2055, in _inline_type_computable
          assert stype.is_view(ctx.env.schema)
      AssertionError
```

- EdgeDB Version: 3.0-rc.5+ca725cb
- EdgeDB CLI Version: 3.3.0-dev.1018+78aa559
- OS Version: macOS 13.3.1

Steps to Reproduce:

1. Add some data to the database. I added three `User` objects with these queries:
```
insert User {name := 'U1'};
```

```
insert User {name := 'U2', friends := (select detached User)};
```

```
insert User {name := 'U3', friends := (select detached User)};
```

2. Run the query `select UserAlias;`
3. Observe error

Schema:

```
module default {
  type User {
      required name: str;
      multi friends: User;
  }

  alias UserAlias := User {
      # declare a computed link
      friend_of := User.<friends[is User]
  };
}
```

**Comment by msullivan** [comment]
Looks like this bug has been around for a while.

**Comment by msullivan** [comment]
I think the bug is:
* selecting an alias without a shape
* when the alias has a computed link in it
* in the CLI with type name injection on
