### ISSUE TITLE
InternalServerError when using multiple type intersection splats in a query

### ISSUE THREAD

**Issue by raddevon** [edgedb/edgedb#5916]
Tried this in the [MCU sandbox](https://github.com/edgedb/mcu-sandbox) database updated to the latest nightly.

- EdgeDB Version: 4.0-dev.7714+e2db9b8
- EdgeDB CLI Version: 3.4.0+4d95a2c
- OS Version: macOS 13.4.1

Steps to Reproduce:

1. Clone the [MCU sandbox repo](https://github.com/edgedb/mcu-sandbox)
2. Update the `edgedb.toml` changing the version to `nightly`
3. Run `edgedb project init`
4. Access the REPL with `edgedb`
5. Run the query`select Content {*, [is Movie].*, [is TVShow].*};`

I would expect this to give back a result set containing objects with all properties of both `Movie` objects and `TVShow` objects, with any properties that are not on a given object containing the empty set for that object. Instead, I get this:

```
edgedb error: InternalServerError:
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "/Users/raddevon/Library/Application Support/edgedb/portable/4.0-dev.7714/lib/python3.11/site-packages/edb/server/compiler_pool/worker.py", line 161, in compile
          units, cstate = COMPILER.compile(
                          ^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/4.0-dev.7714/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 862, in compile
          unit_group = compile(ctx=ctx, source=source)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/4.0-dev.7714/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 2059, in compile
          return _try_compile(ctx=ctx, source=source)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/4.0-dev.7714/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 2127, in _try_compile
          comp, capabilities = _compile_dispatch_ql(
                               ^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/4.0-dev.7714/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 2033, in _compile_dispatch_ql
          query = _compile_ql_query(ctx, ql, script_info=script_info)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/4.0-dev.7714/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 1574, in _compile_ql_query
          ir = qlcompiler.compile_ast_to_ir(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/4.0-dev.7714/lib/python3.11/site-packages/edb/edgeql/compiler/__init__.py", line 182, in wrapper
          return func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/4.0-dev.7714/lib/python3.11/site-packages/edb/edgeql/compiler/__init__.py", line 273, in compile_ast_to_ir
          ir_set = dispatch_mod.compile(tree, ctx=ctx)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/4.0-dev.7714/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/4.0-dev.7714/lib/python3.11/site-packages/edb/edgeql/compiler/stmt.py", line 128, in compile_SelectQuery
          stmt.result = compile_result_clause(
                        ^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/4.0-dev.7714/lib/python3.11/site-packages/edb/edgeql/compiler/stmt.py", line 1364, in compile_result_clause
          ir_result = compile_query_subject(
                      ^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/4.0-dev.7714/lib/python3.11/site-packages/edb/edgeql/compiler/stmt.py", line 1501, in compile_query_subject
          view_scls, expr = viewgen.process_view(
                            ^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/4.0-dev.7714/lib/python3.11/site-packages/edb/edgeql/compiler/viewgen.py", line 153, in process_view
          view_scls, ir = _process_view(
                          ^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/4.0-dev.7714/lib/python3.11/site-packages/edb/edgeql/compiler/viewgen.py", line 363, in _process_view
          pointer, ptr_set = _normalize_view_ptr_expr(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/4.0-dev.7714/lib/python3.11/site-packages/edb/edgeql/compiler/viewgen.py", line 1820, in _normalize_view_ptr_expr
          assert ptrcls not in ctx.env.materialized_sets
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AssertionError
```

**Comment by MrFoxPro** [comment]
This is still issue on 5.6
