### ISSUE TITLE
`Can't find materialized set (__derived__::key~1@w~2).>organization[IS default::Organization]`

### ISSUE THREAD

**Issue by jackfischer** [edgedb/edgedb#6019]
- EdgeDB Version: 3.2
- EdgeDB CLI Version: 3.4.0+4d95a2c
- OS Version: macos 13.5

Steps to Reproduce:

Discovered accidentally while trying to create a nested group by[ [discord]](https://discord.com/channels/841451783728529451/849377751370432573/1148317119872774285)

1. Wrap a group by query in another group by on `.key`
```edgeql
group (
  group (
    select User
  ) by .organization
) by .key
```

Schema:

```
type User {
  required link organization: Organization;
}
type Organization {}
```

**Comment by jackfischer** [comment]
At risk of the above being wrong (group by .key seems suspect), here is my better attempt at a nested groupby
```edgeql
with byAandB := (
  group (
    select ...
  ) by (.a, .b)
),

flattened := (
  select byAandB {a:=(.key.a), b:=(.key.b), elements}
)

group
flattened
by .a
```

```
InternalServerError: Can't find materialized set (__derived__::flattened@w~4)
Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
```

**Comment by jackfischer** [comment]
Confirmed also affects EdgeDB 4.1+0c628ea (repl 4.0.2+500be79)

```
edgedb error: InternalServerError: Can't find materialized set (__derived__::key~1@w~2).>organization[IS default::Organization]
  Server traceback:
      Traceback (most recent call last):
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/__init__.py", line 140, in compile_ir_to_sql_tree
          qtree = dispatch.compile(ir_expr, ctx=ctx)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 60, in compile_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 115, in _compile_set_impl
          _compile_set(ir_set, ctx=ctx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 704, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 165, in get_set_rvar
          return _process_toplevel_query(ir_set, ctx=ctx)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 287, in _process_toplevel_query
          rvars = _get_set_rvar(ir_set, ctx=ctx)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 369, in _get_set_rvar
          return process_set_as_subquery(ir_set, ctx=ctx)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 1446, in process_set_as_subquery
          dispatch.visit(expr, ctx=newctx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/dispatch.py", line 44, in visit
          compile(ir, ctx=ctx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/stmt.py", line 143, in compile_GroupStmt
          return group.compile_group(stmt, ctx=ctx)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/group.py", line 393, in compile_group
          return _compile_group(stmt, ctx=sctx, parent_ctx=ctx)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/group.py", line 366, in _compile_group
          clauses.compile_output(stmt.result, ctx=outctx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/clauses.py", line 227, in compile_output
          dispatch.visit(ir_set, ctx=newctx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 85, in visit_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 111, in _compile_set_impl
          _compile_set(ir_set, ctx=scopectx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 704, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 223, in get_set_rvar
          rvars = _get_set_rvar(ir_set, ctx=subctx)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 369, in _get_set_rvar
          return process_set_as_subquery(ir_set, ctx=ctx)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 1446, in process_set_as_subquery
          dispatch.visit(expr, ctx=newctx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/dispatch.py", line 44, in visit
          compile(ir, ctx=ctx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/stmt.py", line 94, in compile_SelectStmt
          outvar = clauses.compile_output(stmt.result, ctx=ictx)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/clauses.py", line 227, in compile_output
          dispatch.visit(ir_set, ctx=newctx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 85, in visit_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 115, in _compile_set_impl
          _compile_set(ir_set, ctx=ctx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 708, in _compile_set
          _compile_shape(ir_set, ir_set.shape, ctx=ctx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 727, in _compile_shape
          result = shapecomp.compile_shape(ir_set, shape, ctx=ctx)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/shapecomp.py", line 100, in compile_shape
          wrapper = relgen.set_as_subquery(
                    ^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 528, in set_as_subquery
          dispatch.visit(ir_set, ctx=subctx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 85, in visit_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 111, in _compile_set_impl
          _compile_set(ir_set, ctx=scopectx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 704, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 223, in get_set_rvar
          rvars = _get_set_rvar(ir_set, ctx=subctx)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 369, in _get_set_rvar
          return process_set_as_subquery(ir_set, ctx=ctx)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 1446, in process_set_as_subquery
          dispatch.visit(expr, ctx=newctx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/dispatch.py", line 44, in visit
          compile(ir, ctx=ctx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/stmt.py", line 94, in compile_SelectStmt
          outvar = clauses.compile_output(stmt.result, ctx=ictx)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/clauses.py", line 227, in compile_output
          dispatch.visit(ir_set, ctx=newctx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 85, in visit_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 111, in _compile_set_impl
          _compile_set(ir_set, ctx=scopectx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 704, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 223, in get_set_rvar
          rvars = _get_set_rvar(ir_set, ctx=subctx)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 369, in _get_set_rvar
          return process_set_as_subquery(ir_set, ctx=ctx)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 1446, in process_set_as_subquery
          dispatch.visit(expr, ctx=newctx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/dispatch.py", line 44, in visit
          compile(ir, ctx=ctx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/stmt.py", line 94, in compile_SelectStmt
          outvar = clauses.compile_output(stmt.result, ctx=ictx)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/clauses.py", line 227, in compile_output
          dispatch.visit(ir_set, ctx=newctx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 85, in visit_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 115, in _compile_set_impl
          _compile_set(ir_set, ctx=ctx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 708, in _compile_set
          _compile_shape(ir_set, ir_set.shape, ctx=ctx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 727, in _compile_shape
          result = shapecomp.compile_shape(ir_set, shape, ctx=ctx)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/shapecomp.py", line 100, in compile_shape
          wrapper = relgen.set_as_subquery(
                    ^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 528, in set_as_subquery
          dispatch.visit(ir_set, ctx=subctx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 85, in visit_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 111, in _compile_set_impl
          _compile_set(ir_set, ctx=scopectx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 704, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 223, in get_set_rvar
          rvars = _get_set_rvar(ir_set, ctx=subctx)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 369, in _get_set_rvar
          return process_set_as_subquery(ir_set, ctx=ctx)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 1446, in process_set_as_subquery
          dispatch.visit(expr, ctx=newctx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/dispatch.py", line 44, in visit
          compile(ir, ctx=ctx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/stmt.py", line 94, in compile_SelectStmt
          outvar = clauses.compile_output(stmt.result, ctx=ictx)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/clauses.py", line 227, in compile_output
          dispatch.visit(ir_set, ctx=newctx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 85, in visit_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 111, in _compile_set_impl
          _compile_set(ir_set, ctx=scopectx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 704, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 223, in get_set_rvar
          rvars = _get_set_rvar(ir_set, ctx=subctx)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 369, in _get_set_rvar
          return process_set_as_subquery(ir_set, ctx=ctx)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 1446, in process_set_as_subquery
          dispatch.visit(expr, ctx=newctx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/dispatch.py", line 44, in visit
          compile(ir, ctx=ctx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/stmt.py", line 94, in compile_SelectStmt
          outvar = clauses.compile_output(stmt.result, ctx=ictx)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/clauses.py", line 227, in compile_output
          dispatch.visit(ir_set, ctx=newctx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 85, in visit_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 111, in _compile_set_impl
          _compile_set(ir_set, ctx=scopectx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 708, in _compile_set
          _compile_shape(ir_set, ir_set.shape, ctx=ctx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 727, in _compile_shape
          result = shapecomp.compile_shape(ir_set, shape, ctx=ctx)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/shapecomp.py", line 100, in compile_shape
          wrapper = relgen.set_as_subquery(
                    ^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 528, in set_as_subquery
          dispatch.visit(ir_set, ctx=subctx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 85, in visit_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 111, in _compile_set_impl
          _compile_set(ir_set, ctx=scopectx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 704, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 223, in get_set_rvar
          rvars = _get_set_rvar(ir_set, ctx=subctx)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 363, in _get_set_rvar
          return process_set_as_subquery(ir_set, ctx=ctx)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 1426, in process_set_as_subquery
          assert not ir_set.is_materialized_ref, (
      AssertionError: Can't find materialized set (__derived__::key~1@w~2).>organization[IS default::Organization]

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/server/compiler_pool/worker.py", line 178, in compile
          units, cstate = COMPILER.compile(
                          ^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 885, in compile
          unit_group = compile(ctx=ctx, source=source)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 2309, in compile
          return _try_compile(ctx=ctx, source=source)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 2370, in _try_compile
          comp, capabilities = _compile_dispatch_ql(
                               ^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 2283, in _compile_dispatch_ql
          query = _compile_ql_query(ctx, ql, script_info=script_info)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 1716, in _compile_ql_query
          sql_res = pg_compiler.compile_ir_to_sql_tree(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/pgsql/compiler/__init__.py", line 157, in compile_ir_to_sql_tree
          raise errors.InternalServerError(*args) from e
      edb.errors.InternalServerError: Can't find materialized set (__derived__::key~1@w~2).>organization[IS default::Organization]
```

@aljazerzen this one looks fairly different than https://github.com/edgedb/edgedb/issues/6481, but perhaps while your brain is already on groupbys...

**Comment by aljazerzen** [comment]
Yes, this is different than #6481

**Comment by dnwpark** [comment]
#8000 fixes the issue where `group` can't be used in a with binding, but the `group (group X by .x) by .key` issue remains
