### ISSUE TITLE
Installation fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by sfermigier** [edgedb/edgedb#610]
Trying to follow the tutorial (https://edgedb.com/download?distro=linux + https://edgedb.com/docs/tutorial/install/#ref-tutorial-install):

```
root@pilaf:~# apt-get update && apt-get install edgedb-1-alpha1
Get:1 http://ubuntu.mirrors.ovh.net/ftp.ubuntu.com/ubuntu bionic InRelease [242 kB]
Get:2 http://ubuntu.mirrors.ovh.net/ftp.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:3 http://ubuntu.mirrors.ovh.net/ftp.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
0% [1 InRelease gpgv 242 kB] [Connecting to security.ubuntu.com (2001:67c:1562::16)]
Get:4 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:5 https://packages.edgedb.com/apt bionic InRelease [2,470 B]
Hit:6 https://deb.nodesource.com/node_8.x bionic InRelease
Get:7 https://packages.edgedb.com/apt bionic/main amd64 Packages [708 B]
Fetched 497 kB in 1s (632 kB/s)
Reading package lists... Done
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://packages.edgedb.com/apt bionic InRelease' doesn't support architecture 'i386'
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  edgedb-common
The following NEW packages will be installed:
  edgedb-1-alpha1 edgedb-common
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 16.6 MB of archives.
After this operation, 114 MB of additional disk space will be used.
Get:1 https://packages.edgedb.com/apt bionic/main amd64 edgedb-common amd64 1.0a1-1~bionic [1,376 B]
Get:2 https://packages.edgedb.com/apt bionic/main amd64 edgedb-1-alpha1 amd64 1.0a1-1~bionic [16.6 MB]
Fetched 16.6 MB in 2s (7,821 kB/s)
[master 4537b14] saving uncommitted changes in /etc prior to apt run
 3 files changed, 2 insertions(+)
 create mode 100644 apt/sources.list.d/edgedb.list
Selecting previously unselected package edgedb-common.
(Reading database ... 75849 files and directories currently installed.)
Preparing to unpack .../edgedb-common_1.0a1-1~bionic_amd64.deb ...
Unpacking edgedb-common (1.0a1-1~bionic) ...
Selecting previously unselected package edgedb-1-alpha1.
Preparing to unpack .../edgedb-1-alpha1_1.0a1-1~bionic_amd64.deb ...
Unpacking edgedb-1-alpha1 (1.0a1-1~bionic) ...
Setting up edgedb-common (1.0a1-1~bionic) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Setting up edgedb-1-alpha1 (1.0a1-1~bionic) ...
INFO 4037 2019-04-11 23:01:20,393 edb.server: EdgeDB server (1.0.alpha.1) starting.
INFO 4037 2019-04-11 23:01:21,011 edb.server: Initializing database cluster in /var/lib/edgedb/1-alpha1/data
INFO 4037 2019-04-11 23:01:24,023 edb.server: Creating template database...
INFO 4037 2019-04-11 23:01:24,739 edb.server: Bootstrapping meta schema...
INFO 4037 2019-04-11 23:01:47,273 edb.server: Creating database: edgedb
INFO 4037 2019-04-11 23:01:48,678 edb.server: Restarting server to reload configuration...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
root@pilaf:~# sudo -u edgedb edgedb --admin alter role edgedb --password
Traceback (most recent call last):
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/edgedb/blocking_con.py", line 88, in _connect_addr
    sock.connect(addr)
FileNotFoundError: [Errno 2] No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/bin/edgedb", line 11, in <module>
    sys.exit(cli())
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/edb/cli/mng.py", line 306, in alter
    connect(ctx)
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/edb/cli/mng.py", line 37, in connect
    admin=ctx.obj['admin'], password=ctx.obj['password'],
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/edgedb/blocking_con.py", line 156, in connect
    raise last_error
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/edgedb/blocking_con.py", line 147, in connect
    connection_class=BlockingIOConnection)
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/edgedb/blocking_con.py", line 94, in _connect_addr
    ) from e
edgedb.errors.ClientConnectionError: [Errno 2] No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket '/var/run/edgedb/.s.EDGEDB.admin.5656'?
root@pilaf:~# ls /var/run/edgedb/
ls: cannot access '/var/run/edgedb/': No such file or directory
root@pilaf:~# ls /var/log/edgedb
ls: cannot access '/var/log/edgedb': No such file or directory
```

**Comment by elprans** [comment]
Try `sudo systemctl start edgedb-1-alpha1`

**Comment by sfermigier** [comment]
Thanks. I see that you've corrected the tutorial too.
