### ISSUE TITLE
Tutorial fails using docker install

### ISSUE THREAD

**Issue by sfermigier** [edgedb/edgedb#611]
Edgedb seems to install OK using the docker method:

```
root@pilaf ~# docker run -it --rm -p 5656:5656 \
                          -v data:/var/lib/edgedb/data \
                          edgedb/edgedb
INFO 1 2019-04-11 21:10:05,150 edb.server: EdgeDB server (1.0.alpha.1) starting.
INFO 1 2019-04-11 21:10:05,791 edb.server: Initializing database cluster in /var/lib/edgedb/data
INFO 1 2019-04-11 21:10:08,354 edb.server: Creating template database...
INFO 1 2019-04-11 21:10:09,037 edb.server: Bootstrapping meta schema...
INFO 1 2019-04-11 21:10:29,461 edb.server: Creating database: edgedb
INFO 1 2019-04-11 21:10:30,543 edb.server: Restarting server to reload configuration...
INFO 1 2019-04-11 21:10:32,623 edb.server: Serving on 127.0.0.1:5656
INFO 1 2019-04-11 21:10:32,624 edb.server: Serving on /run/edgedb/.s.EDGEDB.5656
INFO 1 2019-04-11 21:10:32,624 edb.server: Serving admin on /run/edgedb/.s.EDGEDB.admin.5656
```

But then if I follow the tutorial:

```
root@pilaf:~# sudo -u edgedb edgedb --admin alter role edgedb --password
Traceback (most recent call last):
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/edgedb/blocking_con.py", line 88, in _connect_addr
    sock.connect(addr)
FileNotFoundError: [Errno 2] No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/bin/edgedb", line 11, in <module>
    sys.exit(cli())
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/edb/cli/mng.py", line 306, in alter
    connect(ctx)
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/edb/cli/mng.py", line 37, in connect
    admin=ctx.obj['admin'], password=ctx.obj['password'],
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/edgedb/blocking_con.py", line 156, in connect
    raise last_error
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/edgedb/blocking_con.py", line 147, in connect
    connection_class=BlockingIOConnection)
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/edgedb/blocking_con.py", line 94, in _connect_addr
    ) from e
edgedb.errors.ClientConnectionError: [Errno 2] No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket '/var/run/edgedb/.s.EDGEDB.admin.5656'?
```

and

```
root@pilaf:~# sudo -u edgedb edgedb -p 5656 -h localhost --admin alter role edgedb --password
Traceback (most recent call last):
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/bin/edgedb", line 11, in <module>
    sys.exit(cli())
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/edb/cli/mng.py", line 306, in alter
    connect(ctx)
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/edb/cli/mng.py", line 37, in connect
    admin=ctx.obj['admin'], password=ctx.obj['password'],
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/edgedb/blocking_con.py", line 137, in connect
    server_settings=None)
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/edgedb/con_utils.py", line 302, in parse_connect_arguments
    server_settings=server_settings,
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/edgedb/con_utils.py", line 257, in _parse_connect_dsn_and_args
    'admin connections are only supported over UNIX sockets')
root@pilaf:~# edgedb -p 5656 -h localhost
Could not establish connection to EdgeDB: [Errno 104] Connection reset by peer
```

**Comment by elprans** [comment]
Looks like the server isn't running on your host.  Try `sudo systemctl start edgedb-1-alpha1`

**Comment by sfermigier** [comment]
I'm talking about the docker install. I believe the issue has more to do with the fact that the socket lives in the docker container while the `edgedb` client lives in the host.

**Comment by elprans** [comment]
Yes, you need to bind mount the /var/run/edgedb folder and specify the host path with `-h`. Also make sure you have the correct permissions to write to the socket on the client side.

This is admittedly not very ergonomic. We need to figure out the usability vs security balance in the docker case.

**Comment by imichael** [comment]
I also found the instructions for using docker for the tutorial to be incomplete but what I did was to connect to the running container from another terminal as follows:

```
  $ sudo docker run -it --rm -p 5656:5656 -v data:/var/lib/edgedb/data edgedb/edgedb
  $ sudo docker ps # get the name of the running container

    CONTAINER ID        IMAGE               COMMAND ...
    8cf93a896817        edgedb/edgedb       "docker-entrypoint.s…"

  $ docker exec -it 8cf93a896817 /bin/bash 
  # now we're in the container...
  root@8cf93a896817:/# su edgedb
  edgedb@8cf93a896817:/$ edgedb --admin alter role edgedb --password
  Password:
  Repeat for confirmation:
  edgedb@8cf93a896817:/$ edgedb
  Password:
  EdgeDB 1.0.alpha.1
  Type "\?" for help.
  edgedb> create database tutorial;
  CREATE
  edgedb> \c tutorial
  tutorial>
```
  ... etc.

I was able to complete the tutorial up to the graphql section but then couldn't go any further because I couldn't figure out how to connect to the http server on port 8888. I get "The connection was reset" even after starting the edgedb container as follows:

`  > sudo docker run -it --rm -p 8888:8888 -p 5656:5656 -v data:/var/lib/edgedb/data edgedb/edgedb
`
I went on to try it in a CentOS VM. The glitch there was that the CentOS install instructions say to do this:

```
    sudo tee <<EOF /etc/yum.repos.d/edgedb.repo
    [edgedb]
    name=edgedb
    baseurl=https://packages.edgedb.com/rpm/el$releasever/
    enabled=1
    gpgcheck=1
    gpgkey=https://packages.edgedb.com/keys/edgedb.asc
    EOF
```

but $releasever isn't defined anywhere. On a hunch I tried "7" since I'm using a CentOS 7 VM and that worked.

**Comment by elprans** [comment]
> $releasever isn't defined anywhere.

There's an error in that snippet (heredoc should be quoted, so `$releasever` doesn't expand into an empty string).  I'll fix that.

> couldn't figure out how to connect to the http server on port 8888.

The tutorial uses '127.0.0.1' as the listen address for the GraphQL port, but that address does not get proxied by docker.  Replace it with '0.0.0.0', and things should work:

```
CONFIGURE SYSTEM INSERT Port {
    protocol := "graphql+http",
    database := "tutorial",
    address := "0.0.0.0",
    port := 8888,
    user := "http",
    concurrency := 4,
};
```

**Comment by imichael** [comment]
In case anyone ever runs into this again, when entering the above CONFIGURE SYSTEM... I initially got the error
`ConstraintViolationError: Port.port violates exclusivity constriant
`

Exploring the docs a little more I found I could do this:
`edgedb> configure system reset Port;
`
and then the CONFIGURE SYSTEM... given above worked.

**Comment by elprans** [comment]
I pushed an updated docker image that has trust auth by default.

**Comment by LeonardAukea** [comment]
@elprans  It's probably worth modifying the website (https://edgedb.com/download?distro=docker) as well, by adding the additional port to the docker run command. It's hard  to anticipate beforehand that another port is needed for graphql.

```

$ docker run -it --rm -p 5656:5656 -p 8888:8888 \
            -v <datadir>:/var/lib/edgedb/data \
            edgedb/edgedb
```

Very interesting project. When do  you think it will reach a  state of reliable use for real prod cases? 
Any idea when it will transition from `alpha`?

**Comment by elprans** [comment]
> Any idea when it will transition from alpha?

We plan to have a few more alphas with alpha 2 planned to be released in a couple weeks.
