### ISSUE TITLE
Unhandled exception when wrong link is used

### ISSUE THREAD

**Issue by steveazz** [edgedb/edgedb#617]
Hello, thank you for all the hard work put into this project, it looks very promising!

I'm not sure if this is a duplicate of some sort if so I apologize. I was following https://edgedb.com/docs/tutorial/queries#ref-tutorial-queries and did a mistake in my `INSERT` for `EdgeQL` by using the wrong link property, instead of `director` I used `directory` and I got the following stack trace:

```
tutorial> INSERT Movie {
.........     title := 'Blade Runner 2049',
.........     year := 2017,
.........     directory := (
.........         INSERT Person {
.........             first_name := 'Dennis',
.........             last_name := 'Villeneuve',
.........         }
.........     ),
.........     cast := {
.........         (INSERT Person {
.........             first_name := 'Harrison',
.........             last_name := 'Ford',
.........          }),
.........          (INSERT Person {
.........              first_name := 'Ryan',
.........              last_name := 'Gosling',
.........          }),
.........          (INSERT Person {
.........              first_name := 'Ana',
.........              last_name := 'de Armas',
.........          }),
.........    }
......... };
InvalidReferenceError: default::Movie has no link or property 'directory'
Traceback (most recent call last):
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/edb/repl/__init__.py", line 462, in run
    results.append(self.fetch(query, json=False))
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/edb/repl/__init__.py", line 383, in fetch
    result = meth(query)
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/edgedb/blocking_con.py", line 40, in fetchall
    query, args, kwargs)
  File "edgedb/protocol/blocking_proto.pyx", line 73, in edgedb.protocol.blocking_proto.BlockingIOProtocol.sync_execute_anonymous
  File "edgedb/protocol/blocking_proto.pyx", line 59, in edgedb.protocol.blocking_proto.BlockingIOProtocol._iter_coroutine
  File "edgedb/protocol/protocol.pyx", line 476, in execute_anonymous
  File "edgedb/protocol/protocol.pyx", line 189, in _parse
edgedb.errors.InvalidReferenceError: default::Movie has no link or property 'directory'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/bin/edgedb", line 11, in <module>
    sys.exit(cli())
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/edb/cli/__init__.py", line 70, in cli
    admin=admin,
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/edb/repl/__init__.py", line 573, in main
    return Cli(connect_kwargs).run()
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/edb/repl/__init__.py", line 477, in run
    render.render_exception(self.context, ex, query=last_query)
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/edb/repl/render.py", line 366, in render_exception
    exc_hint = exc_hint.decode()
AttributeError: 'str' object has no attribute 'decode'
```
I got compeltly logged out of the client after the stack trace.

OS: Ubuntu 18.04

**Comment by elprans** [comment]
Hi, @steveazz.  This has been fixed in 23c3941214f0.  Thanks for reporting!
