### ISSUE TITLE
Internal Server Error in `compile_ir_to_tree_and_sql`

### ISSUE THREAD

**Issue by XAMPPRocky** [edgedb/edgedb#6188]
- EdgeDB Version: 3.4
- EdgeDB CLI Version: N/A
- OS Version: macOS Sonoma (In docker container)

Steps to Reproduce:

1. Execute the following code

```rust
    let config = edgedb_tokio::Builder::new()
        // FIXME: remove once EdgeDB credentials and certificates have been set up
        .client_security(ClientSecurity::InsecureDevMode)
        .wait_until_available(DATABASE_TIMEOUT)
        // read DSN from config
        .dsn("<DSN>")
        .wrap_err("Failed to read database DSN")?
        .build_env()
        .await
        .wrap_err("Failed to build database client")?;

    let edgedb = edgedb_tokio::Client::new(&config);
    edgedb.ensure_connected()
        .await
        .wrap_err("Database not connected after client creation")?;
    let pipeline = edgedb
        .query_single::<BaseObject, _>(
            r#"
                with
                    action0 := (insert Action { wasm_module := (select WasmModule { url } filter .url = "ghcr.io/dynamite-video/src/hello") }),

                    initial_stage := (insert PipelineStage {
                        action := action0,
                        node_id := uuid_generate_v4(),
                    }),

                insert Pipeline {
                    name := "hello test pipeline",
                    stages := { initial_stage }
                }
            "#,
            &(),
        )
        .await
        .unwrap()
        .unwrap();

    let content_models =  edgedb
            .query::<BaseObject, _>(
                r#"
                    with

                        foo := (insert Property { name := "Foo", kind := <PropertyKind>'Text', order := 0 }),
                        bar := (insert Property { name := "Bar", kind := <PropertyKind>'Text', order := 2 }),
                        baz := (insert Property { name := "Baz", kind := <PropertyKind>'Asset', order := 1 }),

                        action0 := (insert Action { wasm_module := (select WasmModule { url } filter .url = "ghcr.io/dynamite-video/src/hello") }),

                        initial_stage := (insert PipelineStage {
                            action := action0,
                            node_id := uuid_generate_v4(),
                        }),

                        pipeline0 := (select Pipeline filter .id = <uuid>$0),

                    insert ContentModel {
                        name := "Test content model",
                        properties := {
                            foo, bar, baz
                        },
                        pipeline := pipeline0
                    }
                "#,
                &(pipeline.id,),
            )
            .await
    .unwrap();
```

Schema:
```edgeql
    type ContentModel {
        required name: str;
        required multi properties: Property;
        required pipeline: Pipeline;
    }

    type Property {
        required name: str;
        required kind: PropertyKind;
        required order: int64;
    }

    scalar type PropertyKind extending enum<Text, Asset, Relation>;
    scalar type RelationshipKind extending enum<OneToOne, OneToMany, ManyToMany>;

    type Relation {
        required parent: ContentModel;
        required child: ContentModel;
        required kind: RelationshipKind;
    }

    type PendingSagas {
        required pipeline: Pipeline;
        required data: json;
        instance: SagaInstance;
    }

    type Pipeline {
        required name: str;
        multi parameters: Parameter;
        required multi stages: PipelineStage;
    }

    type PipelineStage {
        required action: Action;
        required node_id: uuid;
        multi arguments: Argument;
        multi parents: PipelineStage;
    }

    type Argument {
        required parameter: Parameter;
        required kind: ArgumentKind;
        value: ArgumentVariant;
    }

    type Parameter {
        required name: str;
        required kind: ParameterKind;
    }

    scalar type ParameterKind extending enum<Text, Asset, Number, Date, Relation, Any, Collection, Map>;
    scalar type ArgumentKind extending enum<Constant, Dynamic, Mixed>;

    abstract type ArgumentVariant {}

    type ConstantArgument extending ArgumentVariant {
        required value: ParameterVariant;
    }

    type DynamicArgument extending ArgumentVariant {
        required pipeline: PipelineStage;
        required reference: Parameter;
    }

    type MixedArgument extending ArgumentVariant {
        required multi arguments: ArgumentVariant;
    }

    type Action {
        multi parameters: Parameter;
        multi return_types: Parameter;
        required wasm_module: WasmModule;
    }

    type Content {
        required model: ContentModel;
        required multi properties: PropertyInstance;
    }

    type PropertyInstance {
        required name: str;
        required value: PropertyValue;
        required property: Property;
    }

    abstract type PropertyValue;
    abstract type ParameterVariant;

    type DateTime extending PropertyValue, ParameterVariant {
        required inner: datetime;
    }

    type Text extending PropertyValue, ParameterVariant{
        required content: str;
        kind: DerivativeType;
    }

    type Asset extending PropertyValue, ParameterVariant{
        required url: str;
        kind: DerivativeType;
    }

    abstract type DerivativeType {
        required multi inner: Quality | Subscriber | Provider;
    }

    type Quality {}
    type Subscriber {
        multi derivatives: Asset;
    }

    type Provider {}

    type RelationInstance extending PropertyValue {
        required multi parent: Content;
        required multi child: Content;

        required single kind: RelationshipKind;

        required single property num_parent := count(.parent);
        required single property num_child := count(.child);

        # constraint expression on (
        #     (.num_parent = 1 AND .num_child = 1) IF .kind = RelationshipKind.OneToOne ELSE
        #     (.num_parent = 1 AND .num_child >= 1) IF .kind = RelationshipKind.OneToMany ELSE
        #     (.num_parent >= 1 AND .num_child >= 1) IF .kind = RelationshipKind.ManyToMany ELSE
        #     false
        # )
    }

    type WasmModule {
        required url: str {
            constraint exclusive;
        };
        required tags: array<str>;
    }

    ### SECSTORE ###

    scalar type SagaCachedState extending enum<Pending, Running, Unwinding, Done>;

    type SagaInstance {
        required name: str;
        required dag: json;
        required state: SagaCachedState;
    }

    type Event {
        required saga_instance: uuid;
        required node_id: str;
        required event_type: json;
    }
```

### Stack Trace
```
Traceback (most recent call last):
  File "/usr/lib/aarch64-linux-gnu/edgedb-server-3/lib/python3.11/site-packages/edb/pgsql/compiler/__init__.py", line 135, in compile_ir_to_sql_tree
    qtree = dispatch.compile(ir_expr, ctx=ctx)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/aarch64-linux-gnu/edgedb-server-3/lib/python3.11/functools.py", line 909, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/aarch64-linux-gnu/edgedb-server-3/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 60, in compile_Set
    _compile_set_impl(ir_set, ctx=ctx)
  File "/usr/lib/aarch64-linux-gnu/edgedb-server-3/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 115, in _compile_set_impl
    _compile_set(ir_set, ctx=ctx)
  File "/usr/lib/aarch64-linux-gnu/edgedb-server-3/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 701, in _compile_set
    relgen.get_set_rvar(ir_set, ctx=ctx)
  File "/usr/lib/aarch64-linux-gnu/edgedb-server-3/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 164, in get_set_rvar
    return _process_toplevel_query(ir_set, ctx=ctx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/aarch64-linux-gnu/edgedb-server-3/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 286, in _process_toplevel_query
    rvars = _get_set_rvar(ir_set, ctx=ctx)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/aarch64-linux-gnu/edgedb-server-3/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 348, in _get_set_rvar
    return process_set_as_subquery(ir_set, ctx=ctx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/aarch64-linux-gnu/edgedb-server-3/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 1425, in process_set_as_subquery
    dispatch.visit(expr, ctx=newctx)
  File "/usr/lib/aarch64-linux-gnu/edgedb-server-3/lib/python3.11/functools.py", line 909, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/aarch64-linux-gnu/edgedb-server-3/lib/python3.11/site-packages/edb/pgsql/compiler/dispatch.py", line 44, in visit
    compile(ir, ctx=ctx)
  File "/usr/lib/aarch64-linux-gnu/edgedb-server-3/lib/python3.11/functools.py", line 909, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/aarch64-linux-gnu/edgedb-server-3/lib/python3.11/site-packages/edb/pgsql/compiler/stmt.py", line 148, in compile_InsertStmt
    parts = dml.init_dml_stmt(stmt, ctx=ctx)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/aarch64-linux-gnu/edgedb-server-3/lib/python3.11/site-packages/edb/pgsql/compiler/dml.py", line 95, in init_dml_stmt
    clauses.compile_dml_bindings(ir_stmt, ctx=ctx)
  File "/usr/lib/aarch64-linux-gnu/edgedb-server-3/lib/python3.11/site-packages/edb/pgsql/compiler/clauses.py", line 251, in compile_dml_bindings
    dispatch.compile(binding, ctx=bctx)
  File "/usr/lib/aarch64-linux-gnu/edgedb-server-3/lib/python3.11/functools.py", line 909, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/aarch64-linux-gnu/edgedb-server-3/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 60, in compile_Set
    _compile_set_impl(ir_set, ctx=ctx)
  File "/usr/lib/aarch64-linux-gnu/edgedb-server-3/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 111, in _compile_set_impl
    _compile_set(ir_set, ctx=scopectx)
  File "/usr/lib/aarch64-linux-gnu/edgedb-server-3/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 701, in _compile_set
    relgen.get_set_rvar(ir_set, ctx=ctx)
  File "/usr/lib/aarch64-linux-gnu/edgedb-server-3/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 222, in get_set_rvar
    rvars = _get_set_rvar(ir_set, ctx=subctx)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/aarch64-linux-gnu/edgedb-server-3/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 348, in _get_set_rvar
    return process_set_as_subquery(ir_set, ctx=ctx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/aarch64-linux-gnu/edgedb-server-3/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 1425, in process_set_as_subquery
    dispatch.visit(expr, ctx=newctx)
  File "/usr/lib/aarch64-linux-gnu/edgedb-server-3/lib/python3.11/functools.py", line 909, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/aarch64-linux-gnu/edgedb-server-3/lib/python3.11/site-packages/edb/pgsql/compiler/dispatch.py", line 44, in visit
    compile(ir, ctx=ctx)
  File "/usr/lib/aarch64-linux-gnu/edgedb-server-3/lib/python3.11/functools.py", line 909, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/aarch64-linux-gnu/edgedb-server-3/lib/python3.11/site-packages/edb/pgsql/compiler/stmt.py", line 156, in compile_InsertStmt
    dml.process_insert_body(
  File "/usr/lib/aarch64-linux-gnu/edgedb-server-3/lib/python3.11/site-packages/edb/pgsql/compiler/dml.py", line 691, in process_insert_body
    external_inserts = process_insert_shape(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/aarch64-linux-gnu/edgedb-server-3/lib/python3.11/site-packages/edb/pgsql/compiler/dml.py", line 1017, in process_insert_shape
    compile_insert_shape_element(
  File "/usr/lib/aarch64-linux-gnu/edgedb-server-3/lib/python3.11/site-packages/edb/pgsql/compiler/dml.py", line 1090, in compile_insert_shape_element
    dispatch.visit(shape_el, ctx=insvalctx)
  File "/usr/lib/aarch64-linux-gnu/edgedb-server-3/lib/python3.11/functools.py", line 909, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/aarch64-linux-gnu/edgedb-server-3/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 85, in visit_Set
    _compile_set_impl(ir_set, ctx=ctx)
  File "/usr/lib/aarch64-linux-gnu/edgedb-server-3/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 111, in _compile_set_impl
    _compile_set(ir_set, ctx=scopectx)
  File "/usr/lib/aarch64-linux-gnu/edgedb-server-3/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 701, in _compile_set
    relgen.get_set_rvar(ir_set, ctx=ctx)
  File "/usr/lib/aarch64-linux-gnu/edgedb-server-3/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 222, in get_set_rvar
    rvars = _get_set_rvar(ir_set, ctx=subctx)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/aarch64-linux-gnu/edgedb-server-3/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 348, in _get_set_rvar
    return process_set_as_subquery(ir_set, ctx=ctx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/aarch64-linux-gnu/edgedb-server-3/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 1425, in process_set_as_subquery
    dispatch.visit(expr, ctx=newctx)
  File "/usr/lib/aarch64-linux-gnu/edgedb-server-3/lib/python3.11/functools.py", line 909, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/aarch64-linux-gnu/edgedb-server-3/lib/python3.11/site-packages/edb/pgsql/compiler/dispatch.py", line 44, in visit
    compile(ir, ctx=ctx)
  File "/usr/lib/aarch64-linux-gnu/edgedb-server-3/lib/python3.11/functools.py", line 909, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/aarch64-linux-gnu/edgedb-server-3/lib/python3.11/site-packages/edb/pgsql/compiler/stmt.py", line 99, in compile_SelectStmt
    clauses.compile_filter_clause(
  File "/usr/lib/aarch64-linux-gnu/edgedb-server-3/lib/python3.11/site-packages/edb/pgsql/compiler/clauses.py", line 263, in compile_filter_clause
    assert cardinality != qltypes.Cardinality.UNKNOWN
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/aarch64-linux-gnu/edgedb-server-3/lib/python3.11/site-packages/edb/server/compiler_pool/worker.py", line 161, in compile
    units, cstate = COMPILER.compile(
                    ^^^^^^^^^^^^^^^^^
  File "/usr/lib/aarch64-linux-gnu/edgedb-server-3/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 856, in compile
    unit_group = compile(ctx=ctx, source=source)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/aarch64-linux-gnu/edgedb-server-3/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 2068, in compile
    return _try_compile(ctx=ctx, source=source)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/aarch64-linux-gnu/edgedb-server-3/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 2136, in _try_compile
    comp, capabilities = _compile_dispatch_ql(
                         ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/aarch64-linux-gnu/edgedb-server-3/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 2042, in _compile_dispatch_ql
    query = _compile_ql_query(ctx, ql, script_info=script_info)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/aarch64-linux-gnu/edgedb-server-3/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 1588, in _compile_ql_query
    qtree, sql_text, argmap = pg_compiler.compile_ir_to_tree_and_sql(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/aarch64-linux-gnu/edgedb-server-3/lib/python3.11/site-packages/edb/pgsql/compiler/__init__.py", line 170, in compile_ir_to_tree_and_sql
    qtree, _, argmap = compile_ir_to_sql_tree(
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/aarch64-linux-gnu/edgedb-server-3/lib/python3.11/site-packages/edb/pgsql/compiler/__init__.py", line 152, in compile_ir_to_sql_tree
    raise errors.InternalServerError(*args) from e
edb.errors.InternalServerError: None
```

**Comment by aljazerzen** [comment]
Minimal reproducible example:

```
configure current database set allow_bare_ddl := 'AlwaysAllow';

CREATE TYPE default::WasmModule {
    CREATE PROPERTY flag: std::bool;
};
CREATE TYPE default::Action {
    CREATE LINK wasm_module: default::WasmModule;
};
CREATE TYPE default::ContentModel;

with
    action := (insert Action { wasm_module := (select WasmModule filter .flag limit 1) })
insert ContentModel;
```

Already fixed in dda894252, released as 3.4 and 4.0
