### ISSUE TITLE
InternalServerError: AssertionError:

### ISSUE THREAD

**Issue by Gobot1234** [edgedb/edgedb#6334]
- EdgeDB Version: 3.4+6d5921b
- EdgeDB CLI Version: 3.5.0+e1ad387
- OS Version: macOS

Steps to Reproduce:

1. Download attached schema and place in dbschema folder
2. Run edgedb watch.
3. Observe error 
   ```
   Schema migration error: InternalServerError: AssertionError: 
   Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at 
   https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
   Initialized. Monitoring "/Users/James/Programming/anvil-iforge-ts".
   ```

I'm not really sure what's causing it, there's probably an error in the schema. But a nicer message would be appreciated.

Schema:
(.txts so I could upload them they're really esdls)
[3dp.txt](https://github.com/edgedb/edgedb/files/13059239/3dp.txt)
[auth.txt](https://github.com/edgedb/edgedb/files/13059240/auth.txt)
[default.txt](https://github.com/edgedb/edgedb/files/13059241/default.txt)
[event.txt](https://github.com/edgedb/edgedb/files/13059242/event.txt)
[notification.txt](https://github.com/edgedb/edgedb/files/13059243/notification.txt)
[sign_in.txt](https://github.com/edgedb/edgedb/files/13059244/sign_in.txt)
[team.txt](https://github.com/edgedb/edgedb/files/13059245/team.txt)
[training.txt](https://github.com/edgedb/edgedb/files/13059246/training.txt)
[users.txt](https://github.com/edgedb/edgedb/files/13059247/users.txt)

**Comment by Gobot1234** [comment]
Sorry, just realised this isn't in the right repo. Please can someone transfer it to https://github.com/edgedb/edgedb-cli?

**Comment by raddevon** [comment]
I believe all InternalServerError errors originate from the compiler, so this is probably the correct repo after all. Thank you!

**Comment by Gobot1234** [comment]
Is there a way I can start to debug this are there flags to show full tracebacks or do I need to compile everything myself with the traceback in full?

**Comment by elprans** [comment]
You can run your server instance in foreground like so:

```
env EDGEDB_SERVER_LOG_LEVEL=d EDGEDB_DEBUG_SERVER=1 edgedb instance start --auto-restart --foreground -I <your instance>
```

and observe tracebacks.

**Comment by Gobot1234** [comment]
Thanks, it appears like edgedb is compiled (using mypyc if I had to guess) because line numbers aren't matching up after adding debug prints. Anyways the full error is:
```
      Traceback (most recent call last):
        File "/Users/James/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/server/compiler_pool/worker.py", line 161, in compile
          units, cstate = COMPILER.compile(
                          ^^^^^^^^^^^^^^^^^
        File "/Users/James/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 856, in compile
          unit_group = compile(ctx=ctx, source=source)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/James/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 2068, in compile
          return _try_compile(ctx=ctx, source=source)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/James/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 2136, in _try_compile
          comp, capabilities = _compile_dispatch_ql(
                               ^^^^^^^^^^^^^^^^^^^^^
        File "/Users/James/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 1975, in _compile_dispatch_ql
          query = ddl.compile_dispatch_ql_migration(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/James/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/server/compiler/ddl.py", line 382, in compile_dispatch_ql_migration
          return _start_migration(ctx, ql, in_script)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/James/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/server/compiler/ddl.py", line 463, in _start_migration
          target_schema = s_ddl.apply_sdl(
                          ^^^^^^^^^^^^^^^^
        File "/Users/James/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/schema/ddl.py", line 524, in apply_sdl
          process(ddl_stmt)
        File "/Users/James/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/schema/ddl.py", line 511, in process
          target_schema = delta.apply(target_schema, context)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/James/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/schema/delta.py", line 1553, in apply
          schema = self.apply_subcommands(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/James/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/schema/delta.py", line 1580, in apply_subcommands
          schema = objop.apply(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/James/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/schema/delta.py", line 3529, in apply
          schema = self._alter_innards(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/James/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/schema/delta.py", line 3161, in _alter_innards
          return self.apply_subcommands(schema, context)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/James/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/schema/delta.py", line 951, in apply_subcommands
          schema = op.apply(schema, context=context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/James/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/schema/delta.py", line 3529, in apply
          schema = self._alter_innards(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/James/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/schema/delta.py", line 3161, in _alter_innards
          return self.apply_subcommands(schema, context)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/James/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/schema/delta.py", line 951, in apply_subcommands
          schema = op.apply(schema, context=context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/James/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/schema/delta.py", line 3529, in apply
          schema = self._alter_innards(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/James/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/schema/delta.py", line 3161, in _alter_innards
          return self.apply_subcommands(schema, context)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/James/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/schema/delta.py", line 951, in apply_subcommands
          schema = op.apply(schema, context=context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/James/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/schema/delta.py", line 3060, in apply
          schema = self._create_begin(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/James/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/schema/referencing.py", line 1094, in _create_begin
          return super()._create_begin(schema, context)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/James/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/schema/referencing.py", line 660, in _create_begin
          schema = super()._create_begin(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/James/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/schema/inheriting.py", line 746, in _create_begin
          schema = super()._create_begin(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/James/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/schema/delta.py", line 2941, in _create_begin
          schema = self.canonicalize_attributes(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/James/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/schema/rewrites.py", line 108, in canonicalize_attributes
          field=Rewrite.get_field(field),
        File "/Users/James/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/schema/rewrites.py", line 139, in compile_expr_field
          assert isinstance(source, s_types.Type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AssertionError
```

**Comment by aljazerzen** [comment]
@Gobot1234 what you probably want is the use defaults instead of insert rewrites on link properties.

Problematic links:
- `users::User.referrals`
- `notification::Announcement.views`
- `event::Event.attendees`

**Comment by aljazerzen** [comment]
Closing this, as both issues (ISE and the lack of rewrites on link properties) are tracked elsewhere.
