### ISSUE TITLE
UnresolvedReferenceError: reference to an undefined item 

### ISSUE THREAD

**Issue by haikyuu** [edgedb/edgedb#6336]
- EdgeDB Version:'3.4+6d5921b'
- EdgeDB CLI Version:EdgeDB CLI 3.5.0+e1ad387
- OS Version: macos

Error in watch mode
```
InternalServerError: UnresolvedReferenceError: reference to an undefined item default::PublishActivity@object in default::AObject@published_at
```

Error with stacktrace in migration create

```
e migration create
edgedb error: InternalServerError: UnresolvedReferenceError: reference to an undefined item default::PublishActivity@object in default::AObject@published_at
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "/Users/abdellah/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/server/compiler_pool/worker.py", line 186, in compile_in_tx
          units, cstate = COMPILER.compile_in_tx(cstate, *args, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/abdellah/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 913, in compile_in_tx
          return compile(ctx=ctx, source=source), ctx.state
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/abdellah/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 2068, in compile
          return _try_compile(ctx=ctx, source=source)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/abdellah/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 2136, in _try_compile
          comp, capabilities = _compile_dispatch_ql(
                               ^^^^^^^^^^^^^^^^^^^^^
        File "/Users/abdellah/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 1975, in _compile_dispatch_ql
          query = ddl.compile_dispatch_ql_migration(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/abdellah/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/server/compiler/ddl.py", line 382, in compile_dispatch_ql_migration
          return _start_migration(ctx, ql, in_script)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/abdellah/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/server/compiler/ddl.py", line 463, in _start_migration
          target_schema = s_ddl.apply_sdl(
                          ^^^^^^^^^^^^^^^^
        File "/Users/abdellah/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/schema/ddl.py", line 520, in apply_sdl
          ddl_stmts = s_decl.sdl_to_ddl(target_schema, documents)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/abdellah/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/edgeql/declarative.py", line 476, in sdl_to_ddl
          ordered = topological.sort(ddlgraph, allow_unresolved=False)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/abdellah/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/common/topological.py", line 197, in sort
          items = sort_ex(graph, allow_unresolved=allow_unresolved)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/abdellah/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/common/topological.py", line 121, in sort_ex
          raise UnresolvedReferenceError(
      edb.common.topological.UnresolvedReferenceError: reference to an undefined item default::PublishActivity@object in default::AObject@published_at

```
Steps to Reproduce:
1.
2.

Schema:
```
type Actor {
        name: str
}
abstract type AObject {
    required link author: Actor;
    published_at := (.<object[is PublishActivity]).date;
}

type Post extending AObject {
        required content: str;
}
 abstract type Activity {
        required link actor: Actor; 
        required link object: AObject | Activity;
 }
type PublishActivity extending Activity {
    date: datetime {
	    default := datetime_of_statement();
    };
}
```

**Comment by msullivan** [comment]
On 4.2 it instead fails with a real error, but it seems bogus:
```
error: InvalidReferenceError: 'default::Post.<object' does not resolve to any known path
  ┌─ <query>:1:1
  │
1 │ start migration to {                          
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ error
```
