### ISSUE TITLE
Windows - Docker | Can't seem to fully initialize EdgeDB instance (1.0.alpha.1)

### ISSUE THREAD

**Issue by chrizzFTD** [edgedb/edgedb#638]
Hello MagicStack team,

I'm excited to test EdgeDB alpha1!

On windows 10, installing EdgeDB via docker as described on the [download documentation](https://edgedb.com/download?distro=docker), running the container on **step 2** leaves the console hanging. This is all I see:

```
A:\write\sandbox\edgedb\19042701>docker --version
Docker version 18.09.2, build 6247962
A:\write\sandbox\edgedb\19042701>docker run -it --rm -v /var/tmp/edb01:/var/lib/edgedb/data23 edgedb/edgedb
Bootstrapping EdgeDB instance...
CONFIGURE SYSTEM
CONFIGURE SYSTEM
INFO 1 2019-04-27 07:40:44,915 edb.server: EdgeDB server (1.0.alpha.1) starting.
INFO 1 2019-04-27 07:40:47,638 edb.server: Serving on 0.0.0.0:5656
INFO 1 2019-04-27 07:40:47,638 edb.server: Serving on /run/edgedb/.s.EDGEDB.5656
INFO 1 2019-04-27 07:40:47,639 edb.server: Serving admin on /run/edgedb/.s.EDGEDB.admin.5656
```

And it hangs forever until I `ctrl+C`, which then logs the following stack trace:

<details>
  <summary>Click to see log</summary>

```
INFO 1 2019-04-27 07:40:47,639 edb.server: Serving admin on /run/edgedb/.s.EDGEDB.admin.5656





^CTraceback (most recent call last):
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/edb/server/procpool/worker.py", line 151, in <module>
    main()
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/edb/server/procpool/worker.py", line 145, in main
    run_worker(cls, cls_args, args.sockname)
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/edb/server/procpool/worker.py", line 105, in run_worker
    asyncio.run(worker(cls, cls_args, sockname))
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1445, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1438, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1347, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 487, in uvloop.loop.Loop._run
  File "uvloop/handles/poll.pyx", line 214, in uvloop.loop.__on_uvpoll_event
  File "uvloop/cbhandles.pyx", line 71, in uvloop.loop.Handle._run
  File "uvloop/loop.pyx", line 327, in uvloop.loop.Loop._read_from_self
  File "uvloop/loop.pyx", line 332, in uvloop.loop.Loop._invoke_signals
  File "uvloop/loop.pyx", line 307, in uvloop.loop.Loop._ceval_process_signals
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/runpy.py", line 193, in _run_module_as_main
============================================================================================================ Exception occurred =============================================================================================================

1. KeyboardInterrupt:

----------------------------------------------------------------------------------------------------------------- Traceback -----------------------------------------------------------------------------------------------------------------

    uvloop/handles/stream.pyx, line 767, in uvloop.loop.__uv_stream_on_read_common

    uvloop/handles/stream.pyx, line 613, in uvloop.loop.UVStream._on_eof

    /usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/asyncio/protocols.py, line 96, in eof_received
        > def eof_received(self):

KeyboardInterrupt:
ERROR 1 2019-04-27 08:00:31,541 asyncio: Fatal error on transport UnixTransport
protocol: <edb.server.procpool.amsg.HubProtocol object at 0x7f42b5b33860>
transport: <UnixTransport closed=False reading=False 0x7f42b74e06c8>
Traceback (most recent call last):
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/runpy.py", line 85, in _run_code
    "__main__", mod_spec)
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/edb/server/procpool/worker.py", line 151, in <module>
    exec(code, run_globals)
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/edb/server/procpool/worker.py", line 151, in <module>
Traceback (most recent call last):
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    main()
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/edb/server/procpool/worker.py", line 145, in main
    main()
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/edb/server/procpool/worker.py", line 145, in main
    "__main__", mod_spec)
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/runpy.py", line 85, in _run_code
    run_worker(cls, cls_args, args.sockname)
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/edb/server/procpool/worker.py", line 105, in run_worker
    run_worker(cls, cls_args, args.sockname)
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/edb/server/procpool/worker.py", line 105, in run_worker
    asyncio.run(worker(cls, cls_args, sockname))
    exec(code, run_globals)
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/edb/server/procpool/worker.py", line 151, in <module>
    asyncio.run(worker(cls, cls_args, sockname))
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/asyncio/runners.py", line 43, in run
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1445, in uvloop.loop.Loop.run_until_complete
    main()
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1445, in uvloop.loop.Loop.run_until_complete
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/edb/server/procpool/worker.py", line 145, in main
    run_worker(cls, cls_args, args.sockname)
  File "uvloop/loop.pyx", line 1438, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1438, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1347, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 1347, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 487, in uvloop.loop.Loop._run
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/edb/server/procpool/worker.py", line 105, in run_worker
  File "uvloop/loop.pyx", line 487, in uvloop.loop.Loop._run
    asyncio.run(worker(cls, cls_args, sockname))
  File "uvloop/handles/poll.pyx", line 214, in uvloop.loop.__on_uvpoll_event
  File "uvloop/cbhandles.pyx", line 71, in uvloop.loop.Handle._run
  File "uvloop/handles/poll.pyx", line 214, in uvloop.loop.__on_uvpoll_event
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/asyncio/runners.py", line 43, in run
  File "uvloop/loop.pyx", line 327, in uvloop.loop.Loop._read_from_self
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1445, in uvloop.loop.Loop.run_until_complete
  File "uvloop/cbhandles.pyx", line 71, in uvloop.loop.Handle._run
  File "uvloop/loop.pyx", line 327, in uvloop.loop.Loop._read_from_self
  File "uvloop/loop.pyx", line 332, in uvloop.loop.Loop._invoke_signals
  File "uvloop/loop.pyx", line 307, in uvloop.loop.Loop._ceval_process_signals
  File "uvloop/loop.pyx", line 332, in uvloop.loop.Loop._invoke_signals
  File "uvloop/loop.pyx", line 1438, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 307, in uvloop.loop.Loop._ceval_process_signals
KeyboardInterrupt
  File "uvloop/loop.pyx", line 1347, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 487, in uvloop.loop.Loop._run
KeyboardInterrupt
  File "uvloop/handles/poll.pyx", line 214, in uvloop.loop.__on_uvpoll_event
  File "uvloop/cbhandles.pyx", line 71, in uvloop.loop.Handle._run
  File "uvloop/loop.pyx", line 327, in uvloop.loop.Loop._read_from_self
  File "uvloop/loop.pyx", line 332, in uvloop.loop.Loop._invoke_signals
  File "uvloop/loop.pyx", line 307, in uvloop.loop.Loop._ceval_process_signals
KeyboardInterrupt
^CINFO 1 2019-04-27 08:00:32,917 edb.server: Shutting down.
============================================== Exception occurred: pg_ctl stop exited with status 1: pg_ctl: PID file "/var/lib/edgedb/data/postmaster.pid" does not exist
Is server running?
 ==============================================

1. asyncpg.cluster.ClusterError: pg_ctl stop exited with status 1: pg_ctl: PID file "/var/lib/edgedb/data/postmaster.pid" does not exist
Is server running?


----------------------------------------------------------------------------------------------------------------- Traceback -----------------------------------------------------------------------------------------------------------------

    /usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/bin/edgedb-server, line 11, in <module>
        > sys.exit(main())
    /usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/click/core.py, line 722, in __call__
        > return self.main(*args, **kwargs)
    /usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/click/core.py, line 697, in main
        > rv = self.invoke(ctx)
    /usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/click/core.py, line 895, in invoke
        > return ctx.invoke(self.callback, **ctx.params)
    /usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/click/core.py, line 535, in invoke
        > return callback(*args, **kwargs)
    /usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/edb/server/main.py, line 416, in main
        > server_main(**kwargs)
    /usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/edb/server/main.py, line 408, in server_main
        > run_server(kwargs)
    /usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/edb/server/main.py, line 310, in run_server
        > cluster.stop()
    /usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/site-packages/asyncpg/cluster.py, line 268, in stop
        > process.returncode, stderr.decode()))

asyncpg.cluster.ClusterError: pg_ctl stop exited with status 1: pg_ctl: PID file "/var/lib/edgedb/data/postmaster.pid" does not exist
Is server running?
```
</details>

I have tried different values for `-v` and `-p` and a `Git Bash` console without any luck

```bash
Christian@ChristianLT MINGW64 /a/write/sandbox/edgedb/19042701
$ docker run -it --rm -p 5656:5656 -v /${PWD}:/var/lib/edgedb/data edgedb/edgedb
Bootstrapping EdgeDB instance...
CONFIGURE SYSTEM
CONFIGURE SYSTEM
INFO 1 2019-04-27 08:20:58,843 edb.server: EdgeDB server (1.0.alpha.1) starting.
INFO 1 2019-04-27 08:21:02,578 edb.server: Serving on 0.0.0.0:5656
INFO 1 2019-04-27 08:21:02,579 edb.server: Serving on /run/edgedb/.s.EDGEDB.5656
INFO 1 2019-04-27 08:21:02,580 edb.server: Serving admin on /run/edgedb/.s.EDGEDB.admin.5656
^CFatal error on transport UnixTransport
protocol: <edb.server.procpool.amsg.WorkerProtocol object at 0x7ff4f309b198>
transport: <UnixTransport closed=False reading=False 0x7ff4ef4f7ba8>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 767, in uvloop.loop.__uv_stream_on_read_common
  File "uvloop/handles/stream.pyx", line 613, in uvloop.loop.UVStream._on_eof
  File "/usr/lib/x86_64-linux-gnu/edgedb-1-alpha1/lib/python3.7/asyncio/protocols.py", line 96, in eof_received
    def eof_received(self):
KeyboardInterrupt
INFO 1 2019-04-27 08:25:04,145 edb.server: Shutting down.
```
___
If I start the edgedb-preview image that I have downloaded previously, that still works:

```
A:\write\sandbox\edgedb\19042701>docker run -it --rm -v edgedb_data:/data edgedb/edgedb-preview
INFO 32 2019-04-27 07:29:44,891 edgedb.server: EdgeDB server starting.
INFO 32 2019-04-27 07:29:46,370 edgedb.server: Serving on 0.0.0.0:5656
edgedb> quit
INFO 32 2019-04-27 07:29:50,146 edgedb.server: Shutting down.
```
Any ideas on what could be happening?

**Comment by elprans** [comment]
This is actually working as intended.  Unlike the `edgedb-preview` image, the new image starts the server in the foreground by default (as is the norm for server Docker images).  To open the EdgeDB shell, you need to start it explicitly in another container.

To do this, give a known name to the sever container, like so:

```
docker run -it --rm -v /var/tmp/edb01:/var/lib/edgedb/data --name=edgedb-server edgedb/edgedb
```

Then, start EdgeDB shell in another container, linking to the server container:

```
docker run --link=edgedb-server --rm -it edgedb/edgedb:latest edgedb -u edgedb -h edgedb-server
```

**Comment by chrizzFTD** [comment]
Ahh, perfect! Linking like that works properly,  I was not aware of that difference from the preview; thanks a lot for the help, @elprans!
Closing this now.

**Comment by haikyuu** [comment]
@elprans that's very useful thanks. It should be added to the docs ;)
