### ISSUE TITLE
Database wipe fails due to attempt to alter link and possibly more than one element returned

### ISSUE THREAD

**Issue by Dhghomon** [edgedb/edgedb#6439]
Note: originally reported by a user here https://discord.com/channels/841451783728529451/849377751370432573/1170711514773209150 and I'm seeing the same output.

- EdgeDB Version: 4.0+d568f08
- EdgeDB CLI Version:  4.0.0+92e6888
- OS Version: Windows 11

Steps to Reproduce:

1. Create a database with this schema and migrate. Migration will work.

```
    abstract type Timestamped;
    type User;

    type Survey extending Timestamped {
    required name: str;
    description: str;
    single link surveyOrder := .<survey[is SurveyOrder];
    link surveyResponse :=  .<survey[is SurveyResponse];
  }

  type SurveyOrder extending Timestamped {
    required questionOrder: int32;
    required survey: Survey {
    constraint exclusive;
  }
    question: Question;
  }

  scalar type QuestionType extending enum<'Truthy', 'MultipleChoice', 'Text'>;

  type Question extending Timestamped {
    required question: str;
    required questionType: QuestionType;
    link option:= .<question[is QuestionOption];
    # single link correctAnswer := .<question[is QuestionOption];
  }
  
  type QuestionOption extending Timestamped {
    required option: str;
    required optionOrder: int32;
    required question: Question;
  }

  type Answer extending Timestamped {
    required answer: str;
    required question: Question;
    required surveyResponse: SurveyResponse;

  }
  
  type SurveyResponse extending Timestamped {
    totalScore: int32;
    maxScore: int32;
    required survey: Survey;
    link answer:=  .<surveyResponse[is Answer];
    required user: User; 
  }
```

2. `edgedb database wipe`, which produces the following error:

```
edgedb error: SchemaDefinitionError: cannot alter link 'survey' of object type 'default::SurveyOrder' because this affects expression of link 'surveyOrder' of object type 'default::Survey'
  Detail: possibly more than one element returned by an expression for the computed link 'surveyOrder' of object type 'default::Survey' explicitly declared as 'single'
  Server traceback:
      Traceback (most recent call last):
        File "/home/edgedb/.local/share/edgedb/portable/4.0/lib/python3.11/site-packages/edb/schema/delta.py", line 2224, in _finalize_affected_refs
          schema = delta.apply(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/edgedb/.local/share/edgedb/portable/4.0/lib/python3.11/site-packages/edb/schema/delta.py", line 1192, in apply
          schema = self.apply_subcommands(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/edgedb/.local/share/edgedb/portable/4.0/lib/python3.11/site-packages/edb/schema/delta.py", line 976, in apply_subcommands
          schema = op.apply(schema, context=context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/edgedb/.local/share/edgedb/portable/4.0/lib/python3.11/site-packages/edb/schema/delta.py", line 3574, in apply
          schema = self._alter_innards(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/edgedb/.local/share/edgedb/portable/4.0/lib/python3.11/site-packages/edb/schema/delta.py", line 3248, in _alter_innards
          return self.apply_subcommands(schema, context)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/edgedb/.local/share/edgedb/portable/4.0/lib/python3.11/site-packages/edb/schema/delta.py", line 976, in apply_subcommands
          schema = op.apply(schema, context=context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/edgedb/.local/share/edgedb/portable/4.0/lib/python3.11/site-packages/edb/schema/delta.py", line 3573, in apply
          schema = self._alter_begin(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/edgedb/.local/share/edgedb/portable/4.0/lib/python3.11/site-packages/edb/schema/pointers.py", line 2102, in _alter_begin
          schema = super()._alter_begin(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/edgedb/.local/share/edgedb/portable/4.0/lib/python3.11/site-packages/edb/schema/inheriting.py", line 916, in _alter_begin
          schema = super()._alter_begin(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/edgedb/.local/share/edgedb/portable/4.0/lib/python3.11/site-packages/edb/schema/delta.py", line 3236, in _alter_begin
          schema = self.canonicalize_attributes(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/edgedb/.local/share/edgedb/portable/4.0/lib/python3.11/site-packages/edb/schema/pointers.py", line 2162, in canonicalize_attributes
          schema = super().canonicalize_attributes(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/edgedb/.local/share/edgedb/portable/4.0/lib/python3.11/site-packages/edb/schema/pointers.py", line 1180, in canonicalize_attributes
          schema, inf_target_ref, base = self._parse_computable(
                                         ^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/edgedb/.local/share/edgedb/portable/4.0/lib/python3.11/site-packages/edb/schema/pointers.py", line 1412, in _parse_computable
          raise errors.SchemaDefinitionError(
      edb.errors.SchemaDefinitionError: possibly more than one element returned by an expression for the computed link 'surveyOrder' of object type 'default::Survey' explicitly declared as 'single'

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "/home/edgedb/.local/share/edgedb/portable/4.0/lib/python3.11/site-packages/edb/server/compiler_pool/worker.py", line 178, in compile
          units, cstate = COMPILER.compile(
                          ^^^^^^^^^^^^^^^^^
        File "/home/edgedb/.local/share/edgedb/portable/4.0/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 885, in compile
          unit_group = compile(ctx=ctx, source=source)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/edgedb/.local/share/edgedb/portable/4.0/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 2308, in compile
          return _try_compile(ctx=ctx, source=source)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/edgedb/.local/share/edgedb/portable/4.0/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 2369, in _try_compile
          comp, capabilities = _compile_dispatch_ql(
                               ^^^^^^^^^^^^^^^^^^^^^
        File "/home/edgedb/.local/share/edgedb/portable/4.0/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 2214, in _compile_dispatch_ql
          query = ddl.compile_dispatch_ql_migration(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/edgedb/.local/share/edgedb/portable/4.0/lib/python3.11/site-packages/edb/server/compiler/ddl.py", line 410, in compile_dispatch_ql_migration
          return _reset_schema(ctx, ql)
                 ^^^^^^^^^^^^^^^^^^^^^^
        File "/home/edgedb/.local/share/edgedb/portable/4.0/lib/python3.11/site-packages/edb/server/compiler/ddl.py", line 1138, in _reset_schema
          ddl_query = compile_and_apply_ddl_stmt(ctx, create_mig)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/edgedb/.local/share/edgedb/portable/4.0/lib/python3.11/site-packages/edb/server/compiler/ddl.py", line 118, in compile_and_apply_ddl_stmt
          delta = s_ddl.delta_from_ddl(
                  ^^^^^^^^^^^^^^^^^^^^^
        File "/home/edgedb/.local/share/edgedb/portable/4.0/lib/python3.11/site-packages/edb/schema/ddl.py", line 649, in delta_from_ddl
          _, cmd = _delta_from_ddl(
                   ^^^^^^^^^^^^^^^^
        File "/home/edgedb/.local/share/edgedb/portable/4.0/lib/python3.11/site-packages/edb/schema/ddl.py", line 696, in _delta_from_ddl
          schema = cmd.apply(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/edgedb/.local/share/edgedb/portable/4.0/lib/python3.11/site-packages/edb/schema/delta.py", line 3151, in apply
          schema = self._create_innards(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/edgedb/.local/share/edgedb/portable/4.0/lib/python3.11/site-packages/edb/schema/delta.py", line 3119, in _create_innards
          return self.apply_subcommands(schema, context)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/edgedb/.local/share/edgedb/portable/4.0/lib/python3.11/site-packages/edb/schema/delta.py", line 976, in apply_subcommands
          schema = op.apply(schema, context=context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/edgedb/.local/share/edgedb/portable/4.0/lib/python3.11/site-packages/edb/schema/delta.py", line 3574, in apply
          schema = self._alter_innards(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/edgedb/.local/share/edgedb/portable/4.0/lib/python3.11/site-packages/edb/schema/delta.py", line 3248, in _alter_innards
          return self.apply_subcommands(schema, context)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/edgedb/.local/share/edgedb/portable/4.0/lib/python3.11/site-packages/edb/schema/delta.py", line 976, in apply_subcommands
          schema = op.apply(schema, context=context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/edgedb/.local/share/edgedb/portable/4.0/lib/python3.11/site-packages/edb/schema/delta.py", line 3576, in apply
          schema = self._alter_finalize(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/edgedb/.local/share/edgedb/portable/4.0/lib/python3.11/site-packages/edb/schema/referencing.py", line 1261, in _alter_finalize
          schema = super()._alter_finalize(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/edgedb/.local/share/edgedb/portable/4.0/lib/python3.11/site-packages/edb/schema/delta.py", line 3255, in _alter_finalize
          schema = self._finalize_affected_refs(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/edgedb/.local/share/edgedb/portable/4.0/lib/python3.11/site-packages/edb/schema/delta.py", line 2238, in _finalize_affected_refs
          raise errors.SchemaDefinitionError(
      edb.errors.SchemaDefinitionError: cannot alter link 'survey' of object type 'default::SurveyOrder' because this affects expression of link 'surveyOrder' of object type 'default::Survey'
```

**Comment by tomnz** [comment]
Seeing something similar for `database wipe` under a different scenario:

```
module default {
  global currentUserId: uuid;
  required global currentIsAdmin := exists (
    select User filter .id = global currentUserId and .isAdmin
  );

  type User {
    required isAdmin: bool {
      default := false
    }

    required createdAt: datetime {
      default := datetime_of_transaction();
      readonly := true;
    };

    required link profile: user::Profile {
      constraint exclusive;
      on source delete delete target;
      default := (
        insert user::Profile {}
      )
    }

    access policy allHasInsertAccess
      allow insert;
    access policy ownerHasFullAccess
      allow all
      using (global currentUserId ?= .id);
    access policy adminHasFullAccess
      allow all
      using ((global currentIsAdmin) ?? false);
    access policy adminSetIsAdmin
      deny update write, insert
      using ((not global currentIsAdmin) and .isAdmin);
  }
}

module user {
  type Profile {
    link user := .<profile[is default::User];

    name: str;

    access policy allHasReadAccess
      allow select;
    access policy ownerHasFullAccess
      allow all
      using (global default::currentUserId ?= .user.id);
    access policy adminHasFullAccess
      allow all
      using ((global default::currentIsAdmin) ?? false);
  }
}
```

`edgedb database wipe` is failing with the following:

```
edgedb error: SchemaDefinitionError: cannot alter link 'profile' of object type 'default::User' because this affects expression of access policy 'ownerHasFullAccess' of object type 'user::Profile'
  Detail: possibly more than one element returned by using expression for the access policy 'ownerHasFullAccess' of object type 'user::Profile' 
  Server traceback:
      Traceback (most recent call last):
        File "/usr/lib/aarch64-linux-gnu/edgedb-server-4/lib/python3.11/site-packages/edb/schema/delta.py", line 2226, in _finalize_affected_refs
          schema = delta.apply(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/aarch64-linux-gnu/edgedb-server-4/lib/python3.11/site-packages/edb/schema/delta.py", line 1192, in apply
          schema = self.apply_subcommands(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/aarch64-linux-gnu/edgedb-server-4/lib/python3.11/site-packages/edb/schema/delta.py", line 976, in apply_subcommands
          schema = op.apply(schema, context=context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/aarch64-linux-gnu/edgedb-server-4/lib/python3.11/site-packages/edb/schema/delta.py", line 3577, in apply
          schema = self._alter_innards(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/aarch64-linux-gnu/edgedb-server-4/lib/python3.11/site-packages/edb/schema/delta.py", line 3251, in _alter_innards
          return self.apply_subcommands(schema, context)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/aarch64-linux-gnu/edgedb-server-4/lib/python3.11/site-packages/edb/schema/delta.py", line 976, in apply_subcommands
          schema = op.apply(schema, context=context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/aarch64-linux-gnu/edgedb-server-4/lib/python3.11/site-packages/edb/schema/delta.py", line 3576, in apply
          schema = self._alter_begin(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/aarch64-linux-gnu/edgedb-server-4/lib/python3.11/site-packages/edb/schema/policies.py", line 366, in _alter_begin
          schema = super()._alter_begin(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/aarch64-linux-gnu/edgedb-server-4/lib/python3.11/site-packages/edb/schema/inheriting.py", line 916, in _alter_begin
          schema = super()._alter_begin(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/aarch64-linux-gnu/edgedb-server-4/lib/python3.11/site-packages/edb/schema/delta.py", line 3239, in _alter_begin
          schema = self.canonicalize_attributes(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/aarch64-linux-gnu/edgedb-server-4/lib/python3.11/site-packages/edb/schema/policies.py", line 175, in canonicalize_attributes
          raise errors.SchemaDefinitionError(
      edb.errors.SchemaDefinitionError: possibly more than one element returned by using expression for the access policy 'ownerHasFullAccess' of object type 'user::Profile' 
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "/usr/lib/aarch64-linux-gnu/edgedb-server-4/lib/python3.11/site-packages/edb/server/compiler_pool/worker.py", line 178, in compile
          units, cstate = COMPILER.compile(
                          ^^^^^^^^^^^^^^^^^
        File "/usr/lib/aarch64-linux-gnu/edgedb-server-4/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 886, in compile
          unit_group = compile(ctx=ctx, source=source)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/aarch64-linux-gnu/edgedb-server-4/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 2316, in compile
          return _try_compile(ctx=ctx, source=source)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/aarch64-linux-gnu/edgedb-server-4/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 2377, in _try_compile
          comp, capabilities = _compile_dispatch_ql(
                               ^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/aarch64-linux-gnu/edgedb-server-4/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 2222, in _compile_dispatch_ql
          query = ddl.compile_dispatch_ql_migration(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/aarch64-linux-gnu/edgedb-server-4/lib/python3.11/site-packages/edb/server/compiler/ddl.py", line 410, in compile_dispatch_ql_migration
          return _reset_schema(ctx, ql)
                 ^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/aarch64-linux-gnu/edgedb-server-4/lib/python3.11/site-packages/edb/server/compiler/ddl.py", line 1138, in _reset_schema
          ddl_query = compile_and_apply_ddl_stmt(ctx, create_mig)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/aarch64-linux-gnu/edgedb-server-4/lib/python3.11/site-packages/edb/server/compiler/ddl.py", line 118, in compile_and_apply_ddl_stmt
          delta = s_ddl.delta_from_ddl(
                  ^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/aarch64-linux-gnu/edgedb-server-4/lib/python3.11/site-packages/edb/schema/ddl.py", line 649, in delta_from_ddl
          _, cmd = _delta_from_ddl(
                   ^^^^^^^^^^^^^^^^
        File "/usr/lib/aarch64-linux-gnu/edgedb-server-4/lib/python3.11/site-packages/edb/schema/ddl.py", line 696, in _delta_from_ddl
          schema = cmd.apply(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/aarch64-linux-gnu/edgedb-server-4/lib/python3.11/site-packages/edb/schema/delta.py", line 3154, in apply
          schema = self._create_innards(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/aarch64-linux-gnu/edgedb-server-4/lib/python3.11/site-packages/edb/schema/delta.py", line 3122, in _create_innards
          return self.apply_subcommands(schema, context)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/aarch64-linux-gnu/edgedb-server-4/lib/python3.11/site-packages/edb/schema/delta.py", line 976, in apply_subcommands
          schema = op.apply(schema, context=context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/aarch64-linux-gnu/edgedb-server-4/lib/python3.11/site-packages/edb/schema/delta.py", line 3577, in apply
          schema = self._alter_innards(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/aarch64-linux-gnu/edgedb-server-4/lib/python3.11/site-packages/edb/schema/delta.py", line 3251, in _alter_innards
          return self.apply_subcommands(schema, context)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/aarch64-linux-gnu/edgedb-server-4/lib/python3.11/site-packages/edb/schema/delta.py", line 976, in apply_subcommands
          schema = op.apply(schema, context=context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/aarch64-linux-gnu/edgedb-server-4/lib/python3.11/site-packages/edb/schema/delta.py", line 3579, in apply
          schema = self._alter_finalize(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/aarch64-linux-gnu/edgedb-server-4/lib/python3.11/site-packages/edb/schema/referencing.py", line 1261, in _alter_finalize
          schema = super()._alter_finalize(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/aarch64-linux-gnu/edgedb-server-4/lib/python3.11/site-packages/edb/schema/delta.py", line 3258, in _alter_finalize
          schema = self._finalize_affected_refs(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/aarch64-linux-gnu/edgedb-server-4/lib/python3.11/site-packages/edb/schema/delta.py", line 2241, in _finalize_affected_refs
          raise errors.SchemaDefinitionError(
      edb.errors.SchemaDefinitionError: cannot alter link 'profile' of object type 'default::User' because this affects expression of access policy 'ownerHasFullAccess' of object type 'user::Profile'
```
