### ISSUE TITLE
`AssertionError` on groupby + shape

### ISSUE THREAD

**Issue by jackfischer** [edgedb/edgedb#6481]
- EdgeDB Version: 3.5 and 4.1 
- EdgeDB CLI Version:4.0.2+500be79
- OS Version: macos 13

Steps to Reproduce:

1. Run the following query
```
select (
  group (
    select APA {org:=.user.organization}
  )
  by .org
) { }.apa;
```

```
edgedb error: InternalServerError: AssertionError:
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/server/compiler_pool/worker.py", line 178, in compile
          units, cstate = COMPILER.compile(
                          ^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 885, in compile
          unit_group = compile(ctx=ctx, source=source)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 2309, in compile
          return _try_compile(ctx=ctx, source=source)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 2370, in _try_compile
          comp, capabilities = _compile_dispatch_ql(
                               ^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 2283, in _compile_dispatch_ql
          query = _compile_ql_query(ctx, ql, script_info=script_info)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 1707, in _compile_ql_query
          ir = qlcompiler.compile_ast_to_ir(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Schema:
```
    type Organization {}

    type User {
        required link organization: Organization;
    }

    type APA {
        required link user: User;
        required property provider: str;
        required property createdDatetime: datetime {
            default := datetime_current();
        }
    }
```

**Comment by aljazerzen** [comment]
I'm not able to reproduce this.

I've created an empty project, migrated to your schema and ran the query. I've tried this on latest master and 4.1.

Can you re-check that is happening when you start in an empty project?
Alternatively, do you have the whole backtrace?

**Comment by jackfischer** [comment]
Yes, confirming that this happens on a fresh project on 4.1. Here is the whole backtrace

```
jack@Jacks-MacBook-Air ~/d/edgedbnov16> edgedb migration create
Created /Users/jack/dev/edgedbnov16/dbschema/migrations/00001.edgeql, id: m1n7fdfru4dkayv4uvarbkrwvc4qn2baom4nfvw67ejoqarr7mrjkq
jack@Jacks-MacBook-Air ~/d/edgedbnov16> edgedb migrate
Applied m1n7fdfru4dkayv4uvarbkrwvc4qn2baom4nfvw67ejoqarr7mrjkq (00001.edgeql)
jack@Jacks-MacBook-Air ~/d/edgedbnov16> edgedb
EdgeDB 4.1+0c628ea (repl 4.0.2+500be79)
Type \help for help, \quit to quit.
edgedbnov16:edgedb> select (
...................   group (
...................     select APA {org:=.user.organization}
...................   )
...................   by .org
................... ) { }.elements;
edgedb error: InternalServerError: AssertionError:
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/server/compiler_pool/worker.py", line 178, in compile
          units, cstate = COMPILER.compile(
                          ^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 885, in compile
          unit_group = compile(ctx=ctx, source=source)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 2309, in compile
          return _try_compile(ctx=ctx, source=source)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 2370, in _try_compile
          comp, capabilities = _compile_dispatch_ql(
                               ^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 2283, in _compile_dispatch_ql
          query = _compile_ql_query(ctx, ql, script_info=script_info)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 1707, in _compile_ql_query
          ir = qlcompiler.compile_ast_to_ir(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/edgeql/compiler/__init__.py", line 179, in wrapper
          return func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/edgeql/compiler/__init__.py", line 270, in compile_ast_to_ir
          ir_set = dispatch_mod.compile(tree, ctx=ctx)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/edgeql/compiler/stmt.py", line 128, in compile_SelectQuery
          stmt.result = compile_result_clause(
                        ^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/edgeql/compiler/stmt.py", line 1388, in compile_result_clause
          expr = dispatch.compile(result_expr, ctx=ectx)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/edgeql/compiler/expr.py", line 77, in compile_Path
          return stmt.maybe_add_view(setgen.compile_path(expr, ctx=ctx), ctx=ctx)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/edgeql/compiler/setgen.py", line 527, in compile_path
          path_tip = dispatch.compile(step, ctx=subctx)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/edgeql/compiler/stmt.py", line 1117, in compile_Shape
          expr = dispatch.compile(shape_expr, ctx=exposed_ctx)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/edgeql/compiler/stmt.py", line 428, in compile_GroupQuery
          return dispatch.compile(
                 ^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/edgeql/compiler/stmt.py", line 369, in compile_InternalGroupQuery
          viewgen.late_compile_view_shapes(stmt.group_binding, ctx=topctx)
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/edgeql/compiler/viewgen.py", line 2482, in _late_compile_view_shapes_in_set
          late_compile_view_shapes(
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/edgeql/compiler/viewgen.py", line 2399, in _late_compile_view_shapes_in_set
          shape_ptrs = _get_late_shape_configuration(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/edgeql/compiler/viewgen.py", line 2370, in _get_late_shape_configuration
          _get_shape_configuration_inner(
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/edgeql/compiler/viewgen.py", line 2287, in _get_shape_configuration_inner
          _inline_type_computable(
        File "/Users/jack/Library/Application Support/edgedb/portable/4.1/lib/python3.11/site-packages/edb/edgeql/compiler/viewgen.py", line 2142, in _inline_type_computable
          assert stype.is_view(ctx.env.schema)
      AssertionError
edgedbnov16:edgedb>
```

**Comment by aljazerzen** [comment]
Just a few days ago, I was making the point that we don't need to print traceback when InternalServerError is encountered, as we can always reproduce the bug given the schema and the query.

Today I stand corrected, because traceback gave me the idea that I have to enable a flag in the CLI, that makes the compiler work a bit differently.

In any case, thank you for the issue, yours are always of good quality!

This bug is very similar to #5679, I'll work on them both today, if I'm successful will be fixed in 4.2.

**Comment by jackfischer** [comment]
Confirmed still throws ISE in 6.11, though it looks different:

```
gel error: InternalServerError: AssertionError:
  Hint: This is most likely a bug in Gel. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "/usr/lib/x86_64-linux-gnu/gel-server-6/lib/python3.12/site-packages/edb/server/compiler_pool/worker.py", line 169, in compile
          units, cstate = COMPILER.compile_serialized_request(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/x86_64-linux-gnu/gel-server-6/lib/python3.12/site-packages/edb/server/compiler/compiler.py", line 606, in compile_serialized_request
          return self.compile(
                 ^^^^^^^^^^^^^
        File "/usr/lib/x86_64-linux-gnu/gel-server-6/lib/python3.12/site-packages/edb/server/compiler/compiler.py", line 685, in compile
          unit_group = compile(ctx=ctx, source=request.source)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/x86_64-linux-gnu/gel-server-6/lib/python3.12/site-packages/edb/server/compiler/compiler.py", line 2638, in compile
          return _try_compile(ctx=ctx, source=source)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/x86_64-linux-gnu/gel-server-6/lib/python3.12/site-packages/edb/server/compiler/compiler.py", line 2812, in _try_compile
          return _try_compile_ast(statements=statements, source=source, ctx=ctx)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/x86_64-linux-gnu/gel-server-6/lib/python3.12/site-packages/edb/server/compiler/compiler.py", line 2864, in _try_compile_ast
          comp, capabilities = _compile_dispatch_ql(
                               ^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/x86_64-linux-gnu/gel-server-6/lib/python3.12/site-packages/edb/server/compiler/compiler.py", line 2611, in _compile_dispatch_ql
          query = _compile_ql_query(
                  ^^^^^^^^^^^^^^^^^^
        File "/usr/lib/x86_64-linux-gnu/gel-server-6/lib/python3.12/site-packages/edb/server/compiler/compiler.py", line 1836, in _compile_ql_query
          ir = qlcompiler.compile_ast_to_ir(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/x86_64-linux-gnu/gel-server-6/lib/python3.12/site-packages/edb/edgeql/compiler/__init__.py", line 188, in wrapper
          return func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/x86_64-linux-gnu/gel-server-6/lib/python3.12/site-packages/edb/edgeql/compiler/__init__.py", line 283, in compile_ast_to_ir
          ir_set = dispatch_mod.compile(tree, ctx=ctx)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/x86_64-linux-gnu/gel-server-6/lib/python3.12/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/x86_64-linux-gnu/gel-server-6/lib/python3.12/site-packages/edb/edgeql/compiler/stmt.py", line 139, in compile_SelectQuery
          stmt.result = compile_result_clause(
                        ^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/x86_64-linux-gnu/gel-server-6/lib/python3.12/site-packages/edb/edgeql/compiler/stmt.py", line 1421, in compile_result_clause
          expr = dispatch.compile(result_expr, ctx=ectx)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/x86_64-linux-gnu/gel-server-6/lib/python3.12/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/x86_64-linux-gnu/gel-server-6/lib/python3.12/site-packages/edb/edgeql/compiler/stmt.py", line 139, in compile_SelectQuery
          stmt.result = compile_result_clause(
                        ^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/x86_64-linux-gnu/gel-server-6/lib/python3.12/site-packages/edb/edgeql/compiler/stmt.py", line 1421, in compile_result_clause
          expr = dispatch.compile(result_expr, ctx=ectx)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/x86_64-linux-gnu/gel-server-6/lib/python3.12/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/x86_64-linux-gnu/gel-server-6/lib/python3.12/site-packages/edb/edgeql/compiler/expr.py", line 108, in compile_Path
          return stmt.maybe_add_view(setgen.compile_path(expr, ctx=ctx), ctx=ctx)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/x86_64-linux-gnu/gel-server-6/lib/python3.12/site-packages/edb/edgeql/compiler/setgen.py", line 615, in compile_path
          path_tip = dispatch.compile(step, ctx=subctx)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/x86_64-linux-gnu/gel-server-6/lib/python3.12/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/x86_64-linux-gnu/gel-server-6/lib/python3.12/site-packages/edb/edgeql/compiler/stmt.py", line 1148, in compile_Shape
          expr = dispatch.compile(shape_expr, ctx=exposed_ctx)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/x86_64-linux-gnu/gel-server-6/lib/python3.12/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/x86_64-linux-gnu/gel-server-6/lib/python3.12/site-packages/edb/edgeql/compiler/stmt.py", line 441, in compile_GroupQuery
          return dispatch.compile(
                 ^^^^^^^^^^^^^^^^^
        File "/usr/lib/x86_64-linux-gnu/gel-server-6/lib/python3.12/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/x86_64-linux-gnu/gel-server-6/lib/python3.12/site-packages/edb/edgeql/compiler/stmt.py", line 408, in compile_InternalGroupQuery
          viewgen.late_compile_view_shapes(stmt.group_binding, ctx=bctx)
        File "/usr/lib/x86_64-linux-gnu/gel-server-6/lib/python3.12/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/x86_64-linux-gnu/gel-server-6/lib/python3.12/site-packages/edb/edgeql/compiler/viewgen.py", line 2573, in _late_compile_view_shapes_in_set
          late_compile_view_shapes(
        File "/usr/lib/x86_64-linux-gnu/gel-server-6/lib/python3.12/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/x86_64-linux-gnu/gel-server-6/lib/python3.12/site-packages/edb/edgeql/compiler/viewgen.py", line 2484, in _late_compile_view_shapes_in_set
          shape_ptrs = _get_late_shape_configuration(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/x86_64-linux-gnu/gel-server-6/lib/python3.12/site-packages/edb/edgeql/compiler/viewgen.py", line 2453, in _get_late_shape_configuration
          _get_shape_configuration_inner(
        File "/usr/lib/x86_64-linux-gnu/gel-server-6/lib/python3.12/site-packages/edb/edgeql/compiler/viewgen.py", line 2369, in _get_shape_configuration_inner
          _inline_type_computable(
        File "/usr/lib/x86_64-linux-gnu/gel-server-6/lib/python3.12/site-packages/edb/edgeql/compiler/viewgen.py", line 2218, in _inline_type_computable
          assert stype.is_view(ctx.env.schema)
      AssertionError
```
