### ISSUE TITLE
when I restart my IDE (PHPStorm) edgeql-js throws an error

### ISSUE THREAD

**Issue by PaulHolsters** [edgedb/edgedb#6515]
- EdgeDB Version: 4.1+2194ddc
- EdgeDB CLI Version: EdgeDB CLI 4.0.2+b26c502
- OS Version: Windows 10
- PHPStorm Version: 2022.3.3

Steps to Reproduce
---------------------------------------------------------------------
1.  I start a query in a condition my projects (PHPstorm) works:
PS D:\XXXX-edgeql-backend-v0> npx tsx .\query-tester.ts     
ts file:
import * as edgedb from "edgedb";
import e from "./dbschema/edgeql-js";

const client = edgedb.createClient();
async function run() {
    const query = e.select(e.Movie, ()=>({
        id: true,
        title: true,
        actors: { name: true },
        release_year:true
    }));
    const result = await query.run(client)
    console.log(result)
    /*
      {
        id: string;
        title: string;
        actors: { name: string; }[];
      }[]
    */
}
run();

query result:
[
  {
    id: '4ca43fd2-8acd-11ee-b790-b709d488a521',
    actors: [],
    release_year: null
  }
]
2. I restart PHPStorm for my project
3. I do the same query => error
error:
PS D:\XXXX-edgeql-backend-v0> npx tsx .\query-tester.ts
D:\XXXX-edgeql-backend-v0\dbschema\edgeql-js\select.js:324
var $FreeObject = (0, hydrate_1.makeType)(__spec__1.spec, __spreadArray([], __spec__1.spec.values(), true).find(function (s) { return s.name === "std::FreeObject"; }).id, literal_1.literal);
TypeError: Cannot read properties of undefined (reading 'id')
    at Object.<anonymous> (D:\XXXX-edgeql-backend-v0\dbschema\edgeql-js\select.js:324:167)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Object.y (C:\Users\PC Gebruiker\AppData\Local\npm-cache\_npx\fd45a72a545557e9\node_modules\tsx\dist\cjs\index.cjs:1:1151)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (D:\XXXX-edgeql-backend-v0\dbschema\edgeql-js\query.js:43:16)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Object.y (C:\Users\PC Gebruiker\AppData\Local\npm-cache\_npx\fd45a72a545557e9\node_modules\tsx\dist\cjs\index.cjs:1:1151)
Node.js v20.9.0
4. I delete the edgeql-js generated directory form de dbschema directory
5. I reinstall edgeql-js:
PS D:\XXXX-edgeql-backend-v0> npx @edgedb/generate edgeql-js
Generating query builder...
Detected tsconfig.json, generating TypeScript files.
   To override this, use the --target flag.
   Run `npx @edgedb/generate --help` for full options.
Introspecting database schema...
Generating runtime spec...
Generating cast maps...
Generating scalars...
Generating object types...
Generating function types...
Generating operators...
Generating set impl...
Generating globals...
Generating index...
Writing files to D:\XXXX-edgeql-backend-v0\dbschema\edgeql-js
Generation complete! 🤘
Checking the generated files into version control is
not recommended. Consider updating the .gitignore of your
project to exclude these files.
6. I do the same query => it works!
---------------------------------------------------------------------

Additional files that might be of interest:
package.Json:
{
  "name": "XXXX-edgeql-backend-v0",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "edgedb": "^1.4.1"
  },
  "devDependencies": {
    "@edgedb/generate": "^0.4.1"
  }
}

edgedb.toml:
[edgedb]
server-version = "4.1"

tsconfig.json:
{
  "compilerOptions": {
    "target": "es5",                         
    "module": "commonjs",               
    "lib": ["es2015","dom"],                        
    "strict": true,                           
    "esModuleInterop": true,                 
    "forceConsistentCasingInFileNames": true 
  }
}

I ran 2 migrations:
00001.edgeql
CREATE MIGRATION m1eyguovjnuvvepgjdh5rhhwm54obpo7no456jx6meod6rgm5bofoq
    ONTO initial
{
  CREATE TYPE default::Person {
      CREATE REQUIRED PROPERTY name: std::str;
  };
  CREATE TYPE default::Movie {
      CREATE MULTI LINK actors: default::Person;
      CREATE REQUIRED PROPERTY title: std::str {
          CREATE CONSTRAINT std::exclusive;
      };
  };
};

00002.edgeql
CREATE MIGRATION m1emqi4zgw4vdp6g4vgejk4ufrxfe2znn2jsdfdah67eogtetsnxfq
    ONTO m1eyguovjnuvvepgjdh5rhhwm54obpo7no456jx6meod6rgm5bofoq
{
  CREATE ABSTRACT TYPE default::Content {
      CREATE MULTI LINK actors: default::Person {
          CREATE PROPERTY character_name: std::str;
      };
      CREATE REQUIRED PROPERTY title: std::str;
  };
  CREATE TYPE default::Account {
      CREATE MULTI LINK watchlist: default::Content;
      CREATE REQUIRED PROPERTY username: std::str {
          CREATE CONSTRAINT std::exclusive;
      };
  };
  ALTER TYPE default::Movie EXTENDING default::Content LAST;
  ALTER TYPE default::Movie {
      ALTER LINK actors {
          RESET CARDINALITY;
          DROP OWNED;
          RESET TYPE;
      };
      ALTER PROPERTY title {
          DROP CONSTRAINT std::exclusive;
          RESET OPTIONALITY;
          DROP OWNED;
          RESET TYPE;
      };
      CREATE PROPERTY release_year: std::int32;
  };
  CREATE TYPE default::Show EXTENDING default::Content;
  ALTER TYPE default::Person {
      CREATE LINK filmography := (.<actors[IS default::Content]);
  };
  CREATE TYPE default::Season {
      CREATE REQUIRED LINK show: default::Show;
      CREATE REQUIRED PROPERTY number: std::int32;
  };
  ALTER TYPE default::Show {
      CREATE PROPERTY num_seasons := (std::count(.<show[IS default::Season]));
  };
};

Schema:
module default {
  type Account {
    required username: str {
      constraint exclusive;
    };
    multi watchlist: Content;
  }

  type Person {
    required name: str;
    link filmography := .<actors[is Content];
  }

  abstract type Content {
    required title: str;
    multi actors: Person {
      character_name: str;
    };
  }

  type Movie extending Content {
    release_year: int32;
  }

  type Show extending Content {
    property num_seasons := count(.<show[is Season]);
  }

  type Season {
    required number: int32;
    required show: Show;
  }
};

**Comment by PaulHolsters** [comment]
This issue actually seems to happen every time I change the file with the query in it. So it seems that changes aren't picked up by the typescript query builder.

**Comment by PaulHolsters** [comment]
@ My IDE uses ceratin TS settings which causes the issue. After reinstalling everything and adding the necessary dev dependencies everything works fine now:
```
  "devDependencies": {
    "@edgedb/generate": "^0.4.1",
    "@types/node": "^20.10.0",
    "tsx": "^4.5.0",
    "typescript": "^5.3.2"
  }
```
