### ISSUE TITLE
InternalServerError on `for` loop nested insert w/ link prop

### ISSUE THREAD

**Issue by raddevon** [edgedb/edgedb#6618]
Working on an example for #6594. I'm attempting a nested insert of two objects with link properties and using a `for` loop instead of a set of inserts in order to work around `invalid reference to link property in top level shape`. The workaround seems to be broken for me as well.

Here's the resulting error and trace:
```
edgedb error: InternalServerError: Can't compile ref to visible binding (__derived__::color@w~1)
  Server traceback:
      Traceback (most recent call last):
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/pgsql/compiler/__init__.py", line 140, in compile_ir_to_sql_tree
          qtree = dispatch.compile(ir_expr, ctx=ctx)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 60, in compile_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 115, in _compile_set_impl
          _compile_set(ir_set, ctx=ctx)
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 710, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 165, in get_set_rvar
          return _process_toplevel_query(ir_set, ctx=ctx)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 287, in _process_toplevel_query
          rvars = _get_set_rvar(ir_set, ctx=ctx)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 369, in _get_set_rvar
          return process_set_as_subquery(ir_set, ctx=ctx)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 1450, in process_set_as_subquery
          dispatch.visit(expr, ctx=newctx)
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/pgsql/compiler/dispatch.py", line 44, in visit
          compile(ir, ctx=ctx)
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/pgsql/compiler/stmt.py", line 162, in compile_InsertStmt
          dml.process_insert_body(
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/pgsql/compiler/dml.py", line 773, in process_insert_body
          _update_link_tables(contents_cte)
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/pgsql/compiler/dml.py", line 758, in _update_link_tables
          link_cte, check_cte = process_link_update(
                                ^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/pgsql/compiler/dml.py", line 2302, in process_link_update
          data_cte, specified_cols = process_link_values(
                                     ^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/pgsql/compiler/dml.py", line 2907, in process_link_values
          dispatch.visit(ir_expr, ctx=input_rel_ctx)
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 85, in visit_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 111, in _compile_set_impl
          _compile_set(ir_set, ctx=scopectx)
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 710, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 223, in get_set_rvar
          rvars = _get_set_rvar(ir_set, ctx=subctx)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 369, in _get_set_rvar
          return process_set_as_subquery(ir_set, ctx=ctx)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 1450, in process_set_as_subquery
          dispatch.visit(expr, ctx=newctx)
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/pgsql/compiler/dispatch.py", line 44, in visit
          compile(ir, ctx=ctx)
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/pgsql/compiler/stmt.py", line 94, in compile_SelectStmt
          outvar = clauses.compile_output(stmt.result, ctx=ictx)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/pgsql/compiler/clauses.py", line 227, in compile_output
          dispatch.visit(ir_set, ctx=newctx)
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 85, in visit_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 115, in _compile_set_impl
          _compile_set(ir_set, ctx=ctx)
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 720, in _compile_set
          shape_tuple = shapecomp.compile_shape(ir_set, ir_set.shape, ctx=ctx)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/pgsql/compiler/shapecomp.py", line 100, in compile_shape
          wrapper = relgen.set_as_subquery(
                    ^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 528, in set_as_subquery
          dispatch.visit(ir_set, ctx=subctx)
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 85, in visit_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 111, in _compile_set_impl
          _compile_set(ir_set, ctx=scopectx)
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 710, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 223, in get_set_rvar
          rvars = _get_set_rvar(ir_set, ctx=subctx)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 369, in _get_set_rvar
          return process_set_as_subquery(ir_set, ctx=ctx)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 1450, in process_set_as_subquery
          dispatch.visit(expr, ctx=newctx)
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/pgsql/compiler/dispatch.py", line 44, in visit
          compile(ir, ctx=ctx)
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/pgsql/compiler/stmt.py", line 94, in compile_SelectStmt
          outvar = clauses.compile_output(stmt.result, ctx=ictx)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/pgsql/compiler/clauses.py", line 227, in compile_output
          dispatch.visit(ir_set, ctx=newctx)
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 85, in visit_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 115, in _compile_set_impl
          _compile_set(ir_set, ctx=ctx)
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 710, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 223, in get_set_rvar
          rvars = _get_set_rvar(ir_set, ctx=subctx)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 424, in _get_set_rvar
          return process_set_as_tuple_indirection(ir_set, ctx=ctx)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 2033, in process_set_as_tuple_indirection
          rvar = get_set_rvar(tuple_set, ctx=subctx)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 223, in get_set_rvar
          rvars = _get_set_rvar(ir_set, ctx=subctx)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 438, in _get_set_rvar
          return process_set_as_root(ir_set, ctx=ctx)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 785, in process_set_as_root
          assert not ir_set.is_visible_binding_ref, (
      AssertionError: Can't compile ref to visible binding (__derived__::color@w~1)

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/server/compiler_pool/worker.py", line 178, in compile
          units, cstate = COMPILER.compile(
                          ^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 870, in compile
          unit_group = compile(ctx=ctx, source=source)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 2303, in compile
          return _try_compile(ctx=ctx, source=source)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 2364, in _try_compile
          comp, capabilities = _compile_dispatch_ql(
                               ^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 2277, in _compile_dispatch_ql
          query = _compile_ql_query(ctx, ql, script_info=script_info)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 1710, in _compile_ql_query
          sql_res = pg_compiler.compile_ir_to_sql_tree(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/raddevon/Library/Application Support/edgedb/portable/5.0-dev.8091/lib/python3.11/site-packages/edb/pgsql/compiler/__init__.py", line 157, in compile_ir_to_sql_tree
          raise errors.InternalServerError(*args) from e
      edb.errors.InternalServerError: Can't compile ref to visible binding (__derived__::color@w~1)
```

- EdgeDB Version: 5.0-dev.8091+e24f7fd
- EdgeDB CLI Version: 4.0.2+500be79
- OS Version: 14.0

Steps to Reproduce:

1. Start a new project
2. Migrate the schema
3. Try this query:
```edgeql
insert Player {
  name := 'Devon',
  picks := assert_distinct((
    for color in {(<int16>1, 'Red'),(<int16>2,'Blue')} union (
      insert Color {@order := color.0, name := color.1}
    )
  ))
};
```

Schema:
```edgeql
module default {
  type Player {
    required name: str;
    multi picks: Color {
      order: int16;
      constraint exclusive on ((@source, @order));
    }
  }
  type Color {
    required name: str;
  }
}
```

**Comment by msullivan** [comment]
It works if you remove the `assert_distinct`.
And more surprisingly, this works too:
```
insert Player {
  name := 'Name',
  picks := assert_distinct((
    for color in {(<int16>1, 'Red'),(<int16>2,'Blue')} union (
      select (insert Color {name := color.1}) { @order := color.0 }
    )
  ))
};
```

Link property reform: #4436

**Comment by msullivan** [comment]
I think the issue is that the shape compilation that `@order` comes from is being injected on the *outside* of the assert_distinct by viewgen (since it doesn't know if assert_distinct can preserve it). Which is to say, *outside* of the for iterator. This means that to work, the for iterator needs to make it out and be visible in the enclosing scope.
When the shape is provided separately, in a select, this works, but for whatever reason it gets masked off by path_id_mask in the direct insert case.

The big question is whether this is legit? Should the iterator be able to be used by a shape defined outside of it? It seems like probably not, and normally we use materialization to deal with some of the cases like this.

In this comment, https://github.com/edgedb/edgedb/blob/021bc23fb5f22a203fdd6cc6f71374b13d673625/edb/pgsql/compiler/relctx.py#L816-L820 I wanted to mask *all* visible paths, and one of the things that blocked it was some dml linkprop cases, which I now understand why better.
