### ISSUE TITLE
Migration is failing due to a crash

### ISSUE THREAD

**Issue by nikitavoloboev** [edgedb/edgedb#6652]
More information in [Discord thread](https://discord.com/channels/841451783728529451/1190946538122379285).

After [this commit](https://github.com/learn-anything/learn-anything.xyz/pull/92/commits/a178807085253b71410324e4e3afd26c59011435), I ran migration and got this result:

```
: db:migrate
$ cd grafbase/edgedb && edgedb migration create && edgedb migrate && bunx @edgedb/generate edgeql-js --target ts && bunx @edgedb/generate queries --target ts
did you alter object type 'default::User'? [y,n,l,c,b,s,q,?]
> y
Please specify a conversion expression to alter the type of link 'linksBookmarked':
cast_expr_4> .linksBookmarked[IS default::PersonalLink]
Please specify a conversion expression to alter the type of link 'linksCompleted':
cast_expr_5> .linksCompleted[IS default::PersonalLink]
Please specify a conversion expression to alter the type of link 'linksInProgress':
cast_expr_6> .linksInProgress[IS default::PersonalLink]
Please specify a conversion expression to alter the type of link 'linksLiked':
cast_expr_7> .linksLiked[IS default::PersonalLink]
Created /Users/nikiv/src/app/learn-anything.xyz/grafbase/edgedb/dbschema/migrations/00051.edgeql, id: m1kqptpi5yfk3nvgnmiezcg24ew6si6i7mzjhifphi7inyxpw6r5sa
edgedb error: InternalServerError: no rvar in intersection matches path id (default::User).>linksBookmarked[IS default::GlobalLink]
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/pgsql/compiler/__init__.py", line 135, in compile_ir_to_sql_tree
          qtree = dispatch.compile(ir_expr, ctx=ctx)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 60, in compile_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 115, in _compile_set_impl
          _compile_set(ir_set, ctx=ctx)
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 701, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 164, in get_set_rvar
          return _process_toplevel_query(ir_set, ctx=ctx)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 286, in _process_toplevel_query
          rvars = _get_set_rvar(ir_set, ctx=ctx)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 348, in _get_set_rvar
          return process_set_as_subquery(ir_set, ctx=ctx)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 1425, in process_set_as_subquery
          dispatch.visit(expr, ctx=newctx)
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/pgsql/compiler/dispatch.py", line 44, in visit
          compile(ir, ctx=ctx)
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/pgsql/compiler/stmt.py", line 88, in compile_SelectStmt
          outvar = clauses.compile_output(stmt.result, ctx=ictx)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/pgsql/compiler/clauses.py", line 225, in compile_output
          dispatch.visit(ir_set, ctx=newctx)
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 85, in visit_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 111, in _compile_set_impl
          _compile_set(ir_set, ctx=scopectx)
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 701, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 222, in get_set_rvar
          rvars = _get_set_rvar(ir_set, ctx=subctx)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 348, in _get_set_rvar
          return process_set_as_subquery(ir_set, ctx=ctx)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 1425, in process_set_as_subquery
          dispatch.visit(expr, ctx=newctx)
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/pgsql/compiler/dispatch.py", line 44, in visit
          compile(ir, ctx=ctx)
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/pgsql/compiler/stmt.py", line 88, in compile_SelectStmt
          outvar = clauses.compile_output(stmt.result, ctx=ictx)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/pgsql/compiler/clauses.py", line 225, in compile_output
          dispatch.visit(ir_set, ctx=newctx)
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 85, in visit_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 115, in _compile_set_impl
          _compile_set(ir_set, ctx=ctx)
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 701, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 222, in get_set_rvar
          rvars = _get_set_rvar(ir_set, ctx=subctx)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 403, in _get_set_rvar
          return process_set_as_path(ir_set, ctx=ctx)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 1034, in process_set_as_path
          return process_set_as_path_type_intersection(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 919, in process_set_as_path_type_intersection
          source_rvar = get_set_rvar(ir_source, ctx=subctx)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 242, in get_set_rvar
          result_rvar = _include_rvars(rvars, scope_stmt=scope_stmt, ctx=subctx)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 267, in _include_rvars
          relctx.include_specific_rvar(
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/pgsql/compiler/relctx.py", line 267, in include_specific_rvar
          rel_join(stmt, rvar, ctx=ctx)
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/pgsql/compiler/relctx.py", line 1282, in rel_join
          _plain_join(query, right_rvar, ctx=ctx)
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/pgsql/compiler/relctx.py", line 1300, in _plain_join
          rref = pathctx.get_rvar_path_identity_var(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/pgsql/compiler/pathctx.py", line 758, in get_rvar_path_identity_var
          return get_rvar_path_var(rvar, path_id, aspect='identity', env=env)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/pgsql/compiler/pathctx.py", line 730, in get_rvar_path_var
          outvar = get_path_output(
                   ^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/pgsql/compiler/pathctx.py", line 1113, in get_path_output
          return _get_path_output(rel, path_id=path_id, aspect=aspect,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/pgsql/compiler/pathctx.py", line 1174, in _get_path_output
          ref = get_path_var(rel, path_id, aspect=aspect, flavor=flavor, env=env)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/pgsql/compiler/pathctx.py", line 272, in get_path_var
          rel_rvar = _find_rvar_in_intersection_by_typeref(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/pgsql/compiler/pathctx.py", line 484, in _find_rvar_in_intersection_by_typeref
          raise AssertionError(
      AssertionError: no rvar in intersection matches path id (default::User).>linksBookmarked[IS default::GlobalLink]

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/server/compiler_pool/worker.py", line 186, in compile_in_tx
          units, cstate = COMPILER.compile_in_tx(cstate, *args, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 913, in compile_in_tx
          return compile(ctx=ctx, source=source), ctx.state
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 2068, in compile
          return _try_compile(ctx=ctx, source=source)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 2136, in _try_compile
          comp, capabilities = _compile_dispatch_ql(
                               ^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 1975, in _compile_dispatch_ql
          query = ddl.compile_dispatch_ql_migration(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/server/compiler/ddl.py", line 379, in compile_dispatch_ql_migration
          return compile_and_apply_ddl_stmt(ctx, ql)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/server/compiler/ddl.py", line 209, in compile_and_apply_ddl_stmt
          block, new_types, config_ops = _process_delta(ctx, delta)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/server/compiler/ddl.py", line 326, in _process_delta
          schema = pgdelta.apply(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/pgsql/delta.py", line 7198, in apply
          schema = super().apply(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/schema/delta.py", line 1553, in apply
          schema = self.apply_subcommands(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/pgsql/delta.py", line 189, in apply_subcommands
          schema = super().apply_subcommands(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/schema/delta.py", line 1580, in apply_subcommands
          schema = objop.apply(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/schema/delta.py", line 3064, in apply
          schema = self._create_innards(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/schema/delta.py", line 3032, in _create_innards
          return self.apply_subcommands(schema, context)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/pgsql/delta.py", line 189, in apply_subcommands
          schema = super().apply_subcommands(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/schema/delta.py", line 951, in apply_subcommands
          schema = op.apply(schema, context=context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/pgsql/delta.py", line 3744, in apply
          schema = super().apply(schema, context=context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/schema/delta.py", line 3529, in apply
          schema = self._alter_innards(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/schema/delta.py", line 3161, in _alter_innards
          return self.apply_subcommands(schema, context)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/pgsql/delta.py", line 189, in apply_subcommands
          schema = super().apply_subcommands(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/schema/delta.py", line 951, in apply_subcommands
          schema = op.apply(schema, context=context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/schema/delta.py", line 3529, in apply
          schema = self._alter_innards(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/pgsql/delta.py", line 5223, in _alter_innards
          schema = super()._alter_innards(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/schema/delta.py", line 3161, in _alter_innards
          return self.apply_subcommands(schema, context)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/pgsql/delta.py", line 189, in apply_subcommands
          schema = super().apply_subcommands(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/schema/delta.py", line 951, in apply_subcommands
          schema = op.apply(schema, context=context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/schema/delta.py", line 3214, in apply
          schema = self._alter_begin(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/pgsql/delta.py", line 5133, in _alter_begin
          self._alter_pointer_type(self.scls, schema, orig_schema, context)
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/pgsql/delta.py", line 4326, in _alter_pointer_type
          (cast_expr_sql, expr_is_nullable) = self._compile_conversion_expr(
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/pgsql/delta.py", line 4698, in _compile_conversion_expr
          sql_tree, env, _ = compiler.compile_ir_to_sql_tree(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/nikiv/Library/Application Support/edgedb/portable/3.4/lib/python3.11/site-packages/edb/pgsql/compiler/__init__.py", line 152, in compile_ir_to_sql_tree
          raise errors.InternalServerError(*args) from e
      edb.errors.InternalServerError: no rvar in intersection matches path id (default::User).>linksBookmarked[IS default::GlobalLink]
edgedb error: error in one of the migrations
error: script "db:migrate" exited with code 1
```

I don't get why it happens.

**Comment by elprans** [comment]
This looks like a bug.  The first thing I would try is upgrading to the latest EdgeDB version to see if this is still present.
