### ISSUE TITLE
ERROR InternalServerError: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by NetOpWibby** [edgedb/edgedb#6696]
```
ERROR InternalServerError: [Errno 24] Too many open files
Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md

    at RawConnection._parseErrorMessage (https://deno.land/x/edgedb@v1.4.1/_src/baseConn.ts:305:17)
    at RawConnection._executeFlow (https://deno.land/x/edgedb@v1.4.1/_src/baseConn.ts:1139:24)
    at eventLoopTick (ext:core/01_core.js:182:7)
    at async RawConnection.fetch (https://deno.land/x/edgedb@v1.4.1/_src/baseConn.ts:1250:9)
    at async ClientConnectionHolder.retryingFetch (https://deno.land/x/edgedb@v1.4.1/_src/baseClient.ts:177:18)
    at async Client.querySingle (https://deno.land/x/edgedb@v1.4.1/_src/baseClient.ts:615:14)
    at async findDomain (file:///Users/netopwibby/Projects/Beachfront/api/src/component/search/crud/read.ts:507:36)
    at async file:///Users/netopwibby/Projects/Beachfront/api/src/component/search/crud/read.ts:436:26
    at async Promise.all (index 56)
    at async createCollection (file:///Users/netopwibby/Projects/Beachfront/api/src/component/search/crud/read.ts:425:3)
```

- EdgeDB Version: `3.0+7d903be`
- EdgeDB CLI Version: `4.0.2+500be79`
- OS Version: macOS Sonama (14.2.1)

I'm building a domain registrar and the API queries EdgeDB before using external APIs to populate search results. The results vary in length (from as little as 2 to as many as 100+). The database is queried a LOT for each search so maybe that's the issue?

I came across this issue while returning to a background tab so it's possible something was hanging while I was away. Not sure if this issue is a query error but I can share my schema if it'll help.

**Comment by NetOpWibby** [comment]
SMDH I didn't realize I never upgraded to EdgeDB 4!!

**Comment by msullivan** [comment]
Hm, are you making lots of separate connections (like one connection per query)? Can you provide server logs?

It looks like we do try to increase the limit on number of open files on server start, but we only increase it to 2048 which isn't *that* high.

Not sure what would trigger getting that error exactly, though. On my dev setup (on linux), client connections start failing when the server has too many connections open to make more, but it doesn't fail with an ISE, it just fails to connect;

**Comment by NetOpWibby** [comment]
How should I structure the logs? Is there some EdgeDB way? (btw, I just upgraded to the latest database version so it's quite possible I nullified this issue).

**Comment by msullivan** [comment]
I mean logs from the edgedb server when the error occured

**Comment by NetOpWibby** [comment]
This was the response I got immediately before:

```
A client connection error occurred; reconnecting because of "waitUntilAvailable=30000". ClientConnectionClosedError: network error: ConnectionReset: Connection reset by peer (os error 54)
    at RawConnection._onError (https://deno.land/x/edgedb@v1.4.1/_src/rawConn.ts:159:20)
    at TLSSocket.emit (https://deno.land/std@0.177.0/node/_events.mjs:379:28)
    at https://deno.land/x/edgedb@v1.4.1/_src/adapter.deno.ts:308:16
    at eventLoopTick (ext:core/01_core.js:182:7) {
  source: ConnectionReset: Connection reset by peer (os error 54)
    at async Object.connectTls (ext:deno_net/02_tls.js:41:51) {
    name: "ConnectionReset",
    code: "ECONNRESET"
  }
}
```

And after:

```
A client connection error occurred; reconnecting because of "waitUntilAvailable=30000". ClientConnectionClosedError: network error: UnexpectedEof: unexpected end of file
    at RawConnection._onError (https://deno.land/x/edgedb@v1.4.1/_src/rawConn.ts:159:20)
    at TLSSocket.emit (https://deno.land/std@0.177.0/node/_events.mjs:379:28)
    at https://deno.land/x/edgedb@v1.4.1/_src/adapter.deno.ts:308:16
    at eventLoopTick (ext:core/01_core.js:182:7) {
  source: UnexpectedEof: unexpected end of file
    at async https://deno.land/x/edgedb@v1.4.1/_src/adapter.deno.ts:300:29 {
    name: "UnexpectedEof"
  }
}
```

**Comment by NetOpWibby** [comment]
AH, I was able to trigger it again. Making changes to my SvelteKit app on a page that automatically triggers a query to the API. I was making changes and not waiting for the API to finish with a response.

<img width="2056" alt="SS 2024-01-11 at 9 38 28 PM" src="https://github.com/edgedb/edgedb/assets/1288356/80b5528e-c5eb-40ea-b26d-41d0a5a59b0b">

**Comment by NetOpWibby** [comment]
I ran into this issue, was about to open a new issue, deja vu kicked in, I searched the repo, found myself. Hello again!

<img width="1332" alt="SS 2024-02-15 at 11 27 35 AM" src="https://github.com/edgedb/edgedb/assets/1288356/52bf3acf-688d-4ba3-a3fc-733b6c584416">

I wonder if I'm supposed to be closing a socket or something.

**Comment by msullivan** [comment]
These are all client side logs; do you have any logs from the server itself? If this is a local instance you can probably extract them with `edgedb instance logs`

**Comment by NetOpWibby** [comment]
I feel like I may be doing things incorrectly (LOL): I create a new client for every function. Could this be an issue? In my top-level function for `search/crud/read.ts`, I instantiate a client (`const client = createClient(databaseParams);`). I also have a helper function (`findDomain`) that instantiates a client every time it's called. This could be 100+ times.

`edgedb instance logs` doesn't seem to work if you have a custom database (mine is not `edgedb`). I've tried several variants to get the log command to work. I'd expect this to work but nah.

```sh
edgedb instance logs --instance beachfront --database beachfront
```

**Comment by msullivan** [comment]
Yeah, you should just have one client, probably. You'll be establishing way more connections than you need to otherwise. The client does connection pooling internally too, I think, so you might be making even more connections than you realize.

That said we should be producing a clean error message instead of an InternalServerError.

You don't need to (and, it seems, must not) specify the database name when running `edgedb instance logs`. It's all one instance, they share logs.

**Comment by NetOpWibby** [comment]
Ah okay, here's the output of `edgedb instance logs --instance beachfront`:

```
INFO 69446 2024-02-15T11:49:34.878 postgres: checkpoint complete: wrote 4 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.415 s, sync=0.001 s, total=0.435 s; sync files=1, longest=0.001 s, average=0.001 s; distance=15 kB, estimate=5738 kB
INFO 69437 2024-02-15T11:50:43.709 edb.server: shutting down server: no clients connected in last 600.0 seconds
INFO 69437 2024-02-15T11:50:43.713 edb.server: Shutting down.
INFO 69446 2024-02-15T11:50:43.913 postgres: received fast shutdown request
INFO 69446 2024-02-15T11:50:43.913 postgres: aborting any active transactions
INFO 69446 2024-02-15T11:50:43.914 postgres: background worker "logical replication launcher" (PID 69452) exited with exit code 1
INFO 69446 2024-02-15T11:50:43.914 postgres: shutting down
INFO 69446 2024-02-15T11:50:43.914 postgres: checkpoint starting: shutdown immediate
INFO 69446 2024-02-15T11:50:43.918 postgres: checkpoint complete: wrote 9 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.003 s, sync=0.001 s, total=0.005 s; sync files=7, longest=0.001 s, average=0.001 s; distance=39 kB, estimate=5168 kB
INFO 69446 2024-02-15T11:50:43.924 postgres: database system is shut down
```

**Comment by msullivan** [comment]
Could you provide more logs from that last one?

**Comment by NetOpWibby** [comment]
@msullivan What if I just instantiate the client ONCE (in like, a utility file) and import that instance everywhere? I'm creating a new client per file in every component's `crud/` folder:

<img width="268" alt="SS 2024-02-15 at 1 58 03 PM" src="https://github.com/edgedb/edgedb/assets/1288356/cd9ad42b-50a7-41f1-9732-6e322d905a03">

**Comment by msullivan** [comment]
Yes, one client is the recommended workflow

**Comment by NetOpWibby** [comment]
SMDH I've been in shambles this whole time.
