### ISSUE TITLE
Error casting to regclass during schema discovery in PostgreSQL via EdgeDB connection

### ISSUE THREAD

**Issue by danew** [edgedb/edgedb#7163]
When attempting to perform schema discovery on a PostgreSQL database through an EdgeDB-managed connection, the operation fails due to an error in casting to regclass. This error is encountered during the execution of a command that involves casting a value returned by pg_get_serial_sequence to REGCLASS and then to OID. The process is part of a larger ELT pipeline managed by Meltano, specifically utilizing the tap-postgres tool for extracting data from PostgreSQL.

- EdgeDB Version: 4.1+2194ddc
- EdgeDB CLI Version: 4.1.0+a8fe4d7
- OS Version: macOS 12.7.4

**Steps to Reproduce:**
We are using a third-party provider who uses Meltano ELT pipeline with `tap-postgres` configured to extract data from a PostgreSQL database. When we configure the connection, we get the error provided below.

**Expected Behavior**
The schema discovery process completes successfully, with tap-postgres correctly identifying tables, columns, and associated metadata, including sequences and serial columns without any casting errors.

**Actual Behavior**
The schema discovery process fails with the following error message:
```
casting to `regclass` requires a string or number literal LINE 5: ...' AND pg_catalog.pg_sequence.seqrelid = CAST(CAST(pg_catalog... ^
This indicates a failure in the SQL execution related to casting operations within PostgreSQL, specifically triggered during schema reflection.
```
And here's the SQL command causing the issue, simplified for clarity:
```sql
SELECT ... FROM pg_catalog.pg_class
LEFT OUTER JOIN ...
LEFT OUTER JOIN ...
JOIN ...
WHERE ... AND pg_catalog.pg_sequence.seqrelid = CAST(CAST(pg_catalog.pg_get_serial_sequence(...) AS REGCLASS) AS OID)
```

<details>
<summary>Error message</summary>
<code>
Error: ELT could not be completed: Cannot start extractor: Catalog discovery failed: command ['/meltano_dataset_sync/.meltano/extractors/tap-postgres/venv/bin/tap-postgres', '--config', '/meltano_dataset_sync/.meltano/run/elt/dataset_t1948d1431_nodes_dataset/067a3e15-b473-4c56-b84a-b7d008296d44/tap.ffab1b26-bdab-4a90-a2a5-5e26267bb218.config.json', '--discover'] returned 1 with stderr: Traceback (most recent call last): File "/meltano_dataset_sync/.meltano/extractors/tap-postgres/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1971, in _exec_single_context self.dialect.do_execute( File "/meltano_dataset_sync/.meltano/extractors/tap-postgres/venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute cursor.execute(statement, parameters) psycopg2.errors.InternalError_: casting to `regclass` requires a string or number literal LINE 5: ...' AND pg_catalog.pg_sequence.seqrelid = CAST(CAST(pg_catalog... ^ The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/meltano_dataset_sync/.meltano/extractors/tap-postgres/venv/bin/tap-postgres", line 8, in <module> sys.exit(TapPostgres.cli()) ^^^^^^^^^^^^^^^^^ File "/meltano_dataset_sync/.meltano/extractors/tap-postgres/venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__ return self.main(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/meltano_dataset_sync/.meltano/extractors/tap-postgres/venv/lib/python3.11/site-packages/click/core.py", line 1077, in main with self.make_context(prog_name, args, **extra) as ctx: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/meltano_dataset_sync/.meltano/extractors/tap-postgres/venv/lib/python3.11/site-packages/click/core.py", line 943, in make_context self.parse_args(ctx, args) File "/meltano_dataset_sync/.meltano/extractors/tap-postgres/venv/lib/python3.11/site-packages/click/core.py", line 1408, in parse_args value, args = param.handle_parse_result(ctx, opts, args) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/meltano_dataset_sync/.meltano/extractors/tap-postgres/venv/lib/python3.11/site-packages/click/core.py", line 2400, in handle_parse_result value = self.process_value(ctx, value) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/meltano_dataset_sync/.meltano/extractors/tap-postgres/venv/lib/python3.11/site-packages/click/core.py", line 2362, in process_value value = self.callback(ctx, self, value) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/meltano_dataset_sync/.meltano/extractors/tap-postgres/venv/lib/python3.11/site-packages/singer_sdk/tap_base.py", line 540, in cb_discover tap.run_discovery() File "/meltano_dataset_sync/.meltano/extractors/tap-postgres/venv/lib/python3.11/site-packages/singer_sdk/tap_base.py", line 295, in run_discovery catalog_text = self.catalog_json_text ^^^^^^^^^^^^^^^^^^^^^^ File "/meltano_dataset_sync/.meltano/extractors/tap-postgres/venv/lib/python3.11/site-packages/singer_sdk/tap_base.py", line 315, in catalog_json_text return json.dumps(self.catalog_dict, indent=2) ^^^^^^^^^^^^^^^^^ File "/meltano_dataset_sync/.meltano/extractors/tap-postgres/venv/lib/python3.11/site-packages/tap_postgres/tap.py", line 526, in catalog_dict result["streams"].extend(self.connector.discover_catalog_entries()) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/meltano_dataset_sync/.meltano/extractors/tap-postgres/venv/lib/python3.11/site-packages/singer_sdk/connectors/sql.py", line 522, in discover_catalog_entries catalog_entry = self.discover_catalog_entry( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/meltano_dataset_sync/.meltano/extractors/tap-postgres/venv/lib/python3.11/site-packages/singer_sdk/connectors/sql.py", line 461, in discover_catalog_entry for column_def in inspected.get_columns(table_name, schema=schema_name): ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/meltano_dataset_sync/.meltano/extractors/tap-postgres/venv/lib/python3.11/site-packages/sqlalchemy/engine/reflection.py", line 859, in get_columns col_defs = self.dialect.get_columns( ^^^^^^^^^^^^^^^^^^^^^^^^^ File "<string>", line 2, in get_columns File "/meltano_dataset_sync/.meltano/extractors/tap-postgres/venv/lib/python3.11/site-packages/sqlalchemy/engine/reflection.py", line 97, in cache ret = fn(self, con, *args, **kw) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/meltano_dataset_sync/.meltano/extractors/tap-postgres/venv/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/base.py", line 3540, in get_columns data = self.get_multi_columns( ^^^^^^^^^^^^^^^^^^^^^^^ File "/meltano_dataset_sync/.meltano/extractors/tap-postgres/venv/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/base.py", line 3684, in get_multi_columns rows = connection.execute(query, params).mappings() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/meltano_dataset_sync/.meltano/extractors/tap-postgres/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1422, in execute return meth( ^^^^^ File "/meltano_dataset_sync/.meltano/extractors/tap-postgres/venv/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 514, in _execute_on_connection return connection._execute_clauseelement( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/meltano_dataset_sync/.meltano/extractors/tap-postgres/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1644, in _execute_clauseelement ret = self._execute_context( ^^^^^^^^^^^^^^^^^^^^^^ File "/meltano_dataset_sync/.meltano/extractors/tap-postgres/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1850, in _execute_context return self._exec_single_context( ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/meltano_dataset_sync/.meltano/extractors/tap-postgres/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1990, in _exec_single_context self._handle_dbapi_exception( File "/meltano_dataset_sync/.meltano/extractors/tap-postgres/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2357, in _handle_dbapi_exception raise sqlalchemy_exception.with_traceback(exc_info[2]) from e File "/meltano_dataset_sync/.meltano/extractors/tap-postgres/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1971, in _exec_single_context self.dialect.do_execute( File "/meltano_dataset_sync/.meltano/extractors/tap-postgres/venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute cursor.execute(statement, parameters) sqlalchemy.exc.InternalError: (psycopg2.errors.InternalError_) casting to `regclass` requires a string or number literal LINE 5: ...' AND pg_catalog.pg_sequence.seqrelid = CAST(CAST(pg_catalog... ^ [SQL: SELECT pg_catalog.pg_attribute.attname AS name, pg_catalog.format_type(pg_catalog.pg_attribute.atttypid, pg_catalog.pg_attribute.atttypmod) AS format_type, (SELECT pg_catalog.pg_get_expr(pg_catalog.pg_attrdef.adbin, pg_catalog.pg_attrdef.adrelid) AS pg_get_expr_1 FROM pg_catalog.pg_attrdef WHERE pg_catalog.pg_attrdef.adrelid = pg_catalog.pg_attribute.attrelid AND pg_catalog.pg_attrdef.adnum = pg_catalog.pg_attribute.attnum AND pg_catalog.pg_attribute.atthasdef) AS "default", pg_catalog.pg_attribute.attnotnull AS not_null, pg_catalog.pg_class.relname AS table_name, pg_catalog.pg_description.description AS comment, pg_catalog.pg_attribute.attgenerated AS generated, (SELECT json_build_object(%(json_build_object_2)s, pg_catalog.pg_attribute.attidentity = %(attidentity_1)s, %(json_build_object_3)s, pg_catalog.pg_sequence.seqstart, %(json_build_object_4)s, pg_catalog.pg_sequence.seqincrement, %(json_build_object_5)s, pg_catalog.pg_sequence.seqmin, %(json_build_object_6)s, pg_catalog.pg_sequence.seqmax, %(json_build_object_7)s, pg_catalog.pg_sequence.seqcache, %(json_build_object_8)s, pg_catalog.pg_sequence.seqcycle) AS json_build_object_1 FROM pg_catalog.pg_sequence WHERE pg_catalog.pg_attribute.attidentity != %(attidentity_2)s AND pg_catalog.pg_sequence.seqrelid = CAST(CAST(pg_catalog.pg_get_serial_sequence(CAST(CAST(pg_catalog.pg_attribute.attrelid AS REGCLASS) AS TEXT), pg_catalog.pg_attribute.attname) AS REGCLASS) AS OID)) AS identity_options FROM pg_catalog.pg_class LEFT OUTER JOIN pg_catalog.pg_attribute ON pg_catalog.pg_class.oid = pg_catalog.pg_attribute.attrelid AND pg_catalog.pg_attribute.attnum > %(attnum_1)s AND NOT pg_catalog.pg_attribute.attisdropped LEFT OUTER JOIN pg_catalog.pg_description ON pg_catalog.pg_description.objoid = pg_catalog.pg_attribute.attrelid AND pg_catalog.pg_description.objsubid = pg_catalog.pg_attribute.attnum JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace WHERE pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_namespace.nspname = %(nspname_1)s AND pg_catalog.pg_class.relname IN (%(filter_names_1)s) ORDER BY pg_catalog.pg_class.relname, pg_catalog.pg_attribute.attnum] [parameters: {'json_build_object_2': 'always', 'attidentity_1': 'a', 'json_build_object_3': 'start', 'json_build_object_4': 'increment', 'json_build_object_5': 'minvalue', 'json_build_object_6': 'maxvalue', 'json_build_object_7': 'cache', 'json_build_object_8': 'cycle', 'attidentity_2': '', 'attnum_1': 0, 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'information_schema', 'filter_names_1': 'sql_implementation_info'}] (Background on this error at: https://sqlalche.me/e/20/2j85) . For more detailed log messages re-run the command using 'meltano --log-level=debug ...' CLI flag. Note that you can also check the generated log file at '/meltano_dataset_sync/.meltano/logs/elt/dataset_t1948d1431_nodes_dataset/067a3e15-b473-4c56-b84a-b7d008296d44/elt.log'. For more information on debugging and logging: https://docs.meltano.com/reference/command-line-interface#debugging
</code>
</details>

**Comment by BTheunissen** [comment]
Hi folks, I was also able to reproduce the error in another part of the application (Meltano) that leverages SQLAlchemy 2.+ under the hood to get metadata about the database tables. It is the same cast error as above after I manually define the schema to avoid the prior error, so thinking this one cast error may be the root cause.

[edgedb_elt_stacktrace.txt](https://github.com/edgedb/edgedb/files/14962727/edgedb_elt_stacktrace.txt)

**Comment by danew** [comment]
Hi @aljazerzen are there any updates on this bug?

I just tried this again on the latest version of EdgeDB (5.2+ddd8aa4) and still running into the same issue with casting to `regclass`.

**Comment by aljazerzen** [comment]
From what I see here, I suspect that this is hitting the boundaries of the emulation of PostgreSQL behavior that EdgeDB exposes.

I'll take a look.
