### ISSUE TITLE
AssertionError when creating a scalar type with the same name as an existing object type in esdl

### ISSUE THREAD

**Issue by XeniaLu** [edgedb/edgedb#7170]
- EdgeDB Version: 4.5+28216a1
- EdgeDB CLI Version: 4.1.0+03ae624
- OS Version: Linux version 6.7.9-arch1-1

An `AssertionError` is raised when attempting to create a scalar type with the same name as an existing object type. However, if the scalar type is created first followed by the object type with the same name, the expected error "object was already declared" is displayed. Below is the schema and the associated error output.

Schema:

```esdl
module default {
  type A {
    required v: str;
  };
  scalar type A extending str;
}
```

Output:

```bash
$ edgedb migration create
edgedb error: InternalServerError: AssertionError: 
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "/edgedb/portable/4.5/lib/python3.11/site-packages/edb/server/compiler_pool/worker.py", line 178, in compile
          units, cstate = COMPILER.compile(
                          ^^^^^^^^^^^^^^^^^
        File "/edgedb/portable/4.5/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 886, in compile
          unit_group = compile(ctx=ctx, source=source)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/edgedb/portable/4.5/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 2316, in compile
          return _try_compile(ctx=ctx, source=source)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/edgedb/portable/4.5/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 2377, in _try_compile
          comp, capabilities = _compile_dispatch_ql(
                               ^^^^^^^^^^^^^^^^^^^^^
        File "/edgedb/portable/4.5/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 2222, in _compile_dispatch_ql
          query = ddl.compile_dispatch_ql_migration(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/edgedb/portable/4.5/lib/python3.11/site-packages/edb/server/compiler/ddl.py", line 378, in compile_dispatch_ql_migration
          return _start_migration(ctx, ql, in_script)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/edgedb/portable/4.5/lib/python3.11/site-packages/edb/server/compiler/ddl.py", line 459, in _start_migration
          target_schema = s_ddl.apply_sdl(
                          ^^^^^^^^^^^^^^^^
        File "/edgedb/portable/4.5/lib/python3.11/site-packages/edb/schema/ddl.py", line 567, in apply_sdl
          ddl_stmts = s_decl.sdl_to_ddl(target_schema, documents)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/edgedb/portable/4.5/lib/python3.11/site-packages/edb/edgeql/declarative.py", line 408, in sdl_to_ddl
          trace_layout(decl_ast, ctx=ctx)
        File "/edgedb/portable/4.5/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/edgedb/portable/4.5/lib/python3.11/site-packages/edb/edgeql/declarative.py", line 561, in trace_layout_CreateObjectType
          _trace_item_layout(node, ctx=ctx)
        File "/edgedb/portable/4.5/lib/python3.11/site-packages/edb/edgeql/declarative.py", line 641, in _trace_item_layout
          assert isinstance(obj, qltracer.Source)
      AssertionError
```

Expected:

When creating a scalar type with the same name as an existing object type, the migration script returns a clear error message indicating that the object was already declared, similar to the behavior observed when creating an object type with the same name as an existing scalar type, like:

For Schema:

```esdl
module default {
  scalar type A extending str;
  type A {
    required v: str;
  };
}
```

```bash
$ edgedb migration create
error: object 'default::A' was already declared
  ┌─ dbschema/default.esdl:3:3
  │  
3 │ ╭   type A {
4 │ │     required v: str;
5 │ │   };
  │ ╰───^ error

edgedb error: cannot proceed until .esdl files are fixed

```

**Comment by XeniaLu** [comment]
Additionally, if the existing object type doesn't have any properties or links, creating a scalar type with the same name would still return a clear error message.

Schema:
```esdl
module default {
  type A {
    # No properties or links
  }
  scalar type A extending str;
}
```

Output:
```bash
$ edgedb migration create
error: scalar 'default::A' was already declared
  ┌─ /dbschema/default.esdl:5:3
  │
5 │   scalar type A extending str;
  │   ^^^^^^^^^^^^^^^^^^^^^^^^^^^ error

edgedb error: cannot proceed until .esdl files are fixed
```

After reading the source code, I noted that the `ctx.objects` is indexed based on object full names. So when a `CreateScalarType` with the same name follows an existing `CreateObjectType`, the existing `CreateObjectType` is [overwritten](https://github.com/edgedb/edgedb/blob/master/edb/edgeql/declarative.py#L397) in `ctx.objects`. This leads to an `AssertionErrorthe ` when processing the sub-commands of `CreateObjectType` such as `CreateConcretePointer`.
