### ISSUE TITLE
Internal server error when running query

### ISSUE THREAD

**Issue by gregdingle** [edgedb/edgedb#7340]
- EdgeDB Version: "4.2+8778fc1"
- EdgeDB CLI Version: EdgeDB CLI 5.1.0+8ff9f85
- OS Version: MacOS

Steps to Reproduce:

1. Run the [query here](https://gist.github.com/gregdingle/cb97e6e164eb1955447ca4a2a1a90997) in either CLI or cloud UI
2. See `edb.errors.InternalServerError`
3. See traceback

```
edgedb error: InternalServerError: None
  Server traceback:
      Traceback (most recent call last):
        File "/local/edgedb-server/lib/python3.11/site-packages/edb/pgsql/compiler/__init__.py", line 140, in compile_ir_to_sql_tree
          qtree = dispatch.compile(ir_expr, ctx=ctx)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/local/edgedb-server/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/local/edgedb-server/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 60, in compile_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/local/edgedb-server/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 115, in _compile_set_impl
          _compile_set(ir_set, ctx=ctx)
        File "/local/edgedb-server/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 710, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/local/edgedb-server/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 165, in get_set_rvar
          return _process_toplevel_query(ir_set, ctx=ctx)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/local/edgedb-server/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 287, in _process_toplevel_query
          rvars = _get_set_rvar(ir_set, ctx=ctx)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/local/edgedb-server/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 369, in _get_set_rvar
          return process_set_as_subquery(ir_set, ctx=ctx)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/local/edgedb-server/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 1446, in process_set_as_subquery
          dispatch.visit(expr, ctx=newctx)
        File "/local/edgedb-server/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/local/edgedb-server/lib/python3.11/site-packages/edb/pgsql/compiler/dispatch.py", line 44, in visit
          compile(ir, ctx=ctx)
        File "/local/edgedb-server/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/local/edgedb-server/lib/python3.11/site-packages/edb/pgsql/compiler/stmt.py", line 60, in compile_SelectStmt
          clauses.compile_materialized_exprs(query, stmt, ctx=ctx)
        File "/local/edgedb-server/lib/python3.11/site-packages/edb/pgsql/compiler/clauses.py", line 142, in compile_materialized_exprs
          mat_qry = relgen.set_as_subquery(
                    ^^^^^^^^^^^^^^^^^^^^^^^
        File "/local/edgedb-server/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 528, in set_as_subquery
          dispatch.visit(ir_set, ctx=subctx)
        File "/local/edgedb-server/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/local/edgedb-server/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 85, in visit_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/local/edgedb-server/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 111, in _compile_set_impl
          _compile_set(ir_set, ctx=scopectx)
        File "/local/edgedb-server/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 710, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/local/edgedb-server/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 223, in get_set_rvar
          rvars = _get_set_rvar(ir_set, ctx=subctx)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/local/edgedb-server/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 369, in _get_set_rvar
          return process_set_as_subquery(ir_set, ctx=ctx)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/local/edgedb-server/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 1446, in process_set_as_subquery
          dispatch.visit(expr, ctx=newctx)
        File "/local/edgedb-server/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/local/edgedb-server/lib/python3.11/site-packages/edb/pgsql/compiler/dispatch.py", line 44, in visit
          compile(ir, ctx=ctx)
        File "/local/edgedb-server/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/local/edgedb-server/lib/python3.11/site-packages/edb/pgsql/compiler/stmt.py", line 143, in compile_GroupStmt
          return group.compile_group(stmt, ctx=ctx)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/local/edgedb-server/lib/python3.11/site-packages/edb/pgsql/compiler/group.py", line 393, in compile_group
          return _compile_group(stmt, ctx=sctx, parent_ctx=ctx)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/local/edgedb-server/lib/python3.11/site-packages/edb/pgsql/compiler/group.py", line 182, in _compile_group
          dispatch.visit(stmt.subject, ctx=subjctx)
        File "/local/edgedb-server/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/local/edgedb-server/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 85, in visit_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/local/edgedb-server/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 111, in _compile_set_impl
          _compile_set(ir_set, ctx=scopectx)
        File "/local/edgedb-server/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 710, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/local/edgedb-server/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 223, in get_set_rvar
          rvars = _get_set_rvar(ir_set, ctx=subctx)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/local/edgedb-server/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 369, in _get_set_rvar
          return process_set_as_subquery(ir_set, ctx=ctx)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/local/edgedb-server/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 1446, in process_set_as_subquery
          dispatch.visit(expr, ctx=newctx)
        File "/local/edgedb-server/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/local/edgedb-server/lib/python3.11/site-packages/edb/pgsql/compiler/dispatch.py", line 44, in visit
          compile(ir, ctx=ctx)
        File "/local/edgedb-server/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/local/edgedb-server/lib/python3.11/site-packages/edb/pgsql/compiler/stmt.py", line 94, in compile_SelectStmt
          outvar = clauses.compile_output(stmt.result, ctx=ictx)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/local/edgedb-server/lib/python3.11/site-packages/edb/pgsql/compiler/clauses.py", line 227, in compile_output
          dispatch.visit(ir_set, ctx=newctx)
        File "/local/edgedb-server/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/local/edgedb-server/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 85, in visit_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/local/edgedb-server/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 111, in _compile_set_impl
          _compile_set(ir_set, ctx=scopectx)
        File "/local/edgedb-server/lib/python3.11/site-packages/edb/pgsql/compiler/expr.py", line 710, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/local/edgedb-server/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 223, in get_set_rvar
          rvars = _get_set_rvar(ir_set, ctx=subctx)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/local/edgedb-server/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 369, in _get_set_rvar
          return process_set_as_subquery(ir_set, ctx=ctx)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/local/edgedb-server/lib/python3.11/site-packages/edb/pgsql/compiler/relgen.py", line 1446, in process_set_as_subquery
          dispatch.visit(expr, ctx=newctx)
        File "/local/edgedb-server/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/local/edgedb-server/lib/python3.11/site-packages/edb/pgsql/compiler/dispatch.py", line 44, in visit
          compile(ir, ctx=ctx)
        File "/local/edgedb-server/lib/python3.11/functools.py", line 909, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/local/edgedb-server/lib/python3.11/site-packages/edb/pgsql/compiler/stmt.py", line 60, in compile_SelectStmt
          clauses.compile_materialized_exprs(query, stmt, ctx=ctx)
        File "/local/edgedb-server/lib/python3.11/site-packages/edb/pgsql/compiler/clauses.py", line 122, in compile_materialized_exprs
          assert mat_set.finalized
      AssertionError

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "/local/edgedb-server/lib/python3.11/site-packages/edb/server/compiler_pool/multitenant_worker.py", line 336, in call_for_client
          return meth(client_id, dbname, *args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/local/edgedb-server/lib/python3.11/site-packages/edb/server/compiler_pool/multitenant_worker.py", line 198, in compile
          units, cstate = COMPILER.compile(
                          ^^^^^^^^^^^^^^^^^
        File "/local/edgedb-server/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 885, in compile
          unit_group = compile(ctx=ctx, source=source)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/local/edgedb-server/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 2309, in compile
          return _try_compile(ctx=ctx, source=source)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/local/edgedb-server/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 2370, in _try_compile
          comp, capabilities = _compile_dispatch_ql(
                               ^^^^^^^^^^^^^^^^^^^^^
        File "/local/edgedb-server/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 2283, in _compile_dispatch_ql
          query = _compile_ql_query(ctx, ql, script_info=script_info)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/local/edgedb-server/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 1716, in _compile_ql_query
          sql_res = pg_compiler.compile_ir_to_sql_tree(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/local/edgedb-server/lib/python3.11/site-packages/edb/pgsql/compiler/__init__.py", line 157, in compile_ir_to_sql_tree
          raise errors.InternalServerError(*args) from e
      edb.errors.InternalServerError: None
```

**Comment by gregdingle** [comment]
Update: I just reproed after upgrading to 5.2. The error message in the cloud UI changed to 
```
InternalServerError: materialized set was not finalized!
```

After another search, it sounds similar to this issue: https://github.com/edgedb/edgedb/issues/7320.
