### ISSUE TITLE
Cannot create schema migration 

### ISSUE THREAD

**Issue by norregaarden** [edgedb/edgedb#7532]
- EdgeDB Version: 5.5
- EdgeDB CLI Version:EdgeDB CLI 5.1.0+7c5764f
- OS Version:Ubuntu WSL Windows 10

Steps to Reproduce:

(I have tried: edgedb migration extract, doesn't help)

1. edgedb watch 
2. obtain error: Schema migration error: InternalServerError: LookupError: reference to a non-existent schema item 4bd02eeb-3d0d-11ef-80ee-09b55274a723 in schema <FlatSchema gen:1 at 0x7f1af27d4680>
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at 
https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
EdgeDB Watch initialized.

or 1. edgedb migration create
2. obtain error:edgedb error: InternalServerError: LookupError: reference to a non-existent schema item 4bd02eeb-3d0d-11ef-80ee-09b55274a723
in schema <FlatSchema gen:1 at 0x7f1af27d4680>
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "/home/newusername/.local/share/edgedb/portable/5.5/lib/python3.12/site-packages/edb/server/compiler_pool/worker.py", line 210, in compile_in_tx
          units, cstate = COMPILER.compile_in_tx_request(cstate, *args, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/newusername/.local/share/edgedb/portable/5.5/lib/python3.12/site-packages/edb/server/compiler/compiler.py", line 977, in compile_in_tx_request
          units, cstate = self.compile_in_tx(
                          ^^^^^^^^^^^^^^^^^^^
        File "/home/newusername/.local/share/edgedb/portable/5.5/lib/python3.12/site-packages/edb/server/compiler/compiler.py", line 1037, in compile_in_tx
          return compile(ctx=ctx, source=source), ctx.state
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/newusername/.local/share/edgedb/portable/5.5/lib/python3.12/site-packages/edb/server/compiler/compiler.py", line 2586, in compile
          return _try_compile(ctx=ctx, source=original)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/newusername/.local/share/edgedb/portable/5.5/lib/python3.12/site-packages/edb/server/compiler/compiler.py", line 2667, in _try_compile
          comp, capabilities = _compile_dispatch_ql(
                               ^^^^^^^^^^^^^^^^^^^^^
        File "/home/newusername/.local/share/edgedb/portable/5.5/lib/python3.12/site-packages/edb/server/compiler/compiler.py", line 2494, in _compile_dispatch_ql
          query = ddl.compile_dispatch_ql_migration(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/newusername/.local/share/edgedb/portable/5.5/lib/python3.12/site-packages/edb/server/compiler/ddl.py", line 392, in compile_dispatch_ql_migration
          return _describe_current_migration(ctx, ql)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/newusername/.local/share/edgedb/portable/5.5/lib/python3.12/site-packages/edb/server/compiler/ddl.py", line 625, in _describe_current_migration
          proposed_ddl = s_ddl.statements_from_delta(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/newusername/.local/share/edgedb/portable/5.5/lib/python3.12/site-packages/edb/schema/ddl.py", line 802, in statements_from_delta
          stmts = ddlast_from_delta(
                  ^^^^^^^^^^^^^^^^^^
        File "/home/newusername/.local/share/edgedb/portable/5.5/lib/python3.12/site-packages/edb/schema/ddl.py", line 780, in ddlast_from_delta
          schema = command.apply(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/newusername/.local/share/edgedb/portable/5.5/lib/python3.12/site-packages/edb/schema/delta.py", line 3634, in apply
          schema = self._alter_innards(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/newusername/.local/share/edgedb/portable/5.5/lib/python3.12/site-packages/edb/schema/delta.py", line 3308, in _alter_innards
          return self.apply_subcommands(schema, context)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/newusername/.local/share/edgedb/portable/5.5/lib/python3.12/site-packages/edb/schema/delta.py", line 999, in apply_subcommands
          schema = op.apply(schema, context=context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/newusername/.local/share/edgedb/portable/5.5/lib/python3.12/site-packages/edb/schema/delta.py", line 3207, in apply
          schema = self._create_begin(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/newusername/.local/share/edgedb/portable/5.5/lib/python3.12/site-packages/edb/schema/constraints.py", line 1172, in _create_begin
          return super()._create_begin(schema, context)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/newusername/.local/share/edgedb/portable/5.5/lib/python3.12/site-packages/edb/schema/referencing.py", line 1108, in _create_begin
          return super()._create_begin(schema, context)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/newusername/.local/share/edgedb/portable/5.5/lib/python3.12/site-packages/edb/schema/referencing.py", line 683, in _create_begin
          schema = referrer.add_classref(schema, refdict.attr, self.scls)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/newusername/.local/share/edgedb/portable/5.5/lib/python3.12/site-packages/edb/schema/objects.py", line 1544, in add_classref
          schema, all_coll = coll.update(schema, [obj])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/newusername/.local/share/edgedb/portable/5.5/lib/python3.12/site-packages/edb/schema/objects.py", line 2694, in update
          items = dict(self.items(schema))
                       ^^^^^^^^^^^^^^^^^^
        File "/home/newusername/.local/share/edgedb/portable/5.5/lib/python3.12/site-packages/edb/schema/objects.py", line 2725, in items
          obj = schema.get_by_id(item_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/newusername/.local/share/edgedb/portable/5.5/lib/python3.12/site-packages/edb/schema/schema.py", line 2004, in _get_by_id
          obj = self._global_schema.get_by_id(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/newusername/.local/share/edgedb/portable/5.5/lib/python3.12/site-packages/edb/schema/schema.py", line 1339, in _get_by_id
          raise LookupError(
      LookupError: reference to a non-existent schema item 4bd02eeb-3d0d-11ef-80ee-09b55274a723 in schema <FlatSchema gen:1 at 0x7f1af27d4680>

Schema:

**Comment by aljazerzen** [comment]
@norregaarden Can you provide the starting schema and the schema that you are trying to migrate to.

Or your whole `dbschema/` directory if that is possible. If you are not willing to share that publicly, you can email it to aljaz@edgedb.com

**Comment by msullivan** [comment]
Sorry, there's not enough information to reproduce anything here.
