### ISSUE TITLE
Schema migration error InternalServerError: LookupError: schema class 'Property' has no field 'on_target_delete'

### ISSUE THREAD

**Issue by ccsv** [edgedb/edgedb#7577]
InternalServerError: LookupError: schema class 'Property' has no field 'on_target_delete'

 edgedb migration create
Connecting to EdgeDB instance 'Themis' at localhost:10700...
edgedb error: InternalServerError: LookupError: schema class 'Property' has no field 'on_target_delete'
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "/home/edgedb/.local/share/edgedb/portable/4.7/lib/python3.11/site-packages/edb/server/compiler_pool/worker.py", line 178, in compile
          units, cstate = COMPILER.compile(
                          ^^^^^^^^^^^^^^^^^
        File "/home/edgedb/.local/share/edgedb/portable/4.7/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 887, in compile
          unit_group = compile(ctx=ctx, source=source)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/edgedb/.local/share/edgedb/portable/4.7/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 2317, in compile
          return _try_compile(ctx=ctx, source=source)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/edgedb/.local/share/edgedb/portable/4.7/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 2386, in _try_compile
          comp, capabilities = _compile_dispatch_ql(
                               ^^^^^^^^^^^^^^^^^^^^^
        File "/home/edgedb/.local/share/edgedb/portable/4.7/lib/python3.11/site-packages/edb/server/compiler/compiler.py", line 2223, in _compile_dispatch_ql
          query = ddl.compile_dispatch_ql_migration(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/edgedb/.local/share/edgedb/portable/4.7/lib/python3.11/site-packages/edb/server/compiler/ddl.py", line 378, in compile_dispatch_ql_migration
          return _start_migration(ctx, ql, in_script)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/edgedb/.local/share/edgedb/portable/4.7/lib/python3.11/site-packages/edb/server/compiler/ddl.py", line 459, in _start_migration
          target_schema = s_ddl.apply_sdl(
                          ^^^^^^^^^^^^^^^^
        File "/home/edgedb/.local/share/edgedb/portable/4.7/lib/python3.11/site-packages/edb/schema/ddl.py", line 571, in apply_sdl
          process(ddl_stmt)
        File "/home/edgedb/.local/share/edgedb/portable/4.7/lib/python3.11/site-packages/edb/schema/ddl.py", line 518, in process
          target_schema = delta.apply(target_schema, context)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/edgedb/.local/share/edgedb/portable/4.7/lib/python3.11/site-packages/edb/schema/delta.py", line 1579, in apply
          schema = self.apply_subcommands(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/edgedb/.local/share/edgedb/portable/4.7/lib/python3.11/site-packages/edb/schema/delta.py", line 1606, in apply_subcommands
          schema = objop.apply(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/edgedb/.local/share/edgedb/portable/4.7/lib/python3.11/site-packages/edb/schema/delta.py", line 3584, in apply
          schema = self._alter_innards(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/edgedb/.local/share/edgedb/portable/4.7/lib/python3.11/site-packages/edb/schema/delta.py", line 3258, in _alter_innards
          return self.apply_subcommands(schema, context)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/edgedb/.local/share/edgedb/portable/4.7/lib/python3.11/site-packages/edb/schema/delta.py", line 976, in apply_subcommands
          schema = op.apply(schema, context=context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/edgedb/.local/share/edgedb/portable/4.7/lib/python3.11/site-packages/edb/schema/unknown_pointers.py", line 134, in apply
          rschema = ncmd.apply(schema, context)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/edgedb/.local/share/edgedb/portable/4.7/lib/python3.11/site-packages/edb/schema/delta.py", line 3157, in apply
          schema = self._create_begin(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/edgedb/.local/share/edgedb/portable/4.7/lib/python3.11/site-packages/edb/schema/referencing.py", line 1094, in _create_begin
          return super()._create_begin(schema, context)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/edgedb/.local/share/edgedb/portable/4.7/lib/python3.11/site-packages/edb/schema/referencing.py", line 660, in _create_begin
          schema = super()._create_begin(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/edgedb/.local/share/edgedb/portable/4.7/lib/python3.11/site-packages/edb/schema/inheriting.py", line 755, in _create_begin
          schema = super()._create_begin(schema, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/edgedb/.local/share/edgedb/portable/4.7/lib/python3.11/site-packages/edb/schema/delta.py", line 3040, in _create_begin
          self.update_field_status(schema, context)
        File "/home/edgedb/.local/share/edgedb/portable/4.7/lib/python3.11/site-packages/edb/schema/inheriting.py", line 54, in update_field_status
          super().update_field_status(schema, context)
        File "/home/edgedb/.local/share/edgedb/portable/4.7/lib/python3.11/site-packages/edb/schema/delta.py", line 2598, in update_field_status
          computed_status = self._get_computed_status_of_fields(schema, context)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/edgedb/.local/share/edgedb/portable/4.7/lib/python3.11/site-packages/edb/schema/delta.py", line 2257, in _get_computed_status_of_fields
          field = mcls.get_field(op.property)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/edgedb/.local/share/edgedb/portable/4.7/lib/python3.11/site-packages/edb/schema/objects.py", line 866, in get_field
          raise LookupError(
      LookupError: schema class 'Property' has no field 'on_target_delete'

- EdgeDB Version:4.7+cf1464b
- EdgeDB CLI Version: EdgeDB CLI 5.2.1+213dba6
- OS Version: Windows 10

Steps to Reproduce:

1. run  edgedb migration create

**Comment by ccsv** [comment]
After some debugging I found out what caused this. A deletion policy was added to an enum field. Can this be checked when you run migration create?
