### ISSUE TITLE
Flaky test: test_edgeql_extensions_06

### ISSUE THREAD

**Issue by fantix** [edgedb/edgedb#7819]
- EdgeDB Version:   94da38a

```
================================================================================
ERROR: test_edgeql_extensions_06 (test_edgeql_extensions.TestDDLExtensions.test_edgeql_extensions_06)
--------------------------------------------------------------------------------
Py_HashSecret: 9874623529b4883ebe6dc64cd4b1d6046e3483b9c15570af
random.seed(): d2c62d166914dd6d
--------------------------------------------------------------------------------
Server Traceback:
Traceback (most recent call last):
  File "edb/server/protocol/binary.pyx", line 976, in edb.server.protocol.binary.EdgeConnection.main_step
    await self.execute()
  File "edb/server/protocol/binary.pyx", line 856, in execute
    query_req, allow_capabilities = self.parse_execute_request()
  File "edb/server/protocol/binary.pyx", line 791, in edb.server.protocol.binary.EdgeConnection.parse_execute_request
    raise
  File "edb/server/protocol/binary.pyx", line 788, in edb.server.protocol.binary.EdgeConnection.parse_execute_request
    _dbview.decode_state(state_tid, state_data)
  File "edb/server/dbview/dbview.pyx", line 833, in edb.server.dbview.dbview.DatabaseConnectionView.decode_state
    raise errors.StateMismatchError(
edb.errors.StateMismatchError: Cannot decode state: type mismatch

Test Traceback:
Traceback (most recent call last):
  File "/home/runner/work/edgedb/edgedb/edb/testbase/server.py", line 981, in setUp
    self.loop.run_until_complete(
  File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/site-packages/edgedb/abstract.py", line 299, in execute
    await self._execute(ExecuteContext(
  File "/home/runner/work/edgedb/edgedb/edb/testbase/connection.py", line 380, in _execute
    await self._protocol.execute(
  File "edgedb/protocol/protocol.pyx", line 559, in execute
  File "edgedb/protocol/protocol.pyx", line 464, in _execute
edgedb.errors.StateMismatchError: Cannot decode state: type mismatch
```

**Comment by msullivan** [comment]
I am pretty sure I fixed this.
