### ISSUE TITLE
SQL connector support currently broken with Metabase (JDBC)

### ISSUE THREAD

**Issue by tomnz** [edgedb/edgedb#7928]
- EdgeDB Version: 5.6+0521607
- EdgeDB CLI Version: 5.5.2+a5c8312
- OS Version: Debian Bullseye

SQL support currently appears to be broken when attempting to connect with Metabase. This is listed as one of the "tested" tools, and we ourselves had it working 6+ months ago, so something has broken in the intervening months.

Steps to Reproduce:

1. Run latest v5 EdgeDB container locally, and configure it with a user/database. (Schema is irrelevant, although probably want some tables to assess whether it's working).
2. Run latest [Metabase container](https://www.metabase.com/docs/latest/installation-and-operation/running-metabase-on-docker) locally.
3. In a terminal, run `docker logs -f metabase` to observe logging.
4. Under admin settings -> database, add a new Postgres database with host `host.docker.internal` and port 5656, with the user/password/database configured in step 1.
6. (At any time from this UI, hit "Sync database schema now" to re-attempt fetching of the schema).
7. Exit the admin settings, go to databases and pull up the database you just added.
8. You should observe that "the database doesn't have any tables".
9. In the Metabase logs, you should observe an error like `ERROR: incorrect binary data format in bind parameter 1`. [Here's a full example](https://gist.github.com/tomnz/8f4c8114992f243c2c361bd21ae9ef39).

This appears to point to an issue with the EdgeDB Postgres protocol accepting binary data.

I discovered that there is a JDBC option (which can be configured in the Metabase connection settings) to set `binaryTransfer=false`. This causes the error message to disappear, but again no tables ever appear after syncing the database metadata. Here's a sample of the log messages with this option enabled:

![image](https://github.com/user-attachments/assets/8b37c71d-2eca-41eb-b66e-5362d45ad119)

Just to confirm - I am able to connect to the same database just fine with `psql`, and using `\d` shows tables correctly etc. So this seems to be some sort of issue with either the way Metabase is querying for tables, or the JDBC connector - something about which trips up the EdgeDB wire protocol implementation.

It's possible that this might be fixed with something like #7886, but that has not been released yet, and I have not tested it.

**Comment by ruizehung** [comment]
Same issue here with Edgedb 5.7. Any update on this?

**Comment by ruizehung** [comment]
With Gel 6.1, I'm no longer getting `ERROR: incorrect binary data format in bind parameter 1`. But I get `relation "public.XXXX" does not exist` error. Details here https://github.com/geldata/gel/issues/8457

**Comment by ruizehung** [comment]
I tested Gel `6.1+299edfe` out with [superset](https://github.com/apache/superset) commit hash `f45ab70080250fad5c1573e283d6df48f8f6b4ce`. And seems like it's getting `psycopg2.errors.IndeterminateDatatype: could not determine data type of parameter $1` when I select a table from "See Table Schema"

<img width="412" alt="Image" src="https://github.com/user-attachments/assets/b5be2378-7c60-4b08-8d6f-38d550941d0b" />

```
superset_app          | 2025-03-10 04:28:44,186:WARNING:superset.views.error_handling:Exception
superset_app          | Traceback (most recent call last):
superset_app          |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
superset_app          |     self.dialect.do_execute(
superset_app          |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
superset_app          |     cursor.execute(statement, parameters)
superset_app          | psycopg2.errors.IndeterminateDatatype: could not determine data type of parameter $1
superset_app          | 
superset_app          | 
superset_app          | The above exception was the direct cause of the following exception:
superset_app          | 
superset_app          | Traceback (most recent call last):
superset_app          |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
superset_app          |     rv = self.dispatch_request()
superset_app          |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
superset_app          |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
superset_app          |   File "/usr/local/lib/python3.10/site-packages/flask_appbuilder/security/decorators.py", line 95, in wraps
superset_app          |     return f(self, *args, **kwargs)
superset_app          |   File "/app/superset/views/base_api.py", line 119, in wraps
superset_app          |     duration, response = time_function(f, self, *args, **kwargs)
superset_app          |   File "/app/superset/utils/core.py", line 1364, in time_function
superset_app          |     response = func(*args, **kwargs)
superset_app          |   File "/app/superset/utils/log.py", line 303, in wrapper
superset_app          |     value = f(*args, **kwargs)
superset_app          |   File "/app/superset/databases/api.py", line 1024, in table_metadata
superset_app          |     payload = database.db_engine_spec.get_table_metadata(database, table)
superset_app          |   File "/app/superset/db_engine_specs/base.py", line 1079, in get_table_metadata
superset_app          |     return get_table_metadata(database, table)
superset_app          |   File "/app/superset/databases/utils.py", line 75, in get_table_metadata
superset_app          |     columns = database.get_columns(table)
superset_app          |   File "/app/superset/models/core.py", line 940, in get_columns
superset_app          |     return self.db_engine_spec.get_columns(
superset_app          |   File "/app/superset/db_engine_specs/base.py", line 1582, in get_columns
superset_app          |     inspector.get_columns(table.table, table.schema),
superset_app          |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/reflection.py", line 497, in get_columns
superset_app          |     col_defs = self.dialect.get_columns(
superset_app          |   File "<string>", line 2, in get_columns
superset_app          |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/reflection.py", line 55, in cache
superset_app          |     ret = fn(self, con, *args, **kw)
superset_app          |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/base.py", line 3918, in get_columns
superset_app          |     c = connection.execute(s, dict(table_oid=table_oid))
superset_app          |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
superset_app          |     return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
superset_app          |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
superset_app          |     return connection._execute_clauseelement(
superset_app          |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
superset_app          |     ret = self._execute_context(
superset_app          |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
superset_app          |     self._handle_dbapi_exception(
superset_app          |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
superset_app          |     util.raise_(
superset_app          |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
superset_app          |     raise exception
superset_app          |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
superset_app          |     self.dialect.do_execute(
superset_app          |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
superset_app          |     cursor.execute(statement, parameters)
superset_app          | sqlalchemy.exc.ProgrammingError: (psycopg2.errors.IndeterminateDatatype) could not determine data type of parameter $1
superset_app          | 
superset_app          | [SQL: 
superset_app          |             SELECT a.attname,
superset_app          |               pg_catalog.format_type(a.atttypid, a.atttypmod),
superset_app          |               (
superset_app          |                 SELECT pg_catalog.pg_get_expr(d.adbin, d.adrelid)
superset_app          |                 FROM pg_catalog.pg_attrdef d
superset_app          |                 WHERE d.adrelid = a.attrelid AND d.adnum = a.attnum
superset_app          |                 AND a.atthasdef
superset_app          |               ) AS DEFAULT,
superset_app          |               a.attnotnull,
superset_app          |               a.attrelid as table_oid,
superset_app          |               pgd.description as comment,
superset_app          |               a.attgenerated as generated,
superset_app          |                               (SELECT json_build_object(
superset_app          |                     'always', a.attidentity = 'a',
superset_app          |                     'start', s.seqstart,
superset_app          |                     'increment', s.seqincrement,
superset_app          |                     'minvalue', s.seqmin,
superset_app          |                     'maxvalue', s.seqmax,
superset_app          |                     'cache', s.seqcache,
superset_app          |                     'cycle', s.seqcycle)
superset_app          |                 FROM pg_catalog.pg_sequence s
superset_app          |                 JOIN pg_catalog.pg_class c on s.seqrelid = c."oid"
superset_app          |                 WHERE c.relkind = 'S'
superset_app          |                 AND a.attidentity != ''
superset_app          |                 AND s.seqrelid = pg_catalog.pg_get_serial_sequence(
superset_app          |                     a.attrelid::regclass::text, a.attname
superset_app          |                 )::regclass::oid
superset_app          |                 ) as identity_options                
superset_app          |             FROM pg_catalog.pg_attribute a
superset_app          |             LEFT JOIN pg_catalog.pg_description pgd ON (
superset_app          |                 pgd.objoid = a.attrelid AND pgd.objsubid = a.attnum)
superset_app          |             WHERE a.attrelid = %(table_oid)s
superset_app          |             AND a.attnum > 0 AND NOT a.attisdropped
superset_app          |             ORDER BY a.attnum
superset_app          |         ]
superset_app          | [parameters: {'table_oid': 26045}]
superset_app          | (Background on this error at: https://sqlalche.me/e/14/f405)
```

But the good news is that querying works

<img width="1354" alt="Image" src="https://github.com/user-attachments/assets/2c292b14-3d77-4bd6-b467-43da9bd18f81" />

**Comment by aljazerzen** [comment]
@elprans
