### ISSUE TITLE
test_server_ops_multi_tenant is mysteriously failing in CI

### ISSUE THREAD

**Issue by msullivan** [edgedb/edgedb#7933]
See https://github.com/edgedb/edgedb/actions/runs/11558910310/job/32172731799

I can't reproduce locally.

```
Traceback (most recent call last):
  File "/home/runner/work/edgedb/edgedb/tests/test_server_ops.py", line 1338, in test_server_ops_multi_tenant
    await getattr(self, name)(mtargs)
  File "/home/runner/work/edgedb/edgedb/tests/test_server_ops.py", line 1429, in _test_server_ops_multi_tenant_3
    self.assertIn(
AssertionError: '\nedgedb_server_mt_config_reload_errors_total 0.0\n' not found in
...
```

`edgedb_server_mt_config_reload_errors_total` is 1.0 and should be 0.0.

I can't reproduce this locally, so I'm going to disable the test for now.

**Comment by fantix** [comment]
It looks like during the config reload, the config file might be partially written, leading to reload errors (and retries). I have dropped the error == 0 check in #8121
