### ISSUE TITLE
std::net tests fail frequently

### ISSUE THREAD

**Issue by msullivan** [edgedb/edgedb#7993]
```
=========================================================================================================================================================================
FAIL: test_http_std_net_con_schedule_request_bad_address (test_http_std_net.StdNetTestCase.test_http_std_net_con_schedule_request_bad_address)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Py_HashSecret: a7a52c3baba2579aaab84e1970a73214ea593b26f3652665
random.seed(): 4e4d2f54ac0b4372
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sully/src/e/edgedb/edb/testbase/server.py", line 209, in wrapper
    self.loop.run_until_complete(
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/sully/src/e/edgedb/tests/test_http_std_net.py", line 252, in test_http_std_net_con_schedule_request_bad_address
    table_result = await self._wait_for_request_completion(result.id)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sully/src/e/edgedb/tests/test_http_std_net.py", line 77, in _wait_for_request_completion
    self.assertNotEqual(state, 'InProgress')
AssertionError: 'InProgress' == 'InProgress'
```

Usually all three tests fail at once. The failure mode indicates that the request was made but the update isn't being made in the database.

Filing this for tracking; I'm doing some debugging and think I basically have it tracked down.

**Comment by msullivan** [comment]
Hypothesis confirmed. I augmented the `HTTP send failed (instance: %s)` to dump out the full exception info, and got:
```
------------------------------------------------- Exception occurred: unhandled errors in a TaskGroup (1 sub-exception) -------------------------------------------------

1. ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)

------------------------------------------------------------------------------- Traceback -------------------------------------------------------------------------------

    /home/sully/src/e/edgedb/edb/server/net_worker.py, line 54, in _http_task
        > async with (asyncio.TaskGroup() as g,):
    /usr/local/lib/python3.12/asyncio/taskgroups.py, line 145, in __aexit__
        > raise me from None

ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
-------------------------------------------------------------------------- Grouped exceptions ---------------------------------------------------------------------------


    ---------------------------------------------- Exception occurred: database branch 'ftsschema_1413760' does not exist -----------------------------------------------
    
    2. KeyError: 'ftsschema_1413760'
    
    ----------------------------------------------------------------------------- Traceback -----------------------------------------------------------------------------
    
        edb/server/dbview/dbview.pyx, line 1560, in edb.server.dbview.dbview.DatabaseIndex.get_db
            > return self._dbs[dbname]
    
    KeyError: 'ftsschema_1413760'
    
    ------------------------------------------------ During handling of the above exception, another exception occurred -------------------------------------------------
    
    1. edb.errors.UnknownDatabaseError: database branch 'ftsschema_1413760' does not exist
    
    ----------------------------------------------------------------------------- Traceback -----------------------------------------------------------------------------
    
        /home/sully/src/e/edgedb/edb/server/net_worker.py, line 63, in _http_task
            > json_bytes = await execute.parse_execute_json(
        edb/server/protocol/execute.pyx, line 732, in parse_execute_json
            > compiled, dbv = await _parse(
        edb/server/protocol/execute.pyx, line 190, in _parse
            > dbv = await tenant.new_dbview(
        /home/sully/src/e/edgedb/edb/server/tenant.py, line 1421, in new_dbview
            > db = self.get_db(dbname=dbname)
        /home/sully/src/e/edgedb/edb/server/tenant.py, line 361, in get_db
            > return self._dbindex.get_db(dbname)
        edb/server/dbview/dbview.pyx, line 1562, in edb.server.dbview.dbview.DatabaseIndex.get_db
            > raise errors.UnknownDatabaseError(
    
    ------------------------------------------------------------------------------ Details ------------------------------------------------------------------------------
    
    
    edb.errors.UnknownDatabaseError: database branch 'ftsschema_1413760' does not exist
```

The issue is that, since all the tasks are run in a TaskGroup, whenever one of the tasks or the toplevel task group code fails, all of the tasks get cancelled.

In this case, it looks like an exception is being raised because one of the databases got racily deleted.
I think similar failures could happen in the tasks themselves?

Possible solutions include (and maybe we want both):

- Make sure to always catch and swallow any possible error. (Which we probably want to do for this one, either way, so the loop can continue?)
- Don't use TaskGroup

Waiting until all tasks have completed has other potential problems, too. If one request takes a long time, then we won't make any other requests until it has resolved. (What is the timeout situation for requests? If it is short enough, this might not be a problem.)
