### ISSUE TITLE
Investigate CI crashes

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb#863]
```
================================================================================
6222ERROR: test_edgeql_tutorial (test_edgeql_tutorial.TestEdgeQLTutorial) {serialization='json'}
6223--------------------------------------------------------------------------------
6224Traceback (most recent call last):
6225  File "/home/travis/build/edgedb/edgedb/edb/testbase/server.py", line 105, in wrapper
6226    __meth__(self, *args, **kwargs))
6227  File "/opt/python/3.7.1/lib/python3.7/asyncio/base_events.py", line 573, in run_until_complete
6228    return future.result()
6229  File "/home/travis/build/edgedb/edgedb/tests/test_edgeql_tutorial.py", line 247, in test_edgeql_tutorial
6230    'name': 'Zendaya',
6231  File "/home/travis/build/edgedb/edgedb/edb/testbase/server.py", line 297, in assert_query_result
6232    await tx.start()
6233  File "/home/travis/build/edgedb/edgedb/edgedb/edgedb/transaction.py", line 222, in start
6234    await self._connection.execute(query)
6235  File "/home/travis/build/edgedb/edgedb/edgedb/edgedb/asyncio_con.py", line 97, in execute
6236    await self._protocol.simple_query(query)
6237  File "edgedb/protocol/protocol.pyx", line 452, in simple_query
6238edgedb.errors.InvalidReferenceError: reference to a non-existent schema item fdd262a8-0d9f-11ea-980e-e767e22637bd in schema <Schema gen:3944 at 0x7f2036c2c400>
6239
6240================================================================================
6241ERROR: test_edgeql_tutorial (test_edgeql_tutorial.TestEdgeQLTutorial) {serialization='json'}
6242--------------------------------------------------------------------------------
6243Traceback (most recent call last):
6244  File "/home/travis/build/edgedb/edgedb/edb/testbase/server.py", line 577, in tearDown
6245    self.con.execute('RESET ALIAS *;'))
6246  File "/opt/python/3.7.1/lib/python3.7/asyncio/base_events.py", line 573, in run_until_complete
6247    return future.result()
6248  File "/home/travis/build/edgedb/edgedb/edgedb/edgedb/asyncio_con.py", line 97, in execute
6249    await self._protocol.simple_query(query)
6250  File "edgedb/protocol/protocol.pyx", line 452, in simple_query
6251edgedb.errors.InvalidReferenceError: reference to a non-existent schema item fdd262a8-0d9f-11ea-980e-e767e22637bd in schema <Schema gen:3944 at 0x7f2036a35e48>
```

**Comment by elprans** [comment]
Can we enable server tracebacks for these?

**Comment by 1st1** [comment]
Closing this one as if it's not resolved right now it would be with the new introspection implementation.
